#let generateDouble(tbl) = [
#table(
    columns: (auto, auto),
    column-gutter: 0pt, 
    stroke: 1pt,
    align: (x, y) => (left, left).at(x),
    ..tbl
)]

#set text(font: "Monomakh Unicode", lang: "cs", fill: black, size: 13pt, hyphenate: auto)
#generateDouble((
table.cell(colspan:2, text(red, "Hlas 1 - 0_Nedela")),
table.cell(colspan:2, text(red, "Hlas 1 - 1_Pondelok")),
table.cell(colspan:2, text(red, "Hlas 1 - 2_Utorok")),
table.cell(colspan:2, text(red, "Hlas 1 - 3_Streda")),
table.cell(colspan:2, text(red, "Hlas 1 - 4_Stvrtok")),
table.cell(colspan:2, text(red, "Hlas 1 - 5_Piatok")),
table.cell(colspan:2, text(red, "Hlas 1 - 6_Sobota")),
table.cell(colspan:2, text(red, "Hlas 2 - 0_Nedela")),
table.cell(colspan:2, text(red, "Hlas 2 - 1_Pondelok")),
table.cell(colspan:2, text(red, "Hlas 2 - 2_Utorok")),
table.cell(colspan:2, text(red, "Hlas 2 - 3_Streda")),
table.cell(colspan:2, text(red, "Hlas 2 - 4_Stvrtok")),
table.cell(colspan:2, text(red, "Hlas 2 - 5_Piatok")),
table.cell(colspan:2, text(red, "Hlas 2 - 6_Sobota")),
table.cell(colspan:2, text(red, "Hlas 3 - 0_Nedela")),
table.cell(colspan:2, text(red, "Hlas 3 - 1_Pondelok")),
table.cell(colspan:2, text(red, "Hlas 3 - 2_Utorok")),
table.cell(colspan:2, text(red, "Hlas 3 - 3_Streda")),
table.cell(colspan:2, text(red, "Hlas 3 - 4_Stvrtok")),
table.cell(colspan:2, text(red, "Hlas 3 - 5_Piatok")),
table.cell(colspan:2, text(red, "Hlas 3 - 6_Sobota")),
table.cell(colspan:2, text(red, "Hlas 4 - 0_Nedela")),
table.cell(colspan:2, text(red, "Hlas 4 - 1_Pondelok")),
table.cell(colspan:2, text(red, "Hlas 4 - 2_Utorok")),
table.cell(colspan:2, text(red, "Hlas 4 - 3_Streda")),
table.cell(colspan:2, text(red, "Hlas 4 - 4_Stvrtok")),
table.cell(colspan:2, text(red, "Hlas 4 - 5_Piatok")),
table.cell(colspan:2, text(red, "Hlas 4 - 6_Sobota")),
table.cell(colspan:2, text(red, "Hlas 5 - 0_Nedela")),
table.cell(colspan:2, text(red, "Hlas 5 - 1_Pondelok")),
table.cell(colspan:2, text(red, "Hlas 5 - 2_Utorok")),
table.cell(colspan:2, text(red, "Hlas 5 - 3_Streda")),
table.cell(colspan:2, text(red, "Hlas 5 - 4_Stvrtok")),
table.cell(colspan:2, text(red, "Hlas 5 - 5_Piatok")),
table.cell(colspan:2, text(red, "Hlas 5 - 6_Sobota")),
table.cell(colspan:2, text(red, "Hlas 6 - 0_Nedela")),
table.cell(colspan:2, text(red, "Hlas 6 - 1_Pondelok")),
table.cell(colspan:2, text(red, "Hlas 6 - 2_Utorok")),
table.cell(colspan:2, text(red, "Hlas 6 - 3_Streda")),
table.cell(colspan:2, text(red, "Hlas 6 - 4_Stvrtok")),
table.cell(colspan:2, text(red, "Hlas 6 - 5_Piatok")),
table.cell(colspan:2, text(red, "Hlas 6 - 6_Sobota")),
table.cell(colspan:2, text(red, "Hlas 7 - 0_Nedela")),
table.cell(colspan:2, text(red, "Hlas 7 - 1_Pondelok")),
table.cell(colspan:2, text(red, "Hlas 7 - 2_Utorok")),
table.cell(colspan:2, text(red, "Hlas 7 - 3_Streda")),
table.cell(colspan:2, text(red, "Hlas 7 - 4_Stvrtok")),
table.cell(colspan:2, text(red, "Hlas 7 - 5_Piatok")),
table.cell(colspan:2, text(red, "Hlas 7 - 6_Sobota")),
table.cell(colspan:2, text(red, "Hlas 8 - 0_Nedela")),
table.cell(colspan:2, text(red, "Hlas 8 - 1_Pondelok")),
table.cell(colspan:2, text(red, "Hlas 8 - 2_Utorok")),
table.cell(colspan:2, text(red, "Hlas 8 - 3_Streda")),
table.cell(colspan:2, text(red, "Hlas 8 - 4_Stvrtok")),
table.cell(colspan:2, text(red, "Hlas 8 - 5_Piatok")),
table.cell(colspan:2, text(red, "Hlas 8 - 6_Sobota")),
))
