#import "../../../../all.typ": *
= #translation.at("KAFTIZMA") 1

#columns(2, gutter: 2pt, [

== #translation.at("ANTIFON") 1
  #generateTable((
    "",
    sText([Psalóm Davidu, ne nadpísan ú jévréj, (#translation.at("PSALM") 1)]),
    gText("1"),
    par([Blážén múž, íže ne íde na sovít nečestívych, í na putí hríšnych ne stá, í na sidálišči hubítelej ne síde:]),
    gText("2"),
    par([No v zakóňi Hospodni vóľa jéhó, í v zakóňi jéhó poučítsja déň í nóšč.]),
    gText("3"),
    par([Í búdet jáko drévo nasaždénoje pri íschódiščich vód, jéže plód svój dást vo vrémja svojé, í líst jéhó ne otpadét: í vsjá, jélíka ášče tvorít, úspíet.]),
    gText("4"),
    par([Ne táko nečestíviji, ne táko: no jáko prách, jéhóže vozmetájet vítr ot licá zemlí.]),
    gText("5"),
    par([Sehó rádi ne voskrésnut nečestíviji na súd, nižé hríšnicy v sovít právednych.]),
    gText("6"),
    par([Jáko vísť Hospoď púť právednych, í púť nečestívych pohíbnet.]),
    "",
    sText([Psalóm Davidu, (#translation.at("PSALM") 2)]),
    gText("1"),
    par([Vskúju šatášasja jázýcy, í ľúdije poučíšasja tščétnym;]),
    gText("2"),
    par([Predstáša cárije zémstiji, í kňázi sobrášasja vkúpi na Hospoda í na Christá jéhó.]),
    gText("3"),
    par([Rastórhhem #footnote("rastórhnim") úzy ích í otvéržem #footnote("otvéržim") ot nás ího ích.]),
    gText("4"),
    par([Živýj na nebesích posmiétsja ím, í Hospoď poruhájetsja ím.]),
    gText("5"),
    par([Tohdá vozhlahólet k ním hňívom svojím í járostiju svojéju smjatét já:]),
    gText("6"),
    par([Áz že postávlen jésm cer ot nehó nad Sijónom, horóju svjatóju jéhó,]),
    gText("7"),
    par([Vozviščájaj poveľínije Hospodne. Hospoď rečé ko mňí: Sýn mój jésí tý, áz dnés rodích ťá:]),
    gText("8"),
    par([Prosí ot mené, í dám tí jázýki dostojánije tvojé, í óderžánije tvojé koncý zemlí:]),
    gText("9"),
    par([Úpaséši já žezlóm žeľíznym, jáko sosúdy skudéľniči sokrušíši já.]),
    gText("10"),
    par([Í nýňi, cárije, razumíjte, nakažítesja vsí suďáščiji zemlí.]),
    gText("11"),
    par([Rabótajte Hospodevi so stráchom, í rádujtesja jémú so trépetom.]),
    gText("12"),
    par([Prijimíte nakazánije, da ne kohdá prohňívajetsja Hospoď, í pohíbnete ot putí právednaho, jéhdá vozhorítsja vskóri járosť jéhó: blážéni vsí naďíjuščijisja náň.]),
    gText("1"),
    sText([Psalóm Davidu, vnehdá otbiháše ot licá ávessalóma sýna svojehó, (#translation.at("PSALM") 3)]),
    gText("2"),
    par([Hospodi, čtó sja úmnóžiša stužájuščiji mí; mnózi vostajút na mjá,]),
    gText("3"),
    par([Mnózi hlahóľut duší mojéj: ňísť Spasénija jémú v Bózi jéhó.]),
    gText("4"),
    par([Tý že, Hospodi, zastúpnik mój jésí, sláva mojá, í voznosjáj hlavú mojú.]),
    gText("5"),
    par([Hlásom mojím ko Hospodu vozzvách, í úslýša mjá ot horý svjatýja svojejá.]),
    gText("6"),
    par([Áz úsnúch, í spách, vostách, jáko Hospoď zastúpit mjá.]),
    gText("7"),
    par([Ne úbojúsja ot tém ľudéj, ókrest napádajuščich na mjá.]),
    gText("8"),
    par([Voskresní, Hospodi, Spasí mja, Bože mój: jáko tý porazíl jésí vsjá vraždújuščyja mí vsúje, zúby hríšnikov sokrušíl jésí.]),
    gText("9"),
    par([Hospodne jésť Spasénije, í na ľúdech tvojích bláhoslovénije tvojé.]),
    col2(gText([#translation.at("SI")])),
  ))
== #translation.at("ANTIFON") 2
  #generateTable((
    gText("1"),
    sText([V konéc, v písnech, psalóm Davidu, (#translation.at("PSALM") 4)]),
    gText("2"),
    par([Vnehdá prizváti mí, úslýša mjá Boh právdy mojejá: v skórbi rasprostraníl mjá jésí: úščédri mjá í úslýši molítvu mojú.]),
    gText("3"),
    par([Sýnove čelovíčestiji, dokóľi ťažkosérdiji; vskúju ľúbite sujetú í íščete lží;]),
    gText("4"),
    par([Í úvídite, jáko údiví Hospoď prepodóbnaho svojehó. Hospoď úslýšit mjá, vnehdá vozzváti mí k nemú.]),
    gText("5"),
    par([Hňívajtesja, í ne sohrišájte, jáže hlahólete v serdcách vášich, na lóžach vášich úmilítesja:]),
    gText("6"),
    par([Požríte žértvu právdy í úpovájte na Hospoda.]),
    gText("7"),
    par([Mnózi hlahóľut: któ jávít nám bláhája; známenasja na nás svít licá tvojehó, Hospodi.]),
    gText("8"),
    par([Dál jésí vesélije v sérdcy mojém: ot plodá pšenícy, vijná í jéléa svojehó úmnóžišasja:]),
    gText("9"),
    par([V míri vkúpi úsnú í počíju, jáko tý, Hospodi, jédínaho na úpovániji vselíl mjá jésí.]),
    gText("1"),
    sText([Ó nasľídstvujuščem, psalóm Davidu, (#translation.at("PSALM") 5)]),
    gText("2"),
    par([Hlahóly mojá vnuší, Hospodi, razumíj zvánije mojé.]),
    gText("3"),
    par([Vonmí hlásu molénija mojehó, cerjú mój í Bože mój: jáko k tebí pomoľúsja, Hospodi.]),
    gText("4"),
    par([Zaútra úslýši hlás mój: zaútra predstánu tí, í úzriši mjá:]),
    gText("5"),
    par([Jáko Boh ne choťáj bezzakónija tý jésí: ne priselítsja k tebí lukávnujaj,]),
    gText("6"),
    par([Nižé prebúdut bezzakónnicy pred óčíma tvojíma: voznenavíďil jésí vsjá ďílajuščyja bezzakónije,]),
    gText("7"),
    par([Pohubíši vsjá hlahóľuščyja lžú: múža krovéj í ľstíva hnušájetsja Hospoď.]),
    gText("8"),
    par([Áz že mnóžestvom mílosti tvojejá vnídu v dóm tvój, pokloňúsja ko chrámu svjatómu tvojemú, v strási tvojém.]),
    gText("9"),
    par([Hospodi, nastávi mjá právdoju tvojéju, vráh mojích rádi ísprávi pred tobóju púť mój.]),
    gText("10"),
    par([Jáko ňísť vo úsťích ích ístiny, sérdce ích sújetno, hrób otvérst hortáň ích, jázýki svojími ľščáchu.]),
    gText("11"),
    par([Sudí ím, Bože, da otpadút ot mýslej svojích: po mnóžestvu nečéstija ích ízríni já, jáko preohorčíša ťá, Hospodi.]),
    gText("12"),
    par([Í da vozveseľátsja vsí úpovájuščiji na ťá, vo vík vozrádujutsja, í vselíšisja v ních: í pochváľatsja ó tebí ľúbjaščiji ímja tvojé.]),
    gText("13"),
    par([Jáko tý bláhoslovíši právednika, Hospodi, jáko órúžijem bláhovolénija vinčál jésí nás.]),
    gText("1"),
    sText([V konéc, v písnech ó ósmóm, psalóm Davidu, (#translation.at("PSALM") 6)]),
    gText("2"),
    par([Hospodi, da ne járostiju tvojéju óbličíši mené, nižé hňívom tvojím nakážeši mené.]),
    gText("3"),
    par([Pomíluj mjá, Hospodi, jáko némoščen jésm: íscilí mja, Hospodi, jáko smjatóšasja kósti mojá,]),
    gText("4"),
    par([Í dušá mojá smjatésja ziló: í tý, Hospodi, dokóľi;]),
    gText("5"),
    par([Óbratísja, Hospodi, ízbávi dúšu mojú, Spasí mja rádi mílosti tvojejá:]),
    gText("6"),
    par([Jáko ňísť v smérti pominájaj tebé, vo áďi že któ íspovístsja tebí;]),
    gText("7"),
    par([Útrudíchsja vozdychánijem mojím, ízmýju na vsjáku nóšč lóže mojé, slezámi mojími postéľu mojú ómočú.]),
    gText("8"),
    par([Smjatésja ot járosti óko mojé, óbetšách vo vsích vrazích mojích.]),
    gText("9"),
    par([Otstupíte ot mené, vsí ďílajuščiji bezzakónije, jáko úslýša Hospoď hlás pláča mojehó,]),
    gText("10"),
    par([Úslýša Hospoď molénije mojé, Hospoď molítvu mojú priját.]),
    gText("11"),
    par([Da postyďátsja í smjatútsja vsí vrazí moí, da vozvraťátsja í ústyďátsja ziló vskóri.]),
    col2(gText([#translation.at("SI")])),
  ))
== #translation.at("ANTIFON") 3
  #generateTable((
    gText("1"),
    sText([Psalóm Davidu, jéhóže vospít Hospodevi ó slovesích chusíevych, sýna íemeníjina, (#translation.at("PSALM") 7)]),
    gText("2"),
    par([Hospodi Bože mój, na ťá úpovách, Spasí mja ot vsích hoňáščich mjá í ízbávi mjá:]),
    gText("3"),
    par([Da ne kohdá pochítit jáko lév dúšu mojú, ne súšču ízbavľájušču, nižé spasájušču.]),
    gText("4"),
    par([Hospodi Bože mój, ášče sotvorích sijé, ášče jésť neprávda v rukú moéju,]),
    gText("5"),
    par([Ášče vozdách vozdajúščym mí zlá, da otpadú úbo ot vráh mojích tóšč:]),
    gText("6"),
    par([Da poženét úbo vráh dúšu mojú, í da postíhnet, í poperét v zémľu živót mój, í slávu mojú v pérsť vselít.]),
    gText("7"),
    par([Voskresní, Hospodi, hňívom tvojím, voznesísja v koncách vráh tvojích, í vostáni, Hospodi Bože mój, poveľínijem, ímže zapovídal jésí,]),
    gText("8"),
    par([Í sónm ľudéj óbýdet ťá: í ó tóm na vysotú óbratísja.]),
    gText("9"),
    par([Hospoď súdit ľúdem: sudí mi, Hospodi, po právďi mojéj í po nezlóbi mojéj na mjá.]),
    gText("10"),
    par([Da skončájetsja zlóba hríšnych, í íspráviši právednaho, íspytájaj serdcá í útróby, Bože, právedno.]),
    gText("11"),
    par([Pómošč mojá ot Boha, Spasájuščaho právyja sérdcem.]),
    gText("12"),
    par([Boh sudíteľ právedn, í krípok, í dolhoterpilív, í ne hňív navoďáj na vsják déň.]),
    gText("13"),
    par([Ášče ne óbratitésja, órúžije svojé óčístit, lúk svój naprjažé, í úhotóva í,]),
    gText("14"),
    par([Í v ném úhotóva sosúdy smértnyja, stríly svojá sharáemym soďíla.]),
    gText("15"),
    par([Sé, boľí neprávdoju, začát boľízň í rodí bezzakónije:]),
    gText("16"),
    par([Róv ízrý í ískopá í, í padét v jámu, júže soďíla.]),
    gText("17"),
    par([Óbratítsja boľízň jéhó na hlavú jéhó, í na vérch jéhó neprávda jéhó snídet.]),
    gText("18"),
    par([Íspovímsja Hospodevi po právďi jéhó í pojú ímeni Hospoda výšňaho.]),
    gText("1"),
    sText([V konéc, ó točíľich, psalóm Davidu, (#translation.at("PSALM") 8)]),
    gText("2"),
    par([Hospodi Hospoď náš, jáko čúdno ímja tvojé po vséj zemlí, jáko vzjátsja velikoľípije tvojé prevýše nebes.]),
    gText("3"),
    par([Íz úst mladénec í ssúščich soveršíl jésí chvalú, vráh tvojích rádi, jéže razrušíti vrahá í méstnika.]),
    gText("4"),
    par([Jáko úzrjú nebesá, ďilá pérst tvojích, lunú í zvízdy, jáže tý ósnovál jésí:]),
    gText("5"),
    par([čtó jésť čelovík, jáko pómniši jéhó; ílí sýn čelovíč, jáko posiščáješi jéhó;]),
    gText("6"),
    par([Úmálil jésí jéhó málym čím ot Anhel, slávoju í čéstiju vinčál jésí jéhó:]),
    gText("7"),
    par([Í postávil jésí jéhó nad ďíly rukú tvoéju, vsjá pokoríl jésí pod nózi jéhó:]),
    gText("8"),
    par([Óvcy í volý vsjá, jéščé že í skotý poľskíja,]),
    gText("9"),
    par([Ptícy nebésnyja í rýby morskíja, prechoďáščyja stezí morskíja.]),
    gText("10"),
    par([Hospodi Hospoď náš, jáko čúdno ímja tvojé po vséj zemlí.]),
    col2(gText([#translation.at("SI")])),
  ))
  #generateTable((
    col2(sText(translation.at("AFTER_KAFTIZMA"))),
    sText("T"),
    jObj4("",1, "", "V bezzakónijich začávsja áz blúdnyj, ne derzáju vziráti na vysotú nebésnuju, no derzája na čelovikoľúbije tvojé, zovú: Bože, óčísti mjá hríšnaho, í Spasí mja."),
    sText("T"),
    jObj4("",none, "", "Ášče právednik jédvá Spasájetsja, áz hďí jávľúsja hríšnyj; ťahotý í znója dnevnáho ne ponesóch, no s najémniki jédinonadesjátaho časá sopričtí mja Bože, í Spasí mja."),
    
    // S:
    col2(gText(translation.at("S"))),
    "",
    jObj4("",none, "", "Óbjátija Ótča otvérsti mí potščísja, blúdno mojé íždích žitijé, na bohátstvo neiždivájemoje vzirájaj ščedrót tvojích Spase: nýňi óbniščávšeje mojé da ne prézriši sérdce, tebí bo Hospodi, úmilénijem zovú: sohriších na nebo í pred tobóju."),
    
    // I:
    col2(gText(translation.at("IN"))),
    "",
    jObj4("",none, "", "Úpovánije Christiján presvjatája Ďivo, jéhóže rodilá jésí Boha páče úmá že í Slóva, neprestánno molí s hórnimi sílami, dáti óstavlénije hrichóv nám vsím, í íspravlénije žitijá, víroju í ľubóviju prísno ťá čtúščym."),
    col2(translation.at("HOSPODI_POMILUJ")+". "+sText("(40)")),
    col2(sText(translation.at("MOLITVA"))),
    "",
    jObj4("",none, "", "Vladýko vsederžíteľu, nepostižíme, načálo svíta, í preúmnaja sílo, íže ýpostásnaho Slóva Ótc, í jédinosíľnaho tvojehó Dúcha íspustíteľ: mílosrdnyja rádi mílosti, í neizrečénnyja bláhosti, ne prezrívyj čelovíčeskaho jéstestvá, ťmóju hrichá soderžímaho, no Božéstvennymi svíty svjaščénnych tvojích účénij, zakónom í proróki svitívyj míru, posľidí že nám tohó jédinoródnaho tvojehó Sýna bláhovolívyj plótiju vozsijáti, í ko ósijániju nás tvojehó prosviščénija nastáviti: da búdut úši tvoí vnémľušči hlásu molénija nášeho, í dáruj nám Bože, vo bďínnom í trézvennom sérdci vsjú nastojáščaho žitijá nóšč prejtí, óžidájuščym prišéstvija Sýna tvojehó, í Boha nášeho, sudijí vsích, da ne vozležášče í spjášče, no bódrstvujušče í vozdvíženi v ďílanije zápovidej tvojích óbrjáščemsja, í v rádosť jéhó sovnídem, íďíže prázdnujuščich hlás neprestánnyj, í neizrečénnaja sládosť zrjáščich tvojehó licá dobrótu neizhlahólannuju. Jáko bláh í čelovikoľúbec Boh jésí, í tebí slávu vozsylájem, Ótcú, í Sýnu, í svjatómu Dúchu, nýňi í prísno, í vo víki vikóv, ámíň."),
  ))
])
