#import "../../../../all.typ": *
= #translation.at("KAFTIZMA") 10

#columns(2, gutter: 2pt, [

== #translation.at("ANTIFON") 1
  #generateTable((
    "",
    sText([ Davidu psalóm, synóv íonadávovych í pérvych pľínšichsja, ne nadpísan ú jévréj, (#translation.at("PSALM") 70)]),
    gText("1"),
    par([Na ťá, Hospodi, úpovách, da ne postyžúsja v vík.]),
    gText("2"),
    par([Právdoju tvojéju ízbávi mjá í ízmí mja: prikloní ko mňí úcho tvojé í Spasí mja.]),
    gText("3"),
    par([Búdi mí v Boha zaščítiteľa í v místo krípko Spastí mja: jáko útverždénije mojé í pribížišče mojé jésí tý.]),
    gText("4"),
    par([Bože mój, ízbávi mjá íz rukí hríšnaho, íz rukí zakonoprestúpnaho í óbíďaščaho:]),
    gText("5"),
    par([Jáko tý jésí terpínije mojé, Hospodi, Hospodi, úpovánije mojé ot júnosti mojejá.]),
    gText("6"),
    par([V tebí útverdíchsja ot útróby, ot čréva mátere mojejá tý jésí mój pokrovíteľ: ó tebí pínije mojé výnu.]),
    gText("7"),
    par([Jáko čúdo bých mnóhim: í tý pomóščnik mój krípok.]),
    gText("8"),
    par([Da íspólňatsja ústá mojá chvalénija, jáko da vospojú slávu tvojú, vés déň velikoľípije tvojé.]),
    gText("9"),
    par([Ne otvérži mené vo vrémja stárosti: vnehdá óskuďiváti kríposti mojéj, ne óstávi mené.]),
    gText("10"),
    par([Jáko ríša vrazí moí mňí, í strehúščiji dúšu mojú soviščáša vkúpi,]),
    gText("11"),
    par([Hlahóľušče: Boh óstávil jésť jéhó, poženíte í ímíte jéhó, jáko ňísť ízbavľájaj.]),
    gText("12"),
    par([Bože mój, ne údalísja ot mené: Bože mój, v pómošč mojú vonmí.]),
    gText("13"),
    par([Da postyďátsja í ísčéznut óklevetájuščiji dúšu mojú, da óblekútsja v stúd í srám íščuščiji zlája mňí.]),
    gText("14"),
    par([Áz že vsehdá vozupováju na ťá, í priložú na vsjáku pochvalú tvojú.]),
    gText("15"),
    par([Ústá mojá vozvisťát právdu tvojú, vés déň Spasénije tvojé, jáko ne poznách knížnaja.]),
    gText("16"),
    par([Vnídu v síľi Hospodni: Hospodi, pomjanú právdu tebé jédínaho.]),
    gText("17"),
    par([Bože mój, ímže naučíl mjá jésí ot júnosti mojejá, í do nýňi vozviščú čudesá tvojá.]),
    gText("18"),
    par([Í dáže do stárosti í prestarínija, Bože mój, ne óstávi mené, dóndeže vozviščú mýšcu tvojú ródu vsemú hrjadúščemu,]),
    gText("19"),
    par([Sílu tvojú í právdu tvojú, Bože, dáže do výšnich, jáže sotvoríl mí jésí velíčija: Bože, któ podóben tebí;]),
    gText("20"),
    par([Jélíki jávíl mí jésí skórbi mnóhi í zlý; í óbráščsja óživotvoríl mjá jésí í ot bézdn zemlí vozvél mjá jésí.]),
    gText("21"),
    par([Úmnóžil jésí na mňí velíčestvije tvojé, í óbráščsja úťíšil mjá jésí, í ot bézdn zemlí páki vozvél mjá jésí.]),
    gText("22"),
    par([Íbo áz íspovímsja tebí v ľúdech, Hospodi, v sosúďich psalómskich ístinu tvojú, Bože: vospojú tebí v húslech, svjatýj Izráilev.]),
    gText("23"),
    par([Vozrádujeťisja ústňí moí, jéhdá vospojú tebí, í dušá mojá, júže jésí ízbávil:]),
    gText("24"),
    par([Jéščé že í jázýk mój vés déň poučítsja právďi tvojéj, jéhdá postyďátsja í posrámjatsja íščuščij zlája mňí.]),
    "",
    sText([Ó solomóňi, psalóm Davidu, (#translation.at("PSALM") 71)]),
    gText("1"),
    par([Bože, súd tvój carévi dážď, í právdu tvojú sýnu carévu:]),
    gText("2"),
    par([Sudíti ľúdem tvoím v právďi í níščym tvoím v suďí.]),
    gText("3"),
    par([Da vosprijímut hóry mír ľúdem í chólmi právdu.]),
    gText("4"),
    par([Súdit níščym ľudskím, í spasét sýny úbóhich, í smirít klevetniká.]),
    gText("5"),
    par([Í prebúdet s sólncem, í préžde luný róda rodóv.]),
    gText("6"),
    par([Snídet jáko dóžď na runó, í jáko kápľa kápľuščaja na zémľu.]),
    gText("7"),
    par([Vozsijáet vo dnéch jéhó právda í mnóžestvo míra, dóndeže otímetsja luná.]),
    gText("8"),
    par([Í óbladájet ot mórja do mórja, í ot rík do konéc vselénnyja.]),
    gText("9"),
    par([Pred ním pripadút jéthijópľane, í vrazí jéhó pérsť polížut.]),
    gText("10"),
    par([Cárije tharsíjstiji í óstrovi dáry prinesút, cárije árávstiji í savá dáry privedút:]),
    gText("11"),
    par([Í poklóňatsja jémú vsí cárije zémstiji, vsí jázýcy porabótajut jémú.]),
    gText("12"),
    par([Jáko ízbávi níšča ot síľna, í úbóha, jémúže ne bí pomóščnika.]),
    gText("13"),
    par([Poščadít níšča í úbóha, í dúšy úbóhich spasét:]),
    gText("14"),
    par([Ot líchvy í ot neprávdy ízbávit dúšy ích, í čéstno ímja jéhó pred ními.]),
    gText("15"),
    par([Í žív búdet, í dástsja jémú ot zláta áravíjska: í pomóľatsja ó ném výnu, vés déň bláhoslovját jéhó.]),
    gText("16"),
    par([Búdet útverždénije na zemlí na versích hór: prevoznesétsja páče lijvána plód jéhó, í procvitút ot hráda jáko travá zemnája.]),
    gText("17"),
    par([Búdet ímja jéhó bláhoslovéno vo víki, préžde sólnca prebyvájet ímja jéhó: í bláhoslovjátsja v ném vsjá koľína zemnája, vsí jázýcy úblažát jéhó.]),
    gText("18"),
    par([Bláhoslovén Hospoď Boh Izráilev, tvorjáj čudesá jédín,]),
    gText("19"),
    par([Í bláhoslovéno ímja slávy jéhó vo vík í v vík víka: í íspólnitsja slávy jéhó vsjá zemľá: búdi, búdi.]),
    col2(gText([#translation.at("SI")])),
  ))
== #translation.at("ANTIFON") 2
  #generateTable((
    "",
    sText([Óskuďíša písni Davida, sýna íesséova. Psalóm ásáfu, (#translation.at("PSALM") 72)]),
    gText("1"),
    par([Kóľ bláh Boh Izráilev právym sérdcem.]),
    gText("2"),
    par([Mojí že vmáľi ne podvižásťisja nózi: vmáľi ne prolijášasja stopý mojá:]),
    gText("3"),
    par([Jáko vozrevnovách na bezzakónnyja, mír hríšnikov zrjá:]),
    gText("4"),
    par([Jáko ňísť vosklonénija v smérti ích í útverždénija v ráňi ích:]),
    gText("5"),
    par([V truďích čelovíčeskich ne súť, í s čelovíki ne prijímut rán.]),
    gText("6"),
    par([Sehó rádi úderžá já hordýňa ích do koncá: óďíjašasja neprávdoju í nečéstijem svojím.]),
    gText("7"),
    par([Ízýdet jáko íz túka neprávda ích: preidóša v ľubóv sérdca.]),
    gText("8"),
    par([Pomýsliša í hlahólaša v lukávstvi, neprávdu v vysotú hlahólaša:]),
    gText("9"),
    par([Položíša na nebesí ústá svojá, í jázýk ích préjde po zemlí.]),
    gText("10"),
    par([Sehó rádi óbraťátsja ľúdije moí símo, í dníe íspólneni óbrjáščutsja v ních.]),
    gText("11"),
    par([Í ríša: káko úvíďi Boh; í ášče jésť rázum v výšňim;]),
    gText("12"),
    par([Sé, síji hríšnicy í hobzújuščiji v vík úderžáša bohátstvo.]),
    gText("13"),
    par([Í rích: jédá #footnote("úbo") vsúje ópravdích sérdce mojé í úmých v nepovínnych rúci moí,]),
    gText("14"),
    par([Í bých jázven vés déň, í óbličénije mojé na útrennich;]),
    gText("15"),
    par([Ášče hlahólach, povím táko: sé, ródu synóv tvojích, jémúže óbiščáchsja #footnote("sé, ródu synóv tvojích prestupích"):]),
    gText("16"),
    par([Í nepščevách razumíti: sijé trúd jésť predo mnóju,]),
    gText("17"),
    par([Dóndeže vnídu vo svjatílo Božije í razumíju v posľídňaja ích.]),
    gText("18"),
    par([Óbáče za ľščénija ích položíl jésí ím zlája, nizložíl jésí já, vnehdá razhorďíšasja.]),
    gText("19"),
    par([Káko býša v zapusťínije; vnezápu ísčezóša, pohibóša za bezzakónije svojé.]),
    gText("20"),
    par([Jáko sónije vostajúščaho, Hospodi, vo hráďi tvojém óbraz ích úničižíši.]),
    gText("21"),
    par([Jáko razžžésja sérdce mojé, í útróby mojá ízminíšasja:]),
    gText("22"),
    par([Í áz úničižén, í ne razumích, skóten bých ú tebé.]),
    gText("23"),
    par([Í áz výnu s tobóju: úderžál jésí rúku desnúju mojú,]),
    gText("24"),
    par([Í sovítom tvojím nastávil mjá jésí, í so slávoju prijál mjá jésí.]),
    gText("25"),
    par([Čtó bo mí jésť na nebesí; í ot tebé čtó voschoťích na zemlí;]),
    gText("26"),
    par([Ísčezé sérdce mojé í plóť mojá, Bože sérdca mojehó, í čásť mojá, Bože, vo vík.]),
    gText("27"),
    par([Jáko sé, údaľájuščiji sebé ot tebé pohíbnut: potrebíl jésí vsjákaho ľuboďíjuščaho ot tebé.]),
    gText("28"),
    par([Mňí že priľipľátisja Bohovi bláho jésť, polaháti na Hospoda úpovánije mojé, vozvistíti mí vsjá chvalý tvojá, vo vraťích dščére Sijóni.]),
    "",
    sText([Rázuma ásáfu, (#translation.at("PSALM") 73)]),
    gText("1"),
    par([Vskúju, Bože, otrínul jésí do koncá; razhňívasja járosť tvojá na óvcy pážiti tvojejá;]),
    gText("2"),
    par([Pomjaní sónm tvój, jéhóže sťažál jésí íspérva, ízbávil jésí žezlóm dostojánija tvojehó, horá Sijón sijá #footnote("žézl dostojánija tvojehó, hóru Sijón sijú"), v néjže vselílsja jésí.]),
    gText("3"),
    par([Vozdvíhni rúci tvoí na hordýni ích v konéc, jélíka lukávnova vráh vo svjatím tvojém.]),
    gText("4"),
    par([Í voschvalíšasja nenavíďaščiji ťá posreďí prázdnika tvojehó: položíša známenija svojá známenija, í ne poznáša,]),
    gText("5"),
    par([Jáko vo íschóďi prevýše: jáko v dubrávi drévjaňi sikírami razsikóša]),
    gText("6"),
    par([Dvéri jéhó vkúpi, síčivom í óskórdom razrušíša í.]),
    gText("7"),
    par([Vozžhóša óhném svjatílo tvojé: na zemlí óskverníša žilíšče ímene tvojehó.]),
    gText("8"),
    par([Ríša v sérdcy svojém júžiki ích vkúpi: prijidíte, í otstávim vsjá prázdniki Božija ot zemlí.]),
    gText("9"),
    par([Známenija ích #footnote("známenij nášich") ne víďichom: ňísť ktomú proróka, í nás ne poznájet ktomú.]),
    gText("10"),
    par([Dokóľi, Bože, ponósit vráh; razdražít protívnyj ímja tvojé do koncá;]),
    gText("11"),
    par([Vskúju otvraščáješi rúku tvojú í desnícu tvojú ot sredý ňídra tvojehó v konéc;]),
    gText("12"),
    par([Boh že, cer náš, préžde víka soďíla Spasénije posreďí zemlí.]),
    gText("13"),
    par([Tý útverdíl jésí síloju tvojéju móre: tý stérl jésí hlavý zmijév v voďí:]),
    gText("14"),
    par([Tý sokrušíl jésí hlavú zmíevu, dál jésí tohó brášno ľúdem jéthijópskim.]),
    gText("15"),
    par([Tý rastórhl jésí ístóčniki í potóki: tý ízsušíl jésí ríki íthámskija.]),
    gText("16"),
    par([Tvój jésť déň, í tvojá jésť nóšč: tý soveršíl jésí zarjú í sólnce.]),
    gText("17"),
    par([Tý sotvoríl jésí vsjá preďíly zemlí: žátvu í vésnu tý sozdál jésí já.]),
    gText("18"),
    par([Pomjaní sijá: vráh ponosí Hospodevi, í ľúdije bezúmniji razdražíša ímja tvojé.]),
    gText("19"),
    par([Ne predážď zvirém dúšu íspovídajuščujusja tebí: dúš úbóhich tvojích ne zabúdi do koncá.]),
    gText("20"),
    par([Prízri na zavít tvój: jáko íspólnišasja pomračénniji zemlí domóv bezzakónij.]),
    gText("21"),
    par([Da ne vozvratítsja smirénnyj posrámlen: níšč í úbóh voschvalíta ímja tvojé.]),
    gText("22"),
    par([Vostáni, Bože, sudí prjú tvojú: pomjaní ponošénije tvojé, jéže ot bezúmnaho vés déň.]),
    gText("23"),
    par([Ne zabúdi hlása molítvennik tvojích: hordýňa nenavíďaščich ťá vzýde výnu #footnote("da voschódit výnu (k tebí)").]),
    col2(gText([#translation.at("SI")])),
  ))
== #translation.at("ANTIFON") 3
  #generateTable((
    gText("1"),
    sText([V konéc, da ne rastlíši, psalóm písni ásáfu, (#translation.at("PSALM") 74)]),
    gText("2"),
    par([Íspovímysja tebí, Bože, íspovímysja tebí í prizovém ímja tvojé: povím vsjá čudesá tvojá.]),
    gText("3"),
    par([Jéhdá prijimú vrémja, áz pravotý vozsuždú.]),
    gText("4"),
    par([Rastájasja zemľá í vsí živúščiji na néj, áz útverdích stolpý jéjá.]),
    gText("5"),
    par([Rích bezzakónnujuščym, ne bezzakónnujte: í sohrišájuščym, ne voznosíte róha.]),
    gText("6"),
    par([Ne vozdvizájte na vysotú róha vášeho í ne hlahólite na Boha neprávdu:]),
    gText("7"),
    par([Jáko nižé ot íschód, nižé í západ, nižé ot pustých hór.]),
    gText("8"),
    par([Jáko Boh sudijá jésť: sehó smirájet, í sehó voznósit.]),
    gText("9"),
    par([Jáko čáša v rucí Hospodni, vijná nerastvoréna íspólň rastvorénija, í úkloní ot sejá v sijú: óbáče dróždije jéhó ne ístoščísja, íspijút vsí hríšniji zemlí.]),
    gText("10"),
    par([Áz že vozrádujusja v vík, vospojú Bohu Jákovľu:]),
    gText("11"),
    par([Í vsjá róhi hríšnych slomľú, í voznesétsja róh právednaho.]),
    gText("1"),
    sText([V konéc, v písnech, psalóm ásáfu, písň ko ássyríaninu, (#translation.at("PSALM") 75)]),
    gText("2"),
    par([Vídom vo íudéi Boh: vo Izráili vélije ímja jéhó.]),
    gText("3"),
    par([Í býsť v míri místo jéhó, í žilíšče jéhó v sijóňi.]),
    gText("4"),
    par([Támo sokruší kríposti lukóv, órúžije í méč í bráň.]),
    gText("5"),
    par([Prosviščáješi tý dívno ot hór víčnych.]),
    gText("6"),
    par([Smjatóšasja vsí nerazúmniji sérdcem: úsnúša snóm svojím, í ničtóže óbritóša vsí múžije bohátstva v rukách svojích.]),
    gText("7"),
    par([Ot zapreščénija tvojehó, Bože Jákovľ, vozdremáša vsídšiji na kóni.]),
    gText("8"),
    par([Tý strášen jésí, í któ protivostánet tebí; ottóľi hňív tvój.]),
    gText("9"),
    par([S nebesé slýšan sotvoríl jésí súd: zemľá úbojásja í úmolčá,]),
    gText("10"),
    par([Vnehdá vostáti na súd Bohu, Spastí vsjá krótkija zemlí.]),
    gText("11"),
    par([Jáko pomyšlénije čelovíčeskoje íspovístsja tebí, í óstánok pomyšlénija prázdnujet tí.]),
    gText("12"),
    par([Pomolítesja í vozdadíte Hospodevi Bohu nášemu: vsí, íže ókrest jéhó, prinesút dáry]),
    gText("13"),
    par([Strášnomu í otjémľuščemu dúchi kňazéj, strášnomu páče caréj zemných.]),
    gText("1"),
    sText([V konéc, ó ídijthúmi, psalóm ásáfu, (#translation.at("PSALM") 76)]),
    gText("2"),
    par([Hlásom mojím ko Hospodu vozzvách, hlásom mojím k Bohu, í vňát mí.]),
    gText("3"),
    par([V déň skórbi mojejá Boha vzyskách rukáma mojíma, nóščiju pred ním, í ne preľščén bých: otvéržesja úťíšitisja dušá mojá.]),
    gText("4"),
    par([Pomjanúch Boha í vozveselíchsja, pohlumľáchsja #footnote("razmyšľách"), í malodúšstvovaše dúch mój.]),
    gText("5"),
    par([Predvarísťi stražbý óči moí: smjatóchsja í ne hlahólach.]),
    gText("6"),
    par([Pomýslich dní pérvyja, í ľíta víčnaja pomjanúch, í poučáchsja:]),
    gText("7"),
    par([Nóščiju sérdcem mojím hlumľáchsja, í tužáše #footnote("razmyšľách, í íspýtovaše") dúch mój:]),
    gText("8"),
    par([Jédá vo víki otrínet Hospoď í ne priložít bláhovolíti páki;]),
    gText("9"),
    par([Ílí do koncá mílosť svojú otsičét, skončá hlahól ot róda v ród;]),
    gText("10"),
    par([Jédá zabúdet úščédriti Boh; ílí úderžít vo hňívi svojém ščedróty svojá;]),
    gText("11"),
    par([Í rích: nýňi načách, sijá ízmína desnícy výšňaho.]),
    gText("12"),
    par([Pomjanúch ďilá Hospodňa: jáko pomjanú ot načála čudesá tvojá,]),
    gText("13"),
    par([Í poučúsja vo vsích ďíľich tvojích, í v načinánijich tvojích pohlumľúsja #footnote("razmyšľáti búdu").]),
    gText("14"),
    par([Bože, vo svjatím púť tvój: któ Boh vélij, jáko Boh náš;]),
    gText("15"),
    par([Tý jésí Boh tvorjáj čudesá: skazál jésí v ľúdech sílu tvojú,]),
    gText("16"),
    par([Ízbávil jésí mýšceju tvojéju ľúdi tvojá, sýny Jákovli í Jósifovy.]),
    gText("17"),
    par([Víďiša ťá vódy, Bože, víďiša ťá vódy í úbojášasja: smjatóšasja bézdny.]),
    gText("18"),
    par([Mnóžestvo šúma vód: hlás dáša óblacy, íbo stríly tvojá prechóďat.]),
    gText("19"),
    par([Hlás hróma tvojehó v kolesí, ósvitíša mólnija tvojá vselénnuju: podvížesja í trépetna býsť zemľá.]),
    gText("20"),
    par([V móri putijé tvoí, í stezí tvojá v vodách mnóhich, í sľidý tvoí ne poznájutsja.]),
    gText("21"),
    par([Nastávil jésí jáko óvcy ľúdi tvojá rukóju moyséovoju í áaróneju.]),
    col2(gText([#translation.at("SI")])),
  ))
  #generateTable((
    col2(sText(translation.at("AFTER_KAFTIZMA"))),
    sText("T"),
    jObj4("",6, "", "Strášnaho dné prišéstvija tvojehó úžasájusja Christé, í neumýtnaho sudílišča bojásja Hospodi, úžasájusja í trepéšču, jáko ímýj mnóžestvo sohrišénij: no préžde koncá jáko mílostiv Boh óbratí, í Spasí mja Spase mój mnohomílostive."),
    
    // S:
    col2(gText(translation.at("S"))),
    "",
    jObj4("",none, "", "Jéhdá prestóli na súd postávjatsja Hospodi, í sudílišču tvojemú predstánut čelovícy: ne predpočtétsja cár vóina, ne preimúščestvit vladýka rabá: kíjždo bo ot svojích ďíl ílí proslávitsja, ílí postydítsja."),
    
    // I:
    col2(gText(translation.at("IN"))),
    "",
    jObj4("",none, "", "Velíkich darovánij čestaja Ďivo BohoMati, tý spodóbilasja jésí: jáko rodilá jésí plótiju jédínaho ot Trójcy, Christá žiznodávca, vo Spasénije dúš nášich."),
    col2(translation.at("HOSPODI_POMILUJ")+". "+sText("(40)")),
    col2(sText(translation.at("MOLITVA"))),
    "",
    jObj4("",none, "", "Hospodi Bože náš, v mílosti bohátyj, í v ščedrótach nepostižímyj, jédíne po jéstestvú bezhríšen, í nás rádi kromí hrichá býv čelovík, úslýši v čás séj boľíznennoje mojé sijé molénije, jáko níšč í úbóh jésm ot ďíl bláhích, í sérdce mojé smjatésja vnútr mené. Tý bo vísi výšnij cerjú, Hospodi nebesé í zemlí, jáko vsjú mojú júnosť vo hrisích íždích: í v sľíd pochotéj plóti mojejá chodív, vés smích démonom bých, vés dijávolu posľídovach výnu, v timíniji slastéj vaľájajsja. Ómračívsja bo pomyšlénijem ot mladénstva dáže í do nýňi, nikohdáže voschoťích sotvoríti vóľu tvojú svjatúju: no vés ot navítujuščich mjá strastéj pľinívsja, smích í poruhánije démonom bých, nikákože vo úmí pomyšľájaj, jáko nesterpímyj hňív jéže na hríšniki preščénija tvojehó, í ležáščuju hejénnu óhnennuju. Jákože otsjúdu vo otčájanije vpadýj, í nikákože v čúvstvi óbraščénija býv, púst í náh jéže ot tvojejá drúžby bých. Kíj bo víd hrichá ne soďílach; kóje ďílo démonskoje ne soďíjach; kóje ďijánije stúdnoje í blúdnoje ne s preimúščestvom í tščánijem soverších; úm vospomináňmi plotskími óskverních, ťílo smišéňmi ókaľách, dúch sosložénijem óskverních: vsják úd ókajánnyja mojejá plóti služíti í rabótati hrichóm vozľubích. Í któ próčeje ne vozrydájet mjá ókajánnaho; któ ne vospláčet mjá ósuždénnaho; áz bo jédín, Vladýko, járosť tvojú prohňívach: áz jédín hňív tvój na mjá razžehóch: áz jédín lukávoje pred tobóju sotvorích, prevozšéd í prepobidív vsjá ot víka hríšniki, nesravnénno pohrišívyj, í neproščénno. No ponéže mnohomílostivyj í bláhoutróbnyj jésí čelovikoľúbče, í óžidáješi čelovíčeskaho óbraščénija: sé í áz vverháju sebé pred strášnoje í nesterpímoje tvojé sudíšče, í jákože prečestym tvoím nohám kasájajsja, íz hlubiný duší vzyváju tí: óčísti Hospodi, prostí bláhopreminíteľu, pomíluj némošč mojú, priklonísja nedoumíniju mojemú, vonmí moléniju mojemú, í sléz mojích ne premolčí. prijimí mja kájuščahosja, í zablúždšaho óbratí: óbraščájuščahosja óbimí, í moľáščahosja prostí. Ne bó položíl jésí pokajánije právednym, ne položíl jésí proščénije nesohrišájuščym: no položíl jésí pokajánije mňí hríšnomu, v níchže v nehodovánije tvojé soďíjach. náh í óbnažén pred tobóju predstojú, serdcevídče Hospodi, íspovídajaj mojá hrichí: ne bó mohú vozzríti í víďiti vysotú nebésnuju, ot ťážesti hrichóv mojích sľacájem. Prosvití úbo óči sérdca mojehó, í dážď mí úmilénije k pokajániju í sokrušénije sérdca ko íspravléniju: da so bláhóju nadéždeju, í ístinnym úvirénijem, k támošnemu míru pojdú, chvaľá í bláhoslovjá výnu vsesvjatóje ímja tvojé, Ótcá, í Sýna, í svjatáho Dúcha, nýňi í prísno, í vo víki vikóv, ámíň."),
  ))
])
