#import "../../../../all.typ": *
= #translation.at("KAFTIZMA") 11

#columns(2, gutter: 2pt, [

== #translation.at("ANTIFON") 1
  #generateTable((
    "",
    sText([Rázuma ásáfu, (#translation.at("PSALM") 77)]),
    gText("1"),
    par([Vnemlíte, ľúdije moí, zakónu mojemú, prikloníte úcho váše vo hlahóly úst mojích.]),
    gText("2"),
    par([Otvérzu v prítčach ústá mojá, proviščáju hanánija íspérva.]),
    gText("3"),
    par([Jélíka slýšachom í poznáchom já, í ótcý náši povídaša nám:]),
    gText("4"),
    par([Ne útaíšasja ot čád ích v ród ín, vozviščájušče chvalý Hospodni, í síly jéhó í čudesá jéhó, jáže sotvorí.]),
    gText("5"),
    par([Í vozdvíže sviďínije vo Jákovi, í zakón položí vo Izráili, jélíka zapovída ótcém nášym skazáti já synovóm svoím,]),
    gText("6"),
    par([Jáko da poznájet ród ín, sýnove roďáščijisja, í vostánut í povíďat já synovóm svoím:]),
    gText("7"),
    par([Da položát na Boha úpovánije svojé, í ne zabúdut ďíl Božijich, í zápovidi jéhó vzýščut:]),
    gText("8"),
    par([Da ne búdut jákože ótcý ích, ród stroptív í preohorčevájaj, ród íže ne ísprávi sérdca svojehó í ne úvíri s Bohom dúcha svojehó.]),
    gText("9"),
    par([Sýnove jéfrémli naľacájušče í striľájušče lúki vozvratíšasja v déň bráni:]),
    gText("10"),
    par([Ne sochraníša zavíta Božija, í v zakóňi jéhó ne voschoťíša chodíti.]),
    gText("11"),
    par([Í zabýša bláhoďijánija jéhó í čudesá jéhó, jáže pokazá ím]),
    gText("12"),
    par([Pred ótcý ích, jáže sotvorí čudesá v zemlí jéhýpetsťij, na póli taneósi:]),
    gText("13"),
    par([Razvérze móre í provedé ích: predstávi vódy jáko mích,]),
    gText("14"),
    par([Í nastávi já óblakom vo dní í vsjú nóšč prosviščénijem óhňá.]),
    gText("15"),
    par([Razvérze kámeň v pustýni í napoí já jáko v bézdňi mnózi:]),
    gText("16"),
    par([Í ízvedé vódu íz kámene í nizvedé jáko ríki vódy.]),
    gText("17"),
    par([Í priložíša jéščé sohrišáti jémú, preohorčíša výšňaho v bezvódňij:]),
    gText("18"),
    par([Í ískusíša Boha v serdcách svojích, vosprosíti brášna dušám svoím.]),
    gText("19"),
    par([Í klevetáša na Boha í ríša: jédá vozmóžet Boh úhotóvati trapézu v pustýni;]),
    gText("20"),
    par([Ponéže porazí kámeň, í potekóša vódy, í potócy navodníšasja: jédá í chľíb móžet dáti; ílí úhotóvati trapézu ľúdem svoím;]),
    gText("21"),
    par([Sehó rádi slýša Hospoď í prezrí, í óhň vozhorísja vo Jákovi, í hňív vzýde na Izráiľa:]),
    gText("22"),
    par([Jáko ne vírovaša Bohovi, nižé úpováša na Spasénije jéhó.]),
    gText("23"),
    par([Í zapovída óblakóm svýše, í dvéri nebesé otvérze:]),
    gText("24"),
    par([Í ódoždí ím mánnu jásti, í chľíb nebésnyj dadé ím.]),
    gText("25"),
    par([Chľíb Anheľskij jádé čelovík: brášno poslá ím do sýtosti.]),
    gText("26"),
    par([Vozdvíže júh s nebesé, í navedé síloju svojéju líva:]),
    gText("27"),
    par([Í ódoždí na ňá jáko prách plóti, í jáko pesók morskíj ptícy pernáty.]),
    gText("28"),
    par([Í napadóša posreďí stána ích, ókrest žilíšč ích.]),
    gText("29"),
    par([Í jádóša í nasýtišasja ziló, í želánije ích prenesé ím.]),
    gText("30"),
    par([Ne lišíšasja ot želánija svojehó: jéščé brášnu súšču vo úsťích ích,]),
    gText("31"),
    par([Í hňív Božij vzýde na ňá, í úbí mnóžajšaja ích, í ízbránnym Izráilevym zapját.]),
    gText("32"),
    par([Vo vsích sích sohrišíša jéščé í ne vírovaša čudesém jéhó:]),
    gText("33"),
    par([Í ísčezóša v sujeťí dníe ích, í ľíta ích so tščánijem.]),
    gText("34"),
    par([Jéhdá úbiváše já, tohdá vzyskáchu jéhó í óbraščáchusja í útrenevachu k Bohu:]),
    gText("35"),
    par([Í pomjanúša, jáko Boh pomóščnik ím jésť, í Boh výšnij ízbáviteľ ím jésť:]),
    gText("36"),
    par([Í vozľubíša jéhó ústý svojími, í jázýkom svojím solháša jémú:]),
    gText("37"),
    par([Sérdce že ích ne bí právo s ním, nižé úvírišasja v zavíťi jéhó.]),
    gText("38"),
    par([Tój že jésť ščédr, í óčístit hrichí ích, í ne rastlít: í úmnóžit otvratíti járosť svojú, í ne razžžét vsehó hňíva svojehó.]),
    gText("39"),
    par([Í pomjanú, jáko plóť súť, dúch choďáj í ne óbraščájajsja:]),
    gText("40"),
    par([Koľkráty preohorčíša jéhó v pustýni, prohňívaša jéhó v zemlí bezvódňij;]),
    gText("41"),
    par([Í óbratíšasja, í ískusíša Boha, í svjatáho Izráileva razdražíša:]),
    gText("42"),
    par([Í ne pomjanúša rukí jéhó v déň, vóňže ízbávi já íz rukí óskorbľájuščaho:]),
    gText("43"),
    par([Jákože položí vo jéhýpťi známenija svojá, í čudesá svojá na póli taneósi:]),
    gText("44"),
    par([Í preloží v króv ríki ích í ístóčniki ích, jáko da ne pijút.]),
    gText("45"),
    par([Poslá na ňá pésija múchi, í pojadóša já, í žáby, í rastlí já:]),
    gText("46"),
    par([Í dadé rží plodý ích, í trudý ích pruhóm.]),
    gText("47"),
    par([Úbí hrádom vijnohrády ích í černíčije ích slánoju:]),
    gText("48"),
    par([Í predadé hrádu skotý ích, í ímínije ích óhňú.]),
    gText("49"),
    par([Poslá na ňá hňív járosti svojejá, járosť í hňív í skórb, poslánije áhhely ľútymi.]),
    gText("50"),
    par([Putesotvorí stezjú hňívu svojemú, í ne poščaďí ot smérti dúš ích, í skotý ích v smérti zakľučí:]),
    gText("51"),
    par([Í porazí vsjákoje pervoródnoje v zemlí jéhýpetsťij, načátok vsjákaho trudá ích v selénijich chámovych.]),
    gText("52"),
    par([Í vozdvíže jáko óvcy ľúdi svojá, í vozvedé já jáko stádo v pustýni:]),
    gText("53"),
    par([Í nastávi já na úpovánije, í ne úbojášasja: í vrahí ích pokrý móre.]),
    gText("54"),
    par([Í vvedé já v hóru svjatýni svojejá, hóru sijú, júže sťažá desníca jéhó.]),
    gText("55"),
    par([Í ízhná ot licá ích jázýki, í po žrébiju dadé ím (zémľu) úžem žrebodajánija, í vselí v selénijich ích koľína Izráileva.]),
    gText("56"),
    par([Í ískusíša í preohorčíša Boha výšňaho, í sviďínij jéhó ne sochraníša:]),
    gText("57"),
    par([Í otvratíšasja í otverhóšasja, jákože í ótcý ích: prevratíšasja v lúk razvraščén:]),
    gText("58"),
    par([Í prohňívaša jéhó v chólmich svojích, í vo ístukánnych svojích razdražíša jéhó.]),
    gText("59"),
    par([Slýša Boh í prezrí, í úničiží ziló Izráiľa:]),
    gText("60"),
    par([Í otrínu skíniju silómskuju, selénije jéže #footnote("selénije svojé, íďíže") vselísja v čelovícich:]),
    gText("61"),
    par([Í predadé v pľín kríposť ích, í dobrótu ích v rúki vrahóv:]),
    gText("62"),
    par([Í zatvorí vo órúžiji ľúdi svojá í dostojánije svojé prezrí.]),
    gText("63"),
    par([Ю́nošy ích pojadé óhň, í ďívy ích ne ósítovany býša:]),
    gText("64"),
    par([Svjaščénnicy ích mečém padóša, í vdovícy ích ne óplákany búdut.]),
    gText("65"),
    par([Í vostá jáko spjá Hospoď, jáko sílen í šúmen ot vijná:]),
    gText("66"),
    par([Í porazí vrahí svojá vspjáť, ponošénije víčnoje dadé ím:]),
    gText("67"),
    par([Í otrínu selénije Jósifovo, í koľíno jéfrémovo ne ízbrá:]),
    gText("68"),
    par([Í ízbrá koľíno íúdovo, hóru sijóňu, júže vozľubí:]),
    gText("69"),
    par([Í sozdá jáko jédinoróha svjatílišče svojé: na zemlí ósnová í v vík.]),
    gText("70"),
    par([Í ízbrá Davida rabá svojehó, í vospriját jéhó ot stád óvčich:]),
    gText("71"),
    par([Ot dojílic poját jéhó, pastí Jákova rabá svojehó, í Izráiľa dostojánije svojé.]),
    gText("72"),
    par([Í úpasé já v nezlóbiji sérdca svojehó, í v rázumich rukú svoéju nastávil já jésť.]),
    col2(gText([#translation.at("SI")])),
  ))
== #translation.at("ANTIFON") 2
  #generateTable((
    "",
    sText([Psalóm ásáfu, (#translation.at("PSALM") 78)]),
    gText("1"),
    par([Bože, prijidóša jázýcy v dostojánije tvojé, óskverníša chrám svjatýj tvój,]),
    gText("2"),
    par([Položíša Jerúsaľím jáko óvóščnoje chranílišče: položíša trúpija ráb tvojích brášno ptícam nebésnym, plóti prepodóbnych tvojích zvirém zemným:]),
    gText("3"),
    par([Prolijáša króv ích jáko vódu ókrest Jerúsaľíma, í ne bí pohrebájaj.]),
    gText("4"),
    par([Býchom ponošénije sosídom nášym, podražnénije í poruhánije súščym ókrest nás.]),
    gText("5"),
    par([Dokóľi, Hospodi, prohňívaješisja do koncá; razžžétsja jáko óhň rvénije tvojé;]),
    gText("6"),
    par([Proléj hňív tvój na jázýki neznájuščyja tebé, í na cárstvija, jáže ímene tvojehó ne prizváša:]),
    gText("7"),
    par([Jáko pojadóša Jákova, í místo jéhó ópustošíša.]),
    gText("8"),
    par([Ne pomjaní nášich bezzakónij pérvych: skóro da predvarját ný ščedróty tvojá, Hospodi, jáko óbniščáchom ziló.]),
    gText("9"),
    par([Pomozí nám, Bože, Spasíteľu náš, slávy rádi ímene tvojehó: Hospodi, ízbávi ný í óčísti hrichí náša ímene rádi tvojehó.]),
    gText("10"),
    par([Da ne kohdá rekút jázýcy: hďí jésť Boh ích; í da úvístsja vo jázýcich pred óčíma nášima otmščénije króve ráb tvojích prolitýja.]),
    gText("11"),
    par([Da vnídet pred ťá vozdychánije ókovánnych: po velíčiju mýšcy tvojejá snabdí sýny úmerščvlénnych.]),
    gText("12"),
    par([Vozdážď sosídom nášym sedmeríceju v ňídro ích ponošénije ích, ímže ponosíša ťá, Hospodi.]),
    gText("13"),
    par([Mý že ľúdije tvoí í óvcy pážiti tvojejá íspovímysja tebí, Bože, vo vík, v ród í ród vozvistím chvalú tvojú.]),
    gText("1"),
    sText([V konéc, ó ízmínšichsja, sviďínije ásáfu, psalóm (#translation.at("PSALM") 79)]),
    gText("2"),
    par([Pasýj Izráiľa vonmí: nastavľájaj jáko óvčá Jósifa, siďáj na cheruvímich, jávísja:]),
    gText("3"),
    par([Pred jéfrémom í venijamínom í manassíem vozdvíhni sílu tvojú, í prijidí vo jéže Spastí nás.]),
    gText("4"),
    par([Bože, óbratí ny, í prosvití licé tvojé, í spasémsja.]),
    gText("5"),
    par([Hospodi Bože síl, dokóľi hňívaješisja na molítvu ráb tvojích;]),
    gText("6"),
    par([Napitáješi nás chľíbom sléznym, í napojíši nás slezámi v míru.]),
    gText("7"),
    par([Položíl jésí nás v prerikánije sosídom nášym, í vrazí náši podražníša ný.]),
    gText("8"),
    par([Hospodi Bože síl, óbratí ny, í prosvití licé tvojé, í spasémsja.]),
    gText("9"),
    par([Vijnohrád íz jéhýpta prenésl jésí: ízhnál jésí jázýki, í nasadíl jésí í:]),
    gText("10"),
    par([Putesotvoríl jésí pred ním, í nasadíl jésí korénija jéhó, í íspólni zémľu.]),
    gText("11"),
    par([Pokrý hóry síň jéhó, í vítvija jéhó kédry Božija:]),
    gText("12"),
    par([Prostré rózhi jéhó #footnote("svojá") do mórja, í dáže do rík ótrasli jéhó #footnote("svojá").]),
    gText("13"),
    par([Vskúju nizložíl jésí óplót jéhó, í óbimájut í vsí mimochoďáščiji putém;]),
    gText("14"),
    par([Ózobá í vépr ot dubrávy, í úedinénnyj dívij pojadé í.]),
    gText("15"),
    par([Bože síl, óbratísja úbo, í prízri s nebesé í vížď, í posití vijnohrád séj:]),
    gText("16"),
    par([Í soverší í, jéhóže nasadí desníca tvojá, í na sýna čelovíčeskaho, jéhóže úkripíl jésí sebí.]),
    gText("17"),
    par([Požžén óhném í raskópan: ot zapreščénija licá tvojehó pohíbnut.]),
    gText("18"),
    par([Da búdet ruká tvojá na múža desnícy tvojejá í na sýna čelovíčeskaho, jéhóže úkripíl jésí sebí,]),
    gText("19"),
    par([Í ne otstúpim ot tebé: óživíši ný, í ímja tvojé prizovém.]),
    gText("20"),
    par([Hospodi Bože síl, óbratí ny, í prosvití licé tvojé, í spasémsja.]),
    gText("1"),
    sText([V konéc, ó točíľich, psalóm ásáfu, (#translation.at("PSALM") 80)]),
    gText("2"),
    par([Rádujtesja Bohu pomóščniku nášemu, vosklíknite Bohu Jákovľu:]),
    gText("3"),
    par([Prijimíte psalóm í dadíte tympán, psaltír krasén s húsľmi:]),
    gText("4"),
    par([Vostrubíte v novomísjačiji trubóju, vo bláhoznamenítyj déň prázdnika vášeho:]),
    gText("5"),
    par([Jáko poveľínije Izráilevi jésť, í suďbá Bohu Jákovľu.]),
    gText("6"),
    par([Sviďínije vo Jósifi položí jé, vnehdá ízýti jémú ot zemlí jéhýpetskija: jázýka, jéhóže ne víďaše, úslýša.]),
    gText("7"),
    par([Oťát ot brémene chrebét jéhó: rúci jéhó v koší porabótasťi.]),
    gText("8"),
    par([V skórbi prizvál mjá jésí, í ízbávich ťá: úslýšach ťá v tájňi búrňi: ískusích ťá na voďí prerikánija.]),
    gText("9"),
    par([Slýšite, ľúdije moí, í zasviďíteľstvuju vám, Izráiľu, ášče poslúšaješi mené:]),
    gText("10"),
    par([Ne búdet tebí bóh nóv, nižé pokloníšisja bóhu čuždému.]),
    gText("11"),
    par([Áz bo jésm Hospoď Boh tvój, ízvedýj ťá ot zemlí jéhýpetskija: razširí ústá tvojá, í íspólňu já.]),
    gText("12"),
    par([Í ne poslúšaša ľúdije moí hlása mojehó, í Izráiľ ne vňát mí:]),
    gText("13"),
    par([Í otpustích já po načinánijem serdéc ích, pójdut v načinánijich svojích.]),
    gText("14"),
    par([Ášče býša ľúdije moí poslúšali mené, Izráiľ ášče by v putí mojá chodíl:]),
    gText("15"),
    par([Ni ó česóm že úbo vrahí jéhó smiríl bých, í na óskorbľájuščyja ích vozložíl bých rúku mojú.]),
    gText("16"),
    par([Vrazí Hospodni solháša jémú, í búdet vrémja ích v vík:]),
    gText("17"),
    par([Í napitá ích ot túka pšeníčna, í ot kámene méda nasýti ích.]),
    col2(gText([#translation.at("SI")])),
  ))
== #translation.at("ANTIFON") 3
  #generateTable((
    "",
    sText([Psalóm ásáfu, (#translation.at("PSALM") 81)]),
    gText("1"),
    par([Boh stá v sónmi bohóv, posreďí že bóhi razsúdit.]),
    gText("2"),
    par([Dokóľi súdite neprávdu, í líca hríšnikov prijémlete;]),
    gText("3"),
    par([Sudíte síru í úbóhu, smiréna í níšča ópravdájte:]),
    gText("4"),
    par([Ízmíte níšča í úbóha, íz rukí hríšniči ízbávite jéhó.]),
    gText("5"),
    par([Ne poznáša, nižé úrazumíša, vo tmí chóďat: da podvížatsja vsjá ósnovánija zemlí.]),
    gText("6"),
    par([Áz rích: bózi jésté, í sýnove výšňaho vsí:]),
    gText("7"),
    par([Vý že jáko čelovícy úmirájete, í jáko jédín ot kňazéj pádajete.]),
    gText("8"),
    par([Voskresní, Bože, sudí zemlí: jáko tý nasľídiši vo vsích jázýcich.]),
    gText("1"),
    sText([Písň psalmá ásáfu, (#translation.at("PSALM") 82)]),
    gText("2"),
    par([Bože, któ úpodóbitsja tebí; ne premolčí, nižé úkrotí #footnote("nižé úkrotísja"), Bože:]),
    gText("3"),
    par([Jáko sé, vrazí tvoí vozšumíša, í nenavíďaščiji ťá vozdvihóša hlavú.]),
    gText("4"),
    par([Na ľúdi tvojá lukávnovaša vóleju, í soviščáša na svjatýja tvojá.]),
    gText("5"),
    par([Ríša: prijidíte í potrebím já ot jázýk, í ne pomjanétsja ímja Izráilevo ktomú.]),
    gText("6"),
    par([Jáko soviščáša jédinomyšlénijem vkúpi, na ťá zavít zaviščáša:]),
    gText("7"),
    par([Selénija íduméjska í ísmáilijte, moáv í áhárjane,]),
    gText("8"),
    par([Hevál í ámmón í ámalík, ínopleménnicy s živúščimi v týri:]),
    gText("9"),
    par([Íbo í ássúr prijíde s ními, býša v zastuplénije synovóm lótovym:]),
    gText("10"),
    par([Sotvorí ím jáko madijámu í sijsári, jáko íavímu v potóci kíssovi:]),
    gText("11"),
    par([Potrebíšasja vo áendóri, býša jáko hnój zemnýj.]),
    gText("12"),
    par([Položí kňázi ích jáko óríva í zíva, í zevéa í salmána, vsjá kňázi ích,]),
    gText("13"),
    par([Íže ríša: da nasľídim sebí svjatílišče Božije.]),
    gText("14"),
    par([Bože mój, položí já jáko kólo, jáko trósť pred licém vítra.]),
    gText("15"),
    par([Jáko óhň popaľájaj dubrávy, jáko plámeň požihájaj hóry:]),
    gText("16"),
    par([Táko poženéši já búreju tvojéju, í hňívom tvojím smjatéši já.]),
    gText("17"),
    par([Íspólni líca ích bezčéstija, í vzýščut ímene tvojehó, Hospodi.]),
    gText("18"),
    par([Da postyďátsja í smjatútsja v vík víka, í posrámjatsja í pohíbnut.]),
    gText("19"),
    par([Í da poznájut, jáko ímja tebí Hospoď, tý jédín výšnij po vséj zemlí.]),
    gText("1"),
    sText([V konéc, ó točíľich, synóm koréovym, psalóm, (#translation.at("PSALM") 83)]),
    gText("2"),
    par([Kóľ vozľúblenna selénija tvojá, Hospodi síl.]),
    gText("3"),
    par([Želájet í skončavájetsja dušá mojá vo dvorý Hospodni: sérdce mojé í plóť mojá vozrádovastasja ó Bózi žívi.]),
    gText("4"),
    par([Íbo ptíca óbríte sebí chráminu, í hórlica hňizdó sebí, íďíže položít ptencý svojá, óltarí tvojá, Hospodi síl, cerjú mój í Bože mój.]),
    gText("5"),
    par([Blážéni živúščiji v domú tvojém: v víki vikóv voschváľat ťá.]),
    gText("6"),
    par([Blážén múž, jémúže jésť zastuplénije jéhó ú tebé: voschoždénija v sérdcy svojém položí,]),
    gText("7"),
    par([Vo júdóľ plačévnuju, v místo jéže položí #footnote("vo júdóli plačévňij, v mísťi, jéže položí:") íbo bláhoslovénije dást zakonopolahájaj.]),
    gText("8"),
    par([Pójdut ot síly v sílu: jávítsja Boh bohóv v sijóňi.]),
    gText("9"),
    par([Hospodi Bože síl, úslýši molítvu mojú, vnuší, Bože Jákovľ.]),
    gText("10"),
    par([Zaščítniče náš, vížď, Bože, í prízri na licé chrijstá tvojehó.]),
    gText("11"),
    par([Jáko lúčše déň jédín vo dvórich tvojích páče týsjašč: ízvólich primetátisja v domú Boha mojehó páče, néže žíti mí v selénijich hríšničich.]),
    gText("12"),
    par([Jáko mílosť í ístinu ľúbit Hospoď, Boh blh-d*ť í slávu dást: Hospoď ne lišít bláhích choďáščich nezlóbijem.]),
    gText("13"),
    par([Hospodi Bože síl, blážén čelovík úpovájaj na ťá.]),
    gText("1"),
    sText([V konéc, synóm koréovym, psalóm, (#translation.at("PSALM") 84)]),
    gText("2"),
    par([Bláhovolíl jésí, Hospodi, zémľu tvojú, vozvratíl jésí pľín Jákovľ.]),
    gText("3"),
    par([Óstávil jésí bezzakónija ľudéj tvojích, pokrýl jésí vsjá hrichí ích.]),
    gText("4"),
    par([Úkrotíl jésí vés hňív tvój, vozvratílsja jésí ot hňíva járosti tvojejá.]),
    gText("5"),
    par([Vozvratí nás, Bože Spasénij nášich, í otvratí járosť tvojú ot nás.]),
    gText("6"),
    par([Jédá vo víki prohňívaješisja na ný; ílí prostréši hňív tvój ot róda v ród;]),
    gText("7"),
    par([Bože, tý óbráščsja óživíši ný, í ľúdije tvoí vozveseľátsja ó tebí.]),
    gText("8"),
    par([Jáví nám, Hospodi, mílosť tvojú, í Spasénije tvojé dážď nám.]),
    gText("9"),
    par([Úslýšu, čtó rečét ó mňí Hospoď Boh: jáko rečét mír na ľúdi svojá, í na prepodóbnyja svojá, í na óbraščájuščyja serdcá k nemú.]),
    gText("10"),
    par([Óbáče blíz bojáščichsja jéhó Spasénije jéhó, vselíti slávu v zémľu nášu.]),
    gText("11"),
    par([Mílosť í ístina sritósťisja, právda í mír óblobyzástasja:]),
    gText("12"),
    par([Ístina ot zemlí vozsijá, í právda s nebesé priníče:]),
    gText("13"),
    par([Íbo Hospoď dást bláhosť, í zemľá náša dást plód svój.]),
    gText("14"),
    par([Právda pred ním predídet, í položít v púť stopý svojá.]),
    col2(gText([#translation.at("SI")])),
  ))
  #generateTable((
    col2(sText(translation.at("AFTER_KAFTIZMA"))),
    sText("T"),
    jObj4("",7, "", "Ímúšči dušé mojá vračevstvó pokajánija, pristupí, slezjášči, vozdychánijem vopijúšči: vračú dúš í ťilés svobodí mjá čelovikoľúbče, ot mnóhich sohrišénij. sopričtí mja bludníci, í razbójniku, í mytarjú: í dáruj mí Bože, bezzakónij mojích proščénije, í Spasí mja."),
    
    // S:
    col2(gText(translation.at("S"))),
    "",
    jObj4("",none, "", "Mytarévu pokajániju ne porevnovách, í bludnícy sléz ne sťažách: nedoumíjusja bo ot ósľiplénija ó takovóm íspravléniji: no tvojím bláhoutróbijem Spasí mja Christé Bože, jáko čelovikoľúbec."),
    
    // I:
    col2(gText(translation.at("IN"))),
    "",
    jObj4("",none, "", "Bohoródice Ďivo neskvérnaja, Sýna tvojehó molí s hórnimi sílami, proščénije prehrišénij nám préžde koncá darováti, í véliju mílosť."),
    col2(translation.at("HOSPODI_POMILUJ")+". "+sText("(40)")),
    col2(sText(translation.at("MOLITVA"))),
    "",
    jObj4("",none, "", "Vozsijáj v serdcách nášich čelovikoľúbče Hospodi, tvojehó Bohovíďinija netľínnyj svít, í mýslennyja náša otvérzi óči, vo jéy-h**ľskich tvojích propovídanij razumínije: vloží v nás í blážénnych tvojích zápovidej strách, da plotskíja póchoti vsjá poprávše, Dúchóvnoje žíteľstvo prójdem, vsjá jáže ko bláhouhoždéniju tvojemú í múdrstvujušče í ďíjušče. Tý bo jésí prosviščénije dúš í ťilés nášich Christé Bože, í tebí slávu vozsylájem so beznačáľnym tvojím Ótcém, í vsesvjatým í bláhím í životvorjáščim tvojím Dúchom, nýňi í prísno í vo víki vikóv, ámíň."),
  ))
])
