#import "../../../../all.typ": *
= #translation.at("KAFTIZMA") 12

#columns(2, gutter: 2pt, [

== #translation.at("ANTIFON") 1
  #generateTable((
    "",
    sText([Molitva Davidu, (#translation.at("PSALM") 85)]),
    gText("1"),
    par([Prikloní, Hospodi, úcho tvojé, í úslýši mjá: jáko níšč í úbóh jésm áz.]),
    gText("2"),
    par([Sochraní dúšu mojú, jáko prepodóben jésm: Spasí rabá tvojehó, Bože mój, úpovájuščaho na ťá.]),
    gText("3"),
    par([Pomíluj mjá, Hospodi, jáko k tebí vozzovú vés déň.]),
    gText("4"),
    par([Vozveselí dúšu rabá tvojehó: jáko k tebí vzjách dúšu mojú.]),
    gText("5"),
    par([Jáko tý, Hospodi, bláh í krótok í mnohomílostiv vsím prizyvájuščym ťá.]),
    gText("6"),
    par([Vnuší, Hospodi, molítvu mojú í vonmí hlásu molénija mojehó.]),
    gText("7"),
    par([V déň skórbi mojejá vozzvách k tebí, jáko úslýšal mjá jésí.]),
    gText("8"),
    par([Nísť podóben tebí v bozích, Hospodi, í ňísť po ďilóm tvoím.]),
    gText("9"),
    par([Vsí jázýcy, jélíki sotvoríl jésí, prijídut í poklóňatsja pred tobóju, Hospodi, í proslávjat ímja tvojé:]),
    gText("10"),
    par([Jáko vélij jésí tý í tvorjáj čudesá, tý jésí Boh jédín.]),
    gText("11"),
    par([Nastávi mjá, Hospodi, na púť tvój, í pojdú vo ístiňi tvojéj: da vozveselítsja sérdce mojé bojátisja ímene tvojehó.]),
    gText("12"),
    par([Íspovímsja tebí, Hospodi Bože mój, vsím sérdcem mojím í proslávľu ímja tvojé v vík:]),
    gText("13"),
    par([Jáko mílosť tvojá vélija na mňí, í ízbávil jésí dúšu mojú ot áda preispódňijšaho.]),
    gText("14"),
    par([Bože, zakonoprestúpnicy vostáša na mjá, í sónm deržávnych vzyskáša dúšu mojú, í ne predložíša tebé pred sobóju.]),
    gText("15"),
    par([Í tý, Hospodi Bože mój, ščédryj í mílostivyj, dolhoterpilívyj í mnohomílostivyj í ístinnyj,]),
    gText("16"),
    par([Prízri na mjá í pomíluj mjá: dážď deržávu tvojú ótroku tvojemú í Spasí sýna rabý tvojejá.]),
    gText("17"),
    par([Sotvorí so mnóju známenije vo bláho: í da víďat nenavíďaščiji mjá, í postyďátsja, jáko tý, Hospodi, pomóhl mí í úťíšil mjá jésí.]),
    gText("1"),
    sText([Synóm koréovym, psalóm písni, (#translation.at("PSALM") 86)]),
    gText("2"),
    par([Ósnovánija jéhó na horách svjatých: ľúbit Hospoď vratá sijóňa páče vsích selénij Jákovlich.]),
    gText("3"),
    par([Preslávnaja hlahólašasja ó tebí, hráde Božij.]),
    gText("4"),
    par([Pomjanú raáv í vavylóna víduščym mjá: í sé, ínopleménnicy í týr í ľúdije jéthijópstiji, síji býša támo.]),
    gText("5"),
    par([Máti Sijón rečét: čelovík í čelovík rodísja v ném, í tój ósnová í výšnij.]),
    gText("6"),
    par([Hospoď povísť v pisániji ľudéj í kňazéj, sích bývšich v ném.]),
    gText("7"),
    par([Jáko veseľáščichsja vsích žilíšče v tebí.]),
    gText("8"),
    par([Písň psalmá synóm koréovym, v konéc, ó majeléthi jéže]),
    "",
    sText([otviščáti, rázuma jémánu Izráiľťaninu, (#translation.at("PSALM") 87)]),
    gText("1"),
    par([Hospodi Bože Spasénija mojehó, vo dní vozzvách í v noščí pred tobóju:]),
    gText("2"),
    par([Da vnídet pred ťá molítva mojá, prikloní úcho tvojé k moléniju mojemú.]),
    gText("3"),
    par([Jáko íspólnisja zól dušá mojá, í živót mój ádu priblížisja.]),
    gText("4"),
    par([Privminén bých s nizchoďáščimi v róv: bých jáko čelovík bez pómošči,]),
    gText("5"),
    par([V mértvych svobóď: jáko jázvenniji spjáščiji vo hróbi, íchže ne pomjanúl jésí ktomú, í tíji ot rukí tvojejá otrinovéni býša.]),
    gText("6"),
    par([Položíša mjá v róvi preispódňim, v témnych í síni smértňij.]),
    gText("7"),
    par([Na mňí útverdísja járosť tvojá, í vsjá vólny tvojá navél jésí na mjá.]),
    gText("8"),
    par([Údálil jésí znájemych mojích ot mené: položíša mjá mérzosť sebí: prédan bých í ne íschoždách.]),
    gText("9"),
    par([Óči moí íznemohósťi ot niščetý: vozzvách k tebí, Hospodi, vés déň, vozďích k tebí rúci moí.]),
    gText("10"),
    par([Jédá mértvymi tvoríši čudesá; ílí vráčeve voskresját, í íspovíďatsja tebí;]),
    gText("11"),
    par([Jédá povísť któ vo hróbi mílosť tvojú, í ístinu tvojú v pohíbeli;]),
    gText("12"),
    par([Jédá poznána búdut vo tmí čudesá tvojá, í právda tvojá v zemlí zabvénňij;]),
    gText("13"),
    par([Í áz k tebí, Hospodi, vozzvách, í útro molítva mojá predvarít ťá.]),
    gText("14"),
    par([Vskúju, Hospodi, otríeši dúšu mojú; otvraščáješi licé tvojé ot mené;]),
    gText("15"),
    par([Níšč jésm áz, í v truďích ot júnosti mojejá: voznés že sja smiríchsja í íznemohóch.]),
    gText("16"),
    par([Na mňí preidóša hňívi tvoí, ústrašénija tvojá vozmutíša mjá:]),
    gText("17"),
    par([Óbydóša mjá jáko vodá vés déň, óderžáša mjá vkúpi.]),
    gText("18"),
    par([Údálil jésí ot mené drúha í ískrenňaho, í znájemych mojích ot strastéj.]),
    col2(gText([#translation.at("SI")])),
  ))
== #translation.at("ANTIFON") 2
  #generateTable((
    gText("1"),
    sText([Rázuma jétháma Izráiľťanina, (#translation.at("PSALM") 88)]),
    gText("2"),
    par([Mílosti tvojá, Hospodi, vo vík vospojú, v ród í ród vozviščú ístinu tvojú ústý mojími.]),
    gText("3"),
    par([Zané rékl jésí: v vík mílosť sozíždetsja: na nebesích úhotóvitsja ístina tvojá.]),
    gText("4"),
    par([Zaviščách zavít ízbránnym moím, kľáchsja Davidu rabú mojemú:]),
    gText("5"),
    par([Do víka úhotóvaju símja tvojé, í sozíždu v ród í ród prestól tvój.]),
    gText("6"),
    par([Íspovíďat nebesá čudesá tvojá, Hospodi, íbo ístinu tvojú v cerkvi svjatých.]),
    gText("7"),
    par([Jáko któ vo óblacich úravnítsja Hospodevi; úpodóbitsja Hospodevi v syňích Božijich;]),
    gText("8"),
    par([Boh proslavľájem v sovíťi svjatých, vélij í strášen jésť nad vsími ókréstnymi jéhó.]),
    gText("9"),
    par([Hospodi Bože síl, któ podóben tebí; sílen jésí, Hospodi, í ístina tvojá ókrest tebé.]),
    gText("10"),
    par([Tý Vladíčiestvuješi deržávoju morskóju: vozmuščénije že vóln jéhó tý úkročáješi.]),
    gText("11"),
    par([Tý smiríl, jésí, jáko jázvena, hórdaho: mýšceju síly tvojejá rastočíl jésí vrahí tvojá.]),
    gText("12"),
    par([Tvojá súť nebesá, í tvojá jésť zemľá: vselénnuju í íspolnénije jéjá tý ósnovál jésí.]),
    gText("13"),
    par([Síver í móre tý sozdál jésí: thavór í jérmón ó ímeni tvojém vozrádujetasja.]),
    gText("14"),
    par([Tvojá mýšca s síloju: da úkripítsja ruká tvojá, í voznesétsja desníca tvojá.]),
    gText("15"),
    par([Právda í suďbá úhotóvanije prestóla tvojehó: mílosť í ístina predídeťi pred licém tvojím.]),
    gText("16"),
    par([Blážéni ľúdije víduščiji voskliknovénije: Hospodi, vo svíťi licá tvojehó pójdut,]),
    gText("17"),
    par([Í ó ímeni tvojém vozrádujutsja vés déň, í právdoju tvojéju voznesútsja.]),
    gText("18"),
    par([Jáko pochvalá síly ích tý jésí, í vo bláhovoléniji tvojém voznesétsja róh náš:]),
    gText("19"),
    par([Jáko Hospodne jésť zastuplénije, í svjatáho Izráileva cerjá nášeho.]),
    gText("20"),
    par([Tohdá hlahólal jésí v viďíniji synovóm tvoím, í rékl jésí: položích pómošč na síľnaho, voznesóch ízbránnaho ot ľudéj mojích:]),
    gText("21"),
    par([Óbritóch Davida rabá mojehó, jéléem svjatým mojím pomázach jéhó.]),
    gText("22"),
    par([Íbo ruká mojá zastúpit jéhó, í mýšca mojá úkripít jéhó:]),
    gText("23"),
    par([Ničtóže úspíet vráh na nehó, í sýn bezzakónija ne priložít ózlóbiti jéhó.]),
    gText("24"),
    par([Í ssikú ot licá jéhó vrahí jéhó, í nenavíďaščyja jéhó pobiždú:]),
    gText("25"),
    par([Í ístina mojá í mílosť mojá s ním, í ó ímeni mojém voznesétsja róh jéhó:]),
    gText("26"),
    par([Í položú na móri rúku jéhó, í na rikách desnícu jéhó.]),
    gText("27"),
    par([Tój prizovét mjá: Ótc mój jésí tý, Boh mój í zastúpnik Spasénija mojehó.]),
    gText("28"),
    par([Í áz pérvenca položú jéhó, vysoká páče caréj zemných:]),
    gText("29"),
    par([V vík sochraňú jémú mílosť mojú, í zavít mój víren jémú:]),
    gText("30"),
    par([Í položú v vík víka símja jéhó, í prestól jéhó jáko dníe néba.]),
    gText("31"),
    par([Ášče óstávjat sýnove jéhó zakón mój, í v suďbách mojích ne pójdut:]),
    gText("32"),
    par([Ášče ópravdánija mojá óskverňát, í zápovidij mojích ne sochraňát:]),
    gText("33"),
    par([Posiščú žezlóm bezzakónija ích, í ránami neprávdy ích,]),
    gText("34"),
    par([Mílosť že mojú ne razorjú ot ních, ni prevreždú vo ístiňi mojéj:]),
    gText("35"),
    par([Nižé óskverňú zavíta mojehó, í íschoďáščich ot úst mojích ne otvérhusja.]),
    gText("36"),
    par([Jédínoju kľáchsja ó svjatím mojém: ášče Davidu solžú;]),
    gText("37"),
    par([Símja jéhó vo vík prebúdet, í prestól jéhó jáko sólnce predo mnóju,]),
    gText("38"),
    par([Í jáko luná soveršéna v vík, í sviďíteľ na nebesí víren.]),
    gText("39"),
    par([Tý že otrínul jésí í úničižíl, nehodovál jésí pomázannaho tvojehó:]),
    gText("40"),
    par([Razoríl jésí zavít rabá tvojehó, óskverníl jésí na zemlí svjatýňu jéhó:]),
    gText("41"),
    par([Razoríl jésí vsjá óplóty jéhó, položíl jésí tvérdaja jéhó strách.]),
    gText("42"),
    par([Raschiščáchu jéhó vsí mimochoďáščiji putém, býsť ponošénije sosídom svoím.]),
    gText("43"),
    par([Vozvýsil jésí desnícu stužájuščich jémú, vozveselíl jésí vsjá vrahí jéhó:]),
    gText("44"),
    par([Otvratíl jésí pómošč mečá jéhó í ne zastupíl jésí jéhó vo bráni:]),
    gText("45"),
    par([Razoríl jésí ot óčiščénija jéhó, prestól jéhó na zémľu povérhl jésí:]),
    gText("46"),
    par([Úmálil jésí dní vrémene jéhó, óblijál jésí jéhó studóm.]),
    gText("47"),
    par([Dokóľi, Hospodi, otvraščáješisja v konéc, razžžétsja jáko óhň hňív tvój;]),
    gText("48"),
    par([Pomjaní, kíj mój sostáv: jédá bo vsúje sozdál jésí vsjá sýny čelovíčeskija;]),
    gText("49"),
    par([Któ jésť čelovík, íže poživét í ne úzrit smérti, ízbávit dúšu svojú íz rukí ádovy;]),
    gText("50"),
    par([ďí súť mílosti tvojá drévnija, Hospodi, ímiže kľálsja jésí Davidu vo ístiňi tvojéj;]),
    gText("51"),
    par([Pomjaní, Hospodi, ponošénije ráb tvojích, jéže úderžách v ňídri mojém mnóhich jázýk:]),
    gText("52"),
    par([Ímže ponosíša vrazí tvoí, Hospodi, ímže ponosíša ízminéniju chrijstá tvojehó.]),
    gText("53"),
    par([Bláhoslovén Hospoď vo vík: búdi, búdi.]),
    col2(gText([#translation.at("SI")])),
  ))
== #translation.at("ANTIFON") 3
  #generateTable((
    gText("1"),
    sText([Molitva moyséa čelovíka Božija, (#translation.at("PSALM") 89)]),
    gText("2"),
    par([Hospodi, pribížišče býl jésí nám v ród í ród.]),
    gText("3"),
    par([Préžde dáže horám ne býti í sozdátisja zemlí í vselénňij, í ot víka í do víka tý jésí.]),
    gText("4"),
    par([Ne otvratí čelovíka vo smirénije, í rékl jésí: óbratítesja, sýnove čelovíčestiji.]),
    gText("5"),
    par([Jáko týsjašča ľít pred óčíma tvojíma, Hospodi, jáko déň včerášnij, íže mímo íde, í stráža noščnája.]),
    gText("6"),
    par([Úničižénija ích ľíta búdut: útro jáko travá mímo ídet, útro procvitét í préjdet: na véčer otpadét, óžesťíet í ízschnet:]),
    gText("7"),
    par([Jáko ísčezóchom hňívom tvojím, í járostiju tvojéju smutíchomsja.]),
    gText("8"),
    par([Položíl jésí bezzakónija náša pred tobóju, vík náš v prosviščénije licá tvojehó.]),
    gText("9"),
    par([Jáko vsí dníe náši óskuďíša, í hňívom tvojím ísčezóchom:]),
    gText("10"),
    par([Líta náša jáko paučína poučáchusja: dníe ľít nášich v níchže sédmdesjat ľít, ášče že v sílach, ósmdesjat ľít, í mnóžaje ích trúd í boľízň: jáko prijíde krótosť na ný, í nakážemsja.]),
    gText("11"),
    par([Któ vísť deržávu hňíva tvojehó, í ot strácha tvojehó járosť tvojú ísčestí;]),
    gText("12"),
    par([Desnícu tvojú táko skaží mi, í ókovánnyja #footnote("nakázannyja") sérdcem v múdrosti.]),
    gText("13"),
    par([Óbratísja, Hospodi, dokóľi; í úmolén búdi na rabý tvojá.]),
    gText("14"),
    par([Íspólnichomsja zaútra mílosti tvojejá, Hospodi, í vozrádovachomsja í vozveselíchomsja:]),
    gText("15"),
    par([Vo vsjá dní náša vozveselíchomsja, za dní, v ňáže smiríl ný jésí, ľíta, v ňáže víďichom zlája.]),
    gText("16"),
    par([Í prízri na rabý tvojá í na ďilá tvojá, í nastávi sýny ích.]),
    gText("17"),
    par([Í búdi svítlosť Hospoda Boha nášeho na nás, í ďilá rúk nášich ísprávi na nás, í ďílo rúk nášich ísprávi.]),
    "",
    sText([Chvalá písni Davidovy, ne nadpísan ú jévréj, (#translation.at("PSALM") 90)]),
    gText("1"),
    par([Živýj v pómošči výšňaho, v króvi Boha nebésnaho vodvorítsja,]),
    gText("2"),
    par([Rečét Hospodevi: zastúpnik mój jésí í pribížišče mojé, Boh mój, í úpováju na nehó.]),
    gText("3"),
    par([Jáko tój ízbávit ťá ot síti lóvči í ot slovesé mjatéžna:]),
    gText("4"),
    par([Pleščmá svojíma ósinít ťá, í pod kriľí jéhó naďíešisja: órúžijem óbýdet ťá ístina jéhó.]),
    gText("5"),
    par([Ne úbojíšisja ot strácha noščnáho, ot strilý leťáščija vo dní,]),
    gText("6"),
    par([Ot véšči vo tmí prechoďáščija, ot srjášča #footnote("ot napadénija") í bísa polúdennaho.]),
    gText("7"),
    par([Padét ot straný tvojejá týsjašča, í tmá ódesnúju tebé, k tebí že ne priblížitsja:]),
    gText("8"),
    par([Óbáče óčíma tvojíma smótriši í vozdajánije hríšnikov úzriši.]),
    gText("9"),
    par([Jáko tý, Hospodi, úpovánije mojé: výšňaho položíl jésí pribížišče tvojé.]),
    gText("10"),
    par([Ne prijídet k tebí zló, í rána ne priblížitsja ťilesí tvojemú #footnote("seléniju tvojemú"):]),
    gText("11"),
    par([Jáko Anhelom svoím zapovísť ó tebí, sochraníti ťá vo vsích putéch tvojích.]),
    gText("12"),
    par([Na rukách vózmut ťá, da ne kohdá pretknéši ó kámeň nóhu tvojú:]),
    gText("13"),
    par([Na áspijda í vasijlíska nastúpiši, í poperéši ľvá í zmíja.]),
    gText("14"),
    par([Jáko na mjá úpová, í ízbávľu í: pokrýju í, jáko pozná ímja mojé.]),
    gText("15"),
    par([Vozzovét ko mňí, í úslýšu jéhó: s ním jésm v skórbi, ízmú jéhó í proslávľu jéhó:]),
    gText("16"),
    par([Dolhotóju dníj íspólňu jéhó í jávľú jémú Spasénije mojé.]),
    col2(gText([#translation.at("SI")])),
  ))
  #generateTable((
    col2(sText(translation.at("AFTER_KAFTIZMA"))),
    sText("T"),
    jObj4("",7, "", "Bludnícy slézy í petróvy prijémyj Hospodi, í mytarjá ópravdávyj, íz hlubiný vozdochnúvša: í mené vo úmiléniji pripádajušča úščédri Spase, í pomíluj mjá."),
    
    // S:
    col2(gText(translation.at("S"))),
    "",
    jObj4("",none, "", "Prijimí jáko mytarjá Hospodi, jáko bludnícu óčísti mjá Vladýko, jáko chananéju pomíluj, po velícij tvojéj mílosti."),
    
    // I:
    col2(gText(translation.at("IN"))),
    "",
    jObj4("",none, "", "Mati svíta bláhoslovénnaja Bohoródice, molísja Christú Bohu sovozsijáti útro, í véliju mílosť dušám nášym."),
    col2(translation.at("HOSPODI_POMILUJ")+". "+sText("(40)")),
    col2(sText(translation.at("MOLITVA"))),
    "",
    jObj4("",none, "", "Hospodi Bože mój, jédín bláhíj í čelovikoľubívyj, jédín mílostivyj í krótkij, jédín ístinnyj í právednyj, jédín ščédryj í mílostivyj Bože náš: da prijídet síla tvojá na mjá hríšnaho í nepotrébnaho rabá tvojehó, í da úkripít mój chrám jéy-h**lijem Božéstvennaho účénija tvojehó. Vladýko í čelovikoľúbče, ľubobláže, ľubobláhoutróbne, prosvití mojá útróby, í vsjá údy tvojéju vóleju: óčísti mjá ot vsjákija zlóby í hrichá, sobľudí mja neskvérna, í neporóčna ot vsjákaho naítija í ďíjstva dijávoľa, í dáruj mí po tvojéj bláhosti, tvojá razumíti, tvojá múdrstvovati, í v tvojích choťínijich žíti, tvojehó strácha strašítisja, jéže tvoríti tebí bláhouhódnaja do posľídňaho mojehó ízdychánija, jáko da po neispovidímoj tvojéj mílosti sobľudéši mojé ťílo í dúšu, úm že í mýsli, neiskušén vsjákija soprotivoležáščija síti chrám. Hospodi mój Hospodi, pokrýj mjá tvojím bláhoutróbijem, í ne óstávi mjá hríšnaho, í nečístaho, í nedostójnaho rabá tvojehó: jáko tý jésí zaščítiteľ mój Hospodi, í ó tebí pínije mojé výnu, í tebí slávu vozsylájem, Ótcú, í Sýnu, í svjatómu Dúchu, nýňi í prísno, í vo víki vikóv, ámíň."),
  ))
])
