#import "../../../../all.typ": *
= #translation.at("KAFTIZMA") 13

#columns(2, gutter: 2pt, [

== #translation.at("ANTIFON") 1
  #generateTable((
    gText("1"),
    sText([Psalóm písni, v déň subbótnyj, (#translation.at("PSALM") 91)]),
    gText("2"),
    par([Bláho jésť íspovídatisja Hospodevi í píti ímeni tvojemú, výšnij:]),
    gText("3"),
    par([Vozviščáti zaútra mílosť tvojú í ístinu tvojú na vsjáku nóšč,]),
    gText("4"),
    par([V desjatostrúnňim psaltíri s písniju v húslech.]),
    gText("5"),
    par([Jáko vozveselíl mjá jésí, Hospodi, v tvoréniji tvojém, í v ďíľich rukú tvoéju vozrádujusja.]),
    gText("6"),
    par([Jáko vozvelíčišasja ďilá tvojá, Hospodi: ziló úhlubíšasja pomyšlénija tvojá.]),
    gText("7"),
    par([Múž bezúmen ne poznájet, í nerazumív ne razumíet sích.]),
    gText("8"),
    par([Vnehdá prozjabóša hríšnicy jáko travá, í pronikóša vsí ďílajuščiji bezzakónije, jáko da potrebjátsja v vík víka:]),
    gText("9"),
    par([Tý že výšnij vo vík, Hospodi.]),
    gText("10"),
    par([Jáko sé, vrazí tvoí, Hospodi, jáko sé, vrazí tvoí pohíbnut, í razýdutsja vsí ďílajuščiji bezzakónije.]),
    gText("11"),
    par([Í voznesétsja jáko jédinoróha róh mój, í stárosť mojá v jéléi mastíťi:]),
    gText("12"),
    par([Í vozzrí óko mojé na vrahí mojá, í vostajúščyja na mjá lukávnujuščyja úslýšit úcho mojé.]),
    gText("13"),
    par([Právednik jáko fínijž procvitét: jáko kédr, íže v lijváňi, úmnóžitsja.]),
    gText("14"),
    par([Nasaždéni v domú Hospodni vo dvórich Boha nášeho procvitút:]),
    gText("15"),
    par([Jéščé úmnóžatsja v stárosti mastíťi, í bláhoprijémľušče búdut.]),
    gText("16"),
    par([Da vozvisťát, jáko práv Hospoď Boh náš, í ňísť neprávdy v ném.]),
    "",
    sText([V déň predsubbótnyj, vnehdá naselísja zemľá, chvalá písni Davidu, (#translation.at("PSALM") 92)]),
    gText("1"),
    par([Hospoď vocerísja, v ľípotu óblečésja: óblečésja Hospoď v sílu í prepojásasja: íbo útverdí vselénnuju, jáže ne podvížitsja.]),
    gText("2"),
    par([Hotóv prestól tvój ottóľi: ot víka tý jésí.]),
    gText("3"),
    par([Vozdvihóša ríki, Hospodi, vozdvihóša ríki hlásy svojá:]),
    gText("4"),
    par([Vózmut ríki sotrénija svojá, ot hlasóv vód mnóhich.]),
    gText("5"),
    par([Dívny vysotý morskíja: díven v vysókich Hospoď.]),
    gText("6"),
    par([Sviďínija tvojá úvírišasja ziló. Dómu tvojemú podobájet svjatýňa, Hospodi, v dolhotú dníj.]),
    "",
    sText([Psalóm Davidu, v četvértyj subbóty, (#translation.at("PSALM") 93)]),
    gText("1"),
    par([Boh otmščénij Hospoď, Boh otmščénij ne óbinúlsja jésť.]),
    gText("2"),
    par([Voznesísja, suďáj zemlí, vozdážď vozdajánije hórdym.]),
    gText("3"),
    par([Dokóľi hríšnicy, Hospodi, dokóľi hríšnicy voschváľatsja;]),
    gText("4"),
    par([Proviščájut í vozhlahóľut neprávdu, vozhlahóľut vsí ďílajuščiji bezzakónije;]),
    gText("5"),
    par([Ľúdi tvojá, Hospodi, smiríša, í dostojánije tvojé ózlóbiša:]),
    gText("6"),
    par([Vdovícu í síra úmoríša, í prišéľca úbíša,]),
    gText("7"),
    par([Í ríša: ne úzrit Hospoď, nižé úrazumíet Boh Jákovľ.]),
    gText("8"),
    par([Razumíjte že, bezúmniji v ľúdech, í búiji ňíkohda, úmudrítesja:]),
    gText("9"),
    par([Nasaždéj úcho, ne slýšit li; ílí sozdávyj óko, ne smatrájet li;]),
    gText("10"),
    par([Nakazújaj jázýki, ne óbličít li, účáj čelovíka rázumu;]),
    gText("11"),
    par([Hospoď vísť pomyšlénija čelovíčeskaja, jáko súť súetna.]),
    gText("12"),
    par([Blážén čelovík, jéhóže ášče nakážeši, Hospodi, í ot zakóna tvojehó naučíši jéhó:]),
    gText("13"),
    par([Úkrotíti jéhó ot dníj ľútych, dóndeže ízrýetsja hríšnomu jáma.]),
    gText("14"),
    par([Jáko ne otrínet Hospoď ľudéj svojích, í dostojánija svojehó ne óstávit:]),
    gText("15"),
    par([Dóndeže právda óbratítsja na súd, í deržáščijisja jéjá vsí práviji sr-d*cem.]),
    gText("16"),
    par([Któ vostánet mí na lukávnujuščyja; ílí któ spredstánet mí na ďílajuščyja bezzakónije;]),
    gText("17"),
    par([Ášče ne Hospoď pomóhl by mí, vmáľi vselílasja by vo ád dušá mojá.]),
    gText("18"),
    par([Ášče hlahólach: podvížesja nohá mojá, mílosť tvojá, Hospodi, pomoháše mí:]),
    gText("19"),
    par([Po mnóžestvu boľíznej mojích v sérdcy mojém, úťišénija tvojá vozveselíša dúšu mojú.]),
    gText("20"),
    par([Da ne prebúdet tebí prestól bezzakónija, sozidájaj trúd na poveľínije.]),
    gText("21"),
    par([Úlovját na dúšu právedniču, í króv nepovínnuju ósúďat.]),
    gText("22"),
    par([Í býsť mňí Hospoď v pribížišče, í Boh mój v pómošč úpovánija mojehó:]),
    gText("23"),
    par([Í vozdást ím Hospoď bezzakónije ích, í po lukávstviju ích pohubít já Hospoď Boh   #footnote("náš").]),
    col2(gText([#translation.at("SI")])),
  ))
== #translation.at("ANTIFON") 2
  #generateTable((
    "",
    sText([Chvalá písni Davidu, ne nadpísan ú jévréj, (#translation.at("PSALM") 94)]),
    gText("1"),
    par([Prijidíte, vozrádujemsja Hospodevi, vosklíknem Bohu Spasíteľu nášemu:]),
    gText("2"),
    par([Predvarím licé jéhó vo íspovídaniji, í vo psalmích vosklíknem jémú:]),
    gText("3"),
    par([Jáko Boh vélij Hospoď, í cer vélij po vséj zemlí:]),
    gText("4"),
    par([Jáko v rucí jéhó vsí koncý zemlí, í vysotý hór tohó súť.]),
    gText("5"),
    par([Jáko tohó jésť móre, í tój sotvorí jé, í súšu rúci jéhó sozdásťi.]),
    gText("6"),
    par([Prijidíte, poklonímsja í pripadém jémú, í vospláčemsja pred Hospodem sotvóršim nás:]),
    gText("7"),
    par([Jáko tój jésť Boh náš, í mý ľúdije pážiti jéhó í óvcy rukí jéhó. Dnés ášče hlás jéhó úslýšite,]),
    gText("8"),
    par([Ne óžestočíte serdéc vášich, jáko v prohňívaniji, po dní ískušénija v pustýni:]),
    gText("9"),
    par([Vóňže #footnote("íďíže") ískusíša mjá ótcý váši, ískusíša mjá, í víďiša ďilá mojá.]),
    gText("10"),
    par([Četýredesjať ľít nehodovách róda tohó, í rích: presno zabluždájut sérdcem, tíji že ne poznáša putéj mojích:]),
    gText("11"),
    par([Jáko kľáchsja vo hňívi mojém, ášče vnídut v pokój mój.]),
    "",
    sText([Chvalá písni Davidu, vnehdá dóm sozidášesja po pľinéniji, ne nadpísan ú jévréj, (#translation.at("PSALM") 95)]),
    gText("1"),
    par([Vospójte Hospodevi písň nóvu, vospójte Hospodevi vsjá zemľá:]),
    gText("2"),
    par([Vospójte Hospodevi, bláhoslovíte ímja jéhó: bláhovistíte déň ot dné Spasénije jéhó.]),
    gText("3"),
    par([Vozvistíte vo jázýcich slávu jéhó, vo vsích ľúdech čudesá jéhó.]),
    gText("4"),
    par([Jáko vélij Hospoď í chválen ziló, strášen jésť nad vsími bóhi.]),
    gText("5"),
    par([Jáko vsí bózi jázýk bísove: Hospoď že nebesá sotvorí.]),
    gText("6"),
    par([Íspovídanije í krasotá pred ním, svjatýňa í velikoľípije vo svjatíľi jéhó.]),
    gText("7"),
    par([Prinesíte Hospodevi, ótéčestvija jázýk, prinesíte Hospodevi slávu í čésť.]),
    gText("8"),
    par([Prinesíte Hospodevi slávu ímeni jéhó: vozmíte žértvy í vchodíte vo dvorý jéhó.]),
    gText("9"),
    par([Poklonítesja Hospodevi vo dvorí svjatím jéhó: da podvížitsja ot licá jéhó vsjá zemľá.]),
    gText("10"),
    par([Rcýte vo jázýcich, jáko Hospoď vocerísja: íbo ísprávi vselénnuju, jáže ne podvížitsja: súdit ľúdem právostiju.]),
    gText("11"),
    par([Da vozveseľátsja nebesá, í rádujetsja zemľá: da podvížitsja móre í íspolnénije jéhó:]),
    gText("12"),
    par([Vozrádujutsja poľá, í vsjá jáže na ních: tohdá vozrádujutsja vsjá drevá dubrávnaja]),
    gText("13"),
    par([Ot licá Hospodňa, jáko hrjadét, jáko hrjadét sudíti zemlí: sudíti vselénňij v právdu, í ľúdem ístinoju svojéju.]),
    "",
    sText([Psalóm Davidu, jéhdá zemľá jéhó ústrojášesja, ne nadpísan ú jévréj, (#translation.at("PSALM") 96)]),
    gText("1"),
    par([Hospoď vocerísja, da rádujetsja zemľá, da veseľátsja óstrovi mnózi.]),
    gText("2"),
    par([Óblak í mrák ókrest jéhó: právda í suďbá íspravlénije prestóla jéhó.]),
    gText("3"),
    par([Óhň pred ním predídet í popalít ókrest vrahí jéhó.]),
    gText("4"),
    par([Ósvitíša mólnija jéhó vselénnuju: víďi í podvížesja zemľá.]),
    gText("5"),
    par([Hóry jáko vósk rastájaša ot licá Hospodňa, ot licá Hospoda vsejá zemlí.]),
    gText("6"),
    par([Vozvistíša nebesá právdu jéhó, í víďiša vsí ľúdije slávu jéhó.]),
    gText("7"),
    par([Da postyďátsja vsí kláňajuščijisja ístukánnym, chváľaščijisja ó ídoľich svojích: poklonítesja jémú, vsí Anheli jéhó.]),
    gText("8"),
    par([Slýša í vozveselísja Sijón, í vozrádovašasja dščéri íudéjskija, sudéb rádi tvojích, Hospodi:]),
    gText("9"),
    par([Jáko tý Hospoď výšnij nad vséju zemléju, ziló prevoznéslsja jésí nad vsími bóhi.]),
    gText("10"),
    par([Ľúbjaščiji Hospoda, nenavídite zlája: chranít Hospoď dúšy prepodóbnych svojích, íz rukí hríšniči ízbávit já.]),
    gText("11"),
    par([Svít vozsijá právedniku, í právym sr-d*cem vesélije.]),
    gText("12"),
    par([Veselítesja, právedniji, ó Hospodi, í íspovídajte pámjať svjatýni jéhó.]),
    col2(gText([#translation.at("SI")])),
  ))
== #translation.at("ANTIFON") 3
  #generateTable((
    "",
    sText([Psalóm Davidu, (#translation.at("PSALM") 97)]),
    gText("1"),
    par([Vospójte Hospodevi písň nóvu, jáko dívna sotvorí Hospod: Spasé jéhó desníca jéhó í mýšca svjatája jéhó.]),
    gText("2"),
    par([Skazá Hospoď Spasénije svojé, pred jázýki otkrý právdu svojú.]),
    gText("3"),
    par([Pomjanú mílosť svojú Jákovu í ístinu svojú dómu Izráilevu: víďiša vsí koncý zemlí Spasénije Boha nášeho.]),
    gText("4"),
    par([Vosklíknite Bohovi, vsjá zemľá, vospójte í rádujtesja í pójte.]),
    gText("5"),
    par([Pójte Hospodevi v húslech, v húslech í hlási psalómsťi,]),
    gText("6"),
    par([V trubách kóvanych í hlásom trubý róžany: vostrubíte pred cerém Hospodem.]),
    gText("7"),
    par([Da podvížitsja móre í íspolnénije jéhó, vselénnaja í vsí živúščiji na néj.]),
    gText("8"),
    par([Ríki vospléščut rukóju vkúpi, hóry vozrádujutsja]),
    gText("9"),
    par([Ot licá Hospodňa, jáko hrjadét, jáko ídet sudíti zemlí: sudíti vselénňij v právdu, í ľúdem právostiju.]),
    "",
    sText([Psalóm Davidu, (#translation.at("PSALM") 98)]),
    gText("1"),
    par([Hospoď vocerísja, da hňívajutsja ľúdije: siďáj na cheruvímich, da podvížitsja zemľá.]),
    gText("2"),
    par([Hospoď v sijóňi velík, í vysók jésť nad vsími ľuďmí.]),
    gText("3"),
    par([Da íspovíďatsja ímeni tvojemú velíkomu, jáko strášno í svjato jésť.]),
    gText("4"),
    par([Í čésť caréva súd ľúbit: tý úhotóval jésí pravotý, súd í právdu vo Jákovi tý sotvoríl jésí.]),
    gText("5"),
    par([Voznosíte Hospoda Boha nášeho í poklaňájtesja podnóžiju nóhu jéhó, jáko svjato jésť.]),
    gText("6"),
    par([Moyséj í áarón vo íeréech jéhó, í samuíl v prizyvájuščich ímja jéhó: prizyváchu Hospoda, í tój poslúšaše ích.]),
    gText("7"),
    par([V stolpí óblačňi hlahólaše k ním: jáko chraňáchu sviďínija jéhó í poveľínija jéhó, jáže dadé ím.]),
    gText("8"),
    par([Hospodi Bože náš, tý poslúšal jésí ích: Bože, tý mílostiv byvál jésí ím, í mščája na vsjá načinánija ích.]),
    gText("9"),
    par([Voznosíte Hospoda Boha nášeho í poklaňájtesja v horí svjatíj jéhó: jáko svjat Hospoď Boh náš.]),
    "",
    sText([Psalóm Davidu vo íspovídanije, (#translation.at("PSALM") 99)]),
    gText("1"),
    par([Vosklíknite Bohovi vsjá zemľá:]),
    gText("2"),
    par([Rabótajte Hospodevi v veséliji, vnídite pred ním v rádosti.]),
    gText("3"),
    par([Úvídite, jáko Hospoď tój jésť Boh náš: tój sotvorí nás, á ne mý: mý že ľúdije jéhó í óvcy pážiti jéhó.]),
    gText("4"),
    par([Vnídite vo vratá jéhó vo íspovídaniji, vo dvorý jéhó v pínijich: íspovídajtesja jémú, chvalíte ímja jéhó.]),
    gText("5"),
    par([Jáko bláh Hospoď, v vík mílosť jéhó, í dáže do róda í róda ístina jéhó.]),
    "",
    sText([Psalóm Davidu, (#translation.at("PSALM") 100)]),
    gText("1"),
    par([Mílosť í súd vospojú tebí, Hospodi:]),
    gText("2"),
    par([Pojú í razumíju v putí neporóčňi: kohdá prijídeši ko mňí; prechoždách v nezlóbiji sérdca mojehó posreďí dómu mojehó.]),
    gText("3"),
    par([Ne predlahách pred óčíma mojíma véšč zakonoprestúpnuju: tvorjáščyja prestuplénije voznenavíďich:]),
    gText("4"),
    par([Ne priľpé mňí sérdce stroptívo: úkloňájuščahosja ot mené lukávaho ne poznách.]),
    gText("5"),
    par([Óklevetájuščaho táj ískrenňaho svojehó, sehó ízhoňách: hórdym ókom í nesýtym sérdcem, s sím ne jáďách.]),
    gText("6"),
    par([Óči moí na vírnyja zemlí, posaždáti já so mnóju: choďáj po putí neporóčnu, séj mí služáše.]),
    gText("7"),
    par([Ne živjáše posreďí dómu mojehó tvorjáj hordýňu: hlahóľaj neprávednaja ne íspravľáše pred óčíma mojíma.]),
    gText("8"),
    par([Voútrija ízbivách vsjá hríšnyja zemlí, jéže potrebíti ot hráda Hospodňa vsjá ďílajuščyja bezzakónije.]),
    col2(gText([#translation.at("SI")])),
  ))
  #generateTable((
    col2(sText(translation.at("AFTER_KAFTIZMA"))),
    sText("T"),
    jObj4("",8, "", "Ókom bláhoutróbnym, Hospodi, vížď mojé smirénije, jáko pomáľi žízň mojá íždivájetsja, í ot ďíl ňísť mňí Spasénija. sehó rádi moľúsja: ókom bláhoutróbnym Hospodi, vížď mojé smirénije, í Spasí mja."),
    
    // S:
    col2(gText(translation.at("S"))),
    "",
    jObj4("",none, "", "Jáko sudijí predstojášču, popecýsja dušé, í strášnaho dné čás pomyšľáj: súd bo nemílostiv jésť ne sotvóršym mílosti. vozopíj úbo Christú Bohu: serdcevídče, sohriších, préžde dáže ne ósúdiši, pomíluj mjá."),
    
    // I:
    col2(gText(translation.at("IN"))),
    "",
    jObj4("",none, "", "Strášnaho tvojehó í hróznaho í neumýtnaho sudá Christé, vo úmí prijém déň í čás trepéšču jáko zloďíj, studá ďilá í ďijánija ímíja ľútaja, jáže jédín áz soďíjach priľížno. ťímže stráchom pripádaju tebí, vopijá boľíznenno: molitvami róždšija ťá mnohomílostive, Spasí mja."),
    col2(translation.at("HOSPODI_POMILUJ")+". "+sText("(40)")),
    col2(sText(translation.at("MOLITVA"))),
    "",
    jObj4("",none, "", "Hospodi svjatýj, íže v výšnich živýj, í vsevíďaščim tvojím ókom prizirájaj na vsjú tvár, tebí prikloníchom výju duší í ťilesé, í tebí mólimsja svjatýj svjatých: prostrí rúku tvojú nevídimuju ot svjatáho žilíšča tvojehó, í bláhosloví vsjá ný. í ášče čtó k tebí sohrišíchom vóleju í nevóleju, jáko bláh í čelovikoľúbec Boh prostí, dárujaj nám í mírnaja bláhája tvojá. tvojé bo jésť jéže mílovati í Spasáti Bože náš, í tebí slávu vozsylájem, Ótcú, í Sýnu, í svjatómu Dúchu, nýňi í prísno, í vo víki vikóv, ámíň."),
  ))
])
