#import "../../../../all.typ": *
= #translation.at("KAFTIZMA") 14

#columns(2, gutter: 2pt, [

== #translation.at("ANTIFON") 1
  #generateTable((
    gText("1"),
    sText([Molítva níščaho, jéhdá únýet í pred Hospodem prolijét molénije svojé, (#translation.at("PSALM") 101)]),
    gText("2"),
    par([Hospodi, úslýši molítvu mojú, í vópľ mój k tebí da prijídet.]),
    gText("3"),
    par([Ne otvratí licá tvojehó ot mené: vóňže ášče déň skorbľú, prikloní ko mňí úcho tvojé: vóňže ášče déň prizovú ťa, skóro úslýši mjá.]),
    gText("4"),
    par([Jáko ísčezóša jáko dým dníe moí, í kósti mojá jáko sušílo soschóšasja.]),
    gText("5"),
    par([Újázvlen bých jáko travá, í ízsše sérdce mojé, jáko zabých sňísti chľíb mój.]),
    gText("6"),
    par([Ot hlása vozdychánija mojehó priľpé kósť mojá plóti mojéj.]),
    gText("7"),
    par([Úpodóbichsja nejásyti pustýnňij, bých jáko noščnýj vrán na nýrišči #footnote("na razváliňi").]),
    gText("8"),
    par([Bďích í bých jáko ptíca ósóbjaščajasja na zďí #footnote("na króvi").]),
    gText("9"),
    par([Vés déň ponošáchu mí vrazí moí, í chváľaščiji mjá mnóju #footnote("na mjá") kleňáchusja.]),
    gText("10"),
    par([Zané pépel jáko chľíb jáďách í pitijé mojé s pláčem rastvorjách,]),
    gText("11"),
    par([Ot licá hňíva tvojehó í járosti tvojejá: jáko voznés nizvérhl mjá jésí.]),
    gText("12"),
    par([Dníe moí jáko síň úkloníšasja, í áz jáko síno ízschóch.]),
    gText("13"),
    par([Tý že, Hospodi, vo vík prebyváješi, í pámjať tvojá v ród í ród.]),
    gText("14"),
    par([Tý voskres úščédriši Sijóna: jáko vrémja úščédriti jéhó, jáko prijíde vrémja.]),
    gText("15"),
    par([Jáko bláhovolíša rabí tvoí kámenije #footnote("ó kámeniji") jéhó, í pérsť jéhó úščédrjat.]),
    gText("16"),
    par([Í úbojátsja jázýcy ímene Hospodňa, í vsí cárije zémstiji slávy tvojejá:]),
    gText("17"),
    par([Jáko sozíždet Hospoď Sijóna í jávítsja vo slávi svojéj.]),
    gText("18"),
    par([Prizrí na molítvu smirénnych í ne úničiží molénija ích.]),
    gText("19"),
    par([Da napíšetsja sijé v ród ín, í ľúdije zíždemiji voschváľat Hospoda:]),
    gText("20"),
    par([Jáko priníče s vysotý svjatýja svojejá, Hospoď s nebesé na zémľu prizrí,]),
    gText("21"),
    par([Úslýšati vozdychánije ókovánnych, razrišíti sýny úmerščvlénnych:]),
    gText("22"),
    par([Vozvistíti v sijóňi ímja Hospodne í chvalú jéhó vo Jerúsaľími,]),
    gText("23"),
    par([Vnehdá sobrátisja ľúdem vkúpi í carém, jéže rabótati Hospodevi.]),
    gText("24"),
    par([Otviščá jémú na putí kríposti jéhó: úmalénije dníj mojích vozvistí mi:]),
    gText("25"),
    par([Ne vozvedí mené vo prepolovénije dníj mojích: v róďi rodóv ľíta tvojá.]),
    gText("26"),
    par([V načáľich tý, Hospodi, zémľu ósnovál jésí, í ďilá rukú tvoéju súť nebesá.]),
    gText("27"),
    par([Tá pohíbnut, tý že prebyváješi: í vsjá jáko ríza óbetšájut, í jáko ódéždu svijéši já, í ízmiňátsja.]),
    gText("28"),
    par([Tý že tójžde jésí, í ľíta tvojá ne óskuďíjut.]),
    gText("29"),
    par([Sýnove ráb tvojích vseľátsja, í símja ích vo vík ísprávitsja.]),
    "",
    sText([Psalóm Davidu, (#translation.at("PSALM") 102)]),
    gText("1"),
    par([Bláhosloví, dušé mojá, Hospoda, í vsjá vnútrenňaja mojá, ímja svjatóje jéhó:]),
    gText("2"),
    par([Bláhosloví, dušé mojá, Hospoda, í ne zabyváj vsích vozdajánij jéhó:]),
    gText("3"),
    par([Óčiščájuščaho vsjá bezzakónija tvojá, ísciľájuščaho vsjá nedúhi tvojá,]),
    gText("4"),
    par([Ízbavľájuščaho ot ístľínija živót tvój, vinčájuščaho ťá mílostiju í ščedrótami,]),
    gText("5"),
    par([Íspolňájuščaho vo bláhích želánije tvojé: óbnovítsja jáko órľa júnosť tvojá.]),
    gText("6"),
    par([Tvorjáj mílostyni Hospoď í suďbú vsím óbídimym.]),
    gText("7"),
    par([Skazá putí svojá moyséovi, synovóm Izráilevym choťínija svojá.]),
    gText("8"),
    par([Ščédr í mílostiv Hospoď, dolhoterpilív í mnohomílostiv.]),
    gText("9"),
    par([Ne do koncá prohňívajetsja, nižé vo vík vraždújet:]),
    gText("10"),
    par([Ne po bezzakónijem nášym sotvoríl jésť nám, nižé po hrichóm nášym vozdál jésť nám.]),
    gText("11"),
    par([Jáko po vysoťí nebésňij ot zemlí, útverdíl jésť Hospoď mílosť svojú na bojáščichsja jéhó:]),
    gText("12"),
    par([Jélíko otstoját vostócy ot západ, údálil jésť ot nás bezzakónija náša.]),
    gText("13"),
    par([Jákože ščédrit ótéc sýny, úščédri Hospoď bojáščichsja jéhó.]),
    gText("14"),
    par([Jáko tój pozná sozdánije náše, pomjanú, jáko pérsť jésmý.]),
    gText("15"),
    par([Čelovík, jáko travá dníe jéhó, jáko cvít sélnyj, táko ócvitét:]),
    gText("16"),
    par([Jáko dúch prójde v ném, í ne búdet, í ne poznájet ktomú místa svojehó.]),
    gText("17"),
    par([Mílosť že Hospodňa ot víka í do víka na bojáščichsja jéhó,]),
    gText("18"),
    par([Í právda jéhó na syňích synóv, chraňáščich zavít jéhó í pómňaščich zápovidi jéhó tvoríti já.]),
    gText("19"),
    par([Hospoď na nebesí úhotóva prestól svój, í cárstvo jéhó vsími óbladájet.]),
    gText("20"),
    par([Bláhoslovíte Hospoda, vsí Anheli jéhó, síľniji krípostiju, tvorjáščiji Slóvo jéhó, úslýšati hlás slovés jéhó.]),
    gText("21"),
    par([Bláhoslovíte Hospoda, vsjá síly jéhó, sluhí jéhó, tvorjáščiji vóľu jéhó.]),
    gText("22"),
    par([Bláhoslovíte Hospoda, vsjá ďilá jéhó na vsjákom mísťi Vladíčiestva jéhó: bláhosloví, dušé mojá, Hospoda.]),
    col2(gText([#translation.at("SI")])),
  ))
== #translation.at("ANTIFON") 2
  #generateTable((
    "",
    sText([Psalóm Davidu, ó mijrsťím bytijí, (#translation.at("PSALM") 103)]),
    gText("1"),
    par([Bláhosloví, dušé mojá, Hospoda. Hospodi Bože mój, vozvelíčilsja jésí ziló: vo íspovídanije í v veleľípotu óbléklsja jésí:]),
    gText("2"),
    par([Óďijájsja svítom jáko rízoju, prostirájaj nébo jáko kóžu:]),
    gText("3"),
    par([Pokryvájaj vodámi prevýsprenňaja svojá, polahájaj óblaki na voschoždénije svojé, choďáj na krilú vítreňu:]),
    gText("4"),
    par([Tvorjáj Anhely svojá dúchi, í sluhí svojá plámeň óhnennyj:]),
    gText("5"),
    par([Ósnovájaj zémľu na tvérdi jéjá: ne preklonítsja v vík víka.]),
    gText("6"),
    par([Bézdna jáko ríza óďijánije jéjá, na horách stánut vódy:]),
    gText("7"),
    par([Ot zapreščénija tvojehó pobíhnut, ot hlása hróma tvojehó úbojátsja.]),
    gText("8"),
    par([Voschóďat hóry, í nizchóďat poľá, v místo jéže ósnovál jésí ím.]),
    gText("9"),
    par([Preďíl položíl jésí, jéhóže ne préjdut, nižé óbraťátsja pokrýti zémľu.]),
    gText("10"),
    par([Posylájaj ístóčniki v débrech, posreďí hór prójdut vódy.]),
    gText("11"),
    par([Napajájut vsjá zvíri séľnyja, ždút #footnote("vosprijímut") ónáhri v žáždu svojú.]),
    gText("12"),
    par([Na tých ptícy nebésnyja privitájut: ot sredý kámenija daďát hlás.]),
    gText("13"),
    par([Napajájaj hóry ot prevýsprennich svojích: ot plodá ďíl tvojích nasýtitsja zemľá.]),
    gText("14"),
    par([Prozjabájaj travú skotóm, í zlák na slúžbu čelovíkom, ízvestí chľíb ot zemlí:]),
    gText("15"),
    par([Í vijnó veselít sérdce čelovíka, úmástiti licé jéléem: í chľíb sérdce čelovíka úkripít.]),
    gText("16"),
    par([Nasýťatsja drevá poľskája, kédri lijvánstiji, íchže jésí nasadíl:]),
    gText("17"),
    par([Támo ptícy vohňizďátsja, jérodíevo žilíšče predvodíteľstvujet ími.]),
    gText("18"),
    par([Hóry vysókija jélénem, kámeň pribížišče zájacem.]),
    gText("19"),
    par([Sotvoríl jésť lunú vo vremená: sólnce pozná západ svój.]),
    gText("20"),
    par([Položíl jésí tmú, í býsť nóšč, v néjže prójdut vsí zvírije dubrávniji,]),
    gText("21"),
    par([Skýmni rykájuščiji voschítiti í vzyskáti ot Boha píšču sebí.]),
    gText("22"),
    par([Vozsijá sólnce, í sobrášasja, í v lóžach svojích ľáhut.]),
    gText("23"),
    par([Ízýdet čelovík na ďílo svojé í na ďílanije svojé do véčera.]),
    gText("24"),
    par([Jáko vozvelíčišasja ďilá tvojá, Hospodi: vsjá premúdrostiju sotvoríl jésí: íspólnisja zemľá tvári tvojejá.]),
    gText("25"),
    par([Sijé móre velíkoje í prostránnoje: támo hádi, íchže ňísť čislá, živótnaja málaja s velíkimi:]),
    gText("26"),
    par([Támo korablí preplávajut, zmíj séj, jéhóže sozdál jésí ruhátisja jémú.]),
    gText("27"),
    par([Vsjá k tebí čájut, dáti píšču ím vo bláho vrémja.]),
    gText("28"),
    par([Dávšu tebí ím, soberút: otvérzšu tebí rúku, vsjáčeskaja íspólňatsja bláhosti:]),
    gText("29"),
    par([Otvráščšu že tebí licé, vozmjatútsja: otímeši dúch ích, í ísčéznut í v pérsť svojú vozvraťátsja:]),
    gText("30"),
    par([Pósleši Dúcha tvojehó, í sozíždutsja, í óbnovíši licé zemlí.]),
    gText("31"),
    par([Búdi sláva Hospodňa vo víki: vozveselítsja Hospoď ó ďíľich svojích:]),
    gText("32"),
    par([Prizirájaj na zémľu í tvorjáj jú trjastísja: prikasájajsja horám, í dymjátsja.]),
    gText("33"),
    par([Vospojú Hospodevi v živoťí mojém, pojú Bohu mojemú, dóndeže jésm:]),
    gText("34"),
    par([Da úsladítsja jémú besída mojá, áz že vozveseľúsja ó Hospodi.]),
    gText("35"),
    par([Da ísčéznut hríšnicy ot zemlí, í bezzakónnicy, jákože ne býti ím. Bláhosloví, dušé mojá, Hospoda.]),
    col2(gText([#translation.at("SI")])),
  ))
== #translation.at("ANTIFON") 3
  #generateTable((
    "",
    sText([Állilúija, (#translation.at("PSALM") 104)]),
    gText("1"),
    par([Íspovídajtesja Hospodevi í prizyvájte ímja jéhó, vozvistíte vo jázýcich ďilá jéhó:]),
    gText("2"),
    par([Vospójte jémú í pójte jémú, povídite vsjá čudesá jéhó.]),
    gText("3"),
    par([Chvalítesja ó ímeni svjatím jéhó: da vozveselítsja sérdce íščuščich Hospoda:]),
    gText("4"),
    par([Vzyščíte Hospoda í útverdítesja, vzyščíte licá jéhó výnu.]),
    gText("5"),
    par([Pomjaníte čudesá jéhó, jáže sotvorí, čudesá jéhó í suďbý úst jéhó,]),
    gText("6"),
    par([Símja ávraámle rabí jéhó, sýnove Jákovli ízbránniji jéhó.]),
    gText("7"),
    par([Tój Hospoď Boh náš: po vséj zemlí suďbý jéhó.]),
    gText("8"),
    par([Pomjanú v vík zavít svój, Slóvo, jéže zapovída v týsjaščy rodóv,]),
    gText("9"),
    par([Jéže zaviščá ávraámu, í kľátvu svojú ísaáku:]),
    gText("10"),
    par([Í postávi jú Jákovu v poveľínije í Izráiľu v zavít víčen,]),
    gText("11"),
    par([Hl*ja: tebí dám zémľu chanaáňu, úže dostojánija vášeho.]),
    gText("12"),
    par([Vnehdá býti ím málym čislóm, maľíjšym í prišéľcem v néj,]),
    gText("13"),
    par([Í preidóša ot jázýka v jázýk í ot cárstvija v ľúdi íny:]),
    gText("14"),
    par([Ne óstávi čelovíka óbíďiti ích í óbličí ó ních carí:]),
    gText("15"),
    par([Ne prikasájtesja pomázannym moím, í vo prorócich mojích ne lukávnujte.]),
    gText("16"),
    par([Í prizvá hlád na zémľu: vsjáko útverždénije chľíbnoje sotrý.]),
    gText("17"),
    par([Poslá pred ními čelovíka: v rabá pródan býsť Jósif.]),
    gText("18"),
    par([Smiríša vo ókóvach nózi jéhó, žeľízo prójde dušá jéhó,]),
    gText("19"),
    par([Dóndeže prijíde Slóvo jéhó: Slóvo Hospodne razžžé jéhó.]),
    gText("20"),
    par([Poslá cár í razriší jéhó: kňáz ľudéj, í óstávi #footnote("otpustí") jéhó.]),
    gText("21"),
    par([Postávi jéhó hospodína dómu svojemú í kňázja vsemú sťažániju svojemú,]),
    gText("22"),
    par([Nakazáti kňázi jéhó jáko sebé í stárcy jéhó úmudríti.]),
    gText("23"),
    par([Í vníde Izráiľ vo jéhýpet, í Jákov prišéľstvova v zémľu chámovu.]),
    gText("24"),
    par([Í vozrastí ľúdi svojá ziló í úkripí já páče vrahóv ích.]),
    gText("25"),
    par([Prevratí sérdce ích voznenavíďiti ľúdi jéhó, lésť sotvoríti v rabích jéhó.]),
    gText("26"),
    par([Poslá moyséa rabá svojehó, áaróna, jéhóže ízbrá sebí:]),
    gText("27"),
    par([Položí v ních slovesá známenij svojích í čudés svojích v zemlí chámovi.]),
    gText("28"),
    par([Poslá tmú í pomračí, jáko preohorčíša slovesá jéhó.]),
    gText("29"),
    par([Preloží vódy ích v króv í ízmorí rýby ích.]),
    gText("30"),
    par([Voskipí zemľá ích žábami v sokróviščnicach caréj ích.]),
    gText("31"),
    par([Rečé, í prijidóša pésija múchi í sknípy vo vsjá preďíly ích.]),
    gText("32"),
    par([Položí doždí ích hrády, óhň popaľájušč v zemlí ích:]),
    gText("33"),
    par([Í porazí vijnohrády ích í smókvy ích, í sotrý vsjákoje drévo preďíl ích.]),
    gText("34"),
    par([Rečé, í prijidóša prúzi í húsenicy, ímže ne bí čislá,]),
    gText("35"),
    par([Í sňidóša vsjáku travú v zemlí ích, í pojadóša vsják plód zemlí ích.]),
    gText("36"),
    par([Í porazí vsjákaho pérvenca v zemlí ích, načátok vsjákaho trudá ích:]),
    gText("37"),
    par([Í ízvedé já s srebróm í zlátom: í ne bí v koľíňich ích boľáj.]),
    gText("38"),
    par([Vozveselísja jéhýpet vo íschoždéniji ích: jáko napadé strách ích na ňá.]),
    gText("39"),
    par([Rasprostré óblak v pokróv ím, í óhň, jéže prosvitíti ím nóščiju.]),
    gText("40"),
    par([Prosíša, í prijidóša krásteli, í chľíba nebésnaho nasýti já:]),
    gText("41"),
    par([Razvérze kámeň, í potekóša vódy, potekóša v bezvódnych ríki:]),
    gText("42"),
    par([Jáko pomjanú Slóvo svjatóje svojé, jéže ko ávraámu rabú svojemú.]),
    gText("43"),
    par([Í ízvedé ľúdi svojá v rádosti í ízbránnyja svojá v veséliji.]),
    gText("44"),
    par([Í dadé ím straný jázýk, í trudý ľudéj nasľídovaša:]),
    gText("45"),
    par([Jáko da sochraňát ópravdánija jéhó í zakóna jéhó vzýščut.]),
    col2(gText([#translation.at("SI")])),
  ))
  #generateTable((
    col2(sText(translation.at("AFTER_KAFTIZMA"))),
    sText("T"),
    jObj4("",8, "", "Jáko bludníca pripádaju tí, da prijimú óstavlénije, í vmísto mýra slézy ot sérdca prinošú ti, Christé Bože: da jáko ónuju úščédriši mjá Spase, í podási óčiščénije hrichóv. jáko ónaja bo zovú ti: ízbávi mjá ot timínija ďíl mojích."),
    
    // S:
    col2(gText(translation.at("S"))),
    "",
    jObj4("",none, "", "Počtó ne pomyšľáješi dušé mojá smérti; počtó ne óbraščáješisja próčeje ko íspravléniju, préžde trubý hlašénija na suďí; tohdá ňísť vrémja pokajánija. prijimí vo úmí mytarjá í bludnícu, zovúščyja: sohriších tí Hospodi, pomíluj mjá."),
    
    // I:
    col2(gText(translation.at("IN"))),
    "",
    jObj4("",none, "", "Jáko prevoschoďáščaja vojístinnu roždestvóm tvojím síly nebésnyja, prisnoďivo Bohoródice, íže tobóju Božestvóm óbohatívšesja, neprestánno ťá veličájem."),
    col2(translation.at("HOSPODI_POMILUJ")+". "+sText("(40)")),
    col2(sText(translation.at("MOLITVA"))),
    "",
    jObj4("",none, "", "Bláhodarím ťá Hospodi Bože náš, Spasénij nášich, jáko vsjá tvoríši vo bláhoďijánija žízni nášeja: jáko úpokóil jésí nás v prešédšem noščnóm vrémeni, í vozdvíhl jésí nás ot lóžej nášich, í postávil jésí nás v poklonénije čestnáho í slávnaho ímene tvojehó. Tímže mólimsja tebí Hospodi: dážď nám bláhodáť í sílu, da spodóbimsja tebí píti razúmno, í molítisja neprestánno, í výnu k tebí zríti Spasíteľu í bláhoďíteľu nášich dúš, stráchom í trépetom svojé Spasénije ďíjstvujušče. úslýši úbo í pomíluj bláhoutróbne nás, sokruší pod nóhi náša nevídimyja rátniki í vrahí: prijimí jáže po síľi nášej bláhodarénija: dážď nám bláhodáť í sílu, vo otverzénije úst nášich, í naučí nás ópravdánijem tvoím, jáko čtó pomólimsja, jákože podobájet, ne vímy, ášče ne tý Hospodi Dúchom tvojím svjatým nastáviši ný. ášče že čtó sohrišíchom dáže do nastojáščaho časá, Slóvom, ílí ďílom, ílí pomyšlénijem, vóleju, ílí nevóleju, óslábi, óstávi, prostí. Ášče bo bezzakónija názriši Hospodi, Hospodi, któ postojít; jáko ú tebé óčiščénije jésť, ú tebé ízbavlénije. Tý jésí jédín svjat, pomóščnik krípkij, í zaščítiteľ žízni nášeja, í ťá bláhoslovím vo vsjá víki, ámíň."),
  ))
])
