#import "../../../../all.typ": *
= #translation.at("KAFTIZMA") 15

#columns(2, gutter: 2pt, [

== #translation.at("ANTIFON") 1
  #generateTable((
    "",
    sText([Állilúija, (#translation.at("PSALM") 105)]),
    gText("1"),
    par([Íspovídajtesja Hospodevi, jáko bláh, jáko v vík mílosť jéhó.]),
    gText("2"),
    par([Któ vozhlahólet síly Hospodni, slýšany sotvorít vsjá chvalý jéhó;]),
    gText("3"),
    par([Blážéni chraňáščiji súd í tvorjáščiji právdu vo vsjákoje vrémja.]),
    gText("4"),
    par([Pomjaní nás, Hospodi, vo bláhovoléniji ľudéj tvojích, posití nás Spasénijem tvojím,]),
    gText("5"),
    par([Víďiti vo bláhosti ízbránnyja tvojá, vozveselítisja v veséliji jázýka tvojehó, chvalítisja s dostojánijem tvojím.]),
    gText("6"),
    par([Sohrišíchom so ótcý nášimi, bezzakónnovachom, neprávdovachom:]),
    gText("7"),
    par([Ótcý náši vo jéhýpťi ne razumíša čudés tvojích, ni pomjanúša mnóžestva mílosti tvojejá: í preohorčíša voschoďášče v čermnóje móre.]),
    gText("8"),
    par([Í Spasé ích ímene svojehó rádi, skazáti sílu svojú:]),
    gText("9"),
    par([Í zapretí čermnómu mórju, í ízsjáče: í nastávi #footnote("prevedé") já v bézdňi jáko v pustýni.]),
    gText("10"),
    par([Í Spasé já íz rukí nenavíďaščich í ízbávi já íz rukí vrahóv.]),
    gText("11"),
    par([Pokrý vodá stužájuščyja ím: ni jédín ot ních ízbýsť.]),
    gText("12"),
    par([Í vírovaša slovesí jéhó í vospíša chvalú jéhó.]),
    gText("13"),
    par([Úskoríša, zabýša ďilá jéhó, ne sterpíša sovíta jéhó:]),
    gText("14"),
    par([Í pochoťíša želániju v pustýni í ískusíša Boha v bezvódňij.]),
    gText("15"),
    par([Í dadé ím prošénije ích, poslá sýtosť v dúšy ích.]),
    gText("16"),
    par([Í prohňívaša moyséa v stanú, áaróna svjatáho Hospodňa.]),
    gText("17"),
    par([Otvérzesja zemľá í požré dathána í pokrý na sónmišči ávijróna:]),
    gText("18"),
    par([Í razžžésja óhň v sónmi ích, plámeň popalí hríšniki.]),
    gText("19"),
    par([Í sotvoríša teľcá v chorívi í pokloníšasja ístukánnomu:]),
    gText("20"),
    par([Í ízminíša slávu jéhó v podóbije teľcá jádúščaho travú.]),
    gText("21"),
    par([Í zabýša Boha Spasájuščaho ích, sotvóršaho vélija vo jéhýpťi,]),
    gText("22"),
    par([čudesá v zemlí chámovi, strášnaja v móri čermňím.]),
    gText("23"),
    par([Í rečé potrebíti ích, ášče ne bý moyséj ízbránnyj jéhó stál v sokrušéniji pred ním, vozvratíti járosť jéhó, da ne pohubít ích.]),
    gText("24"),
    par([Í úničižíša zémľu želánnuju, ne jáša víry slovesí jéhó:]),
    gText("25"),
    par([Í poroptáša v selénijich svojích, ne úslýšaša hlása Hospodňa.]),
    gText("26"),
    par([Í vozdvíže rúku svojú na ňá, nizložíti já v pustýni,]),
    gText("27"),
    par([Í nizložíti símja ích vo jázýcich, í rastočíti já v straný.]),
    gText("28"),
    par([Í pričastíšasja vejeľfehóru í sňidóša žértvy mértvych:]),
    gText("29"),
    par([Í razdražíša jéhó v načinánijich svojích, í úmnóžisja v ních padénije.]),
    gText("30"),
    par([Í stá fijnejés í úmílostivi, í prestá síč:]),
    gText("31"),
    par([Í vminísja jémú v právdu, v ród í ród do víka.]),
    gText("32"),
    par([Í prohňívaša jéhó na voďí prerikánija, í ózlóblen býsť moyséj ích rádi:]),
    gText("33"),
    par([Jáko preohorčíša dúch jéhó í ráznstvova ústnáma svojíma.]),
    gText("34"),
    par([Ne potrebíša jázýki, jáže rečé Hospoď ím.]),
    gText("35"),
    par([Í smisíšasja vo jázýcich í navykóša ďilóm ích:]),
    gText("36"),
    par([Í porabótaša ístukánnym ích, í býsť ím v soblázn.]),
    gText("37"),
    par([Í požróša sýny svojá í dščéri svojá bisovóm,]),
    gText("38"),
    par([Í prolijáša króv nepovínnuju, króv synóv svojích í dščérej, jáže požróša ístukánnym chanaánskim: í úbijéna býsť zemľá ích krovmí]),
    gText("39"),
    par([Í óskvernísja v ďíľich ích: í sobludíša v načinánijich svojích.]),
    gText("40"),
    par([Í razhňívasja járostiju Hospoď na ľúdi svojá í ómerzí dostojánije svojé:]),
    gText("41"),
    par([Í predadé já v rúki vrahóv, í óbladáša ími nenavíďaščiji ích.]),
    gText("42"),
    par([Í stužíša ím vrazí ích: í smiríšasja pod rukámi ích.]),
    gText("43"),
    par([Mnóžiceju ízbávi já: tíji že preohorčíša jéhó sovítom svojím, í smiríšasja v bezzakónijich svojích.]),
    gText("44"),
    par([Í víďi Hospoď, vnehdá skorbíti ím, vnehdá úslýšaše molénije ích:]),
    gText("45"),
    par([Í pomjanú zavít svój, í raskájasja po mnóžestvu mílosti svojejá:]),
    gText("46"),
    par([Í dadé já v ščedróty pred vsími pľinívšimi já.]),
    gText("47"),
    par([Spasí ny, Hospodi, Bože náš, í soberí ny ot jázýk, íspovídatisja ímeni tvojemú svjatómu, chvalítisja vo chvaľí tvojéj.]),
    gText("48"),
    par([Bláhoslovén Hospoď Boh Izráilev ot víka í do víka. Í rekút vsí ľúdije: búdi, búdi.]),
    col2(gText([#translation.at("SI")])),
  ))
== #translation.at("ANTIFON") 2
  #generateTable((
    "",
    sText([Állilúija, (#translation.at("PSALM") 106)]),
    gText("1"),
    par([Íspovídajtesja Hospodevi, jáko bláh, jáko v vík mílosť jéhó.]),
    gText("2"),
    par([Da rekút ízbávlenniji Hospodem, íchže ízbávi íz rukí vrahá,]),
    gText("3"),
    par([Í ot strán sobrá ích, ot vostók í západ, í sívera í mórja:]),
    gText("4"),
    par([Zabludíša v pustýni bezvódňij, putí hráda óbíteľnaho ne óbritóša:]),
    gText("5"),
    par([Álčušče í žáždušče, dušá ích v ních ísčezé.]),
    gText("6"),
    par([Í vozzváša ko Hospodu, vnehdá skorbíti ím, í ot núžd ích ízbávi já:]),
    gText("7"),
    par([Í nastávi já na púť práv, vníti vo hrád óbíteľnyj.]),
    gText("8"),
    par([Da íspovíďatsja #footnote("da íspovíďat") Hospodevi mílosti jéhó í čudesá jéhó synovóm čelovíčeskim:]),
    gText("9"),
    par([Jáko nasýtil jésť dúšu tščú, í dúšu álčušču íspólni bláh:]),
    gText("10"),
    par([Siďáščyja vo tmí í síni smértňij, ókovánnyja niščetóju í žeľízom,]),
    gText("11"),
    par([Jáko preohorčíša slovesá Božija, í sovít výšňaho razdražíša.]),
    gText("12"),
    par([Í smirísja v truďích sérdce ích, í íznemohóša, í ne bí pomohájaj.]),
    gText("13"),
    par([Í vozzváša ko Hospodu, vnehdá skorbíti ím, í ot núžd ích Spasé já:]),
    gText("14"),
    par([Í ízvedé já íz tmý í síni smértnyja, í úzy ích rasterzá.]),
    gText("15"),
    par([Da íspovíďatsja #footnote("da íspovíďat") Hospodevi mílosti jéhó í čudesá jéhó synovóm čelovíčeskim:]),
    gText("16"),
    par([Jáko sokruší vratá mídnaja, í verejí žeľíznyja slomí.]),
    gText("17"),
    par([Vospriját já ot putí bezzakónija ích: bezzakónij bo rádi svojích smiríšasja.]),
    gText("18"),
    par([Vsjákaho brášna vozhnušásja dušá ích, í priblížišasja do vrát smértnych.]),
    gText("19"),
    par([Í vozzváša ko Hospodu, vnehdá skorbíti ím, í ot núžd ích Spasé já:]),
    gText("20"),
    par([Poslá Slóvo svojé, í íscilí já, í ízbávi já ot rastľínij ích.]),
    gText("21"),
    par([Da íspovíďatsja #footnote("da íspovíďat") Hospodevi mílosti jéhó í čudesá jéhó synovóm čelovíčeskim:]),
    gText("22"),
    par([Í da požrút jémú žértvu chvalý í da vozvisťát ďilá jéhó v rádosti.]),
    gText("23"),
    par([Schoďáščiji v móre v korabléch, tvorjáščiji ďílanija v vodách mnóhich,]),
    gText("24"),
    par([Tíji víďiša ďilá Hospodňa í čudesá jéhó vo hlubiňí.]),
    gText("25"),
    par([Rečé, í stá dúch búren, í voznesóšasja vólny jéhó:]),
    gText("26"),
    par([Voschóďat do nebés í nizchóďat do bézdn: dušá ích v zlých tájaše:]),
    gText("27"),
    par([Smjatóšasja, podvihóšasja jáko pijányj, í vsjá múdrosť ích pohloščená býsť.]),
    gText("28"),
    par([Í vozzváša ko Hospodu, vnehdá skorbíti ím, í ot núžd ích ízvedé já:]),
    gText("29"),
    par([Í poveľí búri, í stá v tišinú, í úmolkóša vólny jéhó.]),
    gText("30"),
    par([Í vozveselíšasja, jáko úmolkóša, í nastávi já v pristánišče choťínija svojehó.]),
    gText("31"),
    par([Da íspovíďatsja #footnote("da íspovíďat") Hospodevi mílosti jéhó í čudesá jéhó synovóm čelovíčeskim:]),
    gText("32"),
    par([Da voznesút jéhó v cerkvi ľudsťíj, í na sidálišči stárec voschváľat jéhó.]),
    gText("33"),
    par([Položíl jésť ríki v pustýňu í íschódišča vodnája v žáždu,]),
    gText("34"),
    par([Zémľu plodonósnuju v slánosť, ot zlóby živúščich na néj.]),
    gText("35"),
    par([Položíl jésť pustýňu vo jézéra vodnája í zémľu bezvódnuju vo íschódišča vodnája.]),
    gText("36"),
    par([Í naselí támo álčuščyja, í sostáviša hrády óbíteľny:]),
    gText("37"),
    par([Í nasíjaša séla, í nasadíša vijnohrády, í sotvoríša plód žíten.]),
    gText("38"),
    par([Í blahosloví já, í úmnóžišasja ziló: í skotý ích ne úmáli.]),
    gText("39"),
    par([Í úmálišasja í ózlóbišasja ot skórbi zól í boľízni:]),
    gText("40"),
    par([Ízlijásja úničižénije na kňázi ích, í óblazní #footnote("zabluždáti sotvorí") já po neprochódňij, á ne po putí.]),
    gText("41"),
    par([Í pomóže úbóhu ot niščetý í položí jáko óvcy ótéčestvija.]),
    gText("42"),
    par([Úzrjat práviji í vozveseľátsja, í vsjákoje bezzakónije zahradít ústá svojá.]),
    gText("43"),
    par([Któ premúdr í sochranít sijá; í úrazumíjut mílosti Hospodni.]),
    col2(gText([#translation.at("SI")])),
  ))
== #translation.at("ANTIFON") 3
  #generateTable((
    gText("1"),
    sText([Písň, psalóm Davidu, (#translation.at("PSALM") 107)]),
    gText("2"),
    par([Hotóvo sérdce mojé, Bože, hotóvo sérdce mojé: vospojú í pojú vo slávi mojéj.]),
    gText("3"),
    par([Vostáni, sláva mojá, vostáni, psaltírju í húsli: vostánu ráno.]),
    gText("4"),
    par([Íspovímsja tebí v ľúdech, Hospodi, pojú tebí vo jázýcich:]),
    gText("5"),
    par([Jáko vélija verchú nebes mílosť tvojá í do óblak ístina tvojá.]),
    gText("6"),
    par([Voznesísja na nebesá, Bože, í po vséj zemlí sláva tvojá,]),
    gText("7"),
    par([Jáko da ízbávjatsja vozľúblenniji tvoí: Spasí desníceju tvojéju í úslýši mjá.]),
    gText("8"),
    par([Boh vozhlahóla vo svjatím svojém: voznesúsja í razďiľú sijkímu, í údóľ selénij razmírju.]),
    gText("9"),
    par([Mój jésť halaád, í mój jésť manassíj, í jéfrém zastuplénije hlavý mojejá: íúda cár mój,]),
    gText("10"),
    par([Moáv konób úpovánija mojehó: na íduméju naložú sapóh mój: mňí ínopleménnicy pokoríšasja.]),
    gText("11"),
    par([Któ vvedét mjá vo hrád óhraždénija; ílí któ nastávit mjá do íduméi;]),
    gText("12"),
    par([Ne tý li, Bože, otrínuvyj nás, í ne ízýdeši, Bože, v sílach nášich;]),
    gText("13"),
    par([Dážď nám pómošč ot skórbi: í sújetno spasénije čelovíčesko.]),
    gText("14"),
    par([Ó Bózi sotvorím sílu, í tój úničižít vrahí náša.]),
    "",
    sText([V konéc, psalóm Davidu, (#translation.at("PSALM") 108)]),
    gText("1"),
    par([Bože, chvalý mojejá ne premolčí:]),
    gText("2"),
    par([Jáko ústá hríšniča í ústá ľstívaho na mjá otverzóšasja, hlahólaša na mjá jázýkom ľstívym,]),
    gText("3"),
    par([Í slovesý nenavístnymi óbydóša mjá, í brášasja so mnóju túne.]),
    gText("4"),
    par([Vmísto jéže ľubíti mjá, óbolháchu mjá, áz že moľáchsja:]),
    gText("5"),
    par([Í položíša na mjá zlája za bláhája, í nénavisť za vozľublénije mojé.]),
    gText("6"),
    par([Postávi na nehó hríšnika, í dijávol da stánet ódesnúju jéhó:]),
    gText("7"),
    par([Vnehdá sudítisja jémú, da ízýdet ósuždén, í molítva jéhó da búdet v hrích.]),
    gText("8"),
    par([Da búdut dníe jéhó máli, í jépískopstvo jéhó da prijímet ín:]),
    gText("9"),
    par([Da búdut sýnove jéhó síri, í žená jéhó vdová:]),
    gText("10"),
    par([Dvížuščesja da preseľátsja sýnove jéhó í vosprósjat, da ízhnáni búdut íz domóv svojích.]),
    gText("11"),
    par([Da vzýščet zaimodávec vsjá, jélíka súť jéhó: í da voschíťat čuždíji trudý jéhó.]),
    gText("12"),
    par([Da ne búdet jémú zastúpnika, nižé da búdet úščedrjájaj sirotý jéhó:]),
    gText("13"),
    par([Da búdut čáda jéhó v pohublénije, v róďi jédíňim da potrebítsja ímja jéhó.]),
    gText("14"),
    par([Da vospomjanétsja bezzakónije ótéc jéhó pred Hospodem, í hrích mátere jéhó da ne óčístitsja:]),
    gText("15"),
    par([Da búdut pred Hospodem výnu, í da potrebítsja ot zemlí pámjať ích:]),
    gText("16"),
    par([Zanéže ne pomjanú sotvoríti mílosť, í pohná čelovíka níšča í úbóha, í úmiléna sérdcem úmertvíti.]),
    gText("17"),
    par([Í vozľubí kľátvu, í prijídet jémú: í ne voschoťí bláhoslovénija, í údalítsja ot nehó.]),
    gText("18"),
    par([Í óblečésja v kľátvu jáko v rízu, í vníde jáko vodá vo útróbu jéhó í jáko jéléj v kósti jéhó:]),
    gText("19"),
    par([Da búdet jémú jáko ríza, v ňúže óblačítsja, í jáko pójas, ímže výnu ópojasújetsja.]),
    gText("20"),
    par([Sijé ďílo óbolhájuščich mjá ú Hospoda í hlahóľuščich lukávaja na dúšu mojú.]),
    gText("21"),
    par([Í tý, Hospodi, Hospodi, sotvorí so mnóju ímene rádi tvojehó, jáko bláha mílosť tvojá:]),
    gText("22"),
    par([Ízbávi mjá, jáko níšč í úbóh jésm áz, í sérdce mojé smjatésja vnútr mené.]),
    gText("23"),
    par([Jáko síň, vnehdá úklonítisja jéj, oťáchsja: strjasóchsja jáko prúzi.]),
    gText("24"),
    par([Koľína mojá íznemohósta ot postá, í plóť mojá ízminísja jéléa rádi.]),
    gText("25"),
    par([Í áz bých ponošénije ím: víďiša mjá, pokiváša hlavámi svojími.]),
    gText("26"),
    par([Pomozí mi, Hospodi Bože mój, í Spasí mja po mílosti tvojéj:]),
    gText("27"),
    par([Í da razumíjut, jáko ruká tvojá sijá, í tý, Hospodi, sotvoríl jésí jú.]),
    gText("28"),
    par([Proklenút tíji, í tý bláhoslovíši: vostajúščiji na mjá da postyďátsja, ráb že tvój vozveselítsja.]),
    gText("29"),
    par([Da óblekútsja óbolhájuščiji mjá v sramotú í ódéždutsja jáko ódéždoju studóm svojím.]),
    gText("30"),
    par([Íspovímsja Hospodevi ziló ústý mojími í posreďí mnóhich voschvaľú jéhó:]),
    gText("31"),
    par([Jáko prestá ódesnúju úbóhaho, jéže Spastí ot hoňáščich dúšu mojú.]),
    col2(gText([#translation.at("SI")])),
  ))
  #generateTable((
    col2(sText(translation.at("AFTER_KAFTIZMA"))),
    sText("T"),
    jObj4("",1, "", "Jáko pučína mnóha prehrišénij mojích Spase, í ľúťi pohruzíchsja sohrišéňmi mojími: dážď mí rúku jáko petróvi, í Spasí mja Bože, í pomíluj mjá."),
    
    // S:
    col2(gText(translation.at("S"))),
    "",
    jObj4("",none, "", "Jáko pomyšléniji lukávymi, í ďíly ósudíchsja Spase, mýsľ mí dáruj óbraščénija Bože, da zovú: Spasí mja bláhoďíteľu bláhíj, í pomíluj mjá."),
    
    // I:
    col2(gText(translation.at("IN"))),
    "",
    jObj4("",none, "", "Bohoblážénnaja ótrokovíce í preneporóčnaja, skvérna mjá súšča í ókaľánna ot ďijánij bezmístnych, í skvérnych pomyšlénij, óčísti mjá ókajánnaho, neskvérnaja í čestaja, vsesvjatája Mati Ďivo."),
    col2(translation.at("HOSPODI_POMILUJ")+". "+sText("(40)")),
    col2(sText(translation.at("MOLITVA"))),
    "",
    jObj4("",none, "", "Vladýko Hospodi Izráise Christé, tý jésí pomóščnik mój, v rukách tvojích jésm áz, pomozí mi, ne óstávi mené sohrišíti k tebí, jáko zabluždén jésm. ne óstávi mjá posľídovati vóli plóti mojejá: ne prézri mjá Hospodi, jáko némoščen jésm. tý vísi poléznoje mňí, ne óstávi mjá pohíbnuti hrichí mojími: ne óstávi mjá Hospodi, ne otstupí ot mené, jáko k tebí pribihóch, naučí mja tvoríti vóľu tvojú, jáko tý jésí Boh mój. íscilí dúšu mojú, jáko sohriších tí, Spasí mja rádi mílosti tvojejá, jáko pred tobóju súť vsí stužájuščiji mí: í ňísť mňí ínóje pribížišče, tókmo tý Hospodi. da postyďátsja úbo vsí vostajúščiji na mjá, í íščuščiji dúšu mojú, jéže potrebíti jú: jáko tý jésí jédín síľnyj Hospodi vo vsích, í tvojá jésť sláva vo víki vikóv, ámíň."),
  ))
])
