#import "../../../../all.typ": *
= #translation.at("KAFTIZMA") 16

#columns(2, gutter: 2pt, [

== #translation.at("ANTIFON") 1
  #generateTable((
    "",
    sText([Psalóm Davidu, (#translation.at("PSALM") 109)]),
    gText("1"),
    par([Rečé Hospoď Hospodevi mojemú: sidí ódesnúju mené, dóndeže položú vrahí tvojá podnóžije nóh tvojích.]),
    gText("2"),
    par([Žézl síly póslet tí Hospoď ot Sijóna, í Hospodstvuj posreďí vrahóv tvojích.]),
    gText("3"),
    par([S tobóju načálo v déň síly tvojejá, vo svítlostech svjatých tvojích: íz čréva préžde dennícy rodích ťá.]),
    gText("4"),
    par([Kľátsja Hospoď í ne raskájetsja: tý íeréj vo vík po čínu melchijsedékovu.]),
    gText("5"),
    par([Hospoď ódesnúju tebé sokrušíl jésť v déň hňíva svojehó carí:]),
    gText("6"),
    par([Súdit vo jázýcich, íspólnit padénija, sokrušít hlavý na zemlí mnóhich.]),
    gText("7"),
    par([Ot potóka na putí pijét: sehó rádi voznesét hlavú.]),
    "",
    sText([Állilúija, (#translation.at("PSALM") 110)]),
    gText("1"),
    par([Íspovímsja tebí, Hospodi, vsím sérdcem mojím v sovíťi právych í sónmi.]),
    gText("2"),
    par([Vélija ďilá Hospodňa, ízýskana vo vsích vóľach jéhó:]),
    gText("3"),
    par([Íspovídanije í velikoľípije ďílo jéhó, í právda jéhó prebyvájet v vík víka.]),
    gText("4"),
    par([Pámjať sotvoríl jésť čudés svojích: mílostiv í ščédr Hospoď.]),
    gText("5"),
    par([Píšču dadé bojáščymsja jéhó: pomjanét v vík zavít svój.]),
    gText("6"),
    par([Kríposť ďíl svojích vozvistí ľúdem svoím, dáti ím dostojánije jázýk.]),
    gText("7"),
    par([Dilá rúk jéhó ístina í súd, vírny vsjá zápovidi jéhó,]),
    gText("8"),
    par([Útveržény v vík víka, sotvorény vo ístiňi í pravoťí.]),
    gText("9"),
    par([Ízbavlénije poslá ľúdem svoím: zapovída v vík zavít svój: svjato í strášno ímja jéhó.]),
    gText("10"),
    par([Načálo premúdrosti strách Hospodeň, rázum že bláh vsím tvorjáščym í: chvalá jéhó prebyvájet v vík víka.]),
    "",
    sText([Állilúija, psalóm, (#translation.at("PSALM") 111)]),
    gText("1"),
    par([Blážén múž bojájsja Hospoda, v zápovidech jéhó voschóščet ziló.]),
    gText("2"),
    par([Síľno na zemlí búdet símja jéhó, ród právych bláhoslovítsja:]),
    gText("3"),
    par([Sláva í bohátstvo v domú jéhó, í právda jéhó prebyvájet v vík víka.]),
    gText("4"),
    par([Vozsijá vo tmí svít právym: mílostiv í ščédr í právedn.]),
    gText("5"),
    par([Bláh múž ščédrja í dajá: ústróit slovesá svojá na suďí, jáko v vík ne podvížitsja.]),
    gText("6"),
    par([V pámjať víčnuju búdet právednik.]),
    gText("7"),
    par([Ot slúcha zlá ne úbojítsja:]),
    gText("8"),
    par([Hotóvo sérdce jéhó úpováti na Hospoda: útverdísja sérdce jéhó, ne úbojítsja, dóndeže vozzrít na vrahí svojá.]),
    gText("9"),
    par([Rastočí, dadé úbóhim: právda jéhó prebyvájet vo vík víka: róh jéhó voznesétsja v slávi.]),
    gText("10"),
    par([Hríšnik úzrit í prohňívajetsja zubý svojími poskrežéščet í rastájet: želánije hríšnika pohíbnet.]),
    col2(gText([#translation.at("SI")])),
  ))
== #translation.at("ANTIFON") 2
  #generateTable((
    "",
    sText([Állilúija, (#translation.at("PSALM") 112)]),
    gText("1"),
    par([Chvalíte, ótrocy, Hospoda, chvalíte ímja Hospodne.]),
    gText("2"),
    par([Búdi ímja Hospodne bláhoslovéno ot nýňi í do víka.]),
    gText("3"),
    par([Ot vostók sólnca do západ chváľno ímja Hospodne.]),
    gText("4"),
    par([Vysók nad vsími jázýki Hospod: nad nebesý sláva jéhó.]),
    gText("5"),
    par([Któ jáko Hospoď Boh náš; na vysókich živýj,]),
    gText("6"),
    par([Í na smirénnyja prizirájaj na nebesí í na zemlí:]),
    gText("7"),
    par([Vozdvizájaj ot zemlí níšča, í ot hnóišča vozvyšájaj úbóha:]),
    gText("8"),
    par([Posadíti jéhó s kňázi, s kňázi ľudéj svojích:]),
    gText("9"),
    par([Vseľája neplódov v dóm, máter ó čáďich veseľáščusja.]),
    "",
    sText([Állilúija, (#translation.at("PSALM") 113)]),
    gText("1"),
    par([Vo íschóďi Izráilevi ot jéhýpta, dómu Jákovľa íz ľudéj várvar,]),
    gText("2"),
    par([Býsť íudéa svjatýňa jéhó, Izráiľ óblasť jéhó.]),
    gText("3"),
    par([Móre víďi í pobižé, íordán vozvratísja vspjáť:]),
    gText("4"),
    par([Hóry vzyhrášasja jáko óvní, í chólmi jáko áhncy óvčiji.]),
    gText("5"),
    par([Čtó ti jésť, móre, jáko pobíhlo jésí, í tebí, íordáne, jáko vozvratílsja jésí vspjáť:]),
    gText("6"),
    par([Hóry, jáko vzyhrástesja jáko óvní, í chólmi jáko áhncy óvčiji.]),
    gText("7"),
    par([Ot licá Hospodňa podvížesja zemľá, ot licá Boha Jákovľa:]),
    gText("8"),
    par([Óbráščšaho kámeň vo jézéra vodnája í nesikómyj vo ístóčniki vodnýja.]),
    gText("9"),
    par([Ne nám, Hospodi, ne nám, no ímeni tvojemú dážď slávu ó mílosti tvojéj í ístiňi tvojéj:]),
    gText("10"),
    par([Da ne kohdá rekút jázýcy: hďí jésť Boh ích;]),
    gText("11"),
    par([Boh že náš na nebesí í na zemlí, vsjá jélíka voschoťí, sotvorí.]),
    gText("12"),
    par([Ídoli jázýk srebró í zláto, ďilá rúk čelovíčeskich:]),
    gText("13"),
    par([Ústá ímut, í ne vozhlahóľut: óči ímut, í ne úzrjat:]),
    gText("14"),
    par([Úši ímut, í ne úslýšat: nózdri ímut, í ne óboňájut:]),
    gText("15"),
    par([Rúci ímut, í ne ósjážut: nózi ímut, í ne pójdut: ne vozhlasját hortánem svojím.]),
    gText("16"),
    par([Podóbni ím da búdut tvorjáščiji já í vsí naďíjuščijisja na ňá.]),
    gText("17"),
    par([Dóm Izráilev úpová na Hospoda: pomóščnik í zaščítiteľ ím jésť.]),
    gText("18"),
    par([Dóm áaróň úpová na Hospoda: pomóščnik í zaščítiteľ ím jésť.]),
    gText("19"),
    par([Bojáščijisja Hospoda úpováša na Hospoda: pomóščnik í zaščítiteľ ím jésť.]),
    gText("20"),
    par([Hospoď pomjanúv ný bláhoslovíl jésť nás: bláhoslovíl jésť dóm Izráilev, bláhoslovíl jésť dóm áaróň,]),
    gText("21"),
    par([Bláhoslovíl jésť bojáščyjasja Hospoda, mályja s velíkimi.]),
    gText("22"),
    par([Da priložít Hospoď na vý, na vý í na sýny váša:]),
    gText("23"),
    par([Bláhoslovéni vý Hospodevi, sotvóršemu nebo í zémľu.]),
    gText("24"),
    par([Nebo nebesé Hospodevi, zémľu že dadé synovóm čelovíčeskim.]),
    gText("25"),
    par([Ne mértviji voschváľat ťá, Hospodi, nižé vsí nizchoďáščiji vo ád:]),
    gText("26"),
    par([No mý živíji bláhoslovím Hospoda ot nýňi í do víka.]),
    "",
    sText([Állilúija, (#translation.at("PSALM") 114)]),
    gText("1"),
    par([Vozľubích, jáko úslýšit Hospoď hlás molénija mojehó,]),
    gText("2"),
    par([Jáko prikloní úcho svojé mňí: í vo dní mojá prizovú.]),
    gText("3"),
    par([Óbjáša mjá boľízni smértnyja, bidý ádovy óbritóša mjá: skórb í boľízň óbritóch í ímja Hospodne prizvách:]),
    gText("4"),
    par([O, Hospodi, ízbávi dúšu mojú: mílostiv Hospoď í právedn, í Boh náš mílujet.]),
    gText("5"),
    par([Chraňáj mladéncy Hospod: smiríchsja, í Spasé mja.]),
    gText("6"),
    par([Óbratísja, dušé mojá, v pokój tvój, jáko Hospoď bláhoďíjstvova ťá:]),
    gText("7"),
    par([Jáko ízját dúšu mojú ot smérti, óči moí ot sléz í nózi moí ot popolznovénija.]),
    gText("8"),
    par([Bláhouhoždú pred Hospodem vo straňí živých.]),
    col2(gText([#translation.at("SI")])),
  ))
== #translation.at("ANTIFON") 3
  #generateTable((
    "",
    sText([Állilúija, (#translation.at("PSALM") 115)]),
    gText("1"),
    par([Vírovach, ťímže vozhlahólach: áz že smiríchsja ziló.]),
    gText("2"),
    par([Áz že rích vo ízstupléniji mojém: vsják čelovík lóž.]),
    gText("3"),
    par([Čtó vozdám Hospodevi ó vsích, jáže vozdadé mi;]),
    gText("4"),
    par([Čášu Spasénija prijimú í ímja Hospodne prizovú:]),
    gText("5"),
    par([Molítvy mojá Hospodevi vozdám pred vsími ľuďmí jéhó.]),
    gText("6"),
    par([Čestná pred Hospodem smérť prepodóbnych jéhó.]),
    gText("7"),
    par([O, Hospodi, áz ráb tvój, áz ráb tvój í sýn rabýni tvojejá: rasterzál jésí úzy mojá.]),
    gText("8"),
    par([Tebí požrú žértvu chvalý, í vo ímja Hospodne prizovú.]),
    gText("9"),
    par([Molítvy mojá Hospodevi vozdám pred vsími ľuďmí jéhó,]),
    gText("10"),
    par([Vo dvórich dómu Hospodňa, posreďí tebé, Jerúsaľíme.]),
    "",
    sText([Állilúija, (#translation.at("PSALM") 116)]),
    gText("1"),
    par([Chvalíte Hospoda, vsí jázýcy, pochvalíte jéhó, vsí ľúdije:]),
    gText("2"),
    par([Jáko útverdísja mílosť jéhó na nás, í ístina Hospodňa prebyvájet vo vík.]),
    "",
    sText([Állilúija, (#translation.at("PSALM") 117)]),
    gText("1"),
    par([Íspovídajtesja Hospodevi, jáko bláh, jáko v vík mílosť jéhó.]),
    gText("2"),
    par([Da rečét úbo dóm Izráilev: jáko bláh, jáko v vík mílosť jéhó.]),
    gText("3"),
    par([Da rečét úbo dóm áaróň: jáko bláh, jáko v vík mílosť jéhó.]),
    gText("4"),
    par([Da rekút úbo vsí bojáščijisja Hospoda: jáko bláh, jáko v vík mílosť jéhó.]),
    gText("5"),
    par([Ot skórbi prizvách Hospoda, í úslýša mjá v prostránstvo.]),
    gText("6"),
    par([Hospoď mňí pomóščnik, í ne úbojúsja: čtó sotvorít mňí čelovík;]),
    gText("7"),
    par([Hospoď mňí pomóščnik, í áz vozzrjú na vrahí mojá.]),
    gText("8"),
    par([Bláho jésť naďíjatisja na Hospoda, néželi naďíjatisja na čelovíka:]),
    gText("9"),
    par([Bláho jésť úpováti na Hospoda, néželi úpováti na kňázi.]),
    gText("10"),
    par([Vsí jázýcy óbydóša mjá, í ímenem Hospodnim protivľáchsja ím:]),
    gText("11"),
    par([Óbyšédše óbydóša mjá, í ímenem Hospodnim protivľáchsja ím:]),
    gText("12"),
    par([Óbydóša mjá jáko pčély sót, í razhoríšasja jáko óhň v térniji: í ímenem Hospodnim protivľáchsja ím.]),
    gText("13"),
    par([Otrinovén prevratíchsja pásti, í Hospoď priját mjá.]),
    gText("14"),
    par([Kríposť mojá í pínije mojé Hospoď, í býsť mí vo Spasénije.]),
    gText("15"),
    par([Hlás rádosti í Spasénija v selénijich právednych: desníca Hospodňa sotvorí sílu.]),
    gText("16"),
    par([Desníca Hospodňa voznesé mja, desníca Hospodňa sotvorí sílu.]),
    gText("17"),
    par([Ne úmrú, no žív búdu í povím ďilá Hospodňa.]),
    gText("18"),
    par([Nakazúja nakazá mja Hospoď, smérti že ne predadé mja.]),
    gText("19"),
    par([Otvérzite mňí vratá právdy: všéd v ňá, íspovímsja Hospodevi.]),
    gText("20"),
    par([Sijá vratá Hospodňa: právedniji vnídut v ňá.]),
    gText("21"),
    par([Íspovímsja tebí, jáko úslýšal mjá jésí í býl jésí mňí vo Spasénije.]),
    gText("22"),
    par([Kámeň, jéhóže nebrehóša zížduščiji, séj býsť vo hlavú úhla:]),
    gText("23"),
    par([Ot Hospoda býsť séj, í jésť díven vo óčesích nášich.]),
    gText("24"),
    par([Séj déň, jéhóže sotvorí Hospoď, vozrádujemsja í vozveselímsja v óň.]),
    gText("25"),
    par([O, Hospodi, Spasí že, o, Hospodi, pospiší že.]),
    gText("26"),
    par([Bláhoslovén hrjadýj vo ímja Hospodne: bláhoslovíchom vý íz dómu Hospodňa.]),
    gText("27"),
    par([Boh Hospoď, í jávísja nám: sostávite prázdnik vo účaščájuščich do róh óltarévych.]),
    gText("28"),
    par([Boh mój jésí tý, í íspovímsja tebí: Boh mój jésí tý, í voznesú ťa: íspovímsja tebí, jáko úslýšal mjá jésí í býl jésí mňí vo Spasénije.]),
    gText("29"),
    par([Íspovídajtesja Hospodevi, jáko bláh, jáko v vík mílosť jéhó.]),
    col2(gText([#translation.at("SI")])),
  ))
  #generateTable((
    col2(sText(translation.at("AFTER_KAFTIZMA"))),
    sText("T"),
    jObj4("",1, "", "Ín mír tebé dušé óžidájet, í sudijá chóščet tvojá óbličíti tájnaja í ľútaja. ne prebúdi úbo v zďíšnich, no predvarí vopijúšči sudijí: Bože, óčísti mjá, í Spasí mja."),
    
    // S:
    col2(gText(translation.at("S"))),
    "",
    jObj4("",none, "", "Jáko prehrišéňmi mnóhimi, í jázvami bezmírnymi óbležím jésm Spase, sohrišájaj moľú tvojé bláhoutróbije Christé: vračú nedúhujuščich posití, í íscilí, í Spasí mja."),
    
    // I:
    col2(gText(translation.at("IN"))),
    "",
    jObj4("",none, "", "Dušé mojá, čtó neradívo živéši ľiňáščisja; čtó ne pečéšisja ó zlých, íchže soďíjala jésí v žitijí; potščísja ísprávitisja, préžde dáže dvér ne zakľučít tebí Hospoď. Bohoródici pritecý, pripadí í vozopíj: úpovánije nenaďíemych, Spasí mja, mnóho k tebí prehrišívša, Vladíčice prečestaja."),
    col2(translation.at("HOSPODI_POMILUJ")+". "+sText("(40)")),
    col2(sText(translation.at("MOLITVA"))),
    "",
    jObj4("",none, "", "Hospodi svjatýj v výšnich živýj, í vsevíďaščim tvojím ókom prizirájaj na vsjú tvár, tebí prikloňáem výju duší í ťilesé, í tebí mólimsja svjatýj svjatých: prostrí rúku tvojú nevídimuju ot svjatáho žilíšča tvojehó, í bláhosloví vsjá ný, í prostí nám vsjákoje sohrišénije, vóľnoje že í nevóľnoje, Slóvom, ílí ďílom. dáruj nám Hospodi úmilénije, dáruj slézy duchóvnyja ot duší, vo óčiščénije mnóhich nášich hrichóv: dáruj véliju tvojú mílosť na mír tvój, í na ný nedostójnyja rabý tvojá: jáko bláhoslovénno í preproslávlenno jésť ímja tvojé, Ótcá, í Sýna, í svjatáho Dúcha, nýňi í prísno, í vo víki vikóv, ámíň."),
  ))
])
