#import "../../../../all.typ": *
= #translation.at("KAFTIZMA") 17

#columns(2, gutter: 2pt, [

== #translation.at("ANTIFON") 1
  #generateTable((
    "",
    sText([Állilúija, (#translation.at("PSALM") 118)]),
    gText("1"),
    par([Blážéni neporóčniji v púť #footnote("v putí"), choďáščiji v zakóňi Hospodni.]),
    gText("2"),
    par([Blážéni íspytájuščiji sviďínija jéhó, vsím sr-d*cem vzýščut jéhó.]),
    gText("3"),
    par([Ne ďílajuščiji bo bezzakónija v putéch jéhó chodíša.]),
    gText("4"),
    par([Tý zapovídal jésí zápovidi tvojá sochraníti ziló:]),
    gText("5"),
    par([Dabý ísprávilisja putijé moí, sochraníti ópravdánija tvojá.]),
    gText("6"),
    par([Tohdá ne postyžúsja, vnehdá prizríti mí na vsjá zápovidi tvojá.]),
    gText("7"),
    par([Íspovímsja tebí v právosti sérdca, vnehdá naučíti mi sja suďbám právdy tvojejá.]),
    gText("8"),
    par([Ópravdánija tvojá sochraňú: ne óstávi mené do zilá.]),
    gText("9"),
    par([V česóm ísprávit júňíjšij púť svój; vnehdá sochraníti slovesá tvojá.]),
    gText("10"),
    par([Vsím sérdcem mojím vzyskách tebé: ne otríni mené ot zápovidij tvojích.]),
    gText("11"),
    par([V sérdcy mojém skrých slovesá tvojá, jáko da ne sohrišú tebí.]),
    gText("12"),
    par([Bláhoslovén jésí, Hospodi: naučí mja ópravdánijem tvoím.]),
    gText("13"),
    par([Ústnáma mojíma vozvistích vsjá suďbý úst tvojích.]),
    gText("14"),
    par([Na putí sviďínij tvojích nasladíchsja, jáko ó vsjákom bohátstvi.]),
    gText("15"),
    par([V zápovidech tvojích pohlumľúsja, í úrazumíju putí tvojá.]),
    gText("16"),
    par([Vo ópravdánijich tvojích poučúsja: ne zabúdu slovés tvojích.]),
    gText("17"),
    par([Vozdážď rabú tvojemú: živí mja, í sochraňú slovesá tvojá.]),
    gText("18"),
    par([Otkrýj óči moí, í úrazumíju čudesá ot zakóna tvojehó.]),
    gText("19"),
    par([Prišléc áz jésm na zemlí: ne skrýj ot mené zápovidi tvojá.]),
    gText("20"),
    par([Vozľubí dušá mojá vozželáti suďbý tvojá na vsjákoje vrémja.]),
    gText("21"),
    par([Zapretíl jésí hórdym: prókľati úkloňájuščijisja ot zápovidij tvojích.]),
    gText("22"),
    par([Otimí ot mené ponós ponošénije í úničižénije, jáko sviďínij tvojích vzyskách.]),
    gText("23"),
    par([Íbo sidóša kňázi í na mjá klevetáchu, ráb že tvój hlumľášesja vo ópravdánijich tvojích:]),
    gText("24"),
    par([Íbo sviďínija tvojá poučénije mojé jésť, í sovíti moí ópravdánija tvojá.]),
    gText("25"),
    par([Priľpé zemlí dušá mojá: živí mja po slovesí tvojemú.]),
    gText("26"),
    par([Putí mojá vozvistích, í úslýšal mjá jésí: naučí mja ópravdánijem tvoím.]),
    gText("27"),
    par([Púť ópravdánij tvojích vrazumí mi, í pohlumľúsja v čudesích tvojích.]),
    gText("28"),
    par([Vozdremá dušá mojá ot únýnija: útverdí mja v slovesích tvojích.]),
    gText("29"),
    par([Púť neprávdy otstávi ot mené í zakónom tvojím pomíluj mjá.]),
    gText("30"),
    par([Púť ístiny ízvólich í suďbý tvojá ne zabých.]),
    gText("31"),
    par([Priľipíchsja sviďínijem tvoím, Hospodi, ne posramí mené.]),
    gText("32"),
    par([Púť zápovidij tvojích tekóch, jéhdá razširíl jésí sérdce mojé.]),
    gText("33"),
    par([Zakonopoloží mňí, Hospodi, púť ópravdánij tvojích, í vzyščú í výnu:]),
    gText("34"),
    par([Vrazumí mja, í íspytáju zakón tvój í sochraňú í vsím sérdcem mojím.]),
    gText("35"),
    par([Nastávi mjá na stezjú zápovidij tvojích, jáko túju voschoťích.]),
    gText("36"),
    par([Prikloní sérdce mojé vo sviďínija tvojá, á ne v lichojímstvo.]),
    gText("37"),
    par([Otvratí óči moí jéže ne víďiti sujetý: v putí tvojém živí mja.]),
    gText("38"),
    par([Postávi rabú tvojemú Slóvo tvojé v strách tvój.]),
    gText("39"),
    par([Otimí ponošénije mojé, jéže nepščevách: jáko suďbý tvojá bláhi.]),
    gText("40"),
    par([Sé, vozželách zápovidi tvojá: v právďi tvojéj živí mja.]),
    gText("41"),
    par([Í da prijídet na mjá mílosť tvojá, Hospodi, Spasénije tvojé po slovesí tvojemú:]),
    gText("42"),
    par([Í otviščáju ponošájuščym mí Slóvo, jáko úpovách na slovesá tvojá.]),
    gText("43"),
    par([Í ne otimí ot úst mojích slovesé ístinna do zilá, jáko na suďbý tvojá úpovách:]),
    gText("44"),
    par([Í sochraňú zakón tvój výnu, v vík í v vík víka.]),
    gText("45"),
    par([Í choždách v široťí, jáko zápovidi tvojá vzyskách:]),
    gText("46"),
    par([Í hlahólach ó sviďínijich tvojích pred carí í ne styďáchsja:]),
    gText("47"),
    par([Í poučáchsja v zápovidech tvojích, jáže vozľubích ziló:]),
    gText("48"),
    par([Í vozdvihóch rúci moí k zápovidem tvoím, jáže vozľubích, í hlumľáchsja vo ópravdánijich tvojích.]),
    gText("49"),
    par([Pomjaní slovesá tvojá rabú tvojemú, íchže úpovánije dál mí jésí.]),
    gText("50"),
    par([Tó mja úťíši vo smiréniji mojém, jáko Slóvo tvojé živí mja.]),
    gText("51"),
    par([Hórdiji zakonoprestupováchu do zilá: ot zakóna že tvojehó ne úkloníchsja.]),
    gText("52"),
    par([Pomjanúch suďbý tvojá ot víka, Hospodi, í úťíšichsja.]),
    gText("53"),
    par([Pečáľ priját mjá ot hríšnik, óstavľájuščich zakón tvój.]),
    gText("54"),
    par([Píta bjáchu mňí ópravdánija tvojá na mísťi prišéľstvija mojehó.]),
    gText("55"),
    par([Pomjanúch v noščí ímja tvojé, Hospodi, í sochraních zakón tvój.]),
    gText("56"),
    par([Séj býsť mňí, jáko ópravdánij tvojích vzyskách.]),
    gText("57"),
    par([Čásť mojá jésí, Hospodi: rích sochraníti zakón tvój.]),
    gText("58"),
    par([Pomolíchsja licú tvojemú vsím sérdcem mojím: pomíluj mjá po slovesí tvojemú.]),
    gText("59"),
    par([Pomýslich putí tvojá í vozvratích nózi moí vo sviďínija tvojá.]),
    gText("60"),
    par([Úhotóvichsja í ne smutíchsja sochraníti zápovidi tvojá.]),
    gText("61"),
    par([Úžja hríšnik óbjazášasja mňí, í zakóna tvojehó ne zabých.]),
    gText("62"),
    par([Polúnošči vostách íspovídatisja tebí ó suďbách právdy tvojejá.]),
    gText("63"),
    par([Pričástnik áz jésm vsím bojáščymsja tebé í chraňáščym zápovidi tvojá.]),
    gText("64"),
    par([Mílosti tvojejá, Hospodi, íspólň zemľá: ópravdánijem tvoím naučí mja.]),
    gText("65"),
    par([Bláhosť sotvoríl jésí s rabóm tvojím, Hospodi, po slovesí tvojemú:]),
    gText("66"),
    par([Bláhosti í nakazániju í rázumu naučí mja, jáko zápovidem tvoím vírovach.]),
    gText("67"),
    par([Préžde dáže ne smiríti mi sja, áz prehriších: sehó rádi Slóvo tvojé sochraních.]),
    gText("68"),
    par([Bláh jésí tý, Hospodi: í bláhostiju tvojéju naučí mja ópravdánijem tvoím.]),
    gText("69"),
    par([Úmnóžisja na mjá neprávda hórdych: áz že vsím sérdcem mojím íspytáju zápovidi tvojá.]),
    gText("70"),
    par([Úsyrísja jáko mlekó sérdce ích: áz že zakónu tvojemú poučíchsja.]),
    gText("71"),
    par([Bláho mňí, jáko smiríl mjá jésí, jáko da naučúsja ópravdánijem tvoím.]),
    gText("72"),
    par([Bláh mňí zakón úst tvojích páče týsjašč zláta í srebrá.]),
    col2(gText([#translation.at("SI")])),
  ))
== #translation.at("ANTIFON") 2
  #generateTable((
    gText("73"),
    par([Rúci tvoí sotvorísťi mjá í sozdásťi mjá: vrazumí mja, í naučúsja zápovidem tvoím.]),
    gText("74"),
    par([Bojáščijisja tebé úzrjat mjá í vozveseľátsja, jáko na slovesá tvojá úpovách.]),
    gText("75"),
    par([Razumích, Hospodi, jáko právda suďbý tvojá, í vojístinnu smiríl mjá jésí.]),
    gText("76"),
    par([Búdi že mílosť tvojá, da úťíšit mjá, po slovesí tvojemú rabú tvojemú:]),
    gText("77"),
    par([Da prijídut mňí ščedróty tvojá, í žív búdu, jáko zakón tvój poučénije mojé jésť.]),
    gText("78"),
    par([Da postyďátsja hórdiji, jáko neprávedno bezzakónnovaša na mjá: áz že pohlumľúsja #footnote("razmyšľáti búdu") v zápovidech tvojích.]),
    gText("79"),
    par([Da óbraťát mjá bojáščijisja tebé í víďaščiji sviďínija tvojá.]),
    gText("80"),
    par([Búdi sérdce mojé neporóčno vo ópravdánijich tvojích, jáko da ne postyžúsja.]),
    gText("81"),
    par([Ísčezájet vo Spasénije tvojé dušá mojá, na slovesá tvojá úpovách:]),
    gText("82"),
    par([Ísčezóša óči moí v Slóvo tvojé, hlahóľušče: kohdá úťíšiši mjá;]),
    gText("83"),
    par([Zané bých jáko mích na sláňi: ópravdánij tvojích ne zabých.]),
    gText("84"),
    par([Kolíko jésť dníj rabá tvojehó; kohdá sotvoríši mí ot hoňáščich mjá súd;]),
    gText("85"),
    par([Povídaša mňí zakonoprestúpnicy hlumlénija, no ne jáko zakón tvój, Hospodi.]),
    gText("86"),
    par([Vsjá zápovidi tvojá ístina: neprávedno pohnáša mjá, pomozí mi.]),
    gText("87"),
    par([Vmáľi ne skončáša mené na zemlí: áz že ne óstávich zápovidij tvojích.]),
    gText("88"),
    par([Po mílosti tvojéj živí mja, í sochraňú sviďínija úst tvojích.]),
    gText("89"),
    par([Vo vík, Hospodi, Slóvo tvojé prebyvájet na nebesí.]),
    gText("90"),
    par([V ród í ród ístina tvojá: ósnovál jésí zémľu, í prebyvájet.]),
    gText("91"),
    par([Účinénijem tvojím prebyvájet déň: jáko vsjáčeskaja rabótna tebí.]),
    gText("92"),
    par([Jáko ášče by ne zakón tvój poučénije mojé býl, tohdá úbo pohíbl bých vo smiréniji mojém:]),
    gText("93"),
    par([Vo vík ne zabúdu ópravdánij tvojích, jáko v ních óživíl mjá jésí.]),
    gText("94"),
    par([Tvój jésm áz, Spasí mja: jáko ópravdánij tvojích vzyskách.]),
    gText("95"),
    par([Mené ždáša hríšnicy pohubíti mjá: sviďínija tvojá razumích.]),
    gText("96"),
    par([Vsjákija končíny víďich konéc: široká zápoviď tvojá ziló.]),
    gText("97"),
    par([Kóľ vozľubích zakón tvój, Hospodi: vés déň poučénije mojé jésť.]),
    gText("98"),
    par([Páče vráh mojích úmudríl mjá jésí zápovidiju tvojéju, jáko v vík mojá jésť.]),
    gText("99"),
    par([Páče vsích účáščich mjá razumích, jáko sviďínija tvojá poučénije mojé jésť.]),
    gText("100"),
    par([Páče stárec razumích, jáko zápovidi tvojá vzyskách.]),
    gText("101"),
    par([Ot vsjákaho putí lukáva vozbraních nohám moím, jáko da sochraňú slovesá tvojá:]),
    gText("102"),
    par([Ot sudéb tvojích ne úkloníchsja, jáko tý zakonopoložíl mí jésí.]),
    gText("103"),
    par([Kóľ sladká hortáni mojemú slovesá tvojá: páče méda ústóm moím.]),
    gText("104"),
    par([Ot zápovidij tvojích razumích: sehó rádi voznenavíďich vsják púť neprávdy.]),
    gText("105"),
    par([Svitíľnik noháma mojíma zakón tvój, í svít stezjám moím.]),
    gText("106"),
    par([Kľáchsja í postávich sochraníti suďbý právdy tvojejá.]),
    gText("107"),
    par([Smiríchsja do zilá: Hospodi, živí mja po slovesí tvojemú.]),
    gText("108"),
    par([Vóľnaja úst mojích bláhovolí že, Hospodi, í suďbám tvoím naučí mja.]),
    gText("109"),
    par([Dušá mojá v rukú tvoéju #footnote("Álež.: moéju") výnu, í zakóna tvojehó ne zabých.]),
    gText("110"),
    par([Položíša hríšnicy síť mňí: í ot zápovidij tvojích ne zabludích.]),
    gText("111"),
    par([Nasľídovach sviďínija tvojá vo vík, jáko rádovanije sérdca mojehó súť:]),
    gText("112"),
    par([Prikloních sérdce mojé sotvoríti ópravdánija tvojá v vík za vozdajánije.]),
    gText("113"),
    par([Zakonoprestúpnyja voznenavíďich, zakón že tvój vozľubích.]),
    gText("114"),
    par([Pomóščnik mój í zastúpnik mój jésí tý: na slovesá tvojá úpovách.]),
    gText("115"),
    par([Úklonítesja ot mené, lukávnujuščiji, í íspytáju zápovidi Boha mojehó.]),
    gText("116"),
    par([Zastupí mja po slovesí tvojemú, í žív búdu: í ne posramí mené ot čájanija mojehó:]),
    gText("117"),
    par([Pomozí mi, í Spasúsja, í poučúsja vo ópravdánijich tvojích výnu.]),
    gText("118"),
    par([Úničižíl jésí vsjá otstupájuščyja ot ópravdánij tvojích: jáko neprávedno pomyšlénije ích.]),
    gText("119"),
    par([Prestupájuščyja nepščevách vsjá hríšnyja zemlí: sehó rádi vozľubích sviďínija tvojá.]),
    gText("120"),
    par([Prihvozdí stráchu tvojemú plóti mojá: ot sudéb bo tvojích úbojáchsja.]),
    gText("121"),
    par([Sotvorích súd í právdu: ne predážď mené óbíďaščym mjá.]),
    gText("122"),
    par([Vosprijimí rabá tvojehó vo bláho, da ne óklevetájut mené hórdiji.]),
    gText("123"),
    par([Óči moí ísčezósťi vo Spasénije tvojé í v Slóvo právdy tvojejá:]),
    gText("124"),
    par([Sotvorí s rabóm tvojím po mílosti tvojéj, í ópravdánijem tvoím naučí mja.]),
    gText("125"),
    par([Ráb tvój jésm áz: vrazumí mja, í úvím sviďínija tvojá.]),
    gText("126"),
    par([Vrémja sotvoríti Hospodevi: razoríša zakón tvój.]),
    gText("127"),
    par([Sehó rádi vozľubích zápovidi tvojá páče zláta í topázija.]),
    gText("128"),
    par([Sehó rádi ko vsím zápovidem tvoím napravľáchsja, vsják púť neprávdy voznenavíďich.]),
    gText("129"),
    par([Dívna sviďínija tvojá: sehó rádi íspytá já dušá mojá.]),
    gText("130"),
    par([Jávlénije slovés tvojích prosviščájet í vrazumľájet mladéncy.]),
    gText("131"),
    par([Ústá mojá otverzóch í privlekóch dúch, jáko zápovidij tvojích želách.]),
    col2(gText([#translation.at("SI")])),
  ))
== #translation.at("ANTIFON") 3
  #generateTable((
    gText("132"),
    par([Prízri na mjá í pomíluj mjá, po sudú ľúbjaščich ímja tvojé.]),
    gText("133"),
    par([Stopý mojá naprávi po slovesí tvojemú, í da ne óbladájet mnóju vsjákoje bezzakónije:]),
    gText("134"),
    par([Ízbávi mjá ot klevetý čelovíčeskija, í sochraňú zápovidi tvojá.]),
    gText("135"),
    par([Licé tvojé prosvití na rabá tvojehó í naučí mja ópravdánijem tvoím.]),
    gText("136"),
    par([Íschódišča vodnája ízvedósťi óči moí, ponéže ne sochraních zakóna tvojehó.]),
    gText("137"),
    par([Právedn jésí, Hospodi, í právi sudí tvoí:]),
    gText("138"),
    par([Zapovídal jésí právdu sviďínija tvojá, í ístinu ziló.]),
    gText("139"),
    par([Ístájala mjá jésť révnosť tvojá: jáko zabýša slovesá tvojá vrazí moí.]),
    gText("140"),
    par([Razžžéno Slóvo tvojé ziló, í ráb tvój vozľubí jé.]),
    gText("141"),
    par([Ю́ňíjšij áz jésm í úničižén: ópravdánij tvojích ne zabých.]),
    gText("142"),
    par([Právda tvojá právda vo vík, í zakón tvój ístina.]),
    gText("143"),
    par([Skórbi í núždi óbritóša mjá: zápovidi tvojá poučénije mojé.]),
    gText("144"),
    par([Právda sviďínija tvojá v vík: vrazumí mja, í žív búdu.]),
    gText("145"),
    par([Vozzvách vsím sérdcem mojím, úslýši mjá, Hospodi: ópravdánija tvojá vzyščú.]),
    gText("146"),
    par([Vozzvách tí, Spasí mja, í sochraňú sviďínija tvojá.]),
    gText("147"),
    par([Predvarích v bezhódiji í vozzvách: na slovesá tvojá úpovách.]),
    gText("148"),
    par([Predvarísťi óči moí ko útru, poučítisja slovesém tvoím.]),
    gText("149"),
    par([Hlás mój úslýši, Hospodi, po mílosti tvojéj: po suďbí tvojéj živí mja.]),
    gText("150"),
    par([Priblížišasja hoňáščiji mjá bezzakónijem: ot zakóna že tvojehó údalíšasja.]),
    gText("151"),
    par([Blíz jésí tý, Hospodi, í vsí putijé tvoí ístina.]),
    gText("152"),
    par([Íspérva poznách ot sviďínij tvojích, jáko v vík ósnovál já jésí.]),
    gText("153"),
    par([Vížď smirénije mojé í ízmí mja: jáko zakóna tvojehó ne zabých.]),
    gText("154"),
    par([Sudí súd mój í ízbávi mjá: slovesé rádi tvojehó živí mja.]),
    gText("155"),
    par([Daléče ot hríšnik Spasénije, jáko ópravdánij tvojích ne vzyskáša.]),
    gText("156"),
    par([Ščedróty tvojá mnóhi, Hospodi: po suďbí tvojéj živí mja.]),
    gText("157"),
    par([Mnózi ízhoňáščiji mjá í stužájuščiji mí: ot sviďínij tvojích ne úkloníchsja.]),
    gText("158"),
    par([Víďich nerazumivájuščyja í ístájach: jáko slovés tvojích ne sochraníša.]),
    gText("159"),
    par([Vížď, jáko zápovidi tvojá vozľubích: Hospodi, po mílosti tvojéj živí mja.]),
    gText("160"),
    par([Načálo slovés tvojích ístina, í vo vík vsjá suďbý právdy tvojejá.]),
    gText("161"),
    par([Kňázi pohnáša mjá túne: í ot slovés tvojích úbojásja sérdce mojé.]),
    gText("162"),
    par([Vozrádujusja áz ó slovesích tvojích, jáko óbritájaj korýsť mnóhu.]),
    gText("163"),
    par([Neprávdu voznenavíďich í ómerzích: zakón že tvój vozľubích.]),
    gText("164"),
    par([Sedmeríceju dném chvalích ťá ó suďbách právdy tvojejá.]),
    gText("165"),
    par([Mír mnóh ľúbjaščym zakón tvój, í ňísť ím soblázna.]),
    gText("166"),
    par([Čájach Spasénija tvojehó, Hospodi, í zápovidi tvojá vozľubích.]),
    gText("167"),
    par([Sochraní dušá mojá sviďínija tvojá í vozľubí já ziló.]),
    gText("168"),
    par([Sochraních zápovidi tvojá í sviďínija tvojá, jáko vsí putijé moí pred tobóju, Hospodi.]),
    gText("169"),
    par([Da priblížitsja molénije mojé pred ťá, Hospodi: po slovesí tvojemú vrazumí mja.]),
    gText("170"),
    par([Da vnídet prošénije mojé pred ťá: Hospodi, po slovesí tvojemú ízbávi mjá.]),
    gText("171"),
    par([Otrýhnut ústňí moí pínije, jéhdá naučíši mjá ópravdánijem tvoím.]),
    gText("172"),
    par([Proviščájet jázýk mój slovesá tvojá, jáko vsjá zápovidi tvojá právda.]),
    gText("173"),
    par([Da búdet ruká tvojá jéže Spastí mja, jáko zápovidi tvojá ízvólich.]),
    gText("174"),
    par([Vozželách Spasénije tvojé, Hospodi, í zakón tvój poučénije mojé jésť.]),
    gText("175"),
    par([Živá búdet dušá mojá í voschválit ťá: í suďbý tvojá pomóhut mňí.]),
    gText("176"),
    par([Zabludích jáko óvčá pohíbšeje: vzyščí rabá tvojehó, jáko zápovidij tvojích ne zabých.]),
    col2(gText([#translation.at("SI")])),
  ))
  #generateTable((
    col2(sText(translation.at("AFTER_KAFTIZMA"))),
    sText("T"),
    jObj4("",2, "", "Sohriších k tebí Spase, jáko blúdnyj sýn, prijimí mja Ótče kájuščahosja, í pomíluj mjá Bože."),
    
    // S:
    col2(gText(translation.at("S"))),
    "",
    jObj4("",none, "", "Zovú k tebí Christé Spase, mytarévym hlásom: óčísti mjá jákože ónaho, í pomíluj mjá Bože."),
    
    // I:
    col2(gText(translation.at("IN"))),
    "",
    jObj4("",none, "", "Bohoródice, ne prézri mjá, trébujušča zastuplénija tvojehó: na ťá bo úpová dušá mojá, pomíluj mjá."),
    col2(translation.at("HOSPODI_POMILUJ")+". "+sText("(40)")),
    col2(sText(translation.at("MOLITVA"))),
    "",
    jObj4("",none, "", "Vladýko Hospodi vsederžíteľu í tvórče vsích, ščedrót Ótc, í mílosti Boh, ot zemlí sozdávyj čelovíka, í pokazávyj jéhó po óbrazu tvojemú í po podóbiju, da í ťím proslávitsja velikoľípoje ímja tvojé na zemlí, í ístórhnena úbo prestuplénijem tvojích zápovidej, páki na lúčšeje vozsozdávyj jéhó vo Chrisťí tvojém, í vozvedýj na nebesá: bláhodarjú ťa, jáko úmnóžil jésí na mňí velíčije tvojé, í ne prédal mjá jésí vrahóm moím v konéc, ístórhnuti mjá íščuščym v própasť ádovu: nižé óstávil mjá jésí pohíbnuti so bezzakóňmi mojími. nýňi úbo, mnohomílostive í ľubobláže Hospodi, ne choťáj smérti hríšnaho, no óbraščénija óžidájaj, í prijémľaj, íže nizvéržennyja íspravľájaj, sokrušénnyja ísciľájaj, óbratí í mené k pokajániju, í nizvéržennaho ísprávi, í sokrušénnaho íscilí: pomjaní tvojá ščedróty, í jéže ot víka tvojú nepostižímuju bláhosť, í mojá bezmírnaja zabúdi bezzakónija, jáže ďílom í Slóvom í mýsliju soverších, razriší ósľiplénije sérdca mojehó, í dážď mí slézy úmilénija na óčiščénije skvérny mýsli mojejá. úslýši Hospodi, vonmí čelovikoľúbče, óčísti bláhoutróbne, í ot mučíteľstva vo mňí cárstvujuščich strastéj, ókajánnuju mojú dúšu svobodí: í ne ktomú da soderžít mjá hrích, nižé da vozmóžet na mjá boríteľ démon, nižé k svojemú choťíniju da vedét mjá, no deržávnoju tvojéju rukóju, jéhó vladýčestva íschítivyj mjá, tý cárstvuj vo mňí, bláhíj í čelovikoľubívyj Hospodi, í vsehó tvojehó býti, í žíti mňí próčeje po tvojéj bláhovolí vóli. í podážď mí neizrečénnoju bláhostiju, sérdca óčiščénije, úst chranénije, pravotú ďijánij, mudrovánije smirénnoje, mír pomyslóv, tišinú dušévnych mojích síl, rádosť duchóvnuju, ľubóv ístinnuju, dolhoterpínije, bláhosť, krótosť, víru nelicemírnu, vozderžánije óbderžáteľnoje, í vsích mjá bláhích plodóv íspólni, darovánijem svjatáho tvojehó Dúcha. í ne vozvedí mené v prepolovénije dníj mojích, nižé neisprávlenu í nehotóvu dúšu mojú voschítiši: no soverší mja tvojím soveršénstvom, í táko mjá nastojáščaho žitijá ízvedí, jáko da nevozbránno prošéd načála í vlásti ťmý, tvojéju bláhodátiju úzrjú í áz nepristúpnyja tvojejá slávy dobrótu neizrečénnuju, so vsími svjatými tvojími: v níchže ósvjatísja, í proslávisja vsečestnóje í velikoľípoje ímja tvojé, Ótcá, í Sýna, í svjatáho Dúcha, nýňi í prísno, í vo víki vikóv, ámíň."),
  ))
])
