#import "../../../../all.typ": *
= #translation.at("KAFTIZMA") 18

#columns(2, gutter: 2pt, [

== #translation.at("ANTIFON") 1
  #generateTable((
    "",
    sText([Písň stepénej, (#translation.at("PSALM") 119)]),
    gText("1"),
    par([Ko Hospodu, vnehdá skorbíti mí, vozzvách, í úslýša mjá.]),
    gText("2"),
    par([Hospodi, ízbávi dúšu mojú ot ústén neprávednych í ot jázýka ľstíva.]),
    gText("3"),
    par([Čtó dástsja tebí, ílí čtó priložítsja tebí k jázýku ľstívu;]),
    gText("4"),
    par([Stríly síľnaho ízoščrény, so úhľmi pustýnnymi.]),
    gText("5"),
    par([Úvý mňí, jáko prišéľstvije mojé prodolžísja, vselíchsja s seléniji kidárskimi:]),
    gText("6"),
    par([Mnóho prišéľstvova dušá mojá: s nenavíďaščimi míra bích míren:]),
    gText("7"),
    par([Jéhdá hlahólach ím, borjáchu mjá túne.]),
    "",
    sText([Písň stepénej, (#translation.at("PSALM") 120)]),
    gText("1"),
    par([Vozvedóch óči moí v hóry, otňúduže prijídet pómošč mojá.]),
    gText("2"),
    par([Pómošč mojá ot Hospoda, sotvóršaho nébo í zémľu.]),
    gText("3"),
    par([Ne dážď vo smjaténije nohí tvojejá, nižé vozdrémlet chraňáj ťá:]),
    gText("4"),
    par([Sé, ne vozdrémlet, nižé úsnet chraňáj Izráiľa.]),
    gText("5"),
    par([Hospoď sochranít ťá, Hospoď pokróv tvój na rúku desnúju tvojú.]),
    gText("6"),
    par([Vo dní sólnce ne óžžét tebé, nižé luná nóščiju.]),
    gText("7"),
    par([Hospoď sochranít ťá ot vsjákaho zlá, sochranít dúšu tvojú Hospod:]),
    gText("8"),
    par([Hospoď sochranít vchoždénije tvojé í íschoždénije tvojé, ot nýňi í do víka.]),
    "",
    sText([Písň stepénej, (#translation.at("PSALM") 121)]),
    gText("1"),
    par([Vozveselíchsja ó rékšich mňí: v dóm Hospodeň pójdem.]),
    gText("2"),
    par([Stojášče bjáchu nóhi náša vo dvórich tvojích, Jerúsaľíme.]),
    gText("3"),
    par([Jerúsaľím zíždemyj jáko hrád, jémúže pričástije jéhó vkúpi.]),
    gText("4"),
    par([Támo bo vzydóša koľína, koľína Hospodňa, sviďínije Izráilevo, íspovídatisja ímeni Hospodňu:]),
    gText("5"),
    par([Jáko támo sidóša prestóli na súd, prestóli v domú Davidovi.]),
    gText("6"),
    par([Voprosíte že jáže ó míri Jerúsaľíma: í óbílije ľúbjaščym ťá.]),
    gText("7"),
    par([Búdi že mír v síľi tvojéj, í óbílije v stolposťinách tvojích.]),
    gText("8"),
    par([Rádi brátij mojích í blížnich mojích hlahólach úbo mír ó tebí.]),
    gText("9"),
    par([Dómu rádi Hospoda Boha nášeho vzyskách bláhája tebí.]),
    "",
    sText([Písň stepénej, (#translation.at("PSALM") 122)]),
    gText("1"),
    par([K tebí vozvedóch óči moí, živúščemu na nebesí.]),
    gText("2"),
    par([Sé, jáko óči ráb v rukú hospódij svojích, jáko óči rabýni v rukú hospoží svojejá: táko óči náši ko Hospodu Bohu nášemu, dóndeže úščédrit ný.]),
    gText("3"),
    par([Pomíluj nás, Hospodi, pomíluj nás, jáko pomnóhu íspólnichomsja úničižénija:]),
    gText("4"),
    par([Naipáče napólnisja dušá náša ponošénija hobzújuščich í úničižénija hórdych.]),
    "",
    sText([Písň stepénej, (#translation.at("PSALM") 123)]),
    gText("1"),
    par([Jáko ášče ne Hospoď by býl v nás, da rečét úbo Izráiľ:]),
    gText("2"),
    par([Jáko ášče ne Hospoď by býl v nás, vnehdá vostáti čelovíkom na ný, úbo živých požérli býša nás:]),
    gText("3"),
    par([Vnehdá prohňívatisja járosti ích na ný, úbo vodá potopíla by nás.]),
    gText("4"),
    par([Potók préjde dušá náša:]),
    gText("5"),
    par([Úbo préjde dušá náša vódu nepostojánnuju.]),
    gText("6"),
    par([Bláhoslovén Hospoď, íže ne dadé nás v lovítvu zubóm ích.]),
    gText("7"),
    par([Dušá náša jáko ptíca ízbávisja ot síti lovjáščich: síť sokrušísja, í mý ízbávleni býchom.]),
    gText("8"),
    par([Pómošč náša vo ímja Hospoda, sotvóršaho nébo í zémľu.]),
    col2(gText([#translation.at("SI")])),
  ))
== #translation.at("ANTIFON") 2
  #generateTable((
    "",
    sText([Písň stepénej, (#translation.at("PSALM") 124)]),
    gText("1"),
    par([Naďíjuščijisja na Hospoda, jáko horá Sijón: ne podvížitsja v vík živýj vo Jerúsaľími.]),
    gText("2"),
    par([Hóry ókrest jéhó, í Hospoď ókrest ľudéj svojích, ot nýňi í do víka.]),
    gText("3"),
    par([Jáko ne óstávit Hospoď žezlá hríšnych na žrébij právednych, jáko da ne próstrut právedniji v bezzakónija rúk svojích.]),
    gText("4"),
    par([Úbláží, Hospodi, bláhíja í právyja sr-d*cem.]),
    gText("5"),
    par([Úkloňájuščyjasja že v razvraščénija otvedét Hospoď s ďílajuščimi bezzakónije: mír na Izráiľa.]),
    "",
    sText([Písň stepénej, (#translation.at("PSALM") 125)]),
    gText("1"),
    par([Vnehdá vozvratíti Hospodu pľín sijóň, býchom jáko úťíšeni.]),
    gText("2"),
    par([Tohdá íspólnišasja rádosti ústá náša, í jázýk náš vesélija: tohdá rekút vo jázýcich: vozvelíčil jésť Hospoď sotvoríti s ními.]),
    gText("3"),
    par([Vozvelíčil jésť Hospoď sotvoríti s námi: býchom veseľáščesja.]),
    gText("4"),
    par([Vozvratí, Hospodi, pľinénije náše, jáko potóki júhom.]),
    gText("5"),
    par([Síjuščiji slezámi, rádostiju póžnut.]),
    gText("6"),
    par([Choďáščiji choždáchu í plákachusja, metájušče símena svojá: hrjadúšče že prijídut rádostiju, vzémľušče rukojáti svojá.]),
    "",
    sText([Písň stepénej, (#translation.at("PSALM") 126)]),
    gText("1"),
    par([Ášče ne Hospoď sozíždet dóm, vsúje trudíšasja zížduščiji: ášče ne Hospoď sochranít hrád, vsúje bďí strehíj.]),
    gText("2"),
    par([Vsúje vám jésť útrenevati: vostánete po siďíniji jádúščiji chľíb boľízni, jéhdá dást vozľúblennym svoím són.]),
    gText("3"),
    par([Sé, dostojánije Hospodne sýnove, mzdá plodá črévňaho.]),
    gText("4"),
    par([Jáko stríly v rucí síľnaho, táko sýnove ottrjasénnych.]),
    gText("5"),
    par([Blážén, íže íspólnit želánije svojé ot ních: ne postyďátsja, jéhdá hlahóľut vrahóm svoím vo vraťích.]),
    "",
    sText([Písň stepénej, (#translation.at("PSALM") 127)]),
    gText("1"),
    par([Blážéni vsí bojáščijisja Hospoda, choďáščiji v putéch jéhó:]),
    gText("2"),
    par([Trudý plodóv #footnote("rúk") tvojích sňísi: blážén jésí, í dobró tebí búdet.]),
    gText("3"),
    par([Žená tvojá jáko lozá plodovíta v stranách dómu tvojehó:]),
    gText("4"),
    par([Sýnove tvoí jáko novosaždénija másličnaja ókrest trapézy tvojejá.]),
    gText("5"),
    par([Sé, táko bláhoslovítsja čelovík bojájsja Hospoda.]),
    gText("6"),
    par([Bláhoslovít ťá Hospoď ot Sijóna, í úzriši bláhája Jerúsaľíma vsjá dní životá tvojehó,]),
    gText("7"),
    par([Í úzriši sýny synóv tvojích: mír na Izráiľa.]),
    "",
    sText([Písň stepénej (#translation.at("PSALM") 128)]),
    gText("1"),
    par([Mnóžiceju brášasja so mnóju ot júnosti mojejá, da rečét úbo Izráiľ:]),
    gText("2"),
    par([Mnóžiceju brášasja so mnóju ot júnosti mojejá, íbo ne premohóša mjá.]),
    gText("3"),
    par([Na chrebťí mojém ďílaša hríšnicy, prodolžíša bezzakónije svojé.]),
    gText("4"),
    par([Hospoď právedn ssičé výja hríšnikov.]),
    gText("5"),
    par([Da postyďátsja í vozvraťátsja vspjáť vsí nenavíďaščiji Sijóna:]),
    gText("6"),
    par([Da búdut jáko travá na zďích #footnote("na króvich"), jáže préžde vostoržénija ízsše:]),
    gText("7"),
    par([Jéjuže ne íspólni rukí svojejá žňáj, í ňídra svojehó rukojáti sobirájaj:]),
    gText("8"),
    par([Í ne ríša mimochoďáščiji: bláhoslovénije Hospodne na vý, bláhoslovíchom vý vo ímja Hospodne.]),
    col2(gText([#translation.at("SI")])),
  ))
== #translation.at("ANTIFON") 3
  #generateTable((
    "",
    sText([Písň stepénej, (#translation.at("PSALM") 129)]),
    gText("1"),
    par([Íz hlubiný vozzvách k tebí, Hospodi: Hospodi, úslýši hlás mój.]),
    gText("2"),
    par([Da búdut úši tvoí vnémľušči hlásu molénija mojehó.]),
    gText("3"),
    par([Ášče bezzakónija názriši, Hospodi, Hospodi, któ postojít; jáko ú tebé óčiščénije jésť.]),
    gText("4"),
    par([Ímene rádi tvojehó poterpích ťá, Hospodi, poterpí dušá mojá v Slóvo tvojé: úpová dušá mojá na Hospoda.]),
    gText("5"),
    par([Ot stráži útrennija do nóšči, ot stráži útrennija da úpovájet Izráiľ na Hospoda:]),
    gText("6"),
    par([Jáko ú Hospoda mílosť, í mnóhoje ú nehó ízbavlénije: í tój ízbávit Izráiľa ot vsích bezzakónij jéhó.]),
    "",
    sText([Písň stepénej, (#translation.at("PSALM") 130)]),
    gText("1"),
    par([Hospodi, ne voznesésja sérdce mojé, nižé voznesósťisja óči moí: nižé chodích v velíkich, nižé v dívnych páče mené.]),
    gText("2"),
    par([Ášče ne smirenomúdrstvovach, no voznesóch dúšu mojú, jáko otdojénoje na máter svojú, táko vozdási na dúšu mojú.]),
    gText("3"),
    par([Da úpovájet Izráiľ na Hospoda ot nýňi í do víka.]),
    "",
    sText([Písň stepénej, (#translation.at("PSALM") 131)]),
    gText("1"),
    par([Pomjaní, Hospodi, Davida í vsjú krótosť jéhó:]),
    gText("2"),
    par([Jáko kľátsja Hospodevi, óbiščásja Bohu Jákovľu:]),
    gText("3"),
    par([Ášče vnídu v selénije dómu mojehó, ílí vzýdu na ódr postéli mojejá:]),
    gText("4"),
    par([Ášče dám són óčíma mojíma, í víždoma mojíma dremánije, í pokój skranijáma mojíma:]),
    gText("5"),
    par([Dóndeže óbrjášču místo Hospodevi, selénije Bohu Jákovľu.]),
    gText("6"),
    par([Sé, slýšachom já vo jéyfráthi, óbritóchom já v poľách dubrávy:]),
    gText("7"),
    par([Vnídem v selénija jéhó, poklonímsja na místo, íďíže stojásťi nózi jéhó.]),
    gText("8"),
    par([Voskresní, Hospodi, v pokój tvój, tý í kijvót svjatýni tvojejá.]),
    gText("9"),
    par([Svjaščénnicy tvoí óblekútsja právdoju, í prepodóbniji tvoí vozrádujutsja.]),
    gText("10"),
    par([ Davida rádi rabá tvojehó, ne otvratí licé pomázannaho tvojehó.]),
    gText("11"),
    par([Kľátsja Hospoď Davidu ístinoju, í ne otvéržetsja jéjá: ot plodá čréva tvojehó posaždú na prestóľi tvojém.]),
    gText("12"),
    par([Ášče sochraňát sýnove tvoí zavít mój í sviďínija mojá sijá, ímže naučú já, í sýnove ích do víka sjádut na prestóľi tvojém.]),
    gText("13"),
    par([Jáko ízbrá Hospoď Sijóna, ízvóli í v žilíšče sebí.]),
    gText("14"),
    par([Séj pokój mój vo vík víka, zďí vseľúsja, jáko ízvólich í.]),
    gText("15"),
    par([Lovítvu jéhó bláhoslovľájaj bláhoslovľú, níščyja jéhó nasýšču chľíby:]),
    gText("16"),
    par([Svjaščénniki jéhó óblekú vo Spasénije, í prepodóbniji jéhó rádostiju vozrádujutsja.]),
    gText("17"),
    par([Támo vozraščú róh Davidovi, úhotóvach svitíľnik pomázannomu mojemú.]),
    gText("18"),
    par([Vrahí jéhó óblekú studóm, na ném že procvitét svjatýňa mojá.]),
    "",
    sText([Písň stepénej, (#translation.at("PSALM") 132)]),
    gText("1"),
    par([Sé, čtó dobró, ílí čtó krasnó, no jéže žíti brátiji vkúpi;]),
    gText("2"),
    par([Jáko mýro na hlaví, schoďáščeje na bradú, bradú áaróňu, schoďáščeje na óméty ódéždy jéhó:]),
    gText("3"),
    par([Jáko rosá áermónskaja schoďáščaja na hóry Sijónskija: jáko támo zapovída Hospoď bláhoslovénije í živót do víka.]),
    "",
    sText([Písň stepénej, (#translation.at("PSALM") 133)]),
    gText("1"),
    par([Sé, nýňi bláhoslovíte Hospoda, vsí rabí Hospodni, stojáščiji v chrámi Hospodni, vo dvórich dómu Boha nášeho.]),
    gText("2"),
    par([V nóščech vozďižíte rúki váša vo svjatája í bláhoslovíte Hospoda.]),
    gText("3"),
    par([Bláhoslovít ťá Hospoď ot Sijóna, sotvorívyj nébo í zémľu.]),
    col2(gText([#translation.at("SI")])),
  ))
  #generateTable((
    col2(sText(translation.at("AFTER_KAFTIZMA"))),
    sText("T"),
    jObj4("",2, "", "Préžde dáže ne ósúdiši mjá, Hospodi mój Hospodi, dážď mí óbraščénije, í íspravlénije mnóhich mojích hrichóv: dážď mí úmilénije duchóvnoje, jáko da vozopijú k tebí: bláhoutróbne, čelovikoľúbče Bože mój, Spasí mja."),
    
    // S:
    col2(gText(translation.at("S"))),
    "",
    jObj4("",none, "", "Nesmýslennym skotóm úpodóbivyjsja áz blúdnyj, priložíchsja ím: óbraščénije mí dáruj Christé, jáko da prijimú ú tebé véliju mílosť."),
    
    // I:
    col2(gText(translation.at("IN"))),
    "",
    jObj4("",none, "", "Ne otvratí Vladíčice, licá tvojehó ot mené moľáščahosja tebí: no jáko bláhoutróbnaja Mati ščédraho Boha, potščísja préžde koncá óbraščénije mňí darováti, jáko da spássja tobóju, vospojú ťa jáko Spasénije í úpovánije mojé neposrámlennoje Hospožé mojá."),
    col2(translation.at("HOSPODI_POMILUJ")+". "+sText("(40)")),
    col2(sText(translation.at("MOLITVA"))),
    "",
    jObj4("",none, "", "Hospodi, da ne járostiju tvojéju óbličíši mené, nižé hňívom tvojím nakážeši mjá. Vladýko Hospodi Izráise Christé, Sýne Boha živáho, pomíluj mjá hríšnaho, níščaho, óbnažénnaho, ľinívaho, neradívaho, prekoslóvnaho, ókajánnaho, bludniká, preľuboďíja, malakíja, muželóžnika, skvérnaho, blúdnaho, neblahodárnaho, nemílostivaho, žestókaho, pijánicu, sožžénnaho sóvistiju, bezlíčnaho, bezderznovénnaho, bezotvítnaho, nedostójnaho tvojehó čelovikoľúbija, í dostójna vsjákaho mučénija, í hejénny, í múki: í ne rádi mnóžestva tolíkich mojích sohrišénij, mnóžestvu podložíši, ízbáviteľu, múk, no pomíluj mjá, jáko némoščen jésm, í dušéju í plótiju, í rázumom í pomyšlénijem: í ímiže vísi suďbámi, Spasí mja nedostójnaho rabá tvojehó, molitvami prečestyja Vladíčicy nášeja Bohoródicy, í vsích svjatých, ot víka tebí bláhouhóždšich: jáko bláhoslovén jésí vo víki vikóv, ámíň."),
  ))
])
