#import "../../../../all.typ": *
= #translation.at("KAFTIZMA") 19

#columns(2, gutter: 2pt, [

== #translation.at("ANTIFON") 1
  #generateTable((
    "",
    sText([Állilúija, (#translation.at("PSALM") 134)]),
    gText("1"),
    par([Chvalíte ímja Hospodne, chvalíte, rabí Hospoda,]),
    gText("2"),
    par([Stojáščiji vo chrámi Hospodni, vo dvórich dómu Boha nášeho.]),
    gText("3"),
    par([Chvalíte Hospoda, jáko bláh Hospod: pójte ímeni jéhó, jáko dobró:]),
    gText("4"),
    par([Jáko Jákova ízbrá sebí Hospoď, Izráiľa v dostojánije sebí:]),
    gText("5"),
    par([Jáko áz poznách, jáko vélij Hospoď, í Hospoď náš nad vsími bóhi:]),
    gText("6"),
    par([Vsjá, jélíka voschoťí Hospoď, sotvorí na nebesí í na zemlí, v morjách í vo vsích bézdnach.]),
    gText("7"),
    par([Vozvoďá óblaki ot posľídnich zemlí, mólniji v dóžď sotvorí, ízvoďáj vítry ot sokróvišč svojích.]),
    gText("8"),
    par([Íže porazí pérvency jéhýpetskija ot čelovíka do skotá:]),
    gText("9"),
    par([Poslá známenija í čudesá posreďí tebé, jéhýpte, na faraóna í na vsjá rabý jéhó.]),
    gText("10"),
    par([Íže porazí jázýki mnóhi í ízbí carí krípki:]),
    gText("11"),
    par([Sióna carjá ámorréjska í óha carjá vasánska, í vsjá cárstvija chanaánska:]),
    gText("12"),
    par([Í dadé zémľu ích dostojánije, dostojánije Izráiľu ľúdem svoím.]),
    gText("13"),
    par([Hospodi, ímja tvojé v vík, í pámjať tvojá v ród í ród:]),
    gText("14"),
    par([Jáko sudíti ímať Hospoď ľúdem svoím, í ó rabích svojích úmólitsja.]),
    gText("15"),
    par([Ídoli jázýk srebró í zláto, ďilá rúk čelovíčeskich:]),
    gText("16"),
    par([Ústá ímut, í ne vozhlahóľut: óči ímut, í ne úzrjat:]),
    gText("17"),
    par([Úši ímut, í ne úslýšat: nižé bo jésť dúch vo úsťích ích.]),
    gText("18"),
    par([Podóbni ím da búdut tvorjáščiji já í vsí naďíjuščijisja na ňá.]),
    gText("19"),
    par([Dóme Izráilev, bláhoslovíte Hospoda: dóme áaróň, bláhoslovíte Hospoda: dóme leyíjin, bláhoslovíte Hospoda:]),
    gText("20"),
    par([Bojáščijisja Hospoda, bláhoslovíte Hospoda.]),
    gText("21"),
    par([Bláhoslovén Hospoď ot Sijóna, živýj vo Jerúsaľími.]),
    "",
    sText([Állilúija, (#translation.at("PSALM") 135)]),
    gText("1"),
    par([Íspovídajtesja Hospodevi, jáko bláh: jáko v vík mílosť jéhó.]),
    gText("2"),
    par([Íspovídajtesja Bohu bohóv: jáko v vík mílosť jéhó.]),
    gText("3"),
    par([Íspovídajtesja Hospodevi hospodéj: jáko v vík mílosť jéhó.]),
    gText("4"),
    par([Sotvóršemu čudesá vélija jédínomu: jáko v vík mílosť jéhó.]),
    gText("5"),
    par([Sotvóršemu nebesá rázumom: jáko v vík mílosť jéhó.]),
    gText("6"),
    par([Útverdívšemu zémľu na vodách: jáko v vík mílosť jéhó.]),
    gText("7"),
    par([Sotvóršemu svitíla vélija jédínomu: jáko v vík mílosť jéhó:]),
    gText("8"),
    par([Sólnce vo óblasť dné: jáko v vík mílosť jéhó:]),
    gText("9"),
    par([Lunú í zvízdy vo óblasť nóšči: jáko v vík mílosť jéhó.]),
    gText("10"),
    par([Porazívšemu jéhýpta s pérvency jéhó: jáko v vík mílosť jéhó:]),
    gText("11"),
    par([Í ízvédšemu Izráiľa ot sredý ích: jáko v vík mílosť jéhó:]),
    gText("12"),
    par([Rukóju krípkoju í mýšceju vysókoju: jáko v vík mílosť jéhó.]),
    gText("13"),
    par([Razďíľšemu čermnóje móre v razďilénija: jáko v vík mílosť jéhó:]),
    gText("14"),
    par([Í provédšemu Izráiľa posreďí jéhó: jáko v vík mílosť jéhó:]),
    gText("15"),
    par([Í ístrjásšemu faraóna í sílu jéhó v móre čermnóje: jáko v vík mílosť jéhó.]),
    gText("16"),
    par([Provédšemu ľúdi svojá v pustýni: jáko v vík mílosť jéhó.]),
    gText("17"),
    par([Porazívšemu carí vélija: jáko v vík mílosť jéhó.]),
    gText("18"),
    par([Í úbívšemu carí krípkija: jáko v vík mílosť jéhó:]),
    gText("19"),
    par([Sióna carjá ámorréjska: jáko v vík mílosť jéhó:]),
    gText("20"),
    par([Í óha carjá vasánska: jáko v vík mílosť jéhó.]),
    gText("21"),
    par([Í dávšemu zémľu ích dostojánije: jáko v vík mílosť jéhó:]),
    gText("22"),
    par([Dostojánije Izráiľu rabú svojemú: jáko v vík mílosť jéhó.]),
    gText("23"),
    par([Jáko vo smiréniji nášem pomjanú ny Hospod: jáko v vík mílosť jéhó.]),
    gText("24"),
    par([Í ízbávil ný jésť ot vrahóv nášich: jáko v vík mílosť jéhó:]),
    gText("25"),
    par([Dajáj píšču vsjákoj plóti: jáko v vík mílosť jéhó.]),
    gText("26"),
    par([Íspovídajtesja Bohu nebésnomu: jáko v vík mílosť jéhó.]),
    "",
    sText([ Davidu íeremíem, (#translation.at("PSALM") 136)]),
    gText("1"),
    par([Na rikách vavylónskich, támo sidóchom í plákachom, vnehdá pomjanúti nám Sijóna:]),
    gText("2"),
    par([Na vérbijich posreďí jéhó óbísichom órhány náša.]),
    gText("3"),
    par([Jáko támo voprosíša ný pľínšiji nás ó slovesích písnej, í védšiji nás ó píniji: vospójte nám ot písnej Sijónskich.]),
    gText("4"),
    par([Káko vospojém písň Hospodňu na zemlí čuždéj;]),
    gText("5"),
    par([Ášče zabúdu tebé, Jerúsaľíme, zabvéna búdi desníca mojá.]),
    gText("6"),
    par([Priľpní jázýk mój hortáni mojemú, ášče ne pomjanú tebé, ášče ne predložú Jerúsaľíma, jáko v načáľi vesélija mojehó.]),
    gText("7"),
    par([Pomjaní, Hospodi, sýny jédómskija v déň Jerúsaľímľ hlahóľuščyja: ístoščájte, ístoščájte do ósnovánij jéhó.]),
    gText("8"),
    par([Dščí vavylóňa ókajánnaja, blážén, íže vozdást tebí vozdajánije tvojé, jéže vozdalá jésí nám:]),
    gText("9"),
    par([Blážén, íže ímet í razbijét mladéncy tvojá ó kámeň.]),
    col2(gText([#translation.at("SI")])),
  ))
== #translation.at("ANTIFON") 2
  #generateTable((
    "",
    sText([Psalóm Davidu, áhhéa í zacháriji, (#translation.at("PSALM") 137)]),
    gText("1"),
    par([Íspovímsja tebí, Hospodi, vsím sérdcem mojím, í pred Anhely vospojú tebí, jáko úslýšal jésí vsjá hlahóly úst mojích:]),
    gText("2"),
    par([Pokloňúsja ko chrámu svjatómu tvojemú í íspovímsja ímeni tvojemú ó mílosti tvojéj í ístiňi tvojéj, jáko vozvelíčil jésí nad vsím ímja tvojé svjatóje.]),
    gText("3"),
    par([Vóňže ášče déň prizovú ťa, skóro úslýši mjá: úmnóžiši mjá v duší mojéj síloju tvojéju.]),
    gText("4"),
    par([Da íspovíďatsja tebí, Hospodi, vsí cárije zémstiji, jáko úslýšaša vsjá hlahóly úst tvojích:]),
    gText("5"),
    par([Í da vospojút v putéch Hospodnich, jáko vélija sláva Hospodňa:]),
    gText("6"),
    par([Jáko vysók Hospoď, í smirénnyja prizirájet, í vysókaja ízdaléča vísť.]),
    gText("7"),
    par([Ášče pojdú posreďí skórbi, živíši mjá: na hňív vráh mojích prostérl jésí rúku tvojú, í Spasé mja desníca tvojá.]),
    gText("8"),
    par([Hospoď vozdást za mjá: Hospodi, mílosť tvojá vo vík: ďíl rukú tvoéju ne prézri.]),
    "",
    sText([V konéc Davidu, psalóm zachárijin, v razsíjaniji, (#translation.at("PSALM") 138)]),
    gText("1"),
    par([Hospodi, ískusíl mjá jésí í poznál mjá jésí: tý poznál jésí sidánije mojé í vostánije mojé.]),
    gText("2"),
    par([Tý razumíl jésí pomyšlénija mojá ízdaléča:]),
    gText("3"),
    par([Stezjú mojú í úže mojé tý jésí ízsľídoval í vsjá putí mojá províďil jésí.]),
    gText("4"),
    par([Jáko ňísť ľstí v jázýci mojém: sé, Hospodi, tý poznál jésí]),
    gText("5"),
    par([Vsjá posľídňaja í drévňaja: tý sozdál jésí mjá í položíl jésí na mňí rúku tvojú.]),
    gText("6"),
    par([Údivísja rázum tvój ot mené, útverdísja, ne vozmohú k nemú.]),
    gText("7"),
    par([Kámo pojdú ot Dúcha tvojehó; í ot licá tvojehó kámo bižú;]),
    gText("8"),
    par([Ášče vzýdu na nebo, tý támo jésí: ášče snídu vo ád, támo jésí.]),
    gText("9"),
    par([Ášče vozmú kriľí moí ráno í vseľúsja v posľídnich mórja,]),
    gText("10"),
    par([Í támo bo ruká tvojá nastávit mjá, í úderžít mjá desníca tvojá.]),
    gText("11"),
    par([Í rích: jédá tmá poperét mjá; í nóšč prosviščénije v sládosti mojéj.]),
    gText("12"),
    par([Jáko tmá ne pomračítsja ot tebé, í nóšč jáko déň prosvitítsja: jáko tmá jéjá, táko í svít jéjá.]),
    gText("13"),
    par([Jáko tý sozdál #footnote("sťažál") jésí útróby mojá, vosprijál mjá jésí íz čréva mátere mojejá.]),
    gText("14"),
    par([Íspovímsja tebí, jáko strášno údivílsja jésí: čúdna ďilá tvojá, í dušá mojá znájet ziló.]),
    gText("15"),
    par([Ne útaísja kósť mojá ot tebé, júže sotvoríl jésí v tájňi, í sostáv mój v preispódnich zemlí.]),
    gText("16"),
    par([Nesoďílannoje mojé víďisťi óči tvoí, í v knízi tvojéj vsí napíšutsja: vo dnéch sozíždutsja, í niktóže v ních.]),
    gText("17"),
    par([Mňí že ziló čéstni býša drúzi tvoí, Bože, ziló útverdíšasja vladýčestvija ích:]),
    gText("18"),
    par([Ízočtú ích, í páče peská úmnóžatsja: vostách, í jéščé jésm s tobóju.]),
    gText("19"),
    par([Ášče ízbijéši hríšniki, Bože: múžije krovéj, úklonítesja ot mené.]),
    gText("20"),
    par([Jáko revnívi jésté v pomyšlénijich, prijímut v sujetú hrády tvojá.]),
    gText("21"),
    par([Ne nenavíďaščyja li ťá, Hospodi, voznenavíďich, í ó vrazích tvojích ístájach;]),
    gText("22"),
    par([Soveršénnoju nénavistiju voznenavíďich já: vo vrahí býša mí.]),
    gText("23"),
    par([Ískusí mja, Bože, í úvížď sérdce mojé: ísťaží mja í razumíj stezí mojá:]),
    gText("24"),
    par([Í vížď, ášče púť bezzakónija vo mňí, í nastávi mjá na púť víčen.]),
    "",
    sText([V konéc, psalóm Davidu, (#translation.at("PSALM") 139)]),
    gText("1"),
    par([Ízmí mja, Hospodi, ot čelovíka lukáva, ot múža neprávedna ízbávi mjá:]),
    gText("2"),
    par([Íže pomýsliša neprávdu v sérdcy, vés déň ópolčáchu bráni:]),
    gText("3"),
    par([Ízostríša jázýk svój jáko zmijín: jád áspijdov pod ústnámi ích.]),
    gText("4"),
    par([Sochraní mja, Hospodi, íz rukí hríšniči, ot čelovík neprávednych ízmí mja, íže pomýsliša zapjáti stopý mojá.]),
    gText("5"),
    par([Skrýša hórdiji síť mňí í úžy, prepjáša síť noháma mojíma:]),
    gText("6"),
    par([Pri stezí soblázny položíša mí.]),
    gText("7"),
    par([Rích Hospodevi: Boh mój jésí tý, vnuší, Hospodi, hlás molénija mojehó.]),
    gText("8"),
    par([Hospodi, Hospodi, sílo Spasénija mojehó, ósiníl jésí nad hlavóju mojéju v déň bráni.]),
    gText("9"),
    par([Ne predážď mené, Hospodi, ot želánija mojehó hríšniku: pomýsliša na mjá, ne óstávi mené, da ne kohdá voznesútsja.]),
    gText("10"),
    par([Hlavá ókružénija ích, trúd ústén ích pokrýet já.]),
    gText("11"),
    par([Padút na ních úhlija óhnennaja, nizložíši já vo strastéch, í ne postoját.]),
    gText("12"),
    par([Múž jázýčen ne ísprávitsja na zemlí: múža neprávedna zlája úlovját vo ístľínije.]),
    gText("13"),
    par([Poznách, jáko sotvorít Hospoď súd níščym í mésť úbóhim.]),
    gText("14"),
    par([Óbáče právedniji íspovíďatsja ímeni tvojemú, í vseľátsja práviji s licém tvojím.]),
    col2(gText([#translation.at("SI")])),
  ))
== #translation.at("ANTIFON") 3
  #generateTable((
    "",
    sText([Psalóm Davidu, (#translation.at("PSALM") 140)]),
    gText("1"),
    par([Hospodi, vozzvách k tebí, úslýši mjá: vonmí hlásu molénija mojehó, vnehdá vozzváti mí k tebí.]),
    gText("2"),
    par([Da ísprávitsja molítva mojá jáko kadílo pred tobóju: vozďijánije rukú moéju, žértva večérňaja.]),
    gText("3"),
    par([Položí, Hospodi, chranénije ústóm moím í dvér óhraždénija ó ústnách mojích.]),
    gText("4"),
    par([Ne úkloní sérdce mojé v slovesá lukávstvija, nepščeváti viný ó hrisích s čelovíki ďílajuščimi bezzakónije: í ne sočtúsja so ízbránnymi ích.]),
    gText("5"),
    par([Nakážet mjá právednik mílostiju í óbličít mjá, jéléj že hríšnaho da ne namástit hlavý mojejá: jáko jéščé í molítva mojá vo bláhovolénijich ích.]),
    gText("6"),
    par([Požérty býša pri kámeni sudijí ích: úslýšatsja hlahóli moí, jáko vozmohóša #footnote("úsladíšasja").]),
    gText("7"),
    par([Jáko tólšča zemlí prosídesja na zemlí, rastočíšasja kósti ích pri áďi.]),
    gText("8"),
    par([Jáko k tebí, Hospodi, Hospodi, óči moí: na ťá úpovách, ne otimí dúšu mojú:]),
    gText("9"),
    par([Sochraní mja ot síti, júže sostáviša mí, í ot soblázn ďílajuščich bezzakónije.]),
    gText("10"),
    par([Padút vo mréžu svojú hríšnicy: jédín jésm áz, dóndeže prejdú.]),
    gText("1"),
    sText([Rázuma Davidu, vnehdá býti jémú v vertépi moľáščemusja, (#translation.at("PSALM") 141)]),
    gText("2"),
    par([Hlásom mojím ko Hospodu vozzvách, hlásom mojím ko Hospodu pomolíchsja.]),
    gText("3"),
    par([Prolijú pred ním molénije mojé, pečáľ mojú pred ním vozviščú.]),
    gText("4"),
    par([Vnehdá ísčezáti ot mené dúchu mojemú, í tý poznál jésí stezí mojá: na putí sém, po nemúže choždách, skrýša síť mňí.]),
    gText("5"),
    par([Smatrjách ódesnúju í vozhľádach, í ne bí znájaj mené: pohíbe bíhstvo ot mené, í ňísť vzyskájaj dúšu mojú.]),
    gText("6"),
    par([Vozzvách k tebí, Hospodi, rích: tý jésí úpovánije mojé, čásť mojá jésí na zemlí živých.]),
    gText("7"),
    par([Vonmí moléniju mojemú, jáko smiríchsja ziló: ízbávi mjá ot hoňáščich mjá, jáko úkripíšasja páče mené.]),
    gText("8"),
    par([Ízvedí íz temnícy dúšu mojú, íspovídatisja ímeni tvojemú: mené ždút právednicy, dóndeže vozdási mňí.]),
    "",
    sText([Psalóm Davidu, jéhdá hoňáše jéhó ávessalóm sýn jéhó, (#translation.at("PSALM") 142)]),
    gText("1"),
    par([Hospodi, úslýši molítvu mojú, vnuší molénije mojé vo ístiňi tvojéj, úslýši mjá v právďi tvojéj:]),
    gText("2"),
    par([Í ne vnídi v súd s rabóm tvojím, jáko ne ópravdítsja pred tobóju vsják živýj.]),
    gText("3"),
    par([Jáko pohná vráh dúšu mojú: smiríl jésť v zémľu živót mój: posadíl mjá jésť v témnych, jáko mértvyja víka.]),
    gText("4"),
    par([Í úný vo mňí dúch mój, vo mňí smjatésja sérdce mojé.]),
    gText("5"),
    par([Pomjanúch dní drévnija, poučíchsja vo vsích ďíľich tvojích, v tvorénijich rukú tvoéju poučáchsja.]),
    gText("6"),
    par([Vozďích k tebí rúci moí: dušá mojá jáko zemľá bezvódnaja tebí.]),
    gText("7"),
    par([Skóro úslýši mjá, Hospodi, ísčezé dúch mój: ne otvratí licá tvojehó ot mené, í úpodóbľusja nizchoďáščym v róv.]),
    gText("8"),
    par([Slýšanu sotvorí mňí zaútra mílosť tvojú, jáko na ťá úpovách: skaží mňí, Hospodi, púť, vóňže pojdú, jáko k tebí vzjách dúšu mojú.]),
    gText("9"),
    par([Ízmí mja ot vráh mojích, Hospodi, k tebí pribihóch.]),
    gText("10"),
    par([Naučí mja tvoríti vóľu tvojú, jáko tý jésí Boh mój: Dúch tvój bláhíj nastávit mjá na zémľu právu.]),
    gText("11"),
    par([Ímene tvojehó rádi, Hospodi, živíši mjá právdoju tvojéju: ízvedéši ot pečáli dúšu mojú:]),
    gText("12"),
    par([Í mílostiju tvojéju potrebíši vrahí mojá í pohubíši vsjá stužájuščyja duší mojéj: jáko áz ráb tvój jésm.]),
    col2(gText([#translation.at("SI")])),
  ))
  #generateTable((
    col2(sText(translation.at("AFTER_KAFTIZMA"))),
    sText("T"),
    jObj4("",7, "", "Bláhodarjá slávľu ťá, Bože mój, jáko vsím dál jésí hríšnikom pokajánije: Spase, ne posramí mené, jéhdá prijídeši sudíti míru vsemú, srámnaja ďilá sotvóršaho."),
    
    // S:
    col2(gText(translation.at("S"))),
    "",
    jObj4("",none, "", "Bezmírnaja tebí prehrišív, í bezmírnych mučénij óžidáju: Bože mój, úščédriv Spasí mja."),
    
    // I:
    col2(gText(translation.at("IN"))),
    "",
    jObj4("",none, "", "Ko mnóžestvu mílosti tvojejá nýňi pribiháju, razriší veríhi Bohoródice, sohrišénij mojích."),
    col2(translation.at("HOSPODI_POMILUJ")+". "+sText("(40)")),
    col2(sText(translation.at("MOLITVA"))),
    "",
    jObj4("",none, "", "Vladýko Christé Bože, íže strásťmí tvojími strásti mojá íscilívyj, í jázvami tvojími jázvy mojá úvračevávyj: dáruj mňí mnóho tebí prehrišívšemu slézy úmilénija. srastvorí mojemú ťílu ot óboňánija životvorjáščaho ťíla tvojehó, í nasladí dúšu mojú tvojéju čestnóju króviju ot hóresti, jéjuže mjá soprotívnik napoí, vozvýsi mój úm k tebí, dólu privlékšijsja, í vozvedí ot própasti pohíbeli: jáko ne ímam pokajánija, ne ímam úmilénija, ne ímam slezý úťíšiteľnyja, vozvoďáščija čáda ko svojemú nasľídiju. ómračíchsja úmóm v žitéjskich strastéch, ne mohú vozzríti k tebí v boľízni, ne mohú sohrítisja slezámi, jáže k tebí ľubvé: no Vladýko Hospodi Izráise Christé, sokróvišče bláhích, dáruj mňí pokajánije vsecíloje, í sérdce ľubotrúdnoje, vo vzyskánije tvojé, dáruj mňí bláhodáť tvojú, í óbnoví vo mňí zráki tvojehó óbraza. óstávich ťá, ne óstávi mené, ízýdi na vzyskánije mojé. vozvedí k pážiti tvojéj, í sopričtí mja óvcám ízbránnaho tvojehó stáda: vospitáj mjá s ními ot zláka Božéstvennych tvojích táinstv, molitvami prečestyja tvojejá Matre, í vsích svjatých tvojích, ámíň."),
  ))
])
