#import "../../../../all.typ": *
= #translation.at("KAFTIZMA") 2

#columns(2, gutter: 2pt, [

== #translation.at("ANTIFON") 1
  #generateTable((
    gText("1"),
    sText([V konéc, ó tájnych sýna, psalóm Davidu, (#translation.at("PSALM") 9)]),
    gText("2"),
    par([Íspovímsja tebí, Hospodi, vsím sérdcem mojím, povím vsjá čudesá tvojá.]),
    gText("3"),
    par([Vozveseľúsja í vozrádujusja ó tebí, pojú ímeni tvojemú, výšnij.]),
    gText("4"),
    par([Vnehdá vozvratítisja vrahú mojemú vspjáť, íznemóhut í pohíbnut ot licá tvojehó.]),
    gText("5"),
    par([Jáko sotvoríl jésí súd mój í prjú mojú: síl jésí na prestóľi, suďáj právdu.]),
    gText("6"),
    par([Zapretíl jésí jázýkom, í pohíbe nečestívyj: ímja jéhó potrebíl jésí v vík í v vík víka.]),
    gText("7"),
    par([Vrahú óskuďíša órúžija v konéc, í hrády razrušíl jésí: pohíbe pámjať jéhó s šúmom.]),
    gText("8"),
    par([Í Hospoď vo vík prebyvájet, úhotóva na súd prestól svój:]),
    gText("9"),
    par([Í tój sudíti ímať vselénňij v právdu, sudíti ímať ľúdem v pravoťí.]),
    gText("10"),
    par([Í býsť Hospoď pribížišče úbóhomu, pomóščnik vo bláhovrémenijich, v skórbech.]),
    gText("11"),
    par([Í da úpovájut na ťá znájuščiji ímja tvojé, jáko ne óstávil jésí vzyskájuščich ťá, Hospodi.]),
    gText("12"),
    par([Pójte Hospodevi, živúščemu v sijóňi, vozvistíte vo jázýcich načinánija jéhó:]),
    gText("13"),
    par([Jáko vzyskájaj króvi ích pomjanú, ne zabý zvánija úbóhich.]),
    gText("14"),
    par([Pomíluj mjá, Hospodi, vížď smirénije mojé ot vráh mojích, voznosjáj mjá ot vrát smértnych:]),
    gText("15"),
    par([Jáko da vozviščú vsjá chvalý tvojá vo vraťích dščére Sijóni: vozrádujemsja ó Spaséniji tvojém.]),
    gText("16"),
    par([Úhľibóša jázýcy v páhubi, júže sotvoríša: v síti séj, júže skrýša, úvjazé nohá ích.]),
    gText("17"),
    par([Znájem jésť Hospoď suďbý tvorjáj: v ďíľich rukú svoéju úvjazé hríšnik.]),
    gText("18"),
    par([Da vozvraťátsja hríšnicy vo ád, vsí jázýcy zabyvájuščiji Boha.]),
    gText("19"),
    par([Jáko ne do koncá zabvén búdet níščij, terpínije úbóhich ne pohíbnet do koncá.]),
    gText("20"),
    par([Voskresní, Hospodi, da ne kripítsja čelovík, da súďatsja jázýcy pred tobóju.]),
    gText("21"),
    par([Postávi, Hospodi, zakonopoložíteľa nad ními, da razumíjut jázýcy, jáko čelovícy súť.]),
    gText("22"),
    par([Vskúju, Hospodi, otstojá daléče, preziráješi vo bláhovrémenijich, v skórbech;]),
    gText("23"),
    par([Vnehdá hordítisja nečestívomu, vozharájetsja níščij: úvjazájut v sovíťich, jáže pomyšľájut.]),
    gText("24"),
    par([Jáko chvalím jésť hríšnyj v póchotech duší svojejá, í óbíďaj bláhoslovím jésť.]),
    gText("25"),
    par([Razdraží Hospoda hríšnyj: po mnóžestvu hňíva svojehó ne vzýščet: ňísť Boha pred ním.]),
    gText("26"),
    par([Óskverňájutsja putijé jéhó na vsjáko vrémja: otjémľutsja suďbý tvojá ot licá jéhó: vsími vrahí svojími óbladájet.]),
    gText("27"),
    par([Rečé bo v sérdcy svojém: ne podvížusja ot róda v ród bez zlá:]),
    gText("28"),
    par([Jéhóže kľátvy ústá jéhó pólna súť, í hóresti í ľstí: pod jázýkom jéhó trúd í boľízň.]),
    gText("29"),
    par([Prisidít v lovíteľstvi s bohátymi v tájnych, jéže úbíti nepovínnaho: óči jéhó na níščaho prizirájeťi.]),
    gText("30"),
    par([Lovít v tájňi jáko lév vo óhráďi svojéj, lovít jéže voschítiti níščaho, voschítiti níščaho, vnehdá privleščí í v síti svojéj.]),
    gText("31"),
    par([Smirít jéhó: preklonítsja í padét, vnehdá jémú óbladáti úbóhimi.]),
    gText("32"),
    par([Rečé bo v sérdcy svojém: zabý Boh, otvratí licé svojé, da ne vídit do koncá.]),
    gText("33"),
    par([Voskresní, Hospodi Bože mój, da voznesétsja ruká tvojá, ne zabúdi úbóhich tvojích do koncá.]),
    gText("34"),
    par([Česó rádi prohňíva nečestívyj Boha; rečé bo v sérdcy svojém: ne vzýščet.]),
    gText("35"),
    par([Vídiši, jáko tý boľízň í járosť smotráješi, da prédan búdet v rúci tvoí: tebí óstávlen jésť níščij, síru tý búdi pomóščnik.]),
    gText("36"),
    par([Sokruší mýšcu hríšnomu í lukávomu: vzýščetsja hrích jéhó í ne óbrjáščetsja.]),
    gText("37"),
    par([Hospoď cer vo vík í v vík víka: pohíbnete, jázýcy, ot zemlí jéhó.]),
    gText("38"),
    par([Želánije úbóhich úslýšal jésí, Hospodi, úhotóvaniju sérdca ích vňát úcho tvojé.]),
    gText("39"),
    par([Sudí síru í smirénu, da ne priložít ktomú veličátisja čelovík na zemlí.]),
    "",
    sText([V konéc, psalóm Davidu, (#translation.at("PSALM") 10)]),
    gText("1"),
    par([Na Hospoda úpovách, káko rečéte duší mojéj: previtáj po horám, jáko ptíca;]),
    gText("2"),
    par([Jáko sé, hríšnicy naľakóša lúk, úhotóvaša stríly v túľi, sostriľáti vo mráci právyja sérdcem.]),
    gText("3"),
    par([Zané jáže tý soveršíl jésí, óní razrušíša: právednik že čtó sotvorí;]),
    gText("4"),
    par([Hospoď vo chrámi svjatím svojém. Hospoď, na nebesí prestól jéhó: óči jéhó na níščaho prizirájeťi, víždi jéhó íspytájeťi sýny čelovíčeskija.]),
    gText("5"),
    par([Hospoď íspytájet právednaho í nečestívaho: ľubjáj že neprávdu nenavídit svojú dúšu.]),
    gText("6"),
    par([Ódoždít na hríšniki síti: óhň í žúpel, í dúch búren čásť čáši ích.]),
    gText("7"),
    par([Jáko právedn Hospoď í právdy vozľubí: pravotý víďi licé jéhó.]),
    col2(gText([#translation.at("SI")])),
  ))
== #translation.at("ANTIFON") 2
  #generateTable((
    gText("1"),
    sText([V konéc, ó ósmíj, psalóm Davidu, (#translation.at("PSALM") 11)]),
    gText("2"),
    par([Spasí mja, Hospodi, jáko óskuďí prepodóbnyj: jáko úmálišasja ístiny ot synóv čelovíčeskich.]),
    gText("3"),
    par([Súetnaja hlahóla kíjždo ko ískrennemu svojemú: ústňí ľstívyja v sérdcy, í v sérdcy hlahólaša zlája.]),
    gText("4"),
    par([Potrebít Hospoď vsjá ústný ľstívyja, jázýk veleríčivyj,]),
    gText("5"),
    par([Rékšyja: jázýk náš vozvelíčim, ústný náša pri nás súť: któ nám Hospoď jésť;]),
    gText("6"),
    par([Strásti rádi níščich í vozdychánija úbóhich nýňi voskresénú, hl*et Hospod: položúsja vo Spasénije, ne óbiňúsja ó ném.]),
    gText("7"),
    par([Slovesá Hospodňa slovesá čísta, srebró razžžéno, ískušéno zemlí, óčiščéno sedmeríceju.]),
    gText("8"),
    par([Tý, Hospodi, sochraníši ný í sobľudéši ný ot róda sehó í vo vík.]),
    gText("9"),
    par([Ókrest nečestíviji chóďat: po vysoťí tvojéj úmnóžil jésí sýny čelovíčeskija.]),
    gText("1"),
    sText([V konéc, psalóm Davidu, (#translation.at("PSALM") 12)]),
    gText("2"),
    par([Dokóľi, Hospodi, zabúdeši mjá do koncá; dokóľi otvraščáješi licé tvojé ot mené;]),
    gText("3"),
    par([Dokóľi položú sovíty v duší mojéj, boľízni v sérdcy mojém déň í nóšč; dokóľi voznesétsja vráh mój na mjá;]),
    gText("4"),
    par([Prízri, úslýši mjá, Hospodi Bože mój: prosvití óči moí, da ne kohdá úsnú v smérť:]),
    gText("5"),
    par([Da ne kohdá rečét vráh mój: úkripíchsja na nehó.]),
    gText("6"),
    par([Stužájuščiji mí vozrádujutsja, ášče podvížusja.]),
    gText("7"),
    par([Áz že na mílosť tvojú úpovách: vozrádujetsja sérdce mojé ó Spaséniji tvojém: vospojú Hospodevi bláhoďíjavšemu mňí í pojú ímeni Hospoda výšňaho.]),
    "",
    sText([V konéc, psalóm Davidu, (#translation.at("PSALM") 13)]),
    gText("1"),
    par([Rečé bezúmen v sérdcy svojém: ňísť Boh. Rastľíša í ómerzíšasja v načinánijich: ňísť tvorjáj bláhostýňu.]),
    gText("2"),
    par([Hospoď s nebesé priníče na sýny čelovíčeskija, víďiti, ášče jésť razumivájaj, ílí vzyskájaj Boha.]),
    gText("3"),
    par([Vsí úkloníšasja, vkúpi nekľučími býša: ňísť tvorjáj bláhostýňu, ňísť do jédínaho.]),
    gText("4"),
    par([Ni lí úrazumíjut vsí ďílajuščiji bezzakónije, sňidájuščiji ľúdi mojá v sňíď chľíba; Hospoda ne prizváša.]),
    gText("5"),
    par([Támo úbojášasja strácha, íďíže ne bí strách: jáko Hospoď v róďi právednych.]),
    gText("6"),
    par([Sovít níščaho posramíste: Hospoď že úpovánije jéhó jésť.]),
    gText("7"),
    par([Któ dást ot Sijóna Spasénije Izráilevo;]),
    gText("8"),
    par([Vnehdá vozvratít Hospoď pľinénije ľudéj svojích, vozrádujetsja Jákov, í vozveselítsja Izráiľ.]),
    col2(gText([#translation.at("SI")])),
  ))
== #translation.at("ANTIFON") 3
  #generateTable((
    "",
    sText([V konéc, psalóm Davidu, (#translation.at("PSALM") 14)]),
    gText("1"),
    par([Hospodi, któ óbitájet v žilíšči tvojém; ílí któ vselítsja vo svjatúju hóru tvojú;]),
    gText("2"),
    par([Choďáj neporóčen í ďílajaj právdu, hlahóľaj ístinu v sérdcy svojém:]),
    gText("3"),
    par([Íže ne úľstí jázýkom svojím í ne sotvorí ískrennemu svojemú zlá, í ponošénija ne priját na blížnija svojá:]),
    gText("4"),
    par([Úničižén jésť pred ním lukávnujaj, bojáščyjažesja Hospoda slávit: klenýjsja ískrennemu svojemú í ne otmetájasja:]),
    gText("5"),
    par([Srebrá svojehó ne dadé v líchvu í mzdý na nepovínnych ne priját. Tvorjáj sijá ne podvížitsja vo vík.]),
    "",
    sText([Stolpopisánije, Davidu, (#translation.at("PSALM") 15)]),
    gText("1"),
    par([Sochraní mja, Hospodi, jáko na ťá úpovách.]),
    gText("2"),
    par([Rích Hospodevi: Hospoď mój jésí tý, jáko blahích mojích ne trébuješi.]),
    gText("3"),
    par([Svjatým, íže súť na zemlí jéhó, údiví Hospoď vsjá choťínija svojá v ních.]),
    gText("4"),
    par([Úmnóžišasja némošči ích, po sích úskoríša: ne soberú sobóry ích ot krovéj, ni pomjanú že ímén ích ústnáma mojíma.]),
    gText("5"),
    par([Hospoď čásť dostojánija mojehó í čáši mojejá: tý jésí ústrojájaj dostojánije mojé mňí.]),
    gText("6"),
    par([Úžja napadóša mí v deržávnych mojích: íbo dostojánije mojé deržávno jésť mňí.]),
    gText("7"),
    par([Bláhoslovľú Hospoda vrazumívšaho mjá: jéščé že í do nóšči nakazáša mjá útróby mojá.]),
    gText("8"),
    par([Predzrích Hospoda predo mnóju výnu, jáko ódesnúju mené jésť, da ne podvížusja.]),
    gText("9"),
    par([Sehó rádi vozveselísja sérdce mojé, í vozrádovasja jázýk mój: jéščé že í plóť mojá vselítsja na úpovániji.]),
    gText("10"),
    par([Jáko ne óstáviši dúšu mojú vo áďi, nižé dási prepodóbnomu tvojemú víďiti ístľínija.]),
    gText("11"),
    par([Skazál mí jésí putí životá: íspólniši mjá vesélija s licém tvojím: krasotá #footnote("sládosť") v desníci tvojéj v konéc.]),
    "",
    sText([Molítva Davidu, (#translation.at("PSALM") 16)]),
    gText("1"),
    par([Úslýši, Hospodi, právdu mojú, vonmí moléniju mojemú, vnuší molítvu mojú ne vo ústnách ľstívych.]),
    gText("2"),
    par([Ot licá tvojehó suďbá mojá ízýdet: óči moí da vídita pravotý.]),
    gText("3"),
    par([Ískusíl jésí sérdce mojé, positíl jésí nóščiju: ískusíl mjá jésí, í ne óbrítesja vo mňí neprávda.]),
    gText("4"),
    par([Jáko da ne vozhlahóľut ústá mojá ďíl čelovíčeskich, za slovesá ústén tvojích áz sochraních putí žéstoki.]),
    gText("5"),
    par([Soverší stopý mojá vo stezjách tvojích, da ne podvížutsja stopý mojá.]),
    gText("6"),
    par([Áz vozzvách, jáko úslýšal mjá jésí, Bože: prikloní úcho tvojé mňí í úslýši hlahóly mojá.]),
    gText("7"),
    par([Údiví mílosti tvojá, Spasájaj úpovájuščyja na ťá ot protívjaščichsja desníci tvojéj:]),
    gText("8"),
    par([Sochraní mja, Hospodi, jáko zínicu óka: v króvi krilú tvoéju pokrýeši mjá]),
    gText("9"),
    par([Ot licá nečestívych óstrástšich #footnote("óbíďaščich") mjá: vrazí moí dúšu mojú óderžáša]),
    gText("10"),
    par([Túk svój zatvoríša, ústá ích hlahólaša hordýňu.]),
    gText("11"),
    par([Ízhoňáščiji mjá nýňi óbydóša mjá, óči svoí vozložíša úkloníti na zémľu.]),
    gText("12"),
    par([Óbjáša mjá jáko lév hotóv na lóv í jáko skýmen óbitájaj v tájnych.]),
    gText("13"),
    par([Voskresní, Hospodi, predvarí já í zapní ím: ízbávi dúšu mojú ot nečestívaho, órúžije tvojé]),
    gText("14"),
    par([Ot vráh rukí tvojejá, Hospodi, ot málych ot zemlí: razďilí já v živoťí ích, í sokrovénnych tvojích íspólnisja črévo ích: nasýtišasja synóv, í óstáviša óstánki mladéncem svoím.]),
    gText("15"),
    par([Áz že právdoju jávľúsja licú tvojemú, nasýščusja, vnehdá jávítimisja slávi tvojéj.]),
    col2(gText([#translation.at("SI")])),
  ))
  #generateTable((
    col2(sText(translation.at("AFTER_KAFTIZMA"))),
    sText("T"),
    jObj4("",2, "", "Áz sýj drévo neplódnoje Hospodi, úmilénija plodá ne nošú otňúd, í posičénija strašúsja í óhňá ónaho bojúsja nehasímaho. ťímže ťá moľú: préžde ónyja núždy, óbratí í Spasí mja."),
    sText("T"),
    jObj4("",none, "", "Jáko vólny morskíja na mjá vozstáša bezzakónija mojá, jáko korabléc v pučíňi áz jédín óburevájusja ot prehrišénij mnóhich: no v tíchoje pristánišče nastávi mjá Hospodi, pokajánijem, í Spasí mja."),
    
    // S:
    col2(gText(translation.at("S"))),
    "",
    jObj4("",none, "", "Pomíluj mjá, rečé David, í áz tebí zovú: sohriších Spase, hrichí mojá óčístiv pokajánijem, pomíluj mjá."),
    
    // I:
    col2(gText(translation.at("IN"))),
    "",
    jObj4("",none, "", "Predstáteľstvo téploje Christiján, Sýna tvojehó molí Bohoródice, vsjákaho zloďíjstva í ľútosti ízbáviti nás rátnika, í dáti proščénije nám, ó níchže sohrišíchom, mílosrdija rádi ščedrót, tvojími molitvami, Mati Ďivo."),
    col2(translation.at("HOSPODI_POMILUJ")+". "+sText("(40)")),
    col2(sText(translation.at("MOLITVA"))),
    "",
    jObj4("",none, "", "Vladýko vsederžíteľu, Ótče Hospoda nášeho Izráisa Christá, jédinoródnaho tvojehó Sýna, dážď mí ťílo neskvérnoje, sérdce čístoje, úm bódr, rázum nezablúdnyj, Dúcha svjatáho našéstvije, k sťažániju í dovóľstvu ístiny vo Chrisťí tvojém: s nímže tebí sláva podobájet, čésť í poklonénije, so svjatým Dúchom, nýňi í prísno, í vo víki vikóv, ámíň."),
  ))
])
