#import "../../../../all.typ": *
= #translation.at("KAFTIZMA") 20

#columns(2, gutter: 2pt, [

== #translation.at("ANTIFON") 1
  #generateTable((
    "",
    sText([Psalóm Davidu, k holijáthu, (#translation.at("PSALM") 143)]),
    gText("1"),
    par([Bláhoslovén Hospoď Boh mój, naučájaj rúci moí na ópolčénije, pérsty mojá na bráň.]),
    gText("2"),
    par([Mílosť mojá í pribížišče mojé, zastúpnik mój í ízbáviteľ mój, zaščítiteľ mój, í na nehó úpovách: povinújaj ľúdi mojá pod mjá.]),
    gText("3"),
    par([Hospodi, čtó jésť čelovík, jáko poználsja jésí jémú; ílí sýn čelovíč, jáko vmiňáeši jéhó;]),
    gText("4"),
    par([Čelovík sujeťí úpodóbisja: dníe jéhó jáko síň prechóďat.]),
    gText("5"),
    par([Hospodi, prekloní nebesá, í snídi: kosnísja horám, í vozdymjátsja:]),
    gText("6"),
    par([Blesní mólniju, í razženéši já: poslí stríly tvojá, í smjatéši já.]),
    gText("7"),
    par([Poslí rúku tvojú s vysotý, ízmí mja í ízbávi mjá ot vód mnóhich, íz rukí synóv čuždích,]),
    gText("8"),
    par([Íchže ústá hlahólaša sujetú, í desníca ích desníca neprávdy.]),
    gText("9"),
    par([Bože, písň nóvu vospojú tebí, vo psaltíri desjatostrúnňim pojú tebí:]),
    gText("10"),
    par([Dajúščemu Spasénije carém, ízbavľájuščemu Davida rabá svojehó ot mečá ľúta.]),
    gText("11"),
    par([Ízbávi mjá í ízmí mja íz rukí synóv čuždích, íchže ústá hlahólaša sujetú, í desníca ích desníca neprávdy:]),
    gText("12"),
    par([Íchže sýnove ích jáko novosaždénija vodružénaja v júnosti svojéj, dščéri ích údóbreny, preukrášeny jáko podóbije chráma:]),
    gText("13"),
    par([Chranílišča ích íspólnena, otryhájuščaja ot sehó v sijé: óvcy ích mnohoplódny, mnóžaščyjasja vo íschódiščich svojích: volóve ích tólsti:]),
    gText("14"),
    par([Nísť padénija óplótu, nižé prochóda, nižé vópľa v stóhnach ích.]),
    gText("15"),
    par([Úblážíša ľúdi, ímže sijá súť: blážéni ľúdije, ímže Hospoď Boh ích.]),
    "",
    sText([Chvalá Davidu, (#translation.at("PSALM") 144)]),
    gText("1"),
    par([Voznesú ťa, Bože mój, cerjú mój, í bláhoslovľú ímja tvojé v vík í v vík víka.]),
    gText("2"),
    par([Na vsják déň bláhoslovľú ťa, í voschvaľú ímja tvojé v vík í v vík víka.]),
    gText("3"),
    par([Vélij Hospoď í chválen ziló, í velíčiju jéhó ňísť koncá.]),
    gText("4"),
    par([Ród í ród voschváľat ďilá tvojá í sílu tvojú vozvisťát:]),
    gText("5"),
    par([Velikoľípije slávy svjatýni tvojejá vozhlahóľut í čudesá tvojá povíďat:]),
    gText("6"),
    par([Í sílu strášnych tvojích rekút í velíčije tvojé povíďat:]),
    gText("7"),
    par([Pámjať mnóžestva bláhosti tvojejá otrýhnut í právdoju tvojéju vozrádujutsja.]),
    gText("8"),
    par([Ščédr í mílostiv Hospoď, dolhoterpilív í mnohomílostiv.]),
    gText("9"),
    par([Bláh Hospoď vsjáčeskim, í ščedróty jéhó na vsích ďíľich jéhó.]),
    gText("10"),
    par([Da íspovíďatsja tebí, Hospodi, vsjá ďilá tvojá, í prepodóbniji tvoí da bláhoslovját ťá:]),
    gText("11"),
    par([Slávu cárstvija tvojehó rekút í sílu tvojú vozhlahóľut,]),
    gText("12"),
    par([Skazáti synovóm čelovíčeskim sílu tvojú í slávu velikoľípija cárstvija tvojehó.]),
    gText("13"),
    par([Carstvo tvojé cárstvo vsích vikóv, í Vladíčiestvo tvojé vo vsjákom róďi í róďi. Víren Hospoď vo vsích slovesích svojích í prepodóben vo vsích ďíľich svojích.]),
    gText("14"),
    par([Útverždájet Hospoď vsjá nizpádajuščyja í vozstavľájet vsjá nizvéržennyja.]),
    gText("15"),
    par([Óči vsích na ťá úpovájut, í tý dajéši ím píšču vo bláhovrémeniji:]),
    gText("16"),
    par([Otverzáješi tý rúku tvojú í íspolňáeši vsjákoje živótno bláhovolénija.]),
    gText("17"),
    par([Právedn Hospoď vo vsích putéch svojích í prepodóben vo vsích ďíľich svojích.]),
    gText("18"),
    par([Blíz Hospoď vsím prizyvájuščym jéhó, vsím prizyvájuščym jéhó vo ístiňi:]),
    gText("19"),
    par([Vóľu bojáščichsja jéhó sotvorít, í molítvu ích úslýšit, í Spasét já.]),
    gText("20"),
    par([Chranít Hospoď vsjá ľúbjaščyja jéhó, í vsjá hríšniki potrebít.]),
    gText("21"),
    par([Chvalú Hospodňu vozhlahóľut ústá mojá: í da bláhoslovít vsjáka plóť ímja svjatóje jéhó v vík í v vík víka.]),
    col2(gText([#translation.at("SI")])),
  ))
== #translation.at("ANTIFON") 2
  #generateTable((
    "",
    sText([Állilúija, áhhéa í zacháriji, (#translation.at("PSALM") 145)]),
    gText("1"),
    par([Chvalí, dušé mojá, Hospoda:]),
    gText("2"),
    par([Voschvaľú Hospoda v živoťí mojém, pojú Bohu mojemú, dóndeže jésm.]),
    gText("3"),
    par([Ne naďíjtesja na kňázi, na sýny čelovíčeskija, v níchže ňísť Spasénija.]),
    gText("4"),
    par([Ízýdet dúch jéhó, í vozvratítsja v zémľu svojú: v tój déň pohíbnut vsjá pomyšlénija jéhó.]),
    gText("5"),
    par([Blážén, jémúže Boh Jákovľ pomóščnik jéhó, úpovánije jéhó na Hospoda Boha svojehó,]),
    gText("6"),
    par([Sotvóršaho nébo í zémľu, móre, í vsjá, jáže v ních: chraňáščaho ístinu v vík,]),
    gText("7"),
    par([Tvorjáščaho súd óbídimym, dajúščaho píšču álčuščym. Hospoď rišít ókovánnyja:]),
    gText("8"),
    par([Hospoď úmudrájet sľipcý: Hospoď vozvódit nizvéržennyja: Hospoď ľúbit právedniki.]),
    gText("9"),
    par([Hospoď chranít prišéľcy, síra í vdovú prijímet, í púť hríšnych pohubít.]),
    gText("10"),
    par([Vocerítsja Hospoď vo vík, Boh tvój, Sijóne, v ród í ród.]),
    "",
    sText([Állilúija, (#translation.at("PSALM") 146)]),
    gText("1"),
    par([Chvalíte Hospoda, jáko bláh psalóm: Bohovi nášemu da úsladítsja chvalénije.]),
    gText("2"),
    par([Zíždaj Jerúsaľíma Hospod: razsíjanija Izráileva soberét:]),
    gText("3"),
    par([Ísciľájaj sokrušénnyja sérdcem í óbjazújaj sokrušénija ích:]),
    gText("4"),
    par([Ísčitájaj mnóžestvo zvízd, í vsím ím ímená naricájaj.]),
    gText("5"),
    par([Vélij Hospoď náš, í vélija kríposť jéhó, í rázuma jéhó ňísť čislá.]),
    gText("6"),
    par([Prijémľaj krótkija Hospoď, smirjájaj že hríšniki do zemlí.]),
    gText("7"),
    par([Načníte Hospodevi vo íspovídaniji, pójte Bohovi nášemu v húslech:]),
    gText("8"),
    par([Óďivájuščemu nébo óblaki, úhotovľájuščemu zemlí dóžď: prozjabájuščemu na horách travú í zlák na slúžbu čelovíkom:]),
    gText("9"),
    par([Dajúščemu skotóm píšču ích, í ptencém vránovym prizyvájuščym jéhó.]),
    gText("10"),
    par([Ne v síľi kónsťij voschóščet, nižé v lýsťich múžeskich bláhovolít:]),
    gText("11"),
    par([Bláhovolít Hospoď v bojáščichsja jéhó í vo úpovájuščich na mílosť jéhó.]),
    "",
    sText([Állilúija, áhhéa í zacháriji, (#translation.at("PSALM") 147)]),
    gText("1"),
    par([Pochvalí, Jerúsaľíme, Hospoda, chvalí Boha tvojehó, Sijóne:]),
    gText("2"),
    par([Jáko úkripí verejí vrát tvojích, blahosloví sýny tvojá v tebí.]),
    gText("3"),
    par([Polahájaj preďíly tvojá mír, í túka pšeníčna nasyščájaj ťá:]),
    gText("4"),
    par([Posylájaj Slóvo svojé zemlí, do skórosti tečét Slóvo jéhó,]),
    gText("5"),
    par([Dajúščaho sňíh svój jáko vólnu, mhlú jáko pépel posypájuščaho,]),
    gText("6"),
    par([Metájuščaho hóloť svój jáko chľíby: protívu licá mráza jéhó któ postojít;]),
    gText("7"),
    par([Póslet Slóvo svojé, í ístájet já: dchnét dúch jéhó, í potekút vódy.]),
    gText("8"),
    par([Vozviščájaj Slóvo svojé Jákovu, ópravdánija í suďbý svojá Izráilevi:]),
    gText("9"),
    par([Ne sotvorí táko vsjákomu jázýku, í suďbý svojá ne jáví ím.]),
    col2(gText([#translation.at("SI")])),
  ))
== #translation.at("ANTIFON") 3
  #generateTable((
    "",
    sText([Állilúija, áhhéa í zacháriji, (#translation.at("PSALM") 148)]),
    gText("1"),
    par([Chvalíte Hospoda s nebes, chvalíte jéhó v výšnich.]),
    gText("2"),
    par([Chvalíte jéhó vsí Anheli jéhó: chvalíte jéhó, vsjá síly jéhó.]),
    gText("3"),
    par([Chvalíte jéhó, sólnce í luná: chvalíte jéhó vsjá zvízdy í svít.]),
    gText("4"),
    par([Chvalíte jéhó, nebesá nebes í vodá, jáže prevýše nebés.]),
    gText("5"),
    par([Da voschváľat ímja Hospodne: jáko tój rečé, í býša: tój poveľí, í sozdášasja.]),
    gText("6"),
    par([Postávi já v vík í v vík víka: poveľínije položí, í ne mímo ídet.]),
    gText("7"),
    par([Chvalíte Hospoda ot zemlí, zmíeve í vsjá bézdny:]),
    gText("8"),
    par([Óhň, hrád, sňíh, hóloť, dúch búren, tvorjáščaja Slóvo jéhó:]),
    gText("9"),
    par([Hóry í vsí chólmi, drevá plodonósna í vsí kédri:]),
    gText("10"),
    par([Zvírije í vsí skóti, hádi í ptícy pernáty:]),
    gText("11"),
    par([Cárije zémstiji í vsí ľúdije, kňázi í vsí sudijí zémstiji:]),
    gText("12"),
    par([Ю́noši í ďívy, stárcy s júnotami.]),
    gText("13"),
    par([Da voschváľat ímja Hospodne: jáko voznesésja ímja tohó jédínaho, íspovídanije jéhó na zemlí í na nebesí.]),
    gText("14"),
    par([Í voznesét róh ľudéj svojích: písň vsím prepodóbnym jéhó, synovóm Izráilevym, ľúdem približájuščymsja jémú.]),
    "",
    sText([Állilúija, (#translation.at("PSALM") 149)]),
    gText("1"),
    par([Vospójte Hospodevi písň nóvu: chvalénije jéhó v cerkvi prepodóbnych.]),
    gText("2"),
    par([Da vozveselítsja Izráiľ ó sotvóršem jéhó, í sýnove Sijóni vozrádujutsja ó cerí svojém.]),
    gText("3"),
    par([Da voschváľat ímja jéhó v líci, v tympáňi í psaltíri da pojút jémú.]),
    gText("4"),
    par([Jáko bláhovolít Hospoď v ľúdech svojích, í voznesét krótkija vo Spasénije.]),
    gText("5"),
    par([Voschváľatsja prepodóbniji vo slávi í vozrádujutsja na lóžach svojích.]),
    gText("6"),
    par([Voznošénija Božija v hortáni ích, í mečí óbojúdu óstrý v rukách ích:]),
    gText("7"),
    par([Sotvoríti otmščénije vo jázýcich, óbličénija v ľúdech:]),
    gText("8"),
    par([Svjazáti carí ích púty, í slávnyja ích ručnými ókóvy žeľíznymi:]),
    gText("9"),
    par([Sotvoríti v ních súd napísan. Sláva sijá búdet vsím prepodóbnym jéhó.]),
    "",
    sText([Állilúija, (#translation.at("PSALM") 150)]),
    gText("1"),
    par([Chvalíte Boha vo svjatých jéhó, chvalíte jéhó vo útveržéniji síly jéhó:]),
    gText("2"),
    par([Chvalíte jéhó na sílach #footnote("v sílach") jéhó, chvalíte jéhó po mnóžestvu velíčestvija jéhó:]),
    gText("3"),
    par([Chvalíte jéhó vo hlási trúbňim, chvalíte jéhó vo psaltíri í húslech:]),
    gText("4"),
    par([Chvalíte jéhó v tympáňi í líci, chvalíte jéhó vo strúnach í órháňi:]),
    gText("5"),
    par([Chvalíte jéhó v kymváľich dobrohlásnych, chvalíte jéhó v kymváľich vosklicánija.]),
    gText("6"),
    par([Vsjákoje dychánije da chválit Hospoda.]),
    col2(gText([#translation.at("SI")])),
  ))
  #generateTable((
    col2(sText(translation.at("AFTER_KAFTIZMA"))),
    sText("T"),
    jObj4("",8, "", "Íspolnénije vsích bláhích tý jésí Christé mój, íspólni rádosti í vesélija dúšu mojú, í Spasí mja, jáko jédín mnohomílostiv."),
    
    // S:
    col2(gText(translation.at("S"))),
    "",
    jObj4("",none, "", "Ášče í sohriších, Christé Spase mój, pred tobóju, ínóho Boha rázvi tebé ne vím: derzáju že na tvojé bláhoutróbije: óbraščájuščahosja prijimí mja bláhoutróbne Ótče, í Sýne jédinoródne, í duše svjatýj, jáko blúdnaho sýna, í Spasí mja."),
    
    // I:
    col2(gText(translation.at("IN"))),
    "",
    jObj4("",none, "", "Ínóho pribížišča, í téplaho predstáteľstva, rázvi tebé ne vím: jáko derznovénije ímúšči ko íz tebé roždénnomu, Vladíčice pomozí, í Spasí mja rabá tvojehó."),
    col2(translation.at("HOSPODI_POMILUJ")+". "+sText("(40)")),
    col2(sText(translation.at("MOLITVA"))),
    "",
    jObj4("",none, "", "Hospodi Izráise Christé Bože mój, pomíluj mjá hríšnaho, í prostí mi nedostójnomu rabú tvojemú, jélíka tí sohriších črez vsé životá mojehó vrémja, í dáže do dnés, í ášče čtó jáko čelovík sohriších, vóľnaja mojá prehrišénija í nevóľnaja, ďílom í Slóvom, jáže úmóm í mýsliju, jáže ot sovoschiščénija í nevnimánija, í mnóhija mojejá ľínosti í nebrežénija. Ášče že ímenem tvojím kľáchsja, ášče že lžekľáchsja, ílí chúlich mýsliju, ílí kohó úkorích, ílí óklevetách, ílí ópečálich, ílí v ňíčesom prohňívach, ílí ókradóch, ílí blúdstvovach, ílí solhách, ílí tájno jádóch: ílí drúh dostíže ko mňí, í prezrích jéhó, ílí bráta óskorbích í preohorčích: ílí stojášču mí na molítvi í psalmopíniji úm mój lukávyj na lukávaja óbchoždáše: ílí páče ľípaho nasladíchsja, ílí bezúmno smijáchsja, ílí koščúnno hlahólach, ílí tščeslávichsja, ílí hordíchsja, ílí dobrótu sújetnuju víďich, í ot nejá preľstíchsja, ílí neľípaja mňí pohlumíchsja: ášče v česóm ó molitvi mojéj ne radích: ílí zápovidej duchóvnaho mojehó ótcá ne sochraních, ílí prazdnoslóvich, ílí íno čtó lukávoje sotvorích: sijá bo vsjá í vjáščšaja sích soďíjach, íchže nižé pómňu: pomíluj Hospodi, í prostí mi vsjá, da v míri úsnú í počíju, pojá, í bláhoslovjá, í slávja ťá, so beznačáľnym tvojím Ótcém, í s presvjatým, í bláhím, í životvorjáščim tvojím Dúchom, nýňi í prísno, í vo víki vikóv, ámíň."),
  ))
])
