#import "../../../../all.typ": *
= #translation.at("KAFTIZMA") 3

#columns(2, gutter: 2pt, [

== #translation.at("ANTIFON") 1
  #generateTable((
    gText("1"),
    sText([V konéc, ótroku Hospodňu Davidu, jáže hlahóla Hospodevi slovesápísni sejá, v déň, vóňže ízbávi jéhó Hospoď ot rukí vsích vráh jéhó í íz rukí saúli: í rečé: (#translation.at("PSALM") 17)]),
    gText("2"),
    par([Vozľubľú ťa, Hospodi, kríposte mojá:]),
    gText("3"),
    par([Hospoď útverždénije mojé, í pribížišče mojé, í ízbáviteľ mój, Boh mój, pomóščnik mój, í úpováju na nehó: zaščítiteľ mój, í róh Spasénija mojehó, í zastúpnik mój.]),
    gText("4"),
    par([Chvaľá prizovú Hospoda í ot vráh mojích spasúsja.]),
    gText("5"),
    par([Óderžáša mjá boľízni smértnyja, í potócy bezzakónija smjatóša mjá:]),
    gText("6"),
    par([Boľízni ádovy óbydóša mjá, predvaríša mjá síti smértnyja.]),
    gText("7"),
    par([Í vnehdá skorbíti mí, prizvách Hospoda í k Bohu mojemú vozzvách: úslýša ot chráma svjatáho svojehó hlás mój, í vópľ mój pred ním vnídet vo úšy jéhó.]),
    gText("8"),
    par([Í podvížesja í trépetna býsť zemľá, í ósnovánija hór smjatóšasja í podvihóšasja, jáko prohňívasja na ňá Boh.]),
    gText("9"),
    par([Vzýde dým hňívom jéhó, í óhň ot licá jéhó vosplámenitsja: úhlije vozhorísja ot nehó.]),
    gText("10"),
    par([Í prikloní nebesá í sníde, í mrák pod noháma jéhó.]),
    gText("11"),
    par([Í vzýde na cheruvímy í leťí, leťí na krilú vítreňu.]),
    gText("12"),
    par([Í položí tmú zakróv svój: ókrest jéhó selénije jéhó: temná vodá vo óblacich vozdúšnych.]),
    gText("13"),
    par([Ot óblistánija pred ním óblacy proidóša, hrád í úhlije óhnennoje.]),
    gText("14"),
    par([Í vozhremí s nebesé Hospoď, í výšnij dadé hlás svój.]),
    gText("15"),
    par([Nizposlá stríly í razhná já, í mólniji úmnóži í smjaté já.]),
    gText("16"),
    par([Í jávíšasja ístóčnicy vodníji, í otkrýšasja ósnovánija vselénnyja ot zapreščénija tvojehó, Hospodi, ot dochnovénija dúcha hňíva tvojehó.]),
    gText("17"),
    par([Nizposlá s vysotý í priját mjá, vospriját mjá ot vód mnóhich.]),
    gText("18"),
    par([Ízbávit mjá ot vrahóv mojích síľnych í ot nenavíďaščich mjá: jáko útverdíšasja páče mené.]),
    gText("19"),
    par([Predvaríša mjá v déň ózloblénija mojehó: í býsť Hospoď útverždénije mojé.]),
    gText("20"),
    par([Í ízvedé mja na širotú: ízbávit mjá, jáko voschoťí mja.]),
    gText("21"),
    par([Í vozdást mí Hospoď po právďi mojéj, í po čistoťí rukú moéju vozdást mí,]),
    gText("22"),
    par([Jáko sochraních putí Hospodni í ne nečéstvovach ot Boha mojehó.]),
    gText("23"),
    par([Jáko vsjá suďbý jéhó predo mnóju, í ópravdánija jéhó ne otstupíša ot mené.]),
    gText("24"),
    par([Í búdu neporóčen s ním í sochraňúsja ot bezzakónija mojehó.]),
    gText("25"),
    par([Í vozdást mí Hospoď po právďi mojéj í po čistoťí rukú moéju pred óčíma jéhó.]),
    gText("26"),
    par([S prepodóbnym prepodóben búdeši, í s múžem nepovínnym nepovínen búdeši,]),
    gText("27"),
    par([Í so ízbránnym ízbrán búdeši, í so stroptívym razvratíšisja.]),
    gText("28"),
    par([Jáko tý ľúdi smirénnyja Spaséši í óči hórdych smiríši.]),
    gText("29"),
    par([Jáko tý prosvitíši svitíľnik mój, Hospodi: Bože mój, prosvitíši tmú mojú.]),
    gText("30"),
    par([Jáko tobóju ízbávľusja ot ískušénija, í Bohom mojím prejdú sťínu.]),
    gText("31"),
    par([Boh mój, neporóčen púť jéhó: slovesá Hospodňa razžžéna. Zaščítiteľ jésť vsích úpovájuščich na nehó.]),
    gText("32"),
    par([Jáko któ Boh, rázvi Hospoda; ílí któ Boh, rázvi Boha nášeho;]),
    gText("33"),
    par([Boh prepojasújaj mjá síloju, í položí neporóčen púť mój:]),
    gText("34"),
    par([Soveršájaj nózi moí jáko jéléni, í na vysókich postavľájaj mjá:]),
    gText("35"),
    par([Naučájaj rúci moí na bráň, í položíl jésí lúk míďan mýšca mojá:]),
    gText("36"),
    par([Í dál mí jésí zaščiščénije Spasénija, í desníca tvojá vospriját mjá: í nakazánije tvojé ísprávit mjá v konéc, í nakazánije tvojé tó mjá naučít.]),
    gText("37"),
    par([Úširíl jésí stopý mojá podo mnóju, í ne íznemohósťi plesňí moí.]),
    gText("38"),
    par([Poženú vrahí mojá, í postíhnu já, í ne vozvraščúsja, dóndeže skončájutsja:]),
    gText("39"),
    par([Óskorbľú ích, í ne vozmóhut státi, padút pod noháma mojíma.]),
    gText("40"),
    par([Í prepojásal mjá jésí síloju na bráň, spjál jésí vsjá vostajúščyja na mjá pod mjá.]),
    gText("41"),
    par([Í vrahóv mojích dál mí jésí chrebét í nenavíďaščyja mjá potrebíl jésí.]),
    gText("42"),
    par([Vozzváša, í ne bí spasájaj: ko Hospodu, í ne úslýša ích.]),
    gText("43"),
    par([Í ístňú já jáko prách pred licém vítra, jáko brénije putéj pohláždu já.]),
    gText("44"),
    par([Ízbáviši mjá ot prerikánija ľudéj: postáviši mjá vo hlavú jázýkov: ľúdije, íchže ne víďich, rabótaša mí,]),
    gText("45"),
    par([V slúch úcha poslúšaša mjá. Sýnove čuždíji solháša mí,]),
    gText("46"),
    par([Sýnove čuždíji óbetšáša í óchromóša ot stéz svojích.]),
    gText("47"),
    par([Žív Hospoď, í bláhoslovén Boh, í da voznesétsja Boh Spasénija mojehó,]),
    gText("48"),
    par([Boh dajáj otmščénije mňí í pokorívyj ľúdi pod mjá,]),
    gText("49"),
    par([Ízbáviteľ mój ot vráh mojích hňivlívych: ot vostajúščich na mjá vozneséši mjá, ot múža neprávedna ízbáviši mjá.]),
    gText("50"),
    par([Sehó rádi íspovímsja tebí vo jázýcich, Hospodi, í ímeni tvojemú pojú:]),
    gText("51"),
    par([Veličájaj spasénija caréva í tvorjáj mílosť chrijstú svojemú Davidu í símeni jéhó do víka.]),
    col2(gText([#translation.at("SI")])),
  ))
== #translation.at("ANTIFON") 2
  #generateTable((
    gText("1"),
    sText([V konéc, psalóm Davidu, (#translation.at("PSALM") 18)]),
    gText("2"),
    par([Nebesá povídajut slávu Božiju, tvorénije že rukú jéhó vozviščájet tvérď.]),
    gText("3"),
    par([Déň dní otryhájet hlahól, í nóšč nóšči vozviščájet rázum.]),
    gText("4"),
    par([Ne súť ríči, nižé slovesá, íchže ne slýšatsja hlási ích.]),
    gText("5"),
    par([Vo vsjú zémľu ízýde viščánije ích, í v koncý vselénnyja hlahóly ích: v sólnci položí selénije svojé:]),
    gText("6"),
    par([Í tój jáko ženích íschoďáj ot čertóha svojehó, vozrádujetsja jáko íspolín teščí púť.]),
    gText("7"),
    par([Ot krája nebesé íschód jéhó, í srítenije jéhó do krája nebesé: í ňísť, íže úkrýetsja teplotý jéhó.]),
    gText("8"),
    par([Zakón Hospodeň neporóčen, óbraščájaj dúšy: sviďíteľstvo Hospodne vírno, úmudrjájuščeje mladéncy.]),
    gText("9"),
    par([Ópravdánija Hospodňa práva, veseľáščaja sérdce: zápoviď Hospodňa svitlá, prosviščájuščaja óči.]),
    gText("10"),
    par([Strách Hospodeň číst, prebyvájaj v vík víka: suďbý Hospodni ístinny, ópravdánny vkúpi,]),
    gText("11"),
    par([Voždeľínny páče zláta í kámene čéstna mnóha, í sláždša páče méda í sóta.]),
    gText("12"),
    par([Íbo ráb tvój chranít já: vnehdá sochraníti já, vozdajánije mnóho.]),
    gText("13"),
    par([Hrichopadénija któ razumíet; ot tájnych mojích óčísti mjá,]),
    gText("14"),
    par([Í ot čuždích poščadí rabá tvojehó: ášče ne óbladájut mnóju, tohdá neporóčen búdu, í óčíščusja ot hrichá velíka.]),
    gText("15"),
    par([Í búdut vo bláhovolénije slovesá úst mojích, í poučénije sérdca mojehó pred tobóju výnu, Hospodi, pomóščniče mój í ízbáviteľu mój.]),
    gText("1"),
    sText([V konéc, psalóm Davidu, (#translation.at("PSALM") 19)]),
    gText("2"),
    par([Úslýšit ťá Hospoď v déň pečáli, zaščítit ťá ímja Boha Jákovľa.]),
    gText("3"),
    par([Póslet tí pómošč ot svjatáho, í ot Sijóna zastúpit ťá.]),
    gText("4"),
    par([Pomjanét vsjáku žértvu tvojú, í vsesožžénije tvojé túčno búdi.]),
    gText("5"),
    par([Dást tí Hospoď po sérdcu tvojemú, í vés sovít tvój íspólnit.]),
    gText("6"),
    par([Vozrádujemsja ó Spaséniji tvojém, í vo ímja Hospoda Boha nášeho vozvelíčimsja: íspólnit Hospoď vsjá prošénija tvojá.]),
    gText("7"),
    par([Nýňi poznách, jáko Spasé Hospoď chrijstá svojehó: úslýšit jéhó s nebesé svjatáho svojehó: v sílach Spasénije desnícy jéhó.]),
    gText("8"),
    par([Síji na kolesnícach, í síji na kónech: mý že vo ímja Hospoda Boha nášeho prizovém.]),
    gText("9"),
    par([Tíji spjáti býša í padóša: mý že vostáchom í ísprávichomsja.]),
    gText("10"),
    par([Hospodi, spasí carjá, í úslýši ný, vóňže ášče déň prizovém ťá.]),
    gText("1"),
    sText([Psalóm Davidu, (#translation.at("PSALM") 20)]),
    gText("2"),
    par([Hospodi, síloju tvojéju vozveselítsja cár, í ó Spaséniji tvojém vozrádujetsja ziló.]),
    gText("3"),
    par([Želánije sérdca jéhó dál jésí jémú, í choťínija ústnú jéhó ňísi lišíl jéhó.]),
    gText("4"),
    par([Jáko predvaríl jésí jéhó bláhoslovénijem bláhostýnnym, položíl jésí na hlaví jéhó vinéc ot kámene čéstna.]),
    gText("5"),
    par([Životá prosíl jésť ú tebé, í dál jésí jémú dolhotú dníj vo vík víka.]),
    gText("6"),
    par([Vélija sláva jéhó Spasénijem tvojím: slávu í veleľípije vozložíši na nehó.]),
    gText("7"),
    par([Jáko dási jémú bláhoslovénije vo vík víka: vozveselíši jéhó rádostiju s licém tvojím.]),
    gText("8"),
    par([Jáko cár úpovájet na Hospoda, í mílostiju výšňaho ne podvížitsja.]),
    gText("9"),
    par([Da óbrjáščetsja ruká tvojá vsím vrahóm tvoím, desníca tvojá da óbrjáščet vsjá nenavíďaščyja tebé.]),
    gText("10"),
    par([Jáko položíši ích jáko péšč óhnennuju vo vrémja licá tvojehó: Hospoď hňívom svojím smjatét já, í sňísť ích óhň.]),
    gText("11"),
    par([Plód ích ot zemlí pohubíši, í símja ích ot synóv čelovíčeskich.]),
    gText("12"),
    par([Jáko úkloníša na ťá zlája, pomýsliša sovíty, íchže ne vozmóhut sostáviti.]),
    gText("13"),
    par([Jáko položíši já chrebét: vo ízbýtcich tvojích úhotóviši licé ích.]),
    gText("14"),
    par([Voznesísja, Hospodi, síloju tvojéju: vospojém í pojém síly tvojá.]),
    col2(gText([#translation.at("SI")])),
  ))
== #translation.at("ANTIFON") 3
  #generateTable((
    gText("1"),
    sText([V konéc, ó zastupléniji útrenňim, psalóm Davidu, (#translation.at("PSALM") 21)]),
    gText("2"),
    par([Bože, Bože mój, vonmí mi, vskúju óstávil mjá jésí; daléče ot Spasénija mojehó slovesá hrichopadénij mojích.]),
    gText("3"),
    par([Bože mój, vozzovú vo dní, í ne úslýšiši, í v noščí, í ne v bezúmije mňí.]),
    gText("4"),
    par([Tý že vo svjatím živéši, chvaló Izráileva.]),
    gText("5"),
    par([Na ťá úpováša ótcý náši: úpováša, í ízbávil jésí já:]),
    gText("6"),
    par([K tebí vozzváša, í spasóšasja: na ťá úpováša, í ne postyďíšasja.]),
    gText("7"),
    par([Áz že jésm čérv, á ne čelovík, ponošénije čelovíkov í úničižénije ľudéj.]),
    gText("8"),
    par([Vsí víďaščiji mjá poruhášamisja, hlahólaša ústnámi, pokiváša hlavóju:]),
    gText("9"),
    par([Úpová na Hospoda, da ízbávit jéhó, da Spasét jéhó, jáko chóščet jéhó.]),
    gText("10"),
    par([Jáko tý jésí ístórhij mjá íz čréva, úpovánije mojé ot soscú mátere mojejá.]),
    gText("11"),
    par([K tebí privéržen jésm ot ložésn, ot čréva mátere mojejá Boh mój jésí tý.]),
    gText("12"),
    par([Da ne otstúpiši ot mené, jáko skórb blíz, jáko ňísť pomohájaj mí.]),
    gText("13"),
    par([Óbydóša mjá teľcý mnózi, júncý túčniji óderžáša mjá:]),
    gText("14"),
    par([Otverzóša na mjá ústá svojá, jáko lév voschiščájaj í rykájaj.]),
    gText("15"),
    par([Jáko vodá ízlijáchsja, í razsýpašasja vsjá kósti mojá: býsť sérdce mojé jáko vósk tájaj posreďí čréva mojehó.]),
    gText("16"),
    par([Ízsše jáko skudéľ kríposť mojá, í jázýk mój priľpé hortáni mojemú, í v pérsť smérti svél mjá jésí.]),
    gText("17"),
    par([Jáko óbydóša mjá psí mnózi, sónm lukávych óderžáša mjá: ískopáša rúci moí í nózi moí.]),
    gText("18"),
    par([Ísčetóša vsjá kósti mojá: tíji že smotríša í prezríša mjá.]),
    gText("19"),
    par([Razďilíša rízy mojá sebí, í ó ódéždi mojéj metáša žrébij.]),
    gText("20"),
    par([Tý že, Hospodi, ne údalí pómošč tvojú ot mené: na zastuplénije mojé vonmí.]),
    gText("21"),
    par([Ízbávi ot órúžija dúšu mojú, í íz rukí pésiji jédinoródnuju mojú.]),
    gText("22"),
    par([Spasí mja ot úst ľvóvych, í ot róh jédinoróž smirénije mojé.]),
    gText("23"),
    par([Povím ímja tvojé brátiji mojéj, posreďí cerkve vospojú ťá.]),
    gText("24"),
    par([Bojáščijisja Hospoda, voschvalíte jéhó, vsé símja Jákovle, proslávite jéhó, da úbojítsja že ot nehó vsé símja Izráilevo:]),
    gText("25"),
    par([Jáko ne úničiží, nižé nehodová molítvy níščaho, nižé otvratí licé svojé ot mené, í jéhdá vozzvách k nemú, úslýša mjá.]),
    gText("26"),
    par([Ot tebé pochvalá mojá, v cerkvi velícij íspovímsja tebí: molítvy mojá vozdám pred bojáščimisja jéhó.]),
    gText("27"),
    par([Jáďát úbóziji, í nasýťatsja, í voschváľat Hospoda vzyskájuščiji jéhó: živá búdut serdcá ích v vík víka.]),
    gText("28"),
    par([Pomjanútsja í óbraťátsja ko Hospodu vsí koncý zemlí, í poklóňatsja pred ním vsjá ótéčestvija jázýk:]),
    gText("29"),
    par([Jáko Hospodne jésť cárstvije, í tój óbladájet jázýki.]),
    gText("30"),
    par([Jádóša í pokloníšasja vsí túčniji zemlí: pred ním pripadút vsí nizchoďáščiji v zémľu: í dušá mojá tomú živét.]),
    gText("31"),
    par([Í símja mojé porabótajet jémú: vozvistít Hospodevi ród hrjadúščij:]),
    gText("32"),
    par([Í vozvisťát právdu jéhó ľúdem róždšymsja #footnote("rodítisja ímúščym"), jáže sotvorí Hospoď.]),
    "",
    sText([Psalóm Davidu, (#translation.at("PSALM") 22)]),
    gText("1"),
    par([Hospoď pasét mjá, í ničtóže mjá lišít.]),
    gText("2"),
    par([Na míste zláčňi, támo vselí mja, na voďí pokójňi vospitá mja.]),
    gText("3"),
    par([Dúšu mojú óbratí, nastávi mjá na stezí právdy, ímene rádi svojehó.]),
    gText("4"),
    par([Ášče bo í pojdú posreďí síni smértnyja, ne úbojúsja zlá, jáko tý so mnóju jésí: žézl tvój í pálica tvojá, tá mjá úťíšista.]),
    gText("5"),
    par([Úhotóval jésí predo mnóju trapézu soprotív stužájuščym mňí: úmástil jésí jéléom hlavú mojú, í čáša tvojá úpojavájušči mjá, jáko deržávna.]),
    gText("6"),
    par([Í mílosť tvojá poženét mjá vsjá dní životá mojehó, í jéže vselítimisja v dóm Hospodeň v dolhotú dníj.]),
    "",
    sText([Psalóm Davidu, jédínyja ot subbót, (#translation.at("PSALM") 23)]),
    gText("1"),
    par([Hospodňa zemľá, í íspolnénije jéjá, vselénnaja í vsí živúščiji na néj.]),
    gText("2"),
    par([Tój na morjách ósnovál jú jésť í na rikách úhotóval jú jésť.]),
    gText("3"),
    par([Któ vzýdet na hóru Hospodňu; ílí któ stánet na mísťi svjatím jéhó;]),
    gText("4"),
    par([Nepovínen rukáma í číst sérdcem, íže ne priját vsúje dúšu svojú í ne kľátsja léstiju ískrennemu svojemú:]),
    gText("5"),
    par([Séj prijímet bláhoslovénije ot Hospoda í mílostyňu ot Boha Spasa svojehó.]),
    gText("6"),
    par([Séj ród íščuščich Hospoda, íščuščich licé Boha Jákovľa.]),
    gText("7"),
    par([Vozmíte vratá kňázi váša, í vozmítesja vratá víčnaja: í vnídet cer slávy.]),
    gText("8"),
    par([Któ jésť séj cer slávy; Hospoď krípok í sílen, Hospoď sílen v bráni.]),
    gText("9"),
    par([Vozmíte vratá kňázi váša, í vozmítesja vratá víčnaja: í vnídet cer slávy.]),
    gText("10"),
    par([Któ jésť séj cer slávy; Hospoď síl, tój jésť cer slávy.]),
    col2(gText([#translation.at("SI")])),
  ))
  #generateTable((
    col2(sText(translation.at("AFTER_KAFTIZMA"))),
    sText("T"),
    jObj4("",3, "", "Živúšči na zemlí, dušé mojá, pokájsja, pérsť vo hróbi ne pojét, prehrišénij ne ízbavľájet. vozopíj Christú Bohu: serdcevídče, sohriších, préžde dáže ne ósúdiši mjá, pomíluj mjá."),
    sText("T"),
    jObj4("",none, "", "Dokóľi, dušé mojá, prebyváješi v prehrišénijich; dokóľi prijémleši pokajánija preložénije; prijimí vo úmí súd hrjadúščij, í vozopíj Hospodu: serdcevídče, sohriších, préžde dáže ne ósúdiši mjá, pomíluj mjá."),
    
    // S:
    col2(gText(translation.at("S"))),
    "",
    jObj4("",none, "", "Na strášnom sudíšči bez óhlahóľnikov óbličájusja, bez sviďítelej ósuždájusja: kníhi bo sóvistnyja razhibájutsja, í ďilá sokrovénnaja otkryvájutsja. préžde néže vo ónom vsenaródnom pozórišči ímaši íspytáti, jáže mnóju soďíjannaja, Bože, óčísti mjá, í Spasí mja."),
    
    // I:
    col2(gText(translation.at("IN"))),
    "",
    jObj4("",none, "", "Nedorazumivájemoje, í nepostižímoje jésť, Vladíčice Bohobláhodátnaja, soďíjannoje ó tebí strášnoje táinstvo: neobémlemaho bo začénši, rodilá jésí plótiju óbložénnaho ot čestych krovéj tvojích. jéhóže čestaja, jáko Sýna tvojehó, molí Spastí vsjá pojúščyja ťá."),
    col2(translation.at("HOSPODI_POMILUJ")+". "+sText("(40)")),
    col2(sText(translation.at("MOLITVA"))),
    "",
    jObj4("",none, "", "Hospodi vsederžíteľu, Slóve prebeznačáľnaho Ótcá, samosoveršénnyj Bože Izráise Christé, mílosrdija rádi bezprikládnaho mílosti tvojejá, nikákože razlučájajsja tvojích rabóv, no prísno v ních počivájaj, ne óstávi mjá rabá tvojehó vsesvjatýj cerjú: no dážď mňí nedostójnomu rádovanije Spasénija tvojehó, í prosvití mój úm svítom poznánija jéy-h**lija tvojehó, dúšu mojú ľubóviju krestá tvojehó óbjaží, ťílo že mojé tvojím bezstrástijem úkrasí, mýsli úmirí, í nózi moí sochraní ot popolznovénija, í ne pohubí mja so bezzakónňmi mojími, bláhíj Hospodi, no ískusí mja Bože, í vrazumí sérdce mojé: íspytáj mjá, í úvížď stezí mojá, í vížď, ášče púť bezzakónija vo mňí, í otvratí ot nehó, í nastávi mjá na púť víčen. Tý bo jésí púť í ístina, í živót, í tebí slávu vozsylájem, so beznačáľnym tvojím Ótcém, í presvjatým í bláhím í životvorjáščim Dúchom, nýňi í prísno, í vo víki vikóv, ámíň."),
  ))
])
