#import "../../../../all.typ": *
= #translation.at("KAFTIZMA") 4

#columns(2, gutter: 2pt, [

== #translation.at("ANTIFON") 1
  #generateTable((
    "",
    sText([Psalóm Davidu, (#translation.at("PSALM") 24)]),
    gText("1"),
    par([K tebí, Hospodi, vozdvihóch dúšu mojú, Bože mój, na ťá úpovách, da ne postyžúsja vo vík, nižé da posmijút mi sja vrazí moí:]),
    gText("2"),
    par([Íbo vsí terpjáščiji ťá ne postyďátsja.]),
    gText("3"),
    par([Da postyďátsja bezzakónnujuščiji votščé.]),
    gText("4"),
    par([Putí tvojá, Hospodi, skaží mi í stezjám tvoím naučí mja.]),
    gText("5"),
    par([Nastávi mjá na ístinu tvojú í naučí mja: jáko tý jésí Boh Spas mój, í tebé terpích vés déň.]),
    gText("6"),
    par([Pomjaní ščedróty tvojá, Hospodi, í mílosti tvojá, jáko ot víka súť.]),
    gText("7"),
    par([Hrích júnosti mojejá í nevíďinija mojehó ne pomjaní: po mílosti tvojéj pomjaní mja tý, rádi bláhosti tvojejá, Hospodi.]),
    gText("8"),
    par([Bláh í práv Hospoď, sehó rádi zakonopoložít sohrišájuščym na putí.]),
    gText("9"),
    par([Nastávit krótkija na súd, naučít krótkija putém svoím.]),
    gText("10"),
    par([Vsí putijé Hospodni mílosť í ístina, vzyskájuščym zavíta jéhó í sviďínija jéhó.]),
    gText("11"),
    par([Rádi ímene tvojehó, Hospodi, í óčísti hrích mój, mnóh bo jésť.]),
    gText("12"),
    par([Któ jésť čelovík bojájsja Hospoda; zakonopoložít jémú na putí, jéhóže ízvóli.]),
    gText("13"),
    par([Dušá jéhó vo blahích vodvorítsja, í símja jéhó nasľídit zémľu.]),
    gText("14"),
    par([Deržáva Hospoď bojáščichsja jéhó, í zavít jéhó jávít ím.]),
    gText("15"),
    par([Óči moí výnu ko Hospodu, jáko tój ístórhnet ot síti nózi moí.]),
    gText("16"),
    par([Prízri na mjá í pomíluj mjá, jáko jédinoród í níšč jésm áz.]),
    gText("17"),
    par([Skórbi sérdca mojehó úmnóžišasja, ot núžd mojích ízvedí mja.]),
    gText("18"),
    par([Vížď smirénije mojé í trúd mój, í óstávi vsjá hrichí mojá.]),
    gText("19"),
    par([Vížď vrahí mojá, jáko úmnóžišasja, í nenaviďínijem neprávednym voznenavíďiša mjá.]),
    gText("20"),
    par([Sochraní dúšu mojú í ízbávi mjá, da ne postyžúsja, jáko úpovách na ťá.]),
    gText("21"),
    par([Nezlóbiviji í práviji priľipľáchusja mňí, jáko poterpích ťá, Hospodi.]),
    gText("22"),
    par([Ízbávi, Bože, Izráiľa ot vsích skorbéj jéhó.]),
    "",
    sText([Psalóm Davidu, (#translation.at("PSALM") 25)]),
    gText("1"),
    par([Sudí mi, Hospodi, jáko áz nezlóboju mojéju chodích: í na Hospoda úpovája ne íznemohú.]),
    gText("2"),
    par([Ískusí mja, Hospodi, í íspytáj mjá, razžží útróby mojá í sérdce mojé.]),
    gText("3"),
    par([Jáko mílosť tvojá pred óčíma mojíma jésť, í bláhouhodích vo ístiňi tvojéj.]),
    gText("4"),
    par([Ne sidóch s sónmom sújetnym, í so zakonoprestúpnymi ne vnídu.]),
    gText("5"),
    par([Voznenavíďich cérkov lukávnujuščich, í s nečestívymi ne sjádu.]),
    gText("6"),
    par([Úmýju v nepovínnych rúci moí, í óbýdu žértvennik tvój, Hospodi,]),
    gText("7"),
    par([Jéže úslýšati mí hlás chvalý tvojejá í povídati vsjá čudesá tvojá.]),
    gText("8"),
    par([Hospodi, vozľubích bláhoľípije dómu tvojehó í místo selénija slávy tvojejá.]),
    gText("9"),
    par([Da ne pohubíši s nečestívymi dúšu mojú í s múži krovéj živót mój,]),
    gText("10"),
    par([Íchže v rukú bezzakónija, desníca ích íspólnisja mzdý.]),
    gText("11"),
    par([Áz že nezlóboju mojéju chodích: ízbávi mjá, Hospodi, í pomíluj mjá.]),
    gText("12"),
    par([Nohá mojá stá na pravoťí: v cerkvach bláhoslovľú ťa, Hospodi.]),
    "",
    sText([Psalóm Davidu, préžde pomázanija, (#translation.at("PSALM") 26)]),
    gText("1"),
    par([Hospoď prosviščénije mojé í Spasíteľ mój, kohó úbojúsja; Hospoď zaščítiteľ životá mojehó, ot kohó ústrašúsja;]),
    gText("2"),
    par([Vnehdá približátisja na mjá zlóbujuščym, jéže sňísti plóti mojá, óskorbľájuščiji mjá í vrazí moí, tíji íznemohóša í padóša.]),
    gText("3"),
    par([Ášče ópolčítsja na mjá pólk, ne úbojítsja sérdce mojé: ášče vostánet na mjá bráň, na nehó áz úpováju.]),
    gText("4"),
    par([Jédíno prosích ot Hospoda, tó vzyščú: jéže žíti mí v domú Hospodni vsjá dní životá mojehó, zríti mí krasotú Hospodňu í posiščáti chrám svjatýj jéhó.]),
    gText("5"),
    par([Jáko skrý mja v seléniji svojém v déň zól mojích, pokrý mja v tájňi selénija svojehó, na kámeň voznesé mja.]),
    gText("6"),
    par([Í nýňi sé, voznesé hlavú mojú na vrahí mojá: óbydóch í požróch v seléniji jéhó žértvu chvalénija í voskliknovénija: pojú í vospojú Hospodevi.]),
    gText("7"),
    par([Úslýši, Hospodi, hlás mój, ímže vozzvách, pomíluj mjá í úslýši mjá.]),
    gText("8"),
    par([Tebí rečé sérdce mojé: Hospoda vzyščú, vzyská tebé licé mojé, licá tvojehó, Hospodi, vzyščú.]),
    gText("9"),
    par([Ne otvratí licá tvojehó ot mené í ne úklonísja hňívom ot rabá tvojehó: pomóščnik mój búdi, ne otríni mené í ne óstávi mené, Bože, Spasíteľu mój.]),
    gText("10"),
    par([Jáko ótéc mój í máti mojá óstávista mjá, Hospoď že vospriját mjá.]),
    gText("11"),
    par([Zakonopoloží mi, Hospodi, v putí tvojém, í nastávi mjá na stezjú právuju vráh mojích rádi.]),
    gText("12"),
    par([Ne predážď mené v dúšy stužájuščich mí: jáko vostáša na mjá sviďítele neprávedniji, í solhá neprávda sebí.]),
    gText("13"),
    par([Víruju víďiti bláhája Hospodňa na zemlí živých.]),
    gText("14"),
    par([Poterpí Hospoda, mužájsja, í da kripítsja sérdce tvojé, í poterpí Hospoda.]),
    col2(gText([#translation.at("SI")])),
  ))
== #translation.at("ANTIFON") 2
  #generateTable((
    "",
    sText([Psalóm Davidu, (#translation.at("PSALM") 27)]),
    gText("1"),
    par([K tebí, Hospodi, vozzovú, Bože mój: da ne premolčíši ot mené #footnote("ó mňí"): da ne kohdá premolčíši ot mené #footnote("ó mňí"), í úpodóbľusja nizchoďáščym v róv.]),
    gText("2"),
    par([Úslýši, Hospodi, hlás molénija mojehó, vnehdá molíti mi sja k tebí, vnehdá vozďíti mí rúci moí ko chrámu svjatómu tvojemú.]),
    gText("3"),
    par([Ne privlecý mené so hríšniki, í s ďílajuščimi neprávdu ne pohubí mené, hlahóľuščimi mír s blížnimi svojími, zlája že v serdcách svojích.]),
    gText("4"),
    par([Dážď ím, Hospodi, po ďilóm ích í po lukávstvu načinánij ích, po ďilóm rukú ích dážď ím, vozdážď vozdajánije ích ím.]),
    gText("5"),
    par([Jáko ne razumíša v ďilá Hospodňa í v ďilá rukú jéhó: razoríši já í ne sozíždeši já.]),
    gText("6"),
    par([Bláhoslovén Hospoď, jáko úslýša hlás molénija mojehó.]),
    gText("7"),
    par([Hospoď pomóščnik mój í zaščítiteľ mój: na nehó úpová sérdce mojé, í pomóže mí, í procvité plóť mojá: í vóleju mojéju íspovímsja jémú.]),
    gText("8"),
    par([Hospoď útverždénije ľudéj svojích í zaščítiteľ spasénij chrijstá svojehó jésť.]),
    gText("9"),
    par([Spasí ľúdi tvojá, í blahosloví dostojánije tvojé, í úpasí já, í vozmí #footnote("í voznesí") já do víka.]),
    "",
    sText([Psalóm Davidu, íschóda skíniji, (#translation.at("PSALM") 28)]),
    gText("1"),
    par([Prinesíte Hospodevi, sýnove Božiji, prinesíte Hospodevi sýny óvni, prinesíte Hospodevi slávu í čésť:]),
    gText("2"),
    par([Prinesíte Hospodevi slávu ímeni jéhó: poklonítesja Hospodevi vo dvorí svjatím jéhó.]),
    gText("3"),
    par([Hlás Hospodeň na vodách, Boh slávy vozhremí, Hospoď na vodách mnóhich.]),
    gText("4"),
    par([Hlás Hospodeň v kríposti, hlás Hospodeň v velikoľípiji.]),
    gText("5"),
    par([Hlás Hospoda, sokrušájuščaho kédry: í strýet Hospoď kédry lijvánskija,]),
    gText("6"),
    par([Í ístnít já jáko teľcá lijvánska: í vozľúblennyj jáko sýn jédinoróž.]),
    gText("7"),
    par([Hlás Hospoda, presicájuščaho plámeň óhňá.]),
    gText("8"),
    par([Hlás Hospoda, strjasájuščaho pustýňu: í strjasét Hospoď pustýňu kaddíjskuju.]),
    gText("9"),
    par([Hlás Hospodeň, sveršájuščij jéléni, í otkrýet dubrávy: í v chrámi jéhó vsjákij hlahólet slávu.]),
    gText("10"),
    par([Hospoď potóp naseľájet, í sjádet Hospoď cer v vík.]),
    gText("11"),
    par([Hospoď kríposť ľúdem svoím dást, Hospoď bláhoslovít ľúdi svojá mírom.]),
    gText("1"),
    sText([Psalóm písni óbnovlénija dómu Davidova, (#translation.at("PSALM") 29)]),
    gText("2"),
    par([Voznesú ťa, Hospodi, jáko podjál mjá jésí, í ne vozveselíl jésí vrahóv mojích ó mňí.]),
    gText("3"),
    par([Hospodi Bože mój, vozzvách k tebí, í íscilíl mjá jésí.]),
    gText("4"),
    par([Hospodi, vozvél jésí ot áda dúšu mojú, Spasl mjá jésí ot nizchoďáščich v róv.]),
    gText("5"),
    par([Pójte Hospodevi, prepodóbniji jéhó, í íspovídajte pámjať svjatýni jéhó:]),
    gText("6"),
    par([Jáko hňív v járosti jéhó, í živót v vóli jéhó: véčer vodvorítsja pláč, í zaútra rádosť.]),
    gText("7"),
    par([Áz že rích vo óbíliji mojém: ne podvížusja vo vík.]),
    gText("8"),
    par([Hospodi, vóleju tvojéju podážď dobróťi mojéj sílu: otvratíl že jésí licé tvojé, í bých smuščén.]),
    gText("9"),
    par([K tebí, Hospodi, vozzovú, í k Bohu mojemú pomoľúsja.]),
    gText("10"),
    par([Kája póľza v króvi mojéj, vnehdá schodíti mí vo ístľínije; jédá íspovístsja tebí pérsť; ílí vozvistít ístinu tvojú;]),
    gText("11"),
    par([Slýša Hospoď í pomílova mjá: Hospoď býsť pomóščnik mój.]),
    gText("12"),
    par([Óbratíl jésí pláč mój v rádosť mňí, rasterzál jésí vrétišče mojé í prepojásal mjá jésí vesélijem,]),
    gText("13"),
    par([Jáko da vospojét tebí sláva mojá, í ne úmiľúsja. Hospodi Bože mój, vo vík íspovímsja tebí.]),
    col2(gText([#translation.at("SI")])),
  ))
== #translation.at("ANTIFON") 3
  #generateTable((
    gText("1"),
    sText([V konéc, psalóm Davidu, ízstuplénija, (#translation.at("PSALM") 30)]),
    gText("2"),
    par([Na ťá, Hospodi, úpovách, da ne postyžúsja vo vík: právdoju tvojéju ízbávi mjá í ízmí mja.]),
    gText("3"),
    par([Prikloní ko mňí úcho tvojé, úskorí ízjáti mjá: búdi mí v Boha zaščítiteľa í v dóm pribížišča, jéže Spastí mja.]),
    gText("4"),
    par([Jáko deržáva mojá í pribížišče mojé jésí tý: í ímene tvojehó rádi nastáviši mjá í prepitáješi mjá.]),
    gText("5"),
    par([Ízvedéši mjá ot síti sejá, júže skrýša mí: jáko tý jésí zaščítiteľ mój, Hospodi.]),
    gText("6"),
    par([V rúci tvoí predložú dúch mój: ízbávil mjá jésí, Hospodi Bože ístiny.]),
    gText("7"),
    par([Voznenavíďil jésí chraňáščyja suetý votščé: áz že na Hospoda úpovách.]),
    gText("8"),
    par([Vozrádujusja í vozveseľúsja ó mílosti tvojéj, jáko prizríl jésí na smirénije mojé, Spasl jésí ot núžd dúšu mojú]),
    gText("9"),
    par([Í ňísi mené zatvoríl v rukách vrážijich, postávil jésí na prostránňi nózi moí.]),
    gText("10"),
    par([Pomíluj mjá, Hospodi, jáko skorbľú: smjatésja járostiju óko mojé, dušá mojá í útróba mojá.]),
    gText("11"),
    par([Jáko ísčezé v boľízni živót mój, í ľíta mojá v vozdychánijich: íznemóže niščetóju kríposť mojá, í kósti mojá smjatóšasja.]),
    gText("12"),
    par([Ot vsích vráh mojích bých ponošénije, í sosídom moím ziló, í strách znáemym moím: víďaščiji mjá vón bižáša ot mené.]),
    gText("13"),
    par([Zabvén bých jáko mértv ot sérdca: bých jáko sosúd pohublén.]),
    gText("14"),
    par([Jáko slýšach haždénije #footnote("úkorénije") mnóhich živúščich ókrest: vnehdá sobrátisja ím vkúpi na mjá, prijáti dúšu mojú soviščáša.]),
    gText("15"),
    par([Áz že na ťá, Hospodi, úpovách, rích: tý jésí Boh mój.]),
    gText("16"),
    par([V rukú tvoéju žrébiji moí: ízbávi mjá íz rukí vráh mojích í ot hoňáščich mjá.]),
    gText("17"),
    par([Prosvití licé tvojé na rabá tvojehó: Spasí mja mílostiju tvojéju.]),
    gText("18"),
    par([Hospodi, da ne postyžúsja, jáko prizvách ťá: da postyďátsja nečestíviji, í snídut vo ád.]),
    gText("19"),
    par([Nímy da búdut ústný ľstívyja, hlahóľuščyja na právednaho bezzakónije, hordýneju í úničižénijem.]),
    gText("20"),
    par([Kóľ mnóhoje mnóžestvo bláhosti tvojejá, Hospodi, júže skrýl jésí bojáščymsja tebé, soďílal jésí úpovájuščym na ťá, pred sýny čelovíčeskimi:]),
    gText("21"),
    par([Skrýeši ích v tájňi licá tvojehó ot mjatéža čelovíčeska, pokrýeši ích v króvi ot prerikánija jázýk.]),
    gText("22"),
    par([Bláhoslovén Hospoď, jáko údiví mílosť svojú vo hráďi óhraždénija.]),
    gText("23"),
    par([Áz že rích vo ízstupléniji mojém: otvéržen jésm ot licá óčiju tvoéju: sehó rádi úslýšal jésí hlás molítvy mojejá, vnehdá vozzvách k tebí.]),
    gText("24"),
    par([Vozľubíte Hospoda, vsí prepodóbniji jéhó: jáko ístiny vzyskájet Hospoď í vozdajét ízlíše tvorjáščym hordýňu.]),
    gText("25"),
    par([Mužájtesja, í da kripítsja sérdce váše, vsí úpovájuščiji na Hospoda.]),
    "",
    sText([Psalóm Davidu, rázuma, (#translation.at("PSALM") 31)]),
    gText("1"),
    par([Blážéni, íchže óstávišasja bezzakónija, í íchže prikrýšasja hrisí.]),
    gText("2"),
    par([Blážén múž, jémúže ne vminít Hospoď hrichá, nižé jésť vo úsťích jéhó lésť.]),
    gText("3"),
    par([Jáko úmolčách, óbetšáša kósti mojá, ot jéže zváti mí vés déň,]),
    gText("4"),
    par([Jáko déň í nóšč óťahoťí na mňí ruká tvojá: vozvratíchsja na strásť, jéhdá únzé mi térn.]),
    gText("5"),
    par([Bezzakónije mojé poznách í hrichá mojehó ne pokrých, rích: íspovím na mjá bezzakónije mojé Hospodevi: í tý óstávil jésí nečéstije sérdca mojehó.]),
    gText("6"),
    par([Za tó pomólitsja k tebí vsják prepodóbnyj vo vrémja bláhopotrébno: óbáče v potópi vód mnóhich k nemú ne priblížatsja.]),
    gText("7"),
    par([Tý jésí pribížišče mojé ot skórbi óbderžáščija mjá: rádoste mojá, ízbávi mjá ot óbyšédšich mjá.]),
    gText("8"),
    par([Vrazumľú ťa, í nastávľu ťá na púť séj, vóňže pójdeši: útveržú na ťá óči moí.]),
    gText("9"),
    par([Ne búdite jáko kóň í mésk, ímže ňísť rázuma: brozdámi í úzdóju čéľusti ích vosťáhneši, ne približájuščichsja k tebí.]),
    gText("10"),
    par([Mnóhi rány hríšnomu: úpovájuščaho že na Hospoda mílosť óbýdet.]),
    gText("11"),
    par([Veselítesja ó Hospodi í rádujtesja právedniji, í chvalítesja, vsí práviji sr-d*cem.]),
    col2(gText([#translation.at("SI")])),
  ))
  #generateTable((
    col2(sText(translation.at("AFTER_KAFTIZMA"))),
    sText("T"),
    jObj4("",7, "", "Smirénnuju mojú dúšu posití Hospodi, vo hrisích vsé žitijé íždívšuju: ímže óbrazom bludnícu prijimí í mené, í Spasí mja."),
    sText("T"),
    jObj4("",none, "", "Preplávaja pučínu nastojáščaho žitijá, pomyšľáju bézdnu mnóhich mojích zól, í ne ímíjaj ókormíteľa pomyšlénij, petróv proviščaváju tí hlás: Spasí mja Christé, Spasí mja Bože, jáko čelovikoľúbec."),
    
    // S:
    col2(gText(translation.at("S"))),
    "",
    jObj4("",none, "", "Skóro sovnídem v nevístnik Christóv, da vsí úslýšim blážénnyj hlás Christá Boha nášeho: prijidíte ľúbjaščiji nebésnuju slávu, sopričástnicy bývše múdrych ďív, újasnívše sviščý náša víroju."),
    
    // I:
    col2(gText(translation.at("IN"))),
    "",
    jObj4("",none, "", "Dušé, pokájsja préžde íschóda tvojehó, súd neumýten hríšnym jésť, í nesterpímyj, vozopíj Hospodu vo úmiléniji sérdca: sohriších tí v víďiniji í ne v víďiniji, ščédryj, molitvami Bohoródicy úščédri, í Spasí mja."),
    col2(translation.at("HOSPODI_POMILUJ")+". "+sText("(40)")),
    col2(sText(translation.at("MOLITVA"))),
    "",
    jObj4("",none, "", "Tebí Hospodi, jédínomu bláhómu í nepamjatozlóbnomu íspovídaju hrichí mojá, tebí pripádaju vopijá nedostójnyj: sohriších Hospodi, sohriších, í ňísm dostóin vozzríti na vysotú nebésnuju ot mnóžestva neprávd mojích. no Hospodi mój Hospodi, dáruj mí slézy úmilénija, jédínyj bláže í mílostivyj, jáko da ími ťá úmoľú, óčístitisja préžde koncá ot vsjákaho hrichá: strášno bo í hrózno místo ímam proití, ťíla razlučívsja, í mnóžestvo mjá mráčnoje í bezčelovíčnoje démonov srjáščet, í niktóže v pómošč spútstvujaj, ílí ízbavľájaj. ťím pripádaju tvojéj bláhosti, ne predážď óbíďaščym mjá, nižé da pochváľatsja ó mňí vrazí moí bláhíj Hospodi, nižé da rekút: v rúki náša prišél jésí, í nám prédan jésí. ní, Hospodi, ne zabúdi ščedrót tvojích, í ne vozdážď mí po bezzakónijem moím, í ne otvratí licá tvojehó ot mené, no tý, Hospodi, nakaží mja, óbáče mílostiju í ščedrótami: vráh že mój da ne vozrádujetsja ó mňí, no úhasí jéhó na mjá preščénija, í vsé úprazdní jéhó ďíjstvo, í dážď mí k tebí púť neukórnyj, bláhíj Hospodi: zanéže í sohrišív ne pribihóch ko ínómu vračú, í ne prostróch rukí mojejá k bóhu čuždému. ne otríni úbo molénija mojehó, no úslýši mjá tvojéju bláhostiju, í útverdí mojé sérdce stráchom tvojím, í da búdet bláhodáť tvojá na mňí Hospodi, jáko óhň popaľájaj nečístyja vo mňí pómysly. tý bo jésí, Hospodi, svít páče vsjákaho svíta: rádosť páče vsjákija rádosti, úpokojénije páče vsjákaho úpokojénija: žízň ístinnaja, í Spasénije, prebyvájuščeje vo víki vikóv, ámíň."),
  ))
])
