#import "../../../../all.typ": *
= #translation.at("KAFTIZMA") 5

#columns(2, gutter: 2pt, [

== #translation.at("ANTIFON") 1
  #generateTable((
    "",
    sText([Psalóm Davidu, ne nadpísan ú jévréj, (#translation.at("PSALM") 32)]),
    gText("1"),
    par([Rádujtesja, právedniji, ó Hospodi: právym podobájet pochvalá.]),
    gText("2"),
    par([Íspovídajtesja Hospodevi v húslech, vo psaltíri desjatostrúnňim pójte jémú:]),
    gText("3"),
    par([Vospójte jémú písň nóvu, dóbri pójte jémú so vosklicánijem:]),
    gText("4"),
    par([Jáko právo Slóvo Hospodne, í vsjá ďilá jéhó v víri.]),
    gText("5"),
    par([Ľúbit mílostyňu í súd Hospoď, mílosti Hospodni íspólň zemľá.]),
    gText("6"),
    par([Slóvom Hospodnim nebesá útverdíšasja, í Dúchom úst jéhó vsjá síla ích:]),
    gText("7"),
    par([Sobirájaj jáko mích vódy morskíja, polahájaj v sokróviščich bézdny.]),
    gText("8"),
    par([Da úbojítsja Hospoda vsjá zemľá, ot nehóže da podvížutsja vsí živúščiji po vselénňij:]),
    gText("9"),
    par([Jáko tój rečé, í býša: tój poveľí, í sozdášasja.]),
    gText("10"),
    par([Hospoď razorájet sovíty jázýkov, otmetájet že mýsli ľudéj í otmetájet sovíty kňazéj.]),
    gText("11"),
    par([Sovít že Hospodeň vo vík prebyvájet, pomyšlénija sr-d*ca jéhó v ród í ród.]),
    gText("12"),
    par([Blážén jázýk, jémúže jésť Hospoď Boh jéhó, ľúdije, jáže ízbrá v nasľídije sebí.]),
    gText("13"),
    par([S nebesé prizrí Hospoď, víďi vsjá sýny čelovíčeskija:]),
    gText("14"),
    par([Ot hotóvaho žilíšča svojehó prizrí na vsjá živúščyja na zemlí:]),
    gText("15"),
    par([Sozdávyj na jédíňi serdcá ích, razumivájaj na vsjá ďilá ích.]),
    gText("16"),
    par([Ne spasájetsja cár mnóhoju síloju, í íspolín ne spasétsja mnóžestvom kríposti svojejá.]),
    gText("17"),
    par([Lóž kóň vo spasénije, vo mnóžestvi že síly svojejá ne spasétsja.]),
    gText("18"),
    par([Sé, óči Hospodni na bojáščyjasja jéhó, úpovájuščyja na mílosť jéhó:]),
    gText("19"),
    par([Ízbáviti ot smérti dúšy ích, í prepitáti já v hlád.]),
    gText("20"),
    par([Dušá že náša čájet Hospoda, jáko pomóščnik í zaščítiteľ náš jésť:]),
    gText("21"),
    par([Jáko ó ném vozveselítsja sérdce náše, í vo ímja svjatóje jéhó úpováchom.]),
    gText("22"),
    par([Búdi, Hospodi, mílosť tvojá na nás, jákože úpováchom na ťá.]),
    gText("1"),
    sText([Psalóm Davidu, vnehdá ízminí licé svojé pred ávijmeléchom: í otpustí jéhó, í otíde, (#translation.at("PSALM") 33)]),
    gText("2"),
    par([Bláhoslovľú Hospoda na vsjákoje vrémja, výnu chvalá jéhó vo úsťích mojích.]),
    gText("3"),
    par([Ó Hospodi pochválitsja dušá mojá: da úslýšat krótcyi í vozveseľátsja.]),
    gText("4"),
    par([Vozvelíčite Hospoda so mnóju, í voznesém ímja jéhó vkúpi.]),
    gText("5"),
    par([Vzyskách Hospoda, í úslýša mjá í ot vsích skorbéj mojích ízbávi mjá.]),
    gText("6"),
    par([Pristupíte k nemú í prosvitítesja, í líca váša ne postyďátsja.]),
    gText("7"),
    par([Séj níščij vozzvá, í Hospoď úslýša í, í ot vsích skorbéj jéhó Spasé í.]),
    gText("8"),
    par([Ópolčítsja Anhel Hospodeň ókrest bojáščichsja jéhó í ízbávit ích.]),
    gText("9"),
    par([Vkusíte í vídite, jáko bláh Hospod: blážén múž, íže úpovájet náň.]),
    gText("10"),
    par([Bójtesja Hospoda, vsí svjatíji jéhó, jáko ňísť lišénija bojáščymsja jéhó.]),
    gText("11"),
    par([Bohátiji óbniščáša í vzalkáša: vzyskájuščiji že Hospoda ne lišátsja vsjákaho bláha.]),
    gText("12"),
    par([Prijidíte, čáda, poslúšajte mené, stráchu Hospodňu naučú vás.]),
    gText("13"),
    par([Któ jésť čelovík choťáj živót, ľubjáj dní víďiti bláhi;]),
    gText("14"),
    par([Úderží jázýk tvój ot zlá í ústňí tvoí, jéže ne hlahólati ľstí.]),
    gText("15"),
    par([Úklonísja ot zlá í sotvorí bláho: vzyščí míra í požení í.]),
    gText("16"),
    par([Óči Hospodni na právednyja, í úši jéhó v molítvu ích.]),
    gText("17"),
    par([Licé že Hospodne na tvorjáščyja zlája, jéže potrebíti ot zemlí pámjať ích.]),
    gText("18"),
    par([Vozzváša právedniji, í Hospoď úslýša ích í ot vsích skorbéj ích ízbávi ích.]),
    gText("19"),
    par([Blíz Hospoď sokrušénnych sérdcem, í smirénnyja dúchom Spasét.]),
    gText("20"),
    par([Mnóhi skórbi právednym, í ot vsích ích ízbávit já Hospoď.]),
    gText("21"),
    par([Chranít Hospoď vsjá kósti ích, ni jédína ot ních sokrušítsja.]),
    gText("22"),
    par([Smérť hríšnikov ľutá, í nenavíďaščiji právednaho prehrišát.]),
    gText("23"),
    par([Ízbávit Hospoď dúšy ráb svojích, í ne prehrišát vsí úpovájuščiji na nehó.]),
    col2(gText([#translation.at("SI")])),
  ))
== #translation.at("ANTIFON") 2
  #generateTable((
    "",
    sText([Psalóm Davidu, (#translation.at("PSALM") 34)]),
    gText("1"),
    par([Sudí, Hospodi, óbíďaščyja mjá, poborí borjúščyja mjá.]),
    gText("2"),
    par([Prijimí órúžije í ščít í vostáni v pómošč mojú:]),
    gText("3"),
    par([Ízsúni méč í zakľučí soprotív hoňáščich mjá: rcý duší mojéj: Spasénije tvojé jésm áz.]),
    gText("4"),
    par([Da postyďátsja í posrámjatsja íščuščiji dúšu mojú, da vozvraťátsja vspjáť í postyďátsja mýsľaščiji mí zlája.]),
    gText("5"),
    par([Da búdut jáko prách pred licém vítra, í Anhel Hospodeň óskorbľája ích:]),
    gText("6"),
    par([Da búdet púť ích tmá í pólzok, í Anhel Hospodeň pohoňájaj ích:]),
    gText("7"),
    par([Jáko túne skrýša mí páhubu síti svojejá, vsúje ponosíša duší mojéj.]),
    gText("8"),
    par([Da prijídet jémú síť, júže ne vísť, í lovítva, júže skrý, da óbímet í, í v síť da vpadét v ňú.]),
    gText("9"),
    par([Dušá že mojá vozrádujetsja ó Hospodi, vozveselítsja ó Spaséniji jéhó.]),
    gText("10"),
    par([Vsjá kósti mojá rekút: Hospodi, Hospodi, któ podóben tebí; ízbavľájaj níšča íz rukí krípľšich jéhó, í níšča, í úbóha ot raschiščájuščich jéhó.]),
    gText("11"),
    par([Vostávše na mjá sviďítele neprávedniji, jáže ne víďach, voprošáchu mjá.]),
    gText("12"),
    par([Vozdáša mí lukávaja voz bláhája, í bezčádije duší mojéj.]),
    gText("13"),
    par([Áz že, vnehdá óní stužáchu mí, óblačáchsja vo vrétišče í smirjách postóm dúšu mojú, í molítva mojá v ňídro mojé vozvratítsja.]),
    gText("14"),
    par([Jáko blížnemu, jáko brátu nášemu, táko úhoždách: jáko pláčja í sítuja, táko smirjáchsja.]),
    gText("15"),
    par([Í na mjá vozveselíšasja í sobrášasja: sobrášasja na mjá rány, í ne poznách: razďilíšasja, í ne úmilíšasja.]),
    gText("16"),
    par([Ískusíša mjá, podražníša mjá podražnénijem, poskrežetáša na mjá zubý svojími.]),
    gText("17"),
    par([Hospodi, kohdá úzriši; ústrój dúšu mojú ot zloďíjstva ích, ot lév jédinoródnuju mojú.]),
    gText("18"),
    par([Íspovímsja tebí v cerkvi mnózi, v ľúdech ťážcich voschvaľú ťa.]),
    gText("19"),
    par([Da ne vozrádujutsja ó mňí vraždújuščiji mí neprávedno, nenavíďaščiji mjá túne í pomizájuščiji óčíma:]),
    gText("20"),
    par([Jáko mňí úbo mírnaja hlahólachu, í na hňív lésti pomyšľáchu.]),
    gText("21"),
    par([Razširíša na mjá ústá svojá, ríša: bláhože, bláhože, víďiša óči náši.]),
    gText("22"),
    par([Víďil jésí, Hospodi, da ne premolčíši: Hospodi, ne otstupí ot mené.]),
    gText("23"),
    par([Vostáni, Hospodi, í vonmí sudú mojemú, Bože mój í Hospodi mój, na prjú mojú.]),
    gText("24"),
    par([Sudí mi, Hospodi, po právďi tvojéj, Hospodi Bože mój, í da ne vozrádujutsja ó mňí.]),
    gText("25"),
    par([Da ne rekút v serdcách svojích: bláhože, bláhože duší nášej: nižé da rekút: požróchom jéhó.]),
    gText("26"),
    par([Da postyďátsja í posrámjatsja vkúpi rádujuščijisja zlóm moím: da óblekútsja v stúd í srám veleríčujuščiji na mjá.]),
    gText("27"),
    par([Da vozrádujutsja í vozveseľátsja choťáščiji právdy mojejá: í da rekút výnu, da vozvelíčitsja Hospoď, choťáščiji míra rabú jéhó.]),
    gText("28"),
    par([Í jázýk mój poučítsja právďi tvojéj, vés déň chvaľí tvojéj.]),
    gText("1"),
    sText([V konéc, ótroku Hospodňu Davidu, (#translation.at("PSALM") 35)]),
    gText("2"),
    par([Hlahólet prebezzakónnyj sohrišáti v sebí: ňísť strácha Božija pred óčíma jéhó:]),
    gText("3"),
    par([Jáko úľstí pred ním óbristí bezzakónije svojé, í voznenavíďiti.]),
    gText("4"),
    par([Hlahóly úst jéhó bezzakónije í lésť: ne voschoťí razumíti jéže úblažíti.]),
    gText("5"),
    par([Bezzakónije pomýsli na lóži svojém: predstá vsjákomu putí nebláhu, ó zlóbi že ne nehodová.]),
    gText("6"),
    par([Hospodi, na nebesí mílosť tvojá, í ístina tvojá do óblak:]),
    gText("7"),
    par([Právda tvojá jáko hóry Božija, suďbý tvojá bézdna mnóha: čelovíki í skotý Spaséši, Hospodi.]),
    gText("8"),
    par([Jáko úmnóžil jésí mílosť tvojú, Bože: sýnove že čelovíčestiji v króvi krilú tvoéju naďíjatisja ímut.]),
    gText("9"),
    par([Úpijútsja ot túka dómu tvojehó, í potókom sládosti tvojejá napojíši já.]),
    gText("10"),
    par([Jáko ú tebé ístóčnik životá, vo svíťi tvojém úzrim svít.]),
    gText("11"),
    par([Probávi mílosť tvojú víduščym ťá í právdu tvojú právym sérdcem.]),
    gText("12"),
    par([Da ne prijídet mňí nohá hordýni, í ruká hríšniča da ne podvížit mené.]),
    gText("13"),
    par([Támo padóša vsí ďílajuščiji bezzakónije: ízrinovéni býša, í ne vozmóhut státi.]),
    col2(gText([#translation.at("SI")])),
  ))
== #translation.at("ANTIFON") 3
  #generateTable((
    "",
    sText([Psalóm Davidu, (#translation.at("PSALM") 36)]),
    gText("1"),
    par([Ne revnúj lukávnujuščym, nižé zavídi tvorjáščym bezzakónije.]),
    gText("2"),
    par([Zané jáko travá skóro ízsšut, í jáko zélije zláka skóro otpadút.]),
    gText("3"),
    par([Úpováj na Hospoda í tvorí bláhostýňu: í naselí zémľu, í úpaséšisja v bohátstvi jéjá.]),
    gText("4"),
    par([Nasladísja Hospodevi, í dást tí prošénija sérdca tvojehó.]),
    gText("5"),
    par([Otkrýj ko Hospodu púť tvój í úpováj na nehó, í tój sotvorít.]),
    gText("6"),
    par([Í ízvedét jáko svít právdu tvojú í suďbú tvojú jáko polúdne.]),
    gText("7"),
    par([Povinísja Hospodevi í úmolí jéhó. Ne revnúj spíjuščemu v putí svojém, čelovíku tvorjáščemu zakonoprestuplénije.]),
    gText("8"),
    par([Prestáni ot hňíva í óstávi járosť: ne revnúj, jéže lukávnovati,]),
    gText("9"),
    par([Zané lukávnujuščiji potrebjátsja, terpjáščiji že Hospoda, tíji nasľíďat zémľu.]),
    gText("10"),
    par([Í jéščé málo, í ne búdet hríšnika: í vzýščeši místo jéhó í ne óbrjáščeši.]),
    gText("11"),
    par([Krótcyi že nasľíďat zémľu í naslaďátsja ó mnóžestvi míra.]),
    gText("12"),
    par([Nazirájet hríšnyj právednaho í poskrežéščet náň zubý svojími:]),
    gText("13"),
    par([Hospoď že posmiétsja jémú, zané prozirájet, jáko prijídet déň jéhó.]),
    gText("14"),
    par([Méč ízvlekóša hríšnicy, naprjahóša lúk svój, nizložíti úbóha í níšča, zakláti právyja sérdcem.]),
    gText("15"),
    par([Méč ích da vnídet v serdcá ích, í lúcy ích da sokrušátsja.]),
    gText("16"),
    par([Lúčše máloje právedniku, páče bohátstva hríšnych mnóha.]),
    gText("17"),
    par([Zané mýšcy hríšnych sokrušátsja, útverždájet že právednyja Hospoď.]),
    gText("18"),
    par([Vísť Hospoď putí neporóčnych, í dostojánije ích v vík búdet.]),
    gText("19"),
    par([Ne postyďátsja vo vrémja ľútoje í vo dnéch hláda nasýťatsja, jáko hríšnicy pohíbnut.]),
    gText("20"),
    par([Vrazí že Hospodni, kúpno proslávitisja ím í voznestísja, ísčezájušče jáko dým ísčezóša.]),
    gText("21"),
    par([Zajémlet hríšnyj í ne vozvratít: právednyj že ščédrit í dajét.]),
    gText("22"),
    par([Jáko bláhoslovjáščiji jéhó nasľíďat zémľu, klenúščiji že jéhó potrebjátsja.]),
    gText("23"),
    par([Ot Hospoda stopý čelovíku íspravľájutsja, í putí jéhó voschóščet ziló.]),
    gText("24"),
    par([Jéhdá padét, ne razbijétsja, jáko Hospoď podkripľájet rúku jéhó.]),
    gText("25"),
    par([Ю́ňíjšij bých, íbo sostaríchsja, í ne víďich právednika óstávlena, nižé símene jéhó prosjášča chľíby.]),
    gText("26"),
    par([Vés déň mílujet í vzaím dajét právednyj, í símja jéhó vo bláhoslovénije búdet.]),
    gText("27"),
    par([Úklonísja ot zlá í sotvorí bláho, í vselísja v vík víka.]),
    gText("28"),
    par([Jáko Hospoď ľúbit súd í ne óstávit prepodóbnych svojích: vo vík sochraňátsja: bezzakónnicy že ízženútsja, í símja nečestívych potrebítsja.]),
    gText("29"),
    par([Právednicy že nasľíďat zémľu í vseľátsja v vík víka na néj.]),
    gText("30"),
    par([Ústá právednaho poučátsja premúdrosti, í jázýk jéhó vozhlahólet súd.]),
    gText("31"),
    par([Zakón Boha jéhó sérdcy jéhó, í ne zápnutsja stopý jéhó.]),
    gText("32"),
    par([Smatrájet hríšnyj právednaho í íščet jéže úmertvíti jéhó:]),
    gText("33"),
    par([Hospoď že ne óstávit jéhó v rukú jéhó, nižé ósúdit jéhó, jéhdá súdit jémú.]),
    gText("34"),
    par([Poterpí Hospoda í sochraní púť jéhó, í voznesét ťá jéže nasľíditi zémľu: vnehdá potrebľátisja hríšnikom, úzriši.]),
    gText("35"),
    par([Víďich nečestívaho prevoznosjáščasja í výsjaščasja jáko kédry lijvánskija:]),
    gText("36"),
    par([Í mímo ídóch, í sé, ne bí, í vzyskách jéhó, í ne óbrítesja místo jéhó.]),
    gText("37"),
    par([Chraní nezlóbije í vížď pravotú, jáko jésť óstánok čelovíku mírnu.]),
    gText("38"),
    par([Bezzakónnicy že potrebjátsja vkúpi: óstáncy že nečestívych potrebjátsja.]),
    gText("39"),
    par([Spasénije že právednych ot Hospoda, í zaščítiteľ ích jésť vo vrémja skórbi:]),
    gText("40"),
    par([Í pomóžet ím Hospoď í ízbávit ích, í ízmet ích ot hríšnik í Spasét ích, jáko úpováša na nehó.]),
    col2(gText([#translation.at("SI")])),
  ))
  #generateTable((
    col2(sText(translation.at("AFTER_KAFTIZMA"))),
    sText("T"),
    jObj4("",5, "", "Strášnyj tvój prestól, lukávoje mojé žitijé, í któ mja ízbávit tohdášnija núždy, ášče ne tý pomíluješi mjá Christé Bože, jáko ščédr í čelovikoľúbec;"),
    
    // S:
    col2(gText(translation.at("S"))),
    "",
    jObj4("",none, "", "Popečénije žitijá ízhná mja rajá, í čtó sotvorjú otčájannyj; sehó rádi tolkú vo vratá í zovú: Hospodi Hospodi, otvérzi mí pokajánijem, í Spasí mja."),
    
    // I:
    col2(gText(translation.at("IN"))),
    "",
    jObj4("",none, "", "Kíj narečém chrám tvój, Bohoródice: pristánišče li Dúchóvnoje; ílí ráj sládosti nebésnyja, chodátajstven žízni nekončájemyja; vsjá bo ímaši dóbraja. vsehdá molísja Christú, spastísja dušám nášym."),
    col2(translation.at("HOSPODI_POMILUJ")+". "+sText("(40)")),
    col2(sText(translation.at("MOLITVA"))),
    "",
    jObj4("",none, "", "Bože právednyj í chváľnyj, Bože velíkij í krípkij, Bože prevíčnyj, úslýši hríšnaho múža molitvu v čás séj: úslýši mjá, óbiščávyj úslýšati vo ístiňi ťá prizyvájuščich, í ne ómerzí mja nečístyja ústňí ímúšča, í vo hrisích soderžíma, úpovánije vsích koncév zemlí, í stránstvujuščich daléče. prijimí órúžije í ščít, í vostáni v pómošč mojú, ízléj méč, í zakľučí soprotív hoňáščich mjá: zapretí nečístym duchovóm ot licá bezúmija mojehó, í da otlučítsja ot mojejá mýsli dúch nénavisti, í zlopomňínija, dúch závisti í lésti, dúch bojázni í únýnija, dúch hórdosti í vsjákija ínýja zlóby: í da úhásnet vsjákoje razžžénije í dvižénije plóti mojejá, ot dijávoľskaho ďíjstva sostavľájemoje, í da prosvitítsja mojá dušá, í ťílo, í dúch svítom tvojehó Božéstvennaho poznánija, da mnóžestvom ščedrót tvojích dostíhnu sojedinénija víry, v múža soveršénna, v míru vózrasta, í proslávľu so Anhely, í vsími svjatými tvojími, vsečestnóje í velikoľípoje ímja tvojé, Ótcá, í Sýna, í svjatáho Dúcha, nýňi í prísno, í vo víki vikóv, ámíň."),
  ))
])
