#import "../../../../all.typ": *
= #translation.at("KAFTIZMA") 6

#columns(2, gutter: 2pt, [

== #translation.at("ANTIFON") 1
  #generateTable((
    gText("1"),
    sText([Psalóm Davidu, v vospominánije ó subbóťi, (#translation.at("PSALM") 37)]),
    gText("2"),
    par([Hospodi, da ne járostiju tvojéju óbličíši mené, nižé hňívom tvojím nakážeši mené:]),
    gText("3"),
    par([Jáko stríly tvojá únzóša vo mňí, í útverdíl jésí na mňí rúku tvojú.]),
    gText("4"),
    par([Nísť íscilénija v plóti mojéj ot licá hňíva tvojehó, ňísť míra v kostéch mojích ot licá hrích mojích.]),
    gText("5"),
    par([Jáko bezzakónija mojá prevzydóša hlavú mojú, jáko brémja ťážkoje óťahoťíša na mňí.]),
    gText("6"),
    par([Vozsmerďíša í sohníša rány mojá, ot licá bezúmija mojehó.]),
    gText("7"),
    par([Postradách í sľakóchsja do koncá, vés déň sítuja choždách:]),
    gText("8"),
    par([Jáko ľádvija mojá napólnišasja poruhánij, í ňísť íscilénija v plóti mojéj.]),
    gText("9"),
    par([Ózlóblen bých í smiríchsja do zilá, rykách ot vozdychánija sérdca mojehó.]),
    gText("10"),
    par([Hospodi, pred tobóju vsé želánije mojé, í vozdychánije mojé ot tebé ne útaísja.]),
    gText("11"),
    par([Sérdce mojé smjatésja, óstávi mjá síla mojá, í svít óčiju moéju, í tój ňísť so mnóju.]),
    gText("12"),
    par([Drúzi moí í ískrenniji moí prjámo mňí priblížišasja í stáša.]),
    gText("13"),
    par([Í blížniji moí otdaléče mené stáša, í nuždáchusja íščuščiji dúšu mojú: í íščuščiji zlája mňí hlahólachu súetnaja, í ľstívnym vés déň poučáchusja.]),
    gText("14"),
    par([Áz že jáko hlúch ne slýšach, í jáko ňím ne otverzájaj úst svojích:]),
    gText("15"),
    par([Í bých jáko čelovík ne slýšaj í ne ímýj vo úsťích svojích óbličénija.]),
    gText("16"),
    par([Jáko na ťá, Hospodi, úpovách, tý úslýšiši, Hospodi Bože mój.]),
    gText("17"),
    par([Jáko rích: da ne kohdá porádujut mi sja vrazí moí: í vnehdá podvižátisja nohám moím, na mjá veleríčevaša.]),
    gText("18"),
    par([Jáko áz na rány hotóv, í boľízň mojá predo mnóju jésť výnu.]),
    gText("19"),
    par([Jáko bezzakónije mojé áz vozviščú í popekúsja ó hrisí mojém.]),
    gText("20"),
    par([Vrazí že moí živút í úkripíšasja páče mené, í úmnóžišasja nenavíďaščiji mjá bez právdy:]),
    gText("21"),
    par([Vozdajúščiji mí zlája voz blahája óbolháchu mjá, zané hoňách bláhostýňu.]),
    gText("22"),
    par([Ne óstávi mené, Hospodi Bože mój, ne otstupí ot mené:]),
    gText("23"),
    par([Vonmí v pómošč mojú, Hospodi Spasénija mojehó.]),
    gText("1"),
    sText([V konéc, ídijthúmu, písň Davidu, (#translation.at("PSALM") 38)]),
    gText("2"),
    par([Rích: sochraňú putí mojá, jéže ne sohrišáti mí jázýkom mojím: položích ústóm moím chranílo, vnehdá vostáti hríšnomu predo mnóju.]),
    gText("3"),
    par([Óňimích í smiríchsja, í úmolčách ot bláh, í boľízň mojá óbnovísja.]),
    gText("4"),
    par([Sohríjasja sérdce mojé vo mňí, í v poučéniji mojém razhorítsja óhň: hlahólach jázýkom mojím:]),
    gText("5"),
    par([Skaží mi, Hospodi, končínu mojú í čisló dníj mojích, kóje jésť, da razumíju, čtó lišájusja áz.]),
    gText("6"),
    par([Sé, pjádi položíl jésí dní mojá, í sostáv mój jáko ničtóže pred tobóju: óbáče vsjáčeskaja sujetá vsják čelovík živýj.]),
    gText("7"),
    par([Úbo óbrazom chódit čelovík, óbáče vsúje mjatétsja: sokróviščstvujet, í ne vísť, komú soberét já.]),
    gText("8"),
    par([Í nýňi któ terpínije mojé; ne Hospoď li; í sostáv mój ot tebé jésť.]),
    gText("9"),
    par([Ot vsích bezzakónij mojích ízbávi mjá: ponošénije bezúmnomu dál mjá jésí.]),
    gText("10"),
    par([Óňimích í ne otverzóch úst mojích, jáko tý sotvoríl jésí.]),
    gText("11"),
    par([Otstávi ot mené rány tvojá: ot kríposti bo rukí tvojejá áz ísčezóch.]),
    gText("12"),
    par([Vo óbličénijich ó bezzakóniji nakazál jésí čelovíka, í ístájal jésí jáko paučínu dúšu jéhó: óbáče vsúje vsják čelovík.]),
    gText("13"),
    par([Úslýši molítvu mojú, Hospodi, í molénije mojé vnuší, sléz mojích ne premolčí: jáko preséľnik áz jésm ú tebé í prišléc, jákože vsí ótcý moí.]),
    gText("14"),
    par([Óslábi mí, da počíju, préžde dáže ne otidú, í ktomú ne búdu.]),
    gText("1"),
    sText([V konéc, psalóm Davidu, (#translation.at("PSALM") 39)]),
    gText("2"),
    par([Terpjá poterpích Hospoda, í vňát mí í úslýša molítvu mojú:]),
    gText("3"),
    par([Í vozvedé mja ot róva strastéj í ot brénija tíny, í postávi na kámeni nózi moí í ísprávi stopý mojá:]),
    gText("4"),
    par([Í vloží vo ústá mojá písň nóvu, pínije Bohu nášemu. Úzrjat mnózi í úbojátsja, í úpovájut na Hospoda.]),
    gText("5"),
    par([Blážén múž, jémúže jésť ímja Hospodne úpovánije jéhó, í ne prizrí v suetý í neistovlénija lóžnaja.]),
    gText("6"),
    par([Mnóha sotvoríl jésí tý, Hospodi Bože mój, čudesá tvojá, í pomyšlénijem tvoím ňísť któ úpodóbitsja tebí: vozvistích í hlahólach: úmnóžišasja páče čislá.]),
    gText("7"),
    par([Žértvy í prinošénija ne voschoťíl jésí, ťílo že sveršíl mí jésí: vsesožžénij í ó hrisí ne vzyskál jésí.]),
    gText("8"),
    par([Tohdá rích: sé, prijidú: v hlavízňi knížňi písano jésť ó mňí:]),
    gText("9"),
    par([Jéže sotvoríti vóľu tvojú, Bože mój, voschoťích, í zakón tvój posreďí čréva mojehó.]),
    gText("10"),
    par([Bláhovistích právdu v cerkvi velícij, sé, ústnám moím ne vozbraňú: Hospodi, tý razumíl jésí.]),
    gText("11"),
    par([Právdu tvojú ne skrých v sérdcy mojém, ístinu tvojú í Spasénije tvojé rích, ne skrých mílosť tvojú í ístinu tvojú ot sónma mnóha.]),
    gText("12"),
    par([Tý že, Hospodi, ne údalí ščedrót tvojích ot mené: mílosť tvojá í ístina tvojá výnu da zastúpiťi mjá.]),
    gText("13"),
    par([Jáko óderžáša mjá zlája, ímže ňísť čislá: postihóša mjá bezzakónija mojá, í ne vozmohóch zríti: úmnóžišasja páče vlás hlavý mojejá, í sérdce mojé óstávi mjá.]),
    gText("14"),
    par([Bláhovolí, Hospodi, ízbáviti mjá: Hospodi, vo jéže pomoščí mi, vonmí.]),
    gText("15"),
    par([Da postyďátsja í posrámjatsja vkúpi íščuščiji dúšu mojú, ízjáti jú: da vozvraťátsja vspjáť í postyďátsja choťáščiji mí zlája.]),
    gText("16"),
    par([Da prijímut ábije stúd svój hlahóľuščiji mí: bláhože, bláhože.]),
    gText("17"),
    par([Da vozrádujutsja í vozveseľátsja ó tebí vsí íščuščiji tebé, Hospodi, í da rekút výnu, da vozvelíčitsja Hospoď, ľúbjaščiji Spasénije tvojé.]),
    gText("18"),
    par([Áz že níšč jésm í úbóh, Hospoď popečétsja ó mňí: pomóščnik mój í zaščítiteľ mój jésí tý, Bože mój, ne zakosní.]),
    col2(gText([#translation.at("SI")])),
  ))
== #translation.at("ANTIFON") 2
  #generateTable((
    gText("1"),
    sText([V konéc, psalóm Davidu, (#translation.at("PSALM") 40)]),
    gText("2"),
    par([Blážén razumivájaj na níšča í úbóha, v déň ľút ízbávit jéhó Hospoď.]),
    gText("3"),
    par([Hospoď da sochranít jéhó í živít jéhó, í da úblážít jéhó na zemlí í da ne predást jéhó v rúki vrahóv jéhó.]),
    gText("4"),
    par([Hospoď da pomóžet jémú na ódrí boľízni jéhó: vsé lóže jéhó óbratíl jésí v boľízni jéhó.]),
    gText("5"),
    par([Áz rích: Hospodi, pomíluj mjá, íscilí dúšu mojú, jáko sohriších tí.]),
    gText("6"),
    par([Vrazí moí ríša mňí zlája: kohdá úmret, í pohíbnet ímja jéhó;]),
    gText("7"),
    par([Í vchoždáše víďiti, vsúje hlahólaše sérdce jéhó: sobrá bezzakónije sebí, íschoždáše vón í hlahólaše vkúpi.]),
    gText("8"),
    par([Na mjá šeptáchu vsí vrazí moí, na mjá pomyšľáchu zlája mňí.]),
    gText("9"),
    par([Slóvo zakonoprestúpnoje vozložíša na mjá: jédá spjáj ne priložít voskresnúti;]),
    gText("10"),
    par([Íbo čelovík míra mojehó, na nehóže úpovách, jádýj chľíby mojá, vozvelíči na mjá zapinánije.]),
    gText("11"),
    par([Tý že, Hospodi, pomíluj mjá í vozstávi mjá, í vozdám ím.]),
    gText("12"),
    par([V sém poznách, jáko voschoťíl mjá jésí, jáko ne vozrádujetsja vráh mój ó mňí.]),
    gText("13"),
    par([Mené že za nezlóbije prijál, í útverdíl mjá jésí pred tobóju v vík.]),
    gText("14"),
    par([Bláhoslovén Hospoď Boh Izráilev ot víka í do víka: búdi, búdi.]),
    gText("1"),
    sText([V konéc, v rázum synóv koréovych, psalóm Davidu, (#translation.at("PSALM") 41)]),
    gText("2"),
    par([Ímže óbrazom želájet jéléň na ístóčniki vodnýja, síce želájet dušá mojá k tebí, Bože.]),
    gText("3"),
    par([Vozžadá dušá mojá k Bohu krípkomu, živómu: kohdá prijidú í jávľúsja licú Božiju;]),
    gText("4"),
    par([Býša slézy mojá mňí chľíb déň í nóšč, vnehdá hlahólatisja mňí na vsják déň: hďí jésť Boh tvój;]),
    gText("5"),
    par([Sijá pomjanúch, í ízlijách na mjá dúšu mojú: jáko projdú v místo selénija dívna, dáže do dómu Božija, vo hlási rádovanija í íspovídanija, šúma prázdnujuščaho.]),
    gText("6"),
    par([Vskúju priskórbna jésí, dušé mojá; í vskúju smuščáješi mjá; úpováj na Boha, jáko íspovímsja jémú, Spasénije licá mojehó í Boh mój.]),
    gText("7"),
    par([Ko mňí samomú dušá mojá smjatésja: sehó rádi pomjanúch ťá ot zemlí íordánski í jérmonijímski, ot horý mályja.]),
    gText("8"),
    par([Bézdna bézdnu prizyvájet vo hlási chľábij tvojích: vsjá vysotý tvojá í vólny tvojá na mňí preidóša.]),
    gText("9"),
    par([V déň zapovísť Hospoď mílosť svojú, í nóščiju písň jéhó ot mené #footnote("ú mené"), molítva Bohu životá mojehó.]),
    gText("10"),
    par([Rekú Bohu: zastúpnik mój jésí, počtó mjá zabýl jésí; í vskúju sítuja choždú, vnehdá óskorbľájet vráh;]),
    gText("11"),
    par([Vnehdá sokrušátisja kostém moím, ponošáchu mí vrazí moí, vnehdá hlahólati ím mňí na vsják déň: hďí jésť Boh tvój;]),
    gText("12"),
    par([Vskúju priskórbna jésí, dušé mojá; í vskúju smuščáješi mjá; úpováj na Boha, jáko íspovímsja jémú, Spasénije licá mojehó í Boh mój.]),
    "",
    sText([Psalóm Davidu, ne nadpísan ú jévréj, (#translation.at("PSALM") 42)]),
    gText("1"),
    par([Sudí mi, Bože, í razsudí prjú mojú: ot jázýka neprepodóbna, ot čelovíka neprávedna í ľstíva ízbávi mjá.]),
    gText("2"),
    par([Zané tý jésí, Bože, kríposť mojá, vskúju otrínul mjá jésí; í vskúju sítuja choždú, vnehdá óskorbľájet vráh;]),
    gText("3"),
    par([Poslí svít tvój í ístinu tvojú: tá mjá nastávista, í vvedósta mjá v hóru svjatúju tvojú í v selénija tvojá.]),
    gText("4"),
    par([Í vnídu k žértvenniku Božiju, k Bohu veseľáščemu júnosť mojú: íspovímsja tebí v húslech, Bože, Bože mój.]),
    gText("5"),
    par([Vskúju priskórbna jésí, dušé mojá; í vskúju smuščáješi mjá; úpováj na Boha, jáko íspovímsja jémú, Spasénije licá mojehó í Boh mój.]),
    col2(gText([#translation.at("SI")])),
  ))
== #translation.at("ANTIFON") 3
  #generateTable((
    gText("1"),
    sText([V konéc, synóv koréovych, v rázum, psalóm (#translation.at("PSALM") 43)]),
    gText("2"),
    par([Bože, úšíma nášima úslýšachom, í ótcý náši vozvistíša nám ďílo, jéže soďílal jésí vo dnéch ích, vo dnéch drévnich.]),
    gText("3"),
    par([Ruká tvojá jázýki potrebí, í nasadíl já jésí: ózlóbil jésí ľúdi í ízhnál jésí já.]),
    gText("4"),
    par([Ne bo mečém svojím nasľídiša zémľu, í mýšca ích ne spasé ích, no desníca tvojá í mýšca tvojá í prosviščénije licá tvojehó, jáko bláhovolíl jésí v ních.]),
    gText("5"),
    par([Tý jésí sám cer mój í Boh mój, zapovídajaj spasénija Jákovľa.]),
    gText("6"),
    par([Ó tebí vrahí náša ízbodém róhi, í ó ímeni tvojém úničižím vostajúščyja na ný.]),
    gText("7"),
    par([Ne na lúk bo mój úpováju, í méč mój ne spasét mené:]),
    gText("8"),
    par([Spasl bo jésí nás ot stužájuščich nám, í nenavíďaščich nás posramíl jésí.]),
    gText("9"),
    par([Ó Bózi pochválimsja vés déň, í ó ímeni tvojém íspovímysja vo vík.]),
    gText("10"),
    par([Nýňi že otrínul jésí í posramíl jésí nás, í ne ízýdeši, Bože, v sílach nášich.]),
    gText("11"),
    par([Vozvratíl jésí nás vspjáť pri vrazích nášich, í nenavíďaščiji nás raschiščáchu sebí.]),
    gText("12"),
    par([Dál jésí nás jáko óvcy sňídi, í vo jázýcich razsíjal ný jésí.]),
    gText("13"),
    par([Otdál jésí ľúdi tvojá bez ciný, í ne bí mnóžestvo v vosklicánijich nášich.]),
    gText("14"),
    par([Položíl jésí nás ponošénije sosídom nášym, podražnénije í poruhánije súščym ókrest nás.]),
    gText("15"),
    par([Položíl jésí nás v prítču vo jázýcich, pokivániju hlavý v ľúdech.]),
    gText("16"),
    par([Vés déň srám mój predo mnóju jésť, í stúd licá mojehó pokrý mja,]),
    gText("17"),
    par([Ot hlása ponošájuščaho í óklevetájuščaho, ot licá vrážija í ízhoňáščaho.]),
    gText("18"),
    par([Sijá vsjá prijidóša na ný, í ne zabýchom tebé, í ne neprávdovachom v zavíťi tvojém,]),
    gText("19"),
    par([Í ne otstupí vspjáť sérdce náše: í úkloníl jésí stezí náša ot putí tvojehó,]),
    gText("20"),
    par([Jáko smiríl jésí nás na mísťi ózloblénija, í prikrý ny síň smértnaja.]),
    gText("21"),
    par([Ášče zabýchom ímja Boha nášeho, í ášče vozďíchom rúki náša k bóhu čuždému,]),
    gText("22"),
    par([Ne Boh li vzýščet sích; tój bo vísť tájnaja sérdca.]),
    gText("23"),
    par([Zané tebé rádi úmerščvľájemsja vés déň, vminíchomsja jáko óvcy zakolénija.]),
    gText("24"),
    par([Vostáni, vskúju spíši, Hospodi; voskreséní, í ne otríni do koncá.]),
    gText("25"),
    par([Vskúju licé tvojé otvraščáješi; zabyváješi niščetú nášu í skórb nášu;]),
    gText("26"),
    par([Jáko smirísja v pérsť dušá náša, priľpé zemlí útróba náša.]),
    gText("27"),
    par([Voskresní, Hospodi, pomozí nám, í ízbávi nás ímene rádi tvojehó.]),
    gText("1"),
    sText([V konéc, ó ízmiňáemych synóm koréovym v rázum, písň ó vozľúblenňim, (#translation.at("PSALM") 44)]),
    gText("2"),
    par([Otrýhnu sérdce mojé Slóvo bláho, hlahóľu áz ďilá mojá cerévi: jázýk mój trósť knížnika skoropísca.]),
    gText("3"),
    par([Krasén dobrótoju páče synóv čelovíčeskich, ízlijásja bláhodáť vo ústnách tvojích: sehó rádi bláhosloví ťa Boh vo vík.]),
    gText("4"),
    par([Prepojáši méč tvój po bedrí tvojéj, síľne,]),
    gText("5"),
    par([Krasotóju tvojéju í dobrótoju tvojéju: í naľacý, í úspiváj, í cárstvuj ístiny rádi í krótosti í právdy: í nastávit ťá dívno desníca tvojá.]),
    gText("6"),
    par([Stríly tvojá ízoščrény, síľne: ľúdije pod tobóju padút v sérdcy vráh cerévych.]),
    gText("7"),
    par([Prestól tvój, Bože, v vík víka: žézl právosti žézl cárstvija tvojehó.]),
    gText("8"),
    par([Vozľubíl jésí právdu í voznenavíďil jésí bezzakónije: sehó rádi pomáza ťá, Bože, Boh tvój jéléem rádosti páče pričástnik tvojích.]),
    gText("9"),
    par([Smýrna í stákti í kasía ot ríz tvojích, ot ťážestej slonóvych #footnote("ot chrámov slonóvych"), íz níchže vozveselíša ťá.]),
    gText("10"),
    par([Dščéri caréj v čésti tvojéj: predstá caríca ódesnúju tebé, v rízach pozlaščénnych óďíjana preispeščréna.]),
    gText("11"),
    par([Slýši, dščí, í vížď, í prikloní úcho tvojé, í zabúdi ľúdi tvojá í dóm ótcá tvojehó:]),
    gText("12"),
    par([Í vozželájet cer dobróty tvojejá, zané tój jésť Hospoď tvój, í pokloníšisja jémú,]),
    gText("13"),
    par([Í dščí týrova s dáry: licú tvojemú pomóľatsja bohátiji ľúdstiji.]),
    gText("14"),
    par([Vsjá sláva dščére cerévy vnútr: rjásny zlatými óďíjana í preispeščréna.]),
    gText("15"),
    par([Privedútsja cerjú ďívy vsľíd jéjá, ískrennija jéjá privedútsja tebí:]),
    gText("16"),
    par([Privedútsja v veséliji í rádovaniji, vvedútsja v chrám cerév.]),
    gText("17"),
    par([Vmísto ótéc tvojích býša sýnove tvoí: postáviši já kňázi po vséj zemlí.]),
    gText("18"),
    par([Pomjanú ímja tvojé vo vsjákom róďi í róďi: sehó rádi ľúdije íspovíďatsja tebí v vík í vo vík víka.]),
    gText("1"),
    sText([V konéc, ó syňích koréovych, ó tájnych, psalóm (#translation.at("PSALM") 45)]),
    gText("2"),
    par([Boh nám pribížišče í síla, pomóščnik v skórbech óbrítšich ný ziló.]),
    gText("3"),
    par([Sehó rádi ne úbojímsja, vnehdá smuščájetsja zemľá, í prelahájutsja hóry v serdcá morskája.]),
    gText("4"),
    par([Vozšumíša í smjatóšasja vódy ích, smjatóšasja hóry krípostiju jéhó.]),
    gText("5"),
    par([Ríčnaja ústremlénija veseľát hrád Božij: ósvjatíl jésť selénije svojé výšnij.]),
    gText("6"),
    par([Boh posreďí jéhó, í ne podvížitsja: pomóžet jémú Boh útro zaútra.]),
    gText("7"),
    par([Smjatóšasja jázýcy, úkloníšasja cárstvija: dadé hlás svój výšnij, podvížesja zemľá.]),
    gText("8"),
    par([Hospoď síl s námi, zastúpnik náš Boh Jákovľ.]),
    gText("9"),
    par([Prijidíte í vídite ďilá Božija, jáže položí čudesá na zemlí:]),
    gText("10"),
    par([Otémľa bráni do konéc zemlí, lúk sokrušít í slómit órúžije, í ščitý sožžét óhném.]),
    gText("11"),
    par([Úprazdnítesja í razumíjte, jáko áz jésm Boh: voznesúsja vo jázýcich, voznesúsja na zemlí.]),
    gText("12"),
    par([Hospoď síl s námi, zastúpnik náš Boh Jákovľ.]),
    col2(gText([#translation.at("SI")])),
  ))
  #generateTable((
    col2(sText(translation.at("AFTER_KAFTIZMA"))),
    sText("T"),
    jObj4("",3, "", "Chvalú prinošú tí Hospodi, prehrišénija mojá vsjá vozviščáju tí, Bože, óbratív pomíluj mjá."),
    
    // S:
    col2(gText(translation.at("S"))),
    "",
    jObj4("",none, "", "Spasí mja Bože mój, jákože ínohdá mytarjá Spasl jésí: í bludnícy sléz ne prezrívyj, í mojé vozdychánije prijimí Spase mój, í Spasí mja."),
    
    // I:
    col2(gText(translation.at("IN"))),
    "",
    jObj4("",none, "", "Rábski nýňi pritekáju k pokróvu tvojemú preneporóčnaja, ízbávi mjá Bohorodíteľnice, slijánija strastéj, jáko bezstrástija vinóvnaho róždšaja."),
    col2(translation.at("HOSPODI_POMILUJ")+". "+sText("(40)")),
    col2(sText(translation.at("MOLITVA"))),
    "",
    jObj4("",none, "", "Bláhodarím ťá Hospodi Bože náš, ó vsích bláhoďijánijich tvojích, jáže ot pérvaho vózrasta do nastojáščaho, v nás nedostójnych bývšich, ó íchže vímy í ne vímy, ó jávlénnych í nejavlénnych, jáže ďílom bývšich, í Slóvom: vozľubívyj nás, jákože í jédinoródnaho tvojehó Sýna ó nás dáti ízvólivyj, spodóbi í nás dostójny býti tvojejá ľubvé. dážď Slóvom tvojím múdrosť, í stráchom tvojím vdochní kríposť ot tvojejá síly, í ášče čtó choťášče, ílí ne choťášče sohrišíchom, prostí, í ne vminí: í sochraní dúšu nášu svjatu, í predstávi jú tvojemú prestólu sóvisť ímúšču čístu, í konéc dostóin čelovikoľúbija tvojehó. í pomjaní Hospodi, vsích prizyvájuščich ímja tvojé vo ístiňi, pomjaní vsích bláha ílí soprotívnaja nám choťáščich, vsí bo čelovícy jésmý, í vsúje vsják čelovík. ťímže mólimsja tebí Hospodi: podážď nám tvojehó bláhoutróbija véliju mílosť."),
  ))
])
