#import "../../../../all.typ": *
= #translation.at("KAFTIZMA") 7

#columns(2, gutter: 2pt, [

== #translation.at("ANTIFON") 1
  #generateTable((
    gText("1"),
    sText([V konéc, ó syňích koréovych, psalóm, (#translation.at("PSALM") 46)]),
    gText("2"),
    par([Vsí jázýcy, vospleščíte rukámi, vosklíknite Bohu hlásom rádovanija:]),
    gText("3"),
    par([Jáko Hospoď výšnij strášen, cer vélij po vséj zemlí:]),
    gText("4"),
    par([Pokorí ľúdi nám í jázýki pod nóhi náša:]),
    gText("5"),
    par([Ízbrá nám dostojánija svojé, dobrótu Jákovľu, júže vozľubí.]),
    gText("6"),
    par([Vzýde Boh v voskliknovéniji, Hospoď vo hlási trúbňi.]),
    gText("7"),
    par([Pójte Bohu nášemu, pójte: pójte cerévi nášemu, pójte:]),
    gText("8"),
    par([Jáko cer vsejá zemlí Boh, pójte razúmno.]),
    gText("9"),
    par([Vocerísja Boh nad jázýki: Boh sidít na prestóľi svjatím svojém.]),
    gText("10"),
    par([Kňázi ľúdstiji sobrášasja s Bohom ávraámlim: jáko Božiji deržávniji zemlí ziló voznesóšasja.]),
    gText("1"),
    sText([Psalóm písni synóv koréovych, vtorýja subbóty, (#translation.at("PSALM") 47)]),
    gText("2"),
    par([Vélij Hospoď í chválen ziló vo hráďi Boha nášeho, v horí svjatíj jéhó,]),
    gText("3"),
    par([Bláhokorénnym rádovanijem vsejá zemlí: hóry Sijónskija, rébra síverova, hrád cerjá velíkaho.]),
    gText("4"),
    par([Boh v ťážesťich #footnote("vo chrámich") jéhó znájem jésť, jéhdá zastupájet í.]),
    gText("5"),
    par([Jáko sé, cárije zémstiji sobrášasja, snidóšasja vkúpi:]),
    gText("6"),
    par([Tíji víďivše táko, údivíšasja, smjatóšasja, podvihóšasja:]),
    gText("7"),
    par([Trépet priját já támo, boľízni jáko raždájuščija.]),
    gText("8"),
    par([Dúchom búrnym sokrušíši korablí tharsíjskija.]),
    gText("9"),
    par([Jákože slýšachom, táko í víďichom vo hráďi Hospoda síl, vo hráďi Boha nášeho: Boh ósnová í v vík.]),
    gText("10"),
    par([Prijáchom, Bože, mílosť tvojú posreďí ľudéj tvojích.]),
    gText("11"),
    par([Po ímeni tvojemú, Bože, táko í chvalá tvojá na koncách zemlí: právdy íspólň desníca tvojá.]),
    gText("12"),
    par([Da vozveselítsja horá Sijónskaja, í da vozrádujutsja dščéri íudéjskija, sudéb rádi tvojích, Hospodi.]),
    gText("13"),
    par([Óbydíte Sijón í óbymíte jéhó, povídite v stolpích jéhó:]),
    gText("14"),
    par([Položíte serdcá váša v sílu jéhó, í razďilíte dómy jéhó, jáko da povíste v róďi íňím.]),
    gText("15"),
    par([Jáko tój jésť Boh náš vo vík í v vík víka: tój úpasét nás vo víki.]),
    gText("1"),
    sText([V konéc, synóm koréovym, psalóm, (#translation.at("PSALM") 48)]),
    gText("2"),
    par([Úslýšite sijá, vsí jázýcy, vnušíte, vsí živúščiji po vselénňij,]),
    gText("3"),
    par([Zemnoródniji že í sýnove čelovíčestiji, vkúpi bohát í úbóh.]),
    gText("4"),
    par([Ústá mojá vozhlahóľut premúdrosť, í poučénije sérdca mojehó rázum.]),
    gText("5"),
    par([Prikloňú v prítču úcho mojé, otvérzu vo psaltíri hanánije mojé.]),
    gText("6"),
    par([Vskúju bojúsja v déň ľút; bezzakónije pjatý mojejá óbýdet mjá.]),
    gText("7"),
    par([Naďíjuščijisja na sílu svojú í ó mnóžestvi bohátstva svojehó chváľaščijisja:]),
    gText("8"),
    par([Brát ne ízbávit, ízbávit li čelovík; ne dást Bohu ízmíny za sjá,]),
    gText("9"),
    par([Í cínu ízbavlénija duší svojejá: í útrudísja v vík,]),
    gText("10"),
    par([Í žív búdet do koncá, ne úzrit páhuby.]),
    gText("11"),
    par([Jéhdá úvídit premúdryja úmirájuščyja, vkúpi bezúmen í nesmýslen pohíbnut, í óstávjat čuždím bohátstvo svojé.]),
    gText("12"),
    par([Í hróbi ích žilíšča ích vo vík, selénija ích v ród í ród, narekóša ímená svojá na zemľách.]),
    gText("13"),
    par([Í čelovík v čésti sýj ne razumí, priložísja skotóm nesmýslennym í úpodóbisja ím.]),
    gText("14"),
    par([Séj púť ích soblázn ím, í po sích vo úsťích svojích bláhovoľát.]),
    gText("15"),
    par([Jáko óvcy vo áďi položéni súť, smérť úpasét já: í óbladájut ími práviji zaútra, í pómošč ích óbetšájet vo áďi: ot slávy svojejá ízrinovéni býša.]),
    gText("16"),
    par([Óbáče Boh ízbávit dúšu mojú íz rukí ádovy, jéhdá prijémlet mjá.]),
    gText("17"),
    par([Ne úbójsja, jéhdá razbohaťíet čelovík, ílí jéhdá úmnóžitsja sláva dómu jéhó:]),
    gText("18"),
    par([Jáko vnehdá úmréti jémú, ne vózmet vsjá, nižé snídet s ním sláva jéhó.]),
    gText("19"),
    par([Jáko dušá jéhó v živoťí jéhó bláhoslovítsja, íspovístsja tebí, jéhdá bláhosotvoríši jémú.]),
    gText("20"),
    par([Vnídet dáže do róda ótéc svojích, dáže do víka ne úzrit svíta.]),
    gText("21"),
    par([Í čelovík v čésti sýj ne razumí, priložísja skotóm nesmýslennym í úpodóbisja ím.]),
    col2(gText([#translation.at("SI")])),
  ))
== #translation.at("ANTIFON") 2
  #generateTable((
    "",
    sText([Psalóm ásáfu, (#translation.at("PSALM") 49)]),
    gText("1"),
    par([Boh bohóv Hospoď hlahóla, í prizvá zémľu ot vostók sólnca do západ.]),
    gText("2"),
    par([Ot Sijóna bláhoľípije krasotý jéhó:]),
    gText("3"),
    par([Boh jávi prijídet, Boh náš, í ne premolčít: óhň pred ním vozhorítsja, í ókrest jéhó búrja zílna.]),
    gText("4"),
    par([Prizovét nébo svýše, í zémľu, razsudíti ľúdi svojá.]),
    gText("5"),
    par([Soberíte jémú prepodóbnyja jéhó, zaviščájuščyja zavít jéhó ó žértvach.]),
    gText("6"),
    par([Í vozvisťát nebesá právdu jéhó: jáko Boh sudijá jésť.]),
    gText("7"),
    par([Úslýšite, ľúdije moí, í vozhlahóľu vám, Izráiľu, í zasviďíteľstvuju tebí: Boh, Boh tvój jésm áz.]),
    gText("8"),
    par([Ne ó žértvach tvojích óbličú ťá, vsesožžénija že tvojá predo mnóju súť výnu:]),
    gText("9"),
    par([Ne prijimú ot dómu tvojehó teľcóv, nižé ot stád tvojích kozlóv.]),
    gText("10"),
    par([Jáko moí súť vsí zvírije dubrávniji, skóti v horách í volóve:]),
    gText("11"),
    par([Poznách vsjá ptícy nebésnyja, í krasotá séľnaja so mnóju jésť.]),
    gText("12"),
    par([Ášče vzálču, ne rekú tebí: mojá bo jésť vselénnaja í íspolnénije jéjá.]),
    gText("13"),
    par([Jédá jám mjasá júnča; ílí króv kozlóv pijú;]),
    gText("14"),
    par([Požrí Bohovi žértvu chvalý í vozdážď výšnemu molítvy tvojá:]),
    gText("15"),
    par([Í prizoví mja v déň skórbi tvojejá, í ízmú ťa, í prosláviši mjá.]),
    gText("16"),
    par([Hríšniku že rečé Boh: vskúju tý povídaješi ópravdánija mojá í vosprijémleši zavít mój ústý tvojími;]),
    gText("17"),
    par([Tý že voznenavíďil jésí nakazánije í otvérhl jésí slovesá mojá vspjáť.]),
    gText("18"),
    par([Ášče víďil jésí táťa, tékl jésí s ním, í s preľuboďíem účástije tvojé polahál jésí:]),
    gText("19"),
    par([Ústá tvojá úmnóžiša zlóbu, í jázýk tvój spletáše ľščénija:]),
    gText("20"),
    par([Siďá na bráta tvojehó klevetál jésí í na sýna mátere tvojejá polahál jésí soblázn.]),
    gText("21"),
    par([Sijá sotvoríl jésí, í úmolčách, voznepščevál jésí bezzakónije, jáko búdu tebí podóben: óbličú ťa í predstávľu pred licém tvojím hrichí tvojá.]),
    gText("22"),
    par([Razumíjte úbo sijá, zabyvájuščiji Boha, da ne kohdá pochítit, í ne búdet ízbavľájaj.]),
    gText("23"),
    par([Žértva chvalý proslávit mjá, í támo púť, ímže jávľú jémú Spasénije mojé.]),
    gText("24"),
    sText([V konéc, psalóm Davidu, vnehdá vníti k nemú nathánu proróku, ]),
    gText("1"),
    sText([Jéhdá vníde k virsavíji žeňí úríevi, (#translation.at("PSALM") 50)]),
    gText("2"),
    par([Pomíluj mjá, Bože, po velícij mílosti tvojéj, í po mnóžestvu ščedrót tvojích óčísti bezzakónije mojé.]),
    gText("3"),
    par([Naipáče ómýj mjá ot bezzakónija mojehó í ot hrichá mojehó óčísti mjá:]),
    gText("4"),
    par([Jáko bezzakónije mojé áz znáju, í hrích mój predo mnóju jésť výnu.]),
    gText("5"),
    par([Tebí jédínomu sohriších í lukávoje pred tobóju sotvorích: jáko da ópravdíšisja vo slovesích tvojích í pobidíši, vnehdá sudíti tí.]),
    gText("6"),
    par([Sé bo, v bezzakónijich začát jésm, í vo hrisích rodí mja máti mojá.]),
    gText("7"),
    par([Sé bo, ístinu vozľubíl jésí, bezvístnaja í tájnaja premúdrosti tvojejá jávíl mí jésí.]),
    gText("8"),
    par([Ókropíši mjá ýssópom, í óčíščusja: ómýeši mjá, í páče sňíha úbiľúsja.]),
    gText("9"),
    par([Slúchu mojemú dási rádosť í vesélije: vozrádujutsja kósti smirénnyja.]),
    gText("10"),
    par([Otvratí licé tvojé ot hrích mojích í vsjá bezzakónija mojá óčísti.]),
    gText("11"),
    par([Sérdce čísto sozíždi vo mňí, Bože, í dúch práv óbnoví vo útróbi mojéj.]),
    gText("12"),
    par([Ne otvérži mené ot licá tvojehó í Dúcha tvojehó svjatáho ne otimí ot mené.]),
    gText("13"),
    par([Vozdážď mí rádosť Spasénija tvojehó í Dúchom Vladíčinim útverdí mja.]),
    gText("14"),
    par([Naučú bezzakónnyja putém tvoím, í nečestíviji k tebí óbraťátsja.]),
    gText("15"),
    par([Ízbávi mjá ot krovéj, Bože, Bože Spasénija mojehó: vozrádujetsja jázýk mój právďi tvojéj.]),
    gText("16"),
    par([Hospodi, ústňí moí otvérzeši, í ústá mojá vozvisťát chvalú tvojú.]),
    gText("17"),
    par([Jáko ášče by voschoťíl jésí žértvy, dál bých úbo: vsesožžénija ne bláhovolíši.]),
    gText("18"),
    par([Žértva Bohu dúch sokrušén: sérdce sokrušénno í smirénno Boh ne úničižít.]),
    gText("19"),
    par([Úbláží, Hospodi, bláhovolénijem tvojím Sijóna, í da sozíždutsja sťíny Jerúsaľímskija:]),
    gText("20"),
    par([Tohdá bláhovolíši žértvu právdy, voznošénije í vsesožeháemaja: tohdá vozložát na óltár tvój teľcý.]),
    col2(gText([#translation.at("SI")])),
  ))
== #translation.at("ANTIFON") 3
  #generateTable((
    gText("21"),
    sText([V konéc, rázuma Davidu, ]),
    gText("1"),
    sText([Vnehdá prijití doíku íduméjsku, í vozvistíti saúlu, í reščí jémú: prijíde David v dóm ávijmeléchov, (#translation.at("PSALM") 51)]),
    gText("2"),
    par([Čtó chválišisja vo zlóbi, síľne; bezzakónije vés déň,]),
    gText("3"),
    par([Neprávdu úmýsli jázýk tvój: jáko brítvu ízoščrénu sotvoríl jésí lésť.]),
    gText("4"),
    par([Vozľubíl jésí zlóbu páče bláhostýni, neprávdu néže hlahólati právdu:]),
    gText("5"),
    par([Vozľubíl jésí vsjá hlahóly potópnyja, jázýk ľstív.]),
    gText("6"),
    par([Sehó rádi Boh razrušít ťá do koncá: vostórhnet ťá, í preselít ťá ot selénija tvojehó í kóreň tvój ot zemlí živých.]),
    gText("7"),
    par([Úzrjat právedniji í úbojátsja, í ó ném vozsmijútsja í rekút:]),
    gText("8"),
    par([Sé, čelovík, íže ne položí Boha pomóščnika sebí, no úpová na mnóžestvo bohátstva svojehó, í vozmóže sujetóju svojéju.]),
    gText("9"),
    par([Áz že jáko máslina plodovíta v domú Božiji: úpovách na mílosť Božiju vo vík í v vík víka.]),
    gText("10"),
    par([Íspovímsja tebí v vík, jáko sotvoríl jésí: í terpľú ímja tvojé, jáko bláho pred prepodóbnymi tvojími.]),
    gText("1"),
    sText([V konéc, ó majeléthi, rázuma Davidu, (#translation.at("PSALM") 52)]),
    gText("2"),
    par([Rečé bezúmen v sérdcy svojém: ňísť Boh. Rastľíša í ómerzíšasja v bezzakónijich, ňísť tvorjáj bláhóje.]),
    gText("3"),
    par([Boh s nebesé priníče na sýny čelovíčeskija, víďiti, ášče jésť razumivájaj ílí vzyskájaj Boha.]),
    gText("4"),
    par([Vsí úkloníšasja, vkúpi nepotrébni býša: ňísť tvorjáj bláhóje, ňísť do jédínaho.]),
    gText("5"),
    par([Ni lí úrazumíjut vsí ďílajuščiji bezzakónije, sňidájuščiji ľúdi mojá v sňíď chľíba; Hospoda ne prizváša.]),
    gText("6"),
    par([Támo ústrašíšasja strácha, íďíže ne bí strách: jáko Boh razsýpa kósti čelovikouhódnikov: postyďíšasja, jáko Boh úničiží ích.]),
    gText("7"),
    par([Któ dást ot Sijóna Spasénije Izráilevo; vnehdá vozvratít Boh pľinénije ľudéj svojích, vozrádujetsja Jákov í vozveselítsja Izráiľ.]),
    gText("8"),
    par([V konéc, v písnech rázuma Davidu,]),
    gText("9"),
    par([Vnehdá prijití zijféem í reščí saúlovi: ne sé li, David skrýsja v]),
    "",
    sText([nás; (#translation.at("PSALM") 53)]),
    gText("1"),
    par([Bože, vo ímja tvojé Spasí mja í v síľi tvojéj sudí mi.]),
    gText("2"),
    par([Bože, úslýši molítvu mojú, vnuší hlahóly úst mojích:]),
    gText("3"),
    par([Jáko čúždiji vostáša na mjá, í krípcyi vzyskáša dúšu mojú, í ne predložíša Boha pred sobóju.]),
    gText("4"),
    par([Sé bo, Boh pomohájet mí, í Hospoď zastúpnik duší mojéj:]),
    gText("5"),
    par([Otvratít zlája vrahóm moím: ístinoju tvojéju potrebí ích.]),
    gText("6"),
    par([Vóleju požrú tebí, íspovímsja ímeni tvojemú, Hospodi, jáko bláho:]),
    gText("7"),
    par([Jáko ot vsjákija pečáli ízbávil mjá jésí, í na vrahí mojá vozzrí óko mojé.]),
    gText("1"),
    sText([V konéc, v písnech rázuma, ásáfu, psalóm, (#translation.at("PSALM") 54)]),
    gText("2"),
    par([Vnuší, Bože, molítvu mojú í ne prézri molénija mojehó:]),
    gText("3"),
    par([Vonmí mi í úslýši mjá: vozskorbích pečáliju mojéju #footnote("vo ískušéniji mojém"), í smjatóchsja]),
    gText("4"),
    par([Ot hlása vrážija í ot stužénija hríšniča: jáko úkloníša na mjá bezzakónije í vo hňívi vraždováchu mí.]),
    gText("5"),
    par([Sérdce mojé smjatésja vo mňí, í bojázň smérti napadé na mjá:]),
    gText("6"),
    par([Strách í trépet prijíde na mjá, í pokrý mja tmá.]),
    gText("7"),
    par([Í rích: któ dást mí kriľí jáko holubíňi; í poleščú, í počíju.]),
    gText("8"),
    par([Sé, údalíchsja bíhaja í vodvoríchsja v pustýni.]),
    gText("9"),
    par([Čájach Boha Spasájuščaho mjá ot malodúšija í ot búri.]),
    gText("10"),
    par([Potopí, Hospodi, í razďilí jázýki ích: jáko víďich bezzakónije í prerikánije vo hráďi.]),
    gText("11"),
    par([Dném í nóščiju óbýdet í po sťinám jéhó: bezzakónije í trúd posreďí jéhó, í neprávda:]),
    gText("12"),
    par([Í ne óskuďí ot stóhn jéhó líchva í lésť.]),
    gText("13"),
    par([Jáko ášče by vráh ponosíl mí, preterpíl bých úbo: í ášče by nenavíďaj mjá na mjá veleríčeval, úkrýl bých sja ot nehó.]),
    gText("14"),
    par([Tý že, čelovíče ravnodúšne, vladýko mój í znájemyj mój,]),
    gText("15"),
    par([Íže kúpno naslaždálsja jésí so mnóju brášen: v domú Božiji chodíchom jédinomyšlénijem.]),
    gText("16"),
    par([Da prijídet že smérť na ňá, í da snídut vo ád žívi: jáko lukávstvo v žilíščach ích, posreďí ích.]),
    gText("17"),
    par([Áz k Bohu vozzvách, í Hospoď úslýša mjá.]),
    gText("18"),
    par([Véčer í zaútra í polúdne povím í vozviščú, í úslýšit hlás mój.]),
    gText("19"),
    par([Ízbávit mírom dúšu mojú ot približájuščichsja mňí: jáko vo mnózi bjáchu so mnóju.]),
    gText("20"),
    par([Úslýšit Boh, í smirít já sýj préžde vík: ňísť bo ím ízminénija, jáko ne úbojášasja Boha.]),
    gText("21"),
    par([Prostré rúku svojú na vozdajánije: óskverníša zavít jéhó.]),
    gText("22"),
    par([Razďilíšasja ot hňíva licá jéhó, í priblížišasja serdcá ích: úmjáknuša slovesá ích páče jéléa, í tá súť stríly.]),
    gText("23"),
    par([Vozvérzi na Hospoda pečáľ tvojú, í tój ťá prepitájet: ne dást v vík molvý právedniku.]),
    gText("24"),
    par([Tý že, Bože, nizvedéši ích v studenéc ístľínija: múžije krovéj í ľstí ne prepolovját dníj svojích. Áz že, Hospodi, úpováju na ťá.]),
    col2(gText([#translation.at("SI")])),
  ))
  #generateTable((
    col2(sText(translation.at("AFTER_KAFTIZMA"))),
    sText("T"),
    jObj4("",5, "", "Sudijí siďášču í Anhelom stojáščym, trubí hlasjáščej, plámeni horjášču, čtó sotvoríši dušé mojá, vedóma na súd; tohdá bo ľútaja tvojá predstánut, í tájnaja óbličátsja sohrišénija. ťímže préžde koncá vozopíj sudijí: Bože óčísti mjá, í Spasí mja."),
    
    // S:
    col2(gText(translation.at("S"))),
    "",
    jObj4("",none, "", "Vsí pobdím, í Christá úsrjáščim so mnóžestvom jéléa, í sviščámi svítlymi, jáko da čertóha vnútr spodóbimsja. íže bo vňí dveréj postíhnuvyj, bezďíľno Bohovi vozzovét: pomíluj mjá."),
    
    // I:
    col2(gText(translation.at("IN"))),
    "",
    jObj4("",none, "", "Na ódrí ležá sohrišénij mnóhich, ókradájem jésm v nadéždi Spasénija mojehó: íbo són mojejá ľínosti chodátajstvujet duší mojéj múku. no tý Bože roždéjsja ot Ďivy, vozdvíhni mjá k tvojemú píniju, da slávľu ťá."),
    col2(translation.at("HOSPODI_POMILUJ")+". "+sText("(40)")),
    col2(sText(translation.at("MOLITVA"))),
    "",
    jObj4("",none, "", "Hospodi Bože mój, jáko bláh í čelovikoľúbec, mnóhija mílosti sotvoríl jésí so mnóju, jáže ne čájach víďiti, í čtó vozdám tvojéj bláhosti, Hospodi mój Hospodi; bláhodarjú tvojé mnohopítoje ímja: bláhodarjú tvojé neispovidímoje na mňí bláhoutróbije: bláhodarjú bezprikládnoje tvojé dolhoterpínije. í ot nýňi zastupí, í pomozí mňí, í pokrýj mjá Vladýko ot vsích, jéže ne ktomú sohrišáti pred tobóju: tý bo vísi jéstestvá mojehó údobopopolznovénnoje, tý vísi bezúmije mojé, tý vísi mnóju soďíjannaja, jáže v víďiniji í ne v víďiniji, jáže vóľnaja í nevóľnaja, jáže v noščí í vo dní, í vo úmí í mýsli: jáko bláh úbo í čelovikoľúbec Boh, óčísti já rosóju mílosti tvojejá prebláhíj Hospodi, í Spasí nás ímene rádi tvojehó svjatáho, ímiže vísi suďbámi. tý bo jésí svít, í ístina, í živót: í tebí slávu vozsylájem, Ótcú, í Sýnu, í svjatómu Dúchu, nýňi í prísno, í vo víki vikóv, ámíň."),
  ))
])
