#import "../../../../all.typ": *
= #translation.at("KAFTIZMA") 8

#columns(2, gutter: 2pt, [

== #translation.at("ANTIFON") 1
  #generateTable((
    gText("1"),
    sText([V konéc, ó ľúdech ot svjatých údalénnych, Davidu v stolpopisánije, vnehdá úderžáša í ínopleménnicy v héthi, psalóm, (#translation.at("PSALM") 55)]),
    gText("2"),
    par([Pomíluj mjá, Bože, jáko poprá mja čelovík: vés déň borjá stuží mi.]),
    gText("3"),
    par([Popráša mjá vrazí moí vés déň: jáko mnózi borjúščiji mjá s vysotý.]),
    gText("4"),
    par([V déň ne úbojúsja #footnote("séj ríči ne, v ňíkijich ne ímíetsja "), áz že úpováju na ťá.]),
    gText("5"),
    par([Ó Bózi pochvaľú slovesá mojá: na Boha úpovách, ne úbojúsja: čtó sotvorít mňí plóť;]),
    gText("6"),
    par([Vés déň slovés mojích hnušáchusja: na mjá vsjá pomyšlénija ích na zló.]),
    gText("7"),
    par([Vseľátsja í skrýjut, tíji pjátu mojú sochraňát, jákože poterpíša dúšu mojú #footnote("tíji pjátu mojú nabľudáti búdut, jákože ždáchu duší mojejá").]),
    gText("8"),
    par([Ni ó česóm že otríneši já, hňívom ľúdi nizvedéši.]),
    gText("9"),
    par([Bože, živót mój vozvistích tebí: položíl jésí slézy mojá pred tobóju, jáko í vo óbitovániji tvojém.]),
    gText("10"),
    par([Da vozvraťátsja vrazí moí vspjáť, vóňže ášče déň prizovú ťa: sé, poznách, jáko Boh mój jésí tý.]),
    gText("11"),
    par([Ó Bózi pochvaľú hlahól, ó Hospodi pochvaľú Slóvo.]),
    gText("12"),
    par([Na Boha úpovách, ne úbojúsja: čtó sotvorít mňí čelovík;]),
    gText("13"),
    par([Vo mňí, Bože, molítvy, jáže vozdám chvalý tvojejá:]),
    gText("14"),
    par([Jáko ízbávil jésí dúšu mojú ot smérti, óči moí ot sléz í nózi moí ot popolznovénija: bláhouhoždú pred Hospodem vo svíťi živých.]),
    gText("15"),
    par([V konéc, da ne rastlíši, Davidu v stolpopisánije, vnehdá jémú]),
    "",
    sText([otbiháti ot licá saúlova v peščéru, (#translation.at("PSALM") 56)]),
    gText("1"),
    par([Pomíluj mjá, Bože, pomíluj mjá: jáko na ťá úpová dušá mojá, í na síň krilú tvoéju naďíjusja, dóndeže préjdet bezzakónije.]),
    gText("2"),
    par([Vozzovú k Bohu výšnemu, Bohu bláhoďíjavšemu mňí.]),
    gText("3"),
    par([Poslá s nebesé í Spasé mja, dadé v ponošénije popirájuščyja mjá: poslá Boh mílosť svojú í ístinu svojú,]),
    gText("4"),
    par([Í ízbávi dúšu mojú ot sredý skýmnov. Pospách smuščén: sýnove čelovíčestiji, zúby ích órúžija í stríly, í jázýk ích méč óstr.]),
    gText("5"),
    par([Voznesísja na nebesá, Bože, í po vséj zemlí sláva tvojá.]),
    gText("6"),
    par([Síť úhotóvaša nohám moím, í sľakóša dúšu mojú: ískopáša pred licém mojím jámu, í vpadóša v ňú.]),
    gText("7"),
    par([Hotóvo sérdce mojé, Bože, hotóvo sérdce mojé: vospojú í pojú vo slávi mojéj.]),
    gText("8"),
    par([Vostáni, sláva mojá, vostáni, psaltírju í húsli: vostánu ráno.]),
    gText("9"),
    par([Íspovímsja tebí v ľúdech, Hospodi, vospojú tebí vo jázýcich:]),
    gText("10"),
    par([Jáko vozvelíčisja do nebes mílosť tvojá í dáže do óblak ístina tvojá.]),
    gText("11"),
    par([Voznesísja na nebesá, Bože, í po vséj zemlí sláva tvojá.]),
    gText("1"),
    sText([V konéc, da ne rastlíši, Davidu v stolpopisánije, (#translation.at("PSALM") 57)]),
    gText("2"),
    par([Ášče vojístinnu úbo právdu hlahólete, právaja sudíte, sýnove čelovíčestiji.]),
    gText("3"),
    par([Íbo v sérdcy bezzakónije ďílajete na zemlí, neprávdu rúki váša spletájut.]),
    gText("4"),
    par([Óčuždíšasja hríšnicy ot ložésn, zabludíša ot čréva, hlahólaša lžú.]),
    gText("5"),
    par([Járosť ích po podóbiju zmijinú, jáko áspijda hlúcha í zatykájuščaho úši svoí,]),
    gText("6"),
    par([Íže ne úslýšit hlása óbavájuščich, óbavájem óbavájetsja ot premúdra.]),
    gText("7"),
    par([Boh sokrušít zúby ích vo úsťích ích: členóvnyja ľvóv sokrušíl jésť Hospoď.]),
    gText("8"),
    par([Úničižátsja jáko vodá mimotekúščaja: naprjažét lúk svój, dóndeže íznemóhut.]),
    gText("9"),
    par([Jáko vósk rastájav otímutsja: padé óhň na ních, í ne víďiša sólnca.]),
    gText("10"),
    par([Préžde jéže razumíti térnija vášeho rámna, jáko žívy, jáko vo hňívi požrét já.]),
    gText("11"),
    par([Vozveselítsja právednik, jéhdá úvídit otmščénije: rúci svoí úmýet v króvi hríšnika.]),
    gText("12"),
    par([Í rečét čelovík: ášče úbo jésť plód právedniku, úbo jésť Boh suďá ím na zemlí.]),
    col2(gText([#translation.at("SI")])),
  ))
== #translation.at("ANTIFON") 2
  #generateTable((
    gText("1"),
    sText([V konéc, da ne rastlíši, Davidu v stolpopisánije, vnehdá poslá saúl í strežé dóm jéhó, jéže úmertvíti jéhó, (#translation.at("PSALM") 58)]),
    gText("2"),
    par([Ízmí mja ot vráh mojích, Bože, í ot vostajúščich na mjá ízbávi mjá:]),
    gText("3"),
    par([Ízbávi mjá ot ďílajuščich bezzakónije, í ot múž krovéj Spasí mja.]),
    gText("4"),
    par([Jáko sé, úlovíša dúšu mojú, napadóša na mjá krípcyi: nižé bezzakónije mojé, nižé hrích mój, Hospodi:]),
    gText("5"),
    par([Bez bezzakónija tekóch í ísprávich: vostáni v srítenije mojé í vížď.]),
    gText("6"),
    par([Í tý, Hospodi Bože síl, Bože Izráilev, vonmí positíti vsjá jázýki: da ne úščédriši vsjá ďílajuščyja bezzakónije.]),
    gText("7"),
    par([Vozvraťátsja na véčer, í vzálčut jáko pés, í óbýdut hrád.]),
    gText("8"),
    par([Sé, tíji otviščájut ústý svojími, í méč vo ústnách ích: jáko któ slýša;]),
    gText("9"),
    par([Í tý, Hospodi, posmiéšisja ím, úničižíši vsjá jázýki.]),
    gText("10"),
    par([Deržávu mojú k tebí sochraňú: jáko tý, Bože, zastúpnik mój jésí.]),
    gText("11"),
    par([Boh mój, mílosť jéhó predvarít mjá: Boh mój, jávít mňí na vrazích mojích.]),
    gText("12"),
    par([Ne úbíj ích, da ne kohdá zabúdut zakón tvój: rastočí já síloju tvojéju í nizvedí já, zaščítniče mój, Hospodi,]),
    gText("13"),
    par([rích úst ích, Slóvo ústén ích: í játi da búdut v hordýni svojéj, í ot kľátvy í lží vozvisťátsja v končíňi,]),
    gText("14"),
    par([Vo hňívi končíny, í ne búdut: í úvíďat, jáko Boh Vladíčiestvujet Jákovom í koncý zemlí.]),
    gText("15"),
    par([Vozvraťátsja na véčer, í vzálčut jáko pés, í óbýdut hrád:]),
    gText("16"),
    par([Tíji razýdutsja jásti: ášče li že ne nasýťatsja, í porópščut.]),
    gText("17"),
    par([Áz že vospojú sílu tvojú í vozrádujusja zaútra ó mílosti tvojéj: jáko býl jésí zastúpnik mój í pribížišče mojé v déň skórbi mojejá.]),
    gText("18"),
    par([Pomóščnik mój jésí, tebí pojú: jáko Boh zastúpnik mój jésí, Bože mój, mílosť mojá.]),
    gText("19"),
    par([V konéc, ó ízminítisja choťáščich, v stolpopisánije Davidu, v naučénije:]),
    gText("20"),
    par([Vnehdá sožžé sredoríčije syríjskoje í syríju soválskuju, í]),
    "",
    sText([vozvratísja íoáv í porazí jédóma v débri soléj dvanádesjať týsjašč, (#translation.at("PSALM") 59)]),
    gText("1"),
    par([Bože, otrínul ný jésí í nizložíl jésí nás, razhňívalsja jésí í úščédril jésí nás.]),
    gText("2"),
    par([Strjásl jésí zémľu í smutíl jésí jú: íscilí sokrušénije jéjá, jáko podvížesja.]),
    gText("3"),
    par([Pokazál jésí ľúdem tvoím žestókaja: napojíl jésí nás vijnóm úmilénija.]),
    gText("4"),
    par([Dál jésí bojáščymsja tebé známenije, jéže úbižáti ot licá lúka.]),
    gText("5"),
    par([Jáko da ízbávjatsja vozľúblenniji tvoí, Spasí desníceju tvojéju í úslýši mjá.]),
    gText("6"),
    par([Boh vozhlahóla vo svjatím svojém: vozrádujusja, í razďiľú sijkímu, í júdóľ žilíšč razmírju.]),
    gText("7"),
    par([Mój jésť halaád, í mój jésť manassíj, jéfrém kríposť hlavý mojejá, íúda cár mój.]),
    gText("8"),
    par([Moáv konób úpovánija mojehó: na íduméju prostrú sapóh mój: mňí ínopleménnicy pokoríšasja.]),
    gText("9"),
    par([Któ vvedét mjá vo hrád óhraždénija; ílí któ nastávit mjá do íduméi;]),
    gText("10"),
    par([Ne tý li, Bože, otrínuvyj nás; í ne ízýdeši, Bože, v sílach nášich;]),
    gText("11"),
    par([Dážď nám pómošč ot skórbi: í sújetno spasénije čelovíčesko.]),
    gText("12"),
    par([Ó Bózi sotvorím sílu: í tój úničižít stužájuščyja nám.]),
    gText("1"),
    sText([V konéc, v písnech, Davidu psalóm, (#translation.at("PSALM") 60)]),
    gText("2"),
    par([Úslýši, Bože, molénije mojé, vonmí molítvi mojéj:]),
    gText("3"),
    par([Ot konéc zemlí k tebí vozzvách, vnehdá úný sérdce mojé: na kámeň voznésl mjá jésí, nastávil mjá jésí,]),
    gText("4"),
    par([Jáko býl jésí úpovánije mojé, stólp kríposti ot licá vrážija.]),
    gText("5"),
    par([Vseľúsja v seléniji tvojém vo víki, pokrýjusja v króvi kríl tvojích.]),
    gText("6"),
    par([Jáko tý, Bože, úslýšal jésí molítvy mojá, dál jésí dostojánije bojáščymsja ímene tvojehó.]),
    gText("7"),
    par([Dní na dní carévy priložíši, ľíta jéhó do dné róda í róda.]),
    gText("8"),
    par([Prebúdet v vík pred Bohom: mílosť í ístinu jéhó któ vzýščet;]),
    gText("9"),
    par([Táko vospojú ímeni tvojemú vo víki, vozdáti mí molítvy mojá déň ot dné.]),
    col2(gText([#translation.at("SI")])),
  ))
== #translation.at("ANTIFON") 3
  #generateTable((
    gText("1"),
    sText([V konéc, ó ídijthúmi, psalóm Davidu, (#translation.at("PSALM") 61)]),
    gText("2"),
    par([Ne Bohu li povinétsja dušá mojá; ot tohó bo Spasénije mojé.]),
    gText("3"),
    par([Íbo tój Boh mój í Spas mój, zastúpnik mój: ne podvížusja naipáče.]),
    gText("4"),
    par([Dokóľi naležité na čelovíka; úbivájete vsí vý, jáko sťiňí preklonéňi í óplótu vozrinovénu.]),
    gText("5"),
    par([Óbáče cínu mojú soviščáša otrínuti, tekóša v žáždi: ústý svojími bláhoslovľáchu, í sérdcem svojím kleňáchu.]),
    gText("6"),
    par([Óbáče Bohovi povinísja, dušé mojá: jáko ot tohó terpínije mojé.]),
    gText("7"),
    par([Íbo tój Boh mój í Spas mój, zastúpnik mój: ne preseľúsja.]),
    gText("8"),
    par([Ó Bózi Spasénije mojé í sláva mojá: Boh pómošči mojejá, í úpovánije mojé na Boha.]),
    gText("9"),
    par([Úpovájte na nehó, vés sónm ľudéj: ízlijájte pred ním serdcá váša, jáko Boh pomóščnik náš.]),
    gText("10"),
    par([Óbáče sújetni sýnove čelovíčestiji, lžívi sýnove čelovíčestiji v míriľich jéže neprávdovati: tíji ot sujetý vkúpi.]),
    gText("11"),
    par([Ne úpovájte na neprávdu, í na voschiščénije ne želájte: bohátstvo ášče tečét, ne prilahájte sérdca.]),
    gText("12"),
    par([Jédínoju hlahóla Boh, dvója sijá slýšach, zané deržáva Božija,]),
    gText("13"),
    par([Í tvojá, Hospodi, mílosť: jáko tý vozdási komúždo po ďilóm jéhó.]),
    gText("1"),
    sText([Psalóm Davidu, vnehdá býti jémú v pustýni íudéjsťij, (#translation.at("PSALM") 62)]),
    gText("2"),
    par([Bože, Bože mój, k tebí útreňuju: vozžadá tebé dušá mojá, kóľ mnóžiceju tebí plóť mojá, v zemlí púsťi í neprochódňi í bezvódňi.]),
    gText("3"),
    par([Táko vo svjatím jávíchsja tebí, víďiti sílu tvojú í slávu tvojú.]),
    gText("4"),
    par([Jáko lúčši mílosť tvojá páče živót: ústňí moí pochvalíťi ťá.]),
    gText("5"),
    par([Táko bláhoslovľú ťa v živoťí mojém í ó ímeni tvojém vozďižú rúci moí.]),
    gText("6"),
    par([Jáko ot túka í másti da íspólnitsja dušá mojá, í ústnáma rádosti voschváľat ťá ústá mojá.]),
    gText("7"),
    par([Ášče pominách ťá na postéli mojéj, na útrennich poučáchsja v ťá:]),
    gText("8"),
    par([Jáko býl jésí pomóščnik mój, í v króvi krilú tvoéju vozrádujusja.]),
    gText("9"),
    par([Priľpé dušá mojá po tebí: mené že priját desníca tvojá.]),
    gText("10"),
    par([Tíji že vsúje ískáša dúšu mojú: vnídut v preispódňaja zemlí:]),
    gText("11"),
    par([Predaďátsja v rúki órúžija, části lísovom búdut.]),
    gText("12"),
    par([Cár že vozveselítsja ó Bózi: pochválitsja vsják klenýjsja ím, jáko zahradíšasja ústá hlahóľuščich neprávednaja.]),
    gText("1"),
    sText([V konéc, psalóm Davidu, (#translation.at("PSALM") 63)]),
    gText("2"),
    par([Úslýši, Bože, hlás mój, vnehdá molíti mi sja k tebí: ot strácha vrážija ízmí dúšu mojú.]),
    gText("3"),
    par([Pokrýj mjá ot sónma lukávnujuščich, ot mnóžestva ďílajuščich neprávdu:]),
    gText("4"),
    par([Íže ízostríša jáko méč jázýki svojá, naprjahóša lúk svój, véšč hórku,]),
    gText("5"),
    par([Sostriľáti v tájnych neporóčna: vnezápu sostriľájut jéhó, í ne úbojátsja.]),
    gText("6"),
    par([Útverdíša sebí Slóvo lukávoje: povídaša skrýti síť, ríša: któ úzrit ích;]),
    gText("7"),
    par([Íspytáša bezzakónije: ísčezóša íspytájuščiji íspytánija: pristúpit čelovík, í sérdce hlubokó.]),
    gText("8"),
    par([Í voznesétsja Boh: stríly mladénec býša jázvy ích,]),
    gText("9"),
    par([Í íznemohóša na ňá jázýcy ích: smutíšasja vsí víďaščiji ích.]),
    gText("10"),
    par([Í úbojásja vsják čelovík: í vozvistíša ďilá Božija, í tvorénija jéhó razumíša.]),
    gText("11"),
    par([Vozveselítsja právednik ó Hospodi í úpovájet na nehó: í pochváľatsja vsí práviji sr-d*cem.]),
    col2(gText([#translation.at("SI")])),
  ))
  #generateTable((
    col2(sText(translation.at("AFTER_KAFTIZMA"))),
    sText("T"),
    jObj4("",5, "", "Vo hlubiný mjá hrichá popólzšasja, trevolnénije óburevájet otčájanija: no predvarí Christé, jáko vsesílen úpráviteľu vsích, í ko pristánišču tíchomu ústremí bezstrástija, za bláhoutróbije Spase, í Spasí mja."),
    
    // S:
    col2(gText(translation.at("S"))),
    "",
    jObj4("",none, "", "Dušé, jáže zďí privrémenna, támo že víčna: zrjú sudílišče, í na prestóľi sudijú, í trepéšču ízrečénija. próčeje dušé óbratísja, súd neproščájem."),
    
    // I:
    col2(gText(translation.at("IN"))),
    "",
    jObj4("",none, "", "Nadéžde nenaďíemych, pómošče bezpomóščnych, zastuplénije na ťá úpovájuščich, svjatája Vladíčice Bohoródice, pómošč tvojú nizposlí nám."),
    col2(translation.at("HOSPODI_POMILUJ")+". "+sText("(40)")),
    col2(sText(translation.at("MOLITVA"))),
    "",
    jObj4("",none, "", "Hospodi ščédryj, í mílostivyj, dolhoterpilíve í mnohomílostive, vnuší molitvu, í vonmí hlásu molénija mojehó, sotvorí so mnóju známenije vo bláho, nastávi mjá na púť tvój, jéže chodíti vo ístiňi tvojéj: vozveselí sérdce mojé, vo jéže bojátisja ímene tvojehó svjatáho. Zanéže vélij jésí, í tvorjáj čudesá, tý jésí Boh jédín, í ňísť podóben tebí v bozích Hospodi, síľnyj v mílosti, í bláhíj v kríposti, vo jéže pomoháti, í úťišáti, í Spasáti vsjá úpovájuščyja na ímja tvojé, Ótcá, í Sýna, í svjatáho Dúcha, nýňi í prísno, í vo víki vikóv, ámíň."),
  ))
])
