#import "../../../../all.typ": *
= #translation.at("KAFTIZMA") 9

#columns(2, gutter: 2pt, [

== #translation.at("ANTIFON") 1
  #generateTable((
    gText("1"),
    sText([V konéc, psalóm písni Davidu, písň íeremíeva í íezekíjileva, ľudéj preselénija, jéhdá choťáchu íschodíti, (#translation.at("PSALM") 64)]),
    gText("2"),
    par([Tebí podobájet písň, Bože, v sijóňi, í tebí vozdástsja molítva vo Jerúsaľími.]),
    gText("3"),
    par([Úslýši molítvu mojú: k tebí vsjáka plóť prijídet.]),
    gText("4"),
    par([Slovesá bezzakónnik premohóša nás: í nečéstija náša tý óčístiši.]),
    gText("5"),
    par([Blážén, jéhóže ízbrál jésí í prijál, vselítsja vo dvórich tvojích. Íspólnimsja vo bláhích dómu tvojehó: svjat chrám tvój.]),
    gText("6"),
    par([Díven v právďi, úslýši ný, Bože, Spasíteľu náš, úpovánije vsích koncéj zemlí í súščich v móri daléče:]),
    gText("7"),
    par([Úhotovľájaj hóry krípostiju svojéju, prepojásan síloju:]),
    gText("8"),
    par([Smuščájaj hlubinú morskúju, šúmu vóln jéhó któ postojít; smjatútsja jázýcy,]),
    gText("9"),
    par([Í úbojátsja živúščiji v koncách ot známenij tvojích: íschódy útra í véčera úkrasíši.]),
    gText("10"),
    par([Positíl jésí zémľu í úpojíl jésí jú, úmnóžil jésí óbohatíti jú: riká Božija napólnisja vód: úhotóval jésí píšču ím, jáko táko (ésť) úhotóvanije.]),
    gText("11"),
    par([Brazdý jéjá úpój, úmnóži žíta jéjá: v kápľach jéjá vozveselítsja vozsijájušči #footnote("prozjabájušči").]),
    gText("12"),
    par([Bláhoslovíši vinéc ľíta bláhosti tvojejá, í poľá tvojá íspólňatsja túka:]),
    gText("13"),
    par([Razboťíjut krásnaja pustýni, í rádostiju chólmi prepojášutsja.]),
    gText("14"),
    par([Óďíjašasja óvni óvčiji, í údólija úmnóžat pšenícu: vozzovút, íbo vospojút.]),
    gText("1"),
    sText([V konéc, písň psalmá voskresénija, (#translation.at("PSALM") 65)]),
    gText("2"),
    par([Vosklíknite Hospodevi vsjá zemľá, pójte že ímeni jéhó, dadíte slávu chvaľí jéhó.]),
    gText("3"),
    par([Rcýte Bohu: kóľ strášna ďilá tvojá; vo mnóžestvi síly tvojejá sólžut tebí vrazí tvoí.]),
    gText("4"),
    par([Vsjá zemľá da poklónitsja tebí í pojét tebí, da pojét že ímeni tvojemú, výšnij.]),
    gText("5"),
    par([Prijidíte í vídite ďilá Božija, kóľ strášen v sovíťich páče synóv čelovíčeskich.]),
    gText("6"),
    par([Óbraščájaj móre v súšu, v ricí prójdut nohámi: támo vozveselímsja ó ném,]),
    gText("7"),
    par([Vladíčiestvujuščem síloju svojéju víkom: óči jéhó na jázýki prizirájeťi: preohorčevájuščiji da ne voznósjatsja v sebí.]),
    gText("8"),
    par([Bláhoslovíte, jázýcy, Boha nášeho, í úslýšan sotvoríte hlás chvalý jéhó,]),
    gText("9"),
    par([Polóžšaho dúšu mojú v živót, í ne dávšaho vo smjaténije nóh mojích.]),
    gText("10"),
    par([Jáko ískusíl ný jésí, Bože, razžéhl ný jésí, jákože razžizájetsja srebró.]),
    gText("11"),
    par([Vvél ný jésí v síť, položíl jésí skórbi na chrebťí nášem.]),
    gText("12"),
    par([Vozvél jésí čelovíki na hlavý náša: proidóchom skvozí óhň í vódu, í ízvél jésí ný v pokój.]),
    gText("13"),
    par([Vnídu v dóm tvój so vsesožžénijem, vozdám tebí molítvy mojá,]),
    gText("14"),
    par([Jáže ízrekósťi ústňí moí, í hlahólaša ústá mojá v skórbi mojéj.]),
    gText("15"),
    par([Vsesožžénija túčna voznesú tebí s kadílom, í óvný, voznesú tebí volý s kozlý.]),
    gText("16"),
    par([Prijidíte, úslýšite, í povím vám, vsí bojáščijisja Boha, jélíka sotvorí duší mojéj.]),
    gText("17"),
    par([K nemú ústý mojími vozzvách, í voznesóch pod jázýkom mojím.]),
    gText("18"),
    par([Neprávdu ášče úzrích v sérdcy mojém, da ne úslýšit mené Hospoď.]),
    gText("19"),
    par([Sehó rádi úslýša mjá Boh, vňát hlásu molénija mojehó.]),
    gText("20"),
    par([Bláhoslovén Boh, íže ne otstávi molítvu mojú í mílosť svojú ot mené.]),
    gText("1"),
    sText([V konéc, v písnech, psalóm písni Davidu, (#translation.at("PSALM") 66)]),
    gText("2"),
    par([Bože, úščédri ný í bláhosloví ny, prosvití licé tvojé na ný í pomíluj ný:]),
    gText("3"),
    par([Poznáti na zemlí púť tvój, vo vsích jázýcich Spasénije tvojé.]),
    gText("4"),
    par([Da íspovíďatsja tebí ľúdije, Bože, da íspovíďatsja tebí ľúdije vsí.]),
    gText("5"),
    par([Da vozveseľátsja í da vozrádujutsja jázýcy: jáko súdiši ľúdem pravotóju, í jázýki na zemlí nastáviši.]),
    gText("6"),
    par([Da íspovíďatsja tebí ľúdije, Bože, da íspovíďatsja tebí ľúdije vsí.]),
    gText("7"),
    par([Zemľá dadé plód svój: bláhosloví ny, Bože, Bože náš,]),
    gText("8"),
    par([Bláhosloví ny, Bože: í da úbojátsja jéhó vsí koncý zemlí.]),
    col2(gText([#translation.at("SI")])),
  ))
== #translation.at("ANTIFON") 2
  #generateTable((
    gText("1"),
    sText([V konéc, psalóm písni Davidu, (#translation.at("PSALM") 67)]),
    gText("2"),
    par([Da voskresénet Boh, í rastočátsja vrazí jéhó, í da bižát ot licá jéhó nenavíďaščiji jéhó.]),
    gText("3"),
    par([Jáko ísčezájet dým, da ísčéznut: jáko tájet vósk ot licá óhňá, táko da pohíbnut hríšnicy ot licá Božija:]),
    gText("4"),
    par([Á právednicy da vozveseľátsja, da vozrádujutsja pred Bohom, da naslaďátsja v veséliji.]),
    gText("5"),
    par([Vospójte Bohu, pójte ímeni jéhó: putesotvoríte vozšédšemu na západy, Hospoď ímja jémú: í rádujtesja pred ním.]),
    gText("6"),
    par([Da smjatútsja ot licá jéhó, Ótcá sírych í sudijí vdovíc: Boh v mísťi svjatím svojém.]),
    gText("7"),
    par([Boh vseľájet jédinomýslennyja v dóm, ízvoďá ókovánnyja múžestvom, tákožde preohorčevájuščyja živúščyja vo hrobích.]),
    gText("8"),
    par([Bože, vnehdá íschodíti tebí pred ľuďmí tvojími, vnehdá mimochodíti tebí v pustýni,]),
    gText("9"),
    par([Zemľá potrjasésja, íbo nebesá kánuša ot licá Boha sijnáina, ot licá Boha Izráileva.]),
    gText("10"),
    par([Dóžď vólen otlučíši, Bože, dostojániju tvojemú, í íznemóže, tý že soveršíl jésí jé.]),
    gText("11"),
    par([Živótnaja tvojá živút na néj: úhotóval jésí bláhostiju tvojéju níščemu, Bože.]),
    gText("12"),
    par([Hospoď dást hlahól bláhovistvújuščym síloju mnóhoju:]),
    gText("13"),
    par([Car síl vozľúblennaho, krasotóju #footnote("rádi krasotý") dómu razďilíti korýsti.]),
    gText("14"),
    par([Ášče pospité posreďí preďíl, kriľí holubíňi posrébreňi, í meždorámija jéjá v bleščániji zláta:]),
    gText("15"),
    par([Vnehdá ráznstvit nebésnyj carí na néj, ósňižátsja v selmóňi.]),
    gText("16"),
    par([Horá Božija, horá túčnaja, horá úsyrénnaja, horá túčnaja.]),
    gText("17"),
    par([Vskúju nepščújete, hóry úsyrénnyja; horá, júže bláhovolí Boh žíti v néj: íbo Hospoď vselítsja do koncá.]),
    gText("18"),
    par([Kolesníca Božija tmámi tém, týsjašča hobzújuščich: Hospoď v ních v sijnái vo svjatím.]),
    gText("19"),
    par([Vozšél jésí na vysotú, pľiníl jésí pľín: prijál jésí dajánija v čelovícich, íbo ne pokarjájuščyjasja, jéže vselítisja.]),
    gText("20"),
    par([Hospoď Boh bláhoslovén, bláhoslovén Hospoď déň dné: pospišít nám Boh Spasénij nášich.]),
    gText("21"),
    par([Boh náš Boh jéže Spasáti: í Hospodňa, Hospodňa íschódišča smértnaja.]),
    gText("22"),
    par([Óbáče Boh sokrušít hlavý vrahóv svojích, vérch vlás prechoďáščich v prehrišénijich svojích.]),
    gText("23"),
    par([Rečé Hospod: ot vasána óbraščú, óbraščú vo hlubinách morskích:]),
    gText("24"),
    par([Jáko da ómóčitsja nohá tvojá v króvi, jázýk pés tvojích ot vráh ot nehó.]),
    gText("25"),
    par([Víďina býša šéstvija tvojá, Bože, šéstvija Boha mojehó cerjá, íže vo svjatím.]),
    gText("26"),
    par([Predvaríša kňázi blíz pojúščich, posreďí ďív tympánnic.]),
    gText("27"),
    par([V cerkvach bláhoslovíte Boha, Hospoda ot ístóčnik Izráilevych.]),
    gText("28"),
    par([Támo venijamín júňíjšij vo úžasi, kňázi íúdovi vladýki ích, kňázi zavulóni, kňázi nefthalímli.]),
    gText("29"),
    par([Zapovížď, Bože, síloju tvojéju: úkripí, Bože, sijé, jéže soďílal jésí v nás.]),
    gText("30"),
    par([Ot chráma tvojehó vo Jerúsaľím tebí prinesút cárije dáry.]),
    gText("31"),
    par([Zapretí zvirém tróstnym: sónm júnéc v júnicach ľudskích, jéže zatvoríti ískušénnyja srebróm: rastočí jázýki choťáščyja bránem.]),
    gText("32"),
    par([Prijídut molítvennicy ot jéhýpta: jéthijópija predvarít rúku svojú k Bohu.]),
    gText("33"),
    par([Cárstva zemnája, pójte Bohu, vospójte Hospodevi,]),
    gText("34"),
    par([Vozšédšemu na nebo nebesé na vostóki: sé, dást hlásu svojemú hlás síly.]),
    gText("35"),
    par([Dadíte slávu Bohovi: na Izráili veleľípota jéhó, í síla jéhó na óblacich.]),
    gText("36"),
    par([Díven Boh vo svjatých svojích: Boh Izráilev, tój dást sílu í deržávu ľúdem svoím. Bláhoslovén Boh.]),
    col2(gText([#translation.at("SI")])),
  ))
== #translation.at("ANTIFON") 3
  #generateTable((
    gText("1"),
    sText([V konéc, ó ízmínšichsja #footnote("ó ímúščich ízminítisja"), psalóm Davidu, (#translation.at("PSALM") 68)]),
    gText("2"),
    par([Spasí mja, Bože, jáko vnidóša vódy do duší mojejá.]),
    gText("3"),
    par([Úhľibóch v timíniji hlubiný, í ňísť postojánija: prijidóch vo hlubiný morskíja, í búrja potopí mja.]),
    gText("4"),
    par([Útrudíchsja zovýj, ízmolčé hortáň mój: ísčezósťi óči moí, ot jéže úpováti mí na Boha mojehó.]),
    gText("5"),
    par([Úmnóžišasja páče vlás hlavý mojejá nenavíďaščiji mjá túne: úkripíšasja vrazí moí, ízhoňáščiji mjá neprávedno: jáže ne voschiščách, tohdá vozdajách.]),
    gText("6"),
    par([Bože, tý úvíďil jésí bezúmije mojé, í prehrišénija mojá ot tebé ne útaíšasja.]),
    gText("7"),
    par([Da ne postyďátsja ó mňí terpjáščiji tebé, Hospodi, Hospodi síl: nižé da posrámjatsja ó mňí íščuščiji tebé, Bože Izráilev.]),
    gText("8"),
    par([Jáko tebé rádi preterpích ponošénije, pokrý sramotá licé mojé.]),
    gText("9"),
    par([Čúžď bých brátiji mojéj í stránen synovóm mátere mojejá:]),
    gText("10"),
    par([Jáko révnosť dómu tvojehó sňidé mja, í ponošénija ponosjáščich tí napadóša na mjá.]),
    gText("11"),
    par([Í pokrých postóm dúšu mojú, í býsť v ponošénije mňí:]),
    gText("12"),
    par([Í položích óďijánije mojé vrétišče, í bých ím v prítču.]),
    gText("13"),
    par([Ó mňí hlumľáchusja siďáščiji vo vraťích, í ó mňí pojáchu pijúščiji vijnó.]),
    gText("14"),
    par([Áz že molítvoju mojéju k tebí, Bože: vrémja bláhovolénija, Bože: vo mnóžestvi mílosti tvojejá úslýši mjá, vo ístiňi Spasénija tvojehó.]),
    gText("15"),
    par([Spasí mja ot brénija, da ne úhľíbnu: da ízbávľusja ot nenavíďaščich mjá í ot hlubókich vód.]),
    gText("16"),
    par([Da ne potopít mené búrja vodnája, nižé da požrét mené hlubiná, nižé svedét ó mňí rovénnik úst svojích.]),
    gText("17"),
    par([Úslýši mjá, Hospodi, jáko bláha mílosť tvojá: po mnóžestvu ščedrót tvojích prízri na mjá.]),
    gText("18"),
    par([Ne otvratí licá tvojehó ot ótroka tvojehó, jáko skorbľú: skóro úslýši mjá.]),
    gText("19"),
    par([Vonmí duší mojéj í ízbávi jú: vráh mojích rádi ízbávi mjá.]),
    gText("20"),
    par([Tý bo vísi ponošénije mojé, í stúd mój, í sramotú mojú: pred tobóju vsí óskorbľájuščiji mjá.]),
    gText("21"),
    par([Ponošénije čájaše dušá mojá í strásť: í ždách soskorbjáščaho, í ne bí, í úťišájuščich, í ne óbritóch.]),
    gText("22"),
    par([Í dáša v sňíď mojú žélč, í v žáždu mojú napojíša mjá ócta.]),
    gText("23"),
    par([Da búdet trapéza ích pred ními v síť í v vozdajánije í v soblázn.]),
    gText("24"),
    par([Da pomračátsja óči ích, jéže ne víďiti, í chrebét ích výnu sľacý.]),
    gText("25"),
    par([Proléj na ňá hňív tvój, í járosť hňíva tvojehó da postíhnet ích.]),
    gText("26"),
    par([Da búdet dvór ích púst, í v žilíščach ích da ne búdet živýj.]),
    gText("27"),
    par([Zané jéhóže tý porazíl jésí, tíji pohnáša, í k boľízni jázv mojích priložíša.]),
    gText("28"),
    par([Priloží bezzakónije k bezzakóniju ích, í da ne vnídut v právdu tvojú.]),
    gText("29"),
    par([Da potrebjátsja ot kníhi živých, í s právednymi da ne napíšutsja.]),
    gText("30"),
    par([Níšč í boľáj jésm áz: Spasénije tvojé, Bože, da prijímet mjá.]),
    gText("31"),
    par([Voschvaľú ímja Boha mojehó s písniju, vozvelíču jéhó vo chvaléniji:]),
    gText("32"),
    par([Í úhódno búdet Bohu páče teľcá júna, róhi íznosjášča í páznokti.]),
    gText("33"),
    par([Da úzrjat níščiji í vozveseľátsja: vzyščíte Boha, í živá búdet dušá váša.]),
    gText("34"),
    par([Jáko úslýša úbóhija Hospoď, í ókovánnyja svojá ne úničiží.]),
    gText("35"),
    par([Da voschváľat jéhó nebesá í zemľá, móre í vsjá živúščaja v ném.]),
    gText("36"),
    par([Jáko Boh Spasét Sijóna, í sozíždutsja hrádi íudéjstiji, í vseľátsja támo í nasľíďat í:]),
    gText("37"),
    par([Í símja rabóv tvojích úderžít í, í ľúbjaščiji ímja tvojé vseľátsja v ném.]),
    gText("1"),
    sText([V konéc Davidu, v vospominánije, vo jéže Spastí mja Hospodu, (#translation.at("PSALM") 69)]),
    gText("2"),
    par([Bože, v pómošč mojú vonmí: Hospodi, pomoščí mi potščísja.]),
    gText("3"),
    par([Da postyďátsja í posrámjatsja íščuščiji dúšu mojú, da vozvraťátsja vspjáť í postyďátsja choťáščiji mí zlája:]),
    gText("4"),
    par([Da vozraťátsja ábije styďáščesja hlahóľuščiji mí: bláhože, bláhože.]),
    gText("5"),
    par([Da vozrádujutsja í vozveseľátsja ó tebí vsí íščuščiji tebé, Bože: í da hlahóľut výnu, da vozvelíčitsja Hospoď, ľúbjaščiji Spasénije tvojé.]),
    gText("6"),
    par([Áz že níšč jésm í úbóh, Bože, pomozí mi: pomóščnik mój í ízbáviteľ mój jésí tý, Hospodi, ne zakosní.]),
    col2(gText([#translation.at("SI")])),
  ))
  #generateTable((
    col2(sText(translation.at("AFTER_KAFTIZMA"))),
    sText("T"),
    jObj4("",6, "", "Pomyšľáju déň strášnyj, í pláču ďijánij mojích lukávych: káko otviščáju bezsmértnomu cerjú; ílí kóim derznovénijem vozzrjú na sudijú blúdnyj áz; bláhoutróbnyj Ótče, Sýne jédinoródnyj, duše svjatýj, pomíluj mjá."),
    
    // S:
    col2(gText(translation.at("S"))),
    "",
    jObj4("",none, "", "Vo údóľi plačévňi, na mísťi jéže zaviščál jésí, jéhdá sjádeši mílostive, sotvoríti právednyj súd, ne óbličí mojá sokrovénnaja, nižé posramí mené pred Anhely: no poščadí mja Bože, í pomíluj mjá."),
    
    // I:
    col2(gText(translation.at("IN"))),
    "",
    jObj4("",none, "", "Úpovánije, í pokróv deržávnyj k tebí pritekájuščich, Bohorodíteľnice, bláhóje predstáteľstvo míra, molí so bezplótnymi priľížno, jéhóže rodilá jésí čelovikoľúbňijšaho Boha, ízbávitisja dušám nášym ot vsjákaho preščénija, jédína bláhoslovénnaja."),
    col2(translation.at("HOSPODI_POMILUJ")+". "+sText("(40)")),
    col2(sText(translation.at("MOLITVA"))),
    "",
    jObj4("",none, "", "Vladýko Hospodi Bože náš, íže jédín ókajánnyja mojejá duší nedúh, í sejá íscilénije vídyj, íscilí jú, jákože vísi rádi mnóžestva mílosti tvojejá, í ščedrót tvojích: ponéže ot ďíl mojích ňísť plástyrja priložíti jéj, nižé jéléa, ni óbjazánija, no tý prišédyj ne právednyja prizváti, no hríšnyja v pokajánije, pomíluj, úščédri, prostí jú, razderí rukopisánije mnóhich mojích í stúdnych ďijánij, í nastávi mjá na právyj púť tvój, da choďáj vo ístiňi tvojéj, vozmohú ízbižáti stríl lukávaho, í síce predstánu neosuždénno pred strášnym prestólom tvojím, slávja í vospivája presvjatóje tvojé ímja vo víki, ámíň."),
  ))
])
