#let translation = (
  "MINEA_OBS": "MINÍA ÓBŠčA",
  "M_PAN": "Prázdnikom Hospoda nášeho Iisusa Christá",
  "M_BOHORODICKA": "Prázdnikom Bohoródičnym",
  "M_KRIZ": "Čestnómu í životvorjáščemu krestú",
  "M_ANJELI": "Svjatým Anhelom í próčym bezplótnym",
  "M_PREDCHODCA": "Ioánna predtéči, proróka í krestíteľa Hospodňa",
  "M_SVATI_OTCOVIA": "Svjatých ótéc, na sobóry",
  "M_PROROK_JEDEN": "Proróku jédínomu",
  "M_APOSTOL_JEDEN": "Apostolu jédínomu",
  "M_APOSTOL_VIAC": "Apostolom dvimá í mnóhim",
  "M_SVATITEL_JEDEN": "Svjatíteľu jédínomu",
  "M_SVATITEL_VIAC": "Svjatítelem dvimá í mnóhim",
  "M_PREPODOBNY_JEDEN": "Prepodóbnomu jédínomu",
  "M_PREPODOBNY_VIAC": "Prepodóbnym dvimá í mnóhim",
  "M_MUCENIK_JEDEN": "Mučeniku jédínomu",
  "M_MUCENIK_VIAC": "Mučenikom, dvimá í mnóhim",
  "M_HIEROMUCENIK_JEDEN": "Svjaščennomučeniku jédínomu",
  "M_HIEROMUCENIK_VIAC": "Svjaščennomučenikom dvimá, í mnóhim",
  "M_PREPODOBNY_MUCENIK_JEDEN": "Prepodóbnomučeniku jédínomu",
  "M_PREPODOBNY_MUCENIK_VIAC": "Prepodóbnomučenikom dvimá í mnóhim",
  "M_MUCENICA_JEDNA": "Mučenici jédínoj",
  "M_MUCENICA_VIAC": "Mučenicam, dvimá í mnóhim",
  "M_PREPODOBNA_ZENA_JEDNA": "Prepodóbňij žeňí jédíňij",
  "M_PREPODOBNA_ZENA_VIAC": "Prepodóbnym ženám dvimá í mnóhim",
  "M_PREPODOBNA_MUCENICA_JEDNA": "Prepodóbnomučenici jédínoj",
  "M_SPOVEDNIK_JEDEN": "Svjaščennoispovídniku í prepodóbnoispovídniku",
  "M_DIVOTVORCA_JEDEN": "Bezmézdnikom í čudotvórcem",
  // "M_":"",
  // "M_":"",

  "M_01_september": "MINÍA MÍSJaC SJePTJéMVRIJ",
  "M_02_oktober": "MINÍA MÍSJaC ÓKTÓVRIJ",
  "M_03_november": "MINÍA MÍSJaC NOJéMVRIJ",
  "M_04_december": "MINÍA MÍSJaC DJeKJéMVRIJ",
  "M_05_januar": "MINÍA MÍSJaC ÍANNUÁRIJ",
  "M_06_februar": "MINÍA MÍSJaC FJeYRUÁRIJ",
  "M_07_marec": "MINÍA MÍSJaC MÁRT",
  "M_08_april": "MINÍA MÍSJaC ÁPRÍLLIJ",
  "M_09_maj": "MINÍA MÍSJaC MÁIJ",
  "M_10_jun": "MINÍA MÍSJaC ÍÚNIJ",
  "M_11_jul": "MINÍA MÍSJaC ÍÚLIJ",
  "M_12_august": "MINÍA MÍSJaC ÁYHUST",

  // 🕀🕁🕂🕃🕄
  "M_NAR_BOHORODICKY": "🕀 Roždestvó presvjatýja Vladíčicy nášeja Bohoródicy, í prisnoďivy Maríji.",
  "M_VOZDV_KRIZA": "🕀 Vsemírnoje vozdvíženije čestnáho í životvorjáščaho krestá.",
  "M_JAN_BOHOSLOV": "🕁 Prestavlénije svjatáho Apostola í jéy-h**lísta Íoánna Bohoslóva.",
  "M_POKROV": "🕀 Pokróv presvjatýja Vladíčicy nášeja Bohoródicy í prisnoďivy Maríji.",
  "M_DEMETER": "🕁 Svjatáho í slávnaho velikomúčenika dimítrija myrotóčca.",
  "M_MICHAL": "🕁 Sobór svjatáho árchijstratíha mijchaíla, í próčich bezplótnych síl.",
  "M_JOZAFAT": "🕁",
  "M_ZLATOUSTY": "🕁 Íže vo svjatých Ótcá nášeho Joánna, árchijepískopa konstantíňa hráda, zlatoústaho.",
  "M_VOVEDENIE": "🕀 Vchód vo chrám presvjatýja Vladíčicy nášeja Bohoródicy í prisnoďívy Maríji.",
  "M_SAVA": "🕁 Prepodóbnaho í Bohonósnaho ótcá nášeho sávvy ósvjaščénnaho.",
  "M_MIKULAS": "🕁 Íže vo svjatých ótcá nášeho Nijkoláa, árchijepískopa myrlykíjskich čudotvórca.",
  "M_POCATIE_BOHORODICKY": "🕁 Začátije svjatýja ánny, jéhdá začát presvjatúju Bohoródicu.",
  "M_NARODENIE": "🕀 Jéže po plóti, roždestvó Hospoda Boha í Spasa nášeho Izráisa Christá.",
  "M_ZHROM_BOHORODICKA": "🕃 Sobór presvjatýja Bohoródicy",
  "M_OBREZANIE": "🕀 ",
  "M_BOHOZJAVENIE": "🕀 ",
  "M_ANTON": "🕁 ",
  "M_EUTMIOS": "🕁 ",
  "M_TRAJA_SVATITELIA": "🕁 ",
  "M_OBETOVANIE": "🕀 ",
  "M_ZVESTOVANIE": "🕀 ",
  "M_JURAJ": "🕁 ",
  "M_JAN_EVANJELISTA": "🕁 ",
  "M_NAR_JAN_KRSTITEL": "🕀 Roždestvó čestnáho slávnaho proróka, predtéči í krestíteľa Ioánna.",
  "M_PETER_PAVOL": "🕀 Svjatých slávnych í vsechváľnych í pervoverchóvnych Apostol, Petrá í Páyla",
  "M_PAVOL_GOJDIC": "🕁 ",
  "M_ELIAS": "🕁 Svjatáho slávnaho proróka Ilijí.",
  "M_PREMENENIE": "🕀 Svjatóje preobražénije Hospoda Boha í Spasa nášeho Iisusa Christá.",
  "M_ZOSNUTIE": "🕀 Úspénije presvjatýja slávnyja Vladíčicy nášeja Bohoródicy í prisnoďivy Maríji.",

  "SI": "Sláva, í nýňi:",
  "S": "Sláva:",
  "IN": "Í nýňi:",
  "PR": "pr",
  "PD": "pod",
  "VV": "v",
  "ST": "st",

  "HLAS": "Hlás",
  "TYZDEN": "Neďíľa svjatáho postá",

  "Ne": "Neďíľa",
  "Po": "Poneďíľnik",
  "Ut": "Vtórnik",
  "Sr": "Sréda",
  "St": "Četvertók",
  "Pi": "Pjatók",
  "So": "Subbóta",
  "M": "Málaja večérňa",
  "V": "Večérňa",
  "P": "Povečérije",
  "N": "Polúnoščnica",
  "U": "Útreňa",
  "L": "Lijturhía",
  "I": "Izobrazíteľnaja",
  "LPD": "Slúžba preždeosvjaščénnych",
  "1": "Čás pérvyj",
  "3": "Čás trétij",
  "6": "Čás šestýj",
  "9": "Čás devjátyj",
  "So_V": "v subbótu véčera",
  "So_N": "v subbótu nóšči",
  "Ne_V": "v neďíľu véčera",
  "Ne_N": "v neďíľu nóšči",
  "Po_V": "v poneďíľnik véčera",
  "Po_N": "v poneďíľnik nóšči",
  "Ut_V": "v vtórnik véčera",
  "Ut_N": "v vtórnik nóšči",
  "Sr_V": "v srédu véčera",
  "Sr_N": "v srédu nóšči",
  "St_V": "v četvertók véčera",
  "St_N": "v četvertók nóšči",
  "Pi_V": "v pjatók véčera",
  "Pi_N": "v pjatók nóšči",
  "HOSPODI_VOZVACH": "Hospodi vozzvách",
  "PARAMIE": "Čténija",
  "LITIA": "Na lijtíji",
  "STICHOVNI": "Na stijchóvňi stijchíru",
  "TROPAR": "Tropár",
  "PIESEN": "Písň",
  "SIDALEN": "Sidálen",
  "SIDALENY": "Sidálňi",
  "SIDALEN_PO": "Po stijchoslóviji",
  "VELICANIE": "Veličánije",
  "YPAKOJ": "Ýpakoí",
  "STEPENNY": "Stepénny",
  "ANTIFONY": "Ántijfóny",
  "ANTIFON": "Antijfón",
  "PROKIMEN": "Prokímen",
  "STICH": "Stích",
  "ALLILUJA": "Állilúija",
  "KANON": "Kanón",
  "KATAVASIA": "Katavásija",
  "KONDAK_IKOS": "Kondák i Íkos",
  "KONDAK": "Kondák",
  "IKOS": "Íkos",
  "CHVALITE": "Na chvalítech stijchíry",
  "BLAZENNA": "Blážénna",
  "TROPAR_KONDAK": "Tropár i Kondák",
  "50_STICHIRA": "Stijchíra po n*-m psalmí",
  "SVITILEN": "Svitílen",
  "PRICASTEN": "Pričásten",
  "IRMOS": "Írmós",
  "JEDINORODNY": "Jédinoródnyj Sýne í Slóve",
  "VCHOD": "Vchódnoje",
  
  "HV_MINEA": "Táže stijchíry 3 íz minéi ílí íz minéi óbščej.",
  "HV_NOTE": "Sláva: íz minéi, Í nýňi: Bohoródičen, ášče ne búdet, Sláva: Í nýňi: Bohoródičen",
  "HV_N_NOTE": "Bohoródičen vo ústávi",
  "T_NOTE": "Sláva: minéi; Í nýňi: Bohoródičen voskresényj",

  "NACALO": "Načálo",
  "PSALM": "Psalóm",
)