#import "../all.typ": *

#show: four_col_book

#t((
  ([= Вече́рньа],
   [= Εσπερινός],
   [= Vespers],
   [= Večiereň]),
  ([== Ѱало́мъ р҃г],
   [== Ψαλμὸς ΡΓʹ],
   [== Psalm 103],
   [== Žalm 103]),
  ("Бл҃гословѝ дꙋшѐ моѧ̀ гдⷭ҇а: * гдⷭ҇и бж҃е мо́й, возвели́чилсѧ є҆сѝ ѕѣлѡ̀,",
   "Εὐλόγει, ἡ ψυχή μου, τὸν Κύριον. Κύριε ὁ Θεός μου, ἐμεγαλύνθης σφόδρα,",
   "Bless the Lord, O my soul. O Lord my God, You are magnified exceedingly;",
   "Dobroreč, duša moja, Pánovi; * Pane, Bože môj, ty si nesmierne veľký."),
  ("во и҆сповѣ́данїе и҆ въ велелѣ́потꙋ ѡ҆бле́клсѧ є҆сѝ. * Ѡ҆дѣѧ́йсѧ свѣ́томъ ꙗ҆́кѡ ри́зою,",
   "ἐξομολόγησιν καὶ μεγαλοπρέπειαν ἐνεδύσω ἀναβαλλόμενος φῶς ὡς ἱμάτιον,",
   "You clothe Yourself with thanksgiving and majesty, who cover Yourself with light as with a garment,",
   "Odel si sa do slávy a veleby, * do svetla si sa zahalil ako do rúcha."),
  ("простира́ѧй нб҃о ꙗ҆́кѡ ко́жꙋ. * Покрыва́ѧй вода́ми превы́спрєннѧѧ своѧ̑,",
   "ἐκτείνων τὸν οὐρανὸν ὡσεὶ δέρριν· ὁ στεγάζων ἐν ὕδασι τὰ ὑπερῷα αὐτοῦ,",
   "who stretch out the heavens like a curtain; You are He who covers His upper chambers with water,",
   "Nebesia rozpínaš ako stan, * nad vodami si buduješ komnaty."),
  ("полага́ѧй ѻ҆́блаки на восхожде́нїе своѐ, * ходѧ́й на крилꙋ̀ вѣ́трєню.",
   "ὁ τιθεὶς νέφη τὴν ἐπίβασιν αὐτοῦ, ὁ περιπατῶν ἐπὶ πτερύγων ἀνέμων·",
   "who makes the clouds His means of approach, who walks on the wings of the winds,",
   "Po oblakoch vystupuješ ako po schodoch, * na krídlach vánku sa prechádzaš."),
   
  ("",
   "",
   "",
   ""),
  ("",
   "",
   "",
   ""),
  ("",
   "",
   "",
   ""),
  ("",
   "",
   "",
   ""),
  ("",
   "",
   "",
   ""),
  ("",
   "",
   "",
   ""),
  ("",
   "",
   "",
   ""),
  ("",
   "",
   "",
   ""),
))