#import "../../../all.typ": *
#columns(2, gutter: 2pt, [

  #generateTable((
    col2([== #translation.at("V")]),
    col2(align(center,sText("("+translation.at("So_V")+")"))),
    cText[$#sym.ast.circle$],
    cText("Nacalo, 103, 12xHP, Kathisma, 3xHP, HV, 104 a 141 a 129"),
    col2([=== #translation.at("HOSPODI_VOZVACH")]),
    sub(sText("(10)")),
    gText("И҆зведѝ и҆з̾ темни́цы дꙋ́шꙋ мою̀, и҆сповѣ́датисѧ и҆́мени твоемꙋ̀."),
    col2("Majúc víťazstvo nad peklom, Kriste, vystúpil si na kríž, aby si tých, čo sedia v temnote smrti, so sebou vzkriesil, Ty, ktorý si slobodný medzi mŕtvymi a zo svojho svetla prameníš život. Všemohúci Spasiteľ, zmiluj sa nad nami."),
    sub(sText("(9)")),
    gText("Менѐ ждꙋ́тъ пра́вєдницы, до́ндеже возда́си мнѣ̀."),
    col2("Dnes Kristus pošliapal smrť, ako povedal, vstal z mŕtvych a svetu daroval radosť; preto všetci, volajúc, zaspievajme takúto pieseň: Ó prameň života, neprístupné Svetlo, všemohúci Spasiteľ, zmiluj sa nad nami."),
    sub(sText("(8)")),
    gText("И҆з̾ глꙋбины̀ воззва́хъ къ тебѣ̀ гдⷭ҇и, гдⷭ҇и, ᲂу҆слы́ши гла́съ мо́й."),
    col2("Tebe, Pane, ktorý si prítomný v celom stvorení, my hriešni — kam sa utečieme? Na nebi Ty sám prebývaš, v podsvetí si pošliapal smrť, v morských hlbinách — tam je Tvoja ruka, Vládca. K Tebe sa utiekame, Tebe padajúc sa modlíme: Ty, ktorý si vstal z mŕtvych, zmiluj sa nad nami."),
    sub(sText("(7)")),
    gText("Да бꙋ́дꙋтъ ᲂу҆́ши твоѝ, вне́млющѣ гла́сꙋ моле́нїѧ моегѡ̀."),
    col2("Tvojím krížom, Kriste, sa chválime a tvoje vzkriesenie spievame a oslavujeme: lebo ty si náš Boh. Okrem teba iného nepoznáme."),
    sub(sText("(6)")),
    gText("А҆́ще беззакѡ́нїѧ на́зриши гдⷭ҇и, гдⷭ҇и, кто̀ постои́тъ; ꙗ҆́кѡ ᲂу҆ тебѐ ѡ҆чище́нїе є҆́сть."),
    col2("Vždy velebujúc Pána, spievame jeho zmŕtvychvstanie: lebo keď pretrpel kríž, smrť smrťou premohol."),
    sub(sText("(5)")),
    gText("И҆́мене ра́ди твоегѡ̀ потерпѣ́хъ тѧ̀ гдⷭ҇и, потерпѣ̀ дꙋша̀ моѧ̀ въ сло́во твоѐ, ᲂу҆пова̀ дꙋша̀ моѧ̀ на гдⷭ҇а."),
    col2("Sláva tvojej moci, Pane, lebo si zmaril vládu toho, čo mal moc nad smrťou; obnovil si nás svojím krížom a daroval nám život a neporušenosť."),
    sub(sText("(4)")),
    gText("Ѿ стра́жи ᲂу҆́треннїѧ до но́щи, ѿ стра́жи ᲂу҆́треннїѧ, да ᲂу҆пова́етъ і҆и҃ль на гдⷭ҇а."),
    col2("Tvoje pochovanie, Pane, rozdrvilo a roztrhalo putá podsvetia; vzkriesením z mŕtvych si osvietil svet. Pane, sláva Tebe."),
    sub(sText("(3)")),
    gText("Ꙗ҆́кѡ ᲂу҆ гдⷭ҇а млⷭ҇ть, и҆ мно́гое ᲂу҆ негѡ̀ и҆збавле́нїе, и҆ то́й и҆зба́витъ і҆и҃лѧ ѿ всѣ́хъ беззако́нїй є҆гѡ̀."),
    col2("Keď vidíš moju telesnú slabosť, duševné utrpenie a srdcové súženie, učiň ma dôstojným božského navštívenia, Všenepoškvrnená Panna; zachráň ma, prosím, svojimi vrúcnymi modlitbami."),
    sub(sText("(2)")),
    gText("Хвали́те гдⷭ҇а всѝ ꙗ҆зы́цы, похвали́те є҆го̀ всѝ лю́дїе."),
    col2("Hriechmi som predčil všetkých, Vládkyňa; ale keď očistíš množstvo týchto hriechov, Panna, urob ma, Čistá, hodným prijať milosti pri budúcom súde tvojho Syna a Boha."),
    sub(sText("(1)")),
    gText("Ꙗ҆́кѡ ᲂу҆тверди́сѧ млⷭ҇ть є҆гѡ̀ на на́съ, и҆ и҆́стина гдⷭ҇нѧ пребыва́етъ во вѣ́къ."),
    col2("Množstvo mojich hriechov, mňa volajúceho, očisti, Čistá, a neprestajné pohyby mojich zmyslov presekni modlitebným mečom, aby som s vierou a láskou spieval tvoje bezsemenné narodenie."),
    "",
    gText([#translation.at("SI")]),
    col2("Kto ťa nebude blahoslaviť, Presvätá Panna? Kto nezaspieva tvoj prečistý pôrod? Veď Jednorodený Syn, ktorý bezčasne zažiaril z Otca, ten istý z teba, Čistá, vyšiel, nevýslovne sa vtelil, podľa prirodzenosti Boh a podľa prirodzenosti sa stal človekom pre nás; nie rozdeľovaný na dve osoby, ale poznávaný v dvoch prirodzenostiach nezmiešane. Toho pros, Čistá, Všeblažená, aby sa zľutoval nad našimi dušami."),
    cText[$#sym.ast.circle$],
    cText("Svite tichyj"),
    col2([=== #translation.at("PROKIMEN")]),
    col2("Гдⷭ҇ь воцр҃и́сѧ, въ лѣ́потꙋ ѡ҆блече́сѧ."),
    sText(translation.at("ST")),
    "Ѡ҆блече́сѧ гдⷭ҇ь въ си́лꙋ и҆ препоѧ́сасѧ.",
    sText(translation.at("ST")),
    "И҆́бо ᲂу҆твердѝ вселе́ннꙋю, ꙗ҆́же не подви́житсѧ.",
    sText(translation.at("ST")),
    "До́мꙋ твоемꙋ̀ подоба́етъ ст҃ы́нѧ гдⷭ҇и, въ долготꙋ̀ дні́й.",
    cText[$#sym.ast.circle$],
    cText("N/S: 12xHP, Spodobi Hospodi, 12xHP"),
    col2([=== #translation.at("STICHOVNI")]),
    col2("Tvoje vzkriesenie, Kriste Spasiteľu, anjeli na nebesiach spievajú; aj nás na zemi učiň hodnými, aby sme ťa čistým srdcom oslavovali."),
    "",
    gText("Гдⷭ҇ь воцари́сѧ, въ лѣ́потꙋ ѡ҆блече́сѧ."),
    col2("Rozlámal si medené brány a polámal závory podsvetia; ako všemohúci Boh si vzkriesil padlé ľudské pokolenie. Preto aj my jednomyseľne voláme: Ty, čo si vstal z mŕtvych, Pane, sláva tebe."),
    "",
    gText("И҆́бо ᲂу҆твердѝ вселе́ннꙋю, ꙗ҆́же не подви́житсѧ."),
    col2("Kristus, keď chcel napraviť našu prastarú porušenosť, bol pribitý na kríž a uložený do hrobu; jeho hľadali ženy myronosičky so slzami a plačúc vraveli: Beda nám, Spasiteľ všetkých, ako si sa rozhodol prebývať v hrobe? A keď si tam prebýval, ako si mohol byť ukradnutý? Ako si bol prenesený? Aké miesto skrylo tvoje životodarné telo? Ale, Vládca, ako si nám prisľúbil, zjav sa a utíš nárek sĺz. A keď plakali, anjel k nim zvolal: Prestaňte plakať, povedzte apoštolom, že Pán vstal z mŕtvych, dávajúc svetu očistenie a veľké milosrdenstvo."),
    "",
    gText("До́мꙋ твоемꙋ̀ подоба́етъ ст҃ы́нѧ гдⷭ҇и, въ долготꙋ̀ дні́й."),
    col2("Dal si sa ukrižovať, ako si chcel, Kriste, a smrť si svojím pochovaním premohol; na tretí deň si vstal z mŕtvych ako Boh so slávou, svetu darujúc večný život a veľké milosrdenstvo."),
    "",
    gText([#translation.at("SI")]),
    col2("Môj Stvoriteľ a Vykupiteľ, Prečistá, Pán Kristus, keď vyšiel z tvojho lona a obliekol sa do mňa, oslobodil ma od prvej Adamovej kliatby. Preto tebe, Všetkočistá, ako Božej Matke a Panne, vpravde neprestajne voláme: Raduj sa anjelsky, raduj sa, Vládkyňa, príhovor a ochrana a spása našich duší."),
    cText[$#sym.ast.circle$],
    cText("Simeon, nacalo"),
    col2([=== #translation.at("TROPAR")]),
    col2("Anjelské mocnosti pri tvojom hrobe a strážcovia sa stali ako mŕtvi; Mária stála pri hrobe a hľadala tvoje prečisté telo. Spustošil si podsvetie bez toho, aby sa ťa dotklo; stretol si Pannu, darujúc život. Vstal si z mŕtvych, Pane, sláva tebe."),
    "",
    gText([#translation.at("SI")]),
    col2("Keď si nazval svoju Matku blahoslavenou, prišiel si na utrpenie z vlastnej vôle, zažiaril si na kríži, aby si vyhľadal Adama, a anjelom si povedal: Radujte sa so mnou, lebo našla sa stratená drachma. Ty, ktorý múdro všetko usporiadal, náš Bože, sláva tebe."),
    cText[$#sym.ast.circle$],
    cText("prepustenie"),
  ))
  #generateTable((
    col2([== #translation.at("U")]),
    cText[$#sym.ast.circle$],
    cText("Nacalo, Z19, Z20, nacalo, tropare, 12xHP, Slava svatej, 6zalmie, 12xHP, BohHospod"),
    col2([=== #translation.at("TROPAR") ]),
    col2("Anjelské mocnosti pri tvojom hrobe a strážcovia sa stali ako mŕtvi; Mária stála pri hrobe a hľadala tvoje prečisté telo. Spustošil si podsvetie bez toho, aby sa ťa dotklo; stretol si Pannu, darujúc život. Vstal si z mŕtvych, Pane, sláva tebe."),
    "",
    gText([#translation.at("SI")]),
    col2("Keď si nazval svoju Matku blahoslavenou, prišiel si na utrpenie z vlastnej vôle, zažiaril si na kríži, aby si vyhľadal Adama, a anjelom si povedal: Radujte sa so mnou, lebo našla sa stratená drachma. Ty, ktorý múdro všetko usporiadal, náš Bože, sláva tebe."),
    col2([=== #translation.at("SIDALENY") ]),
    col2([==== #translation.at("SIDALEN_PO") 1 ]),
    col2(sub(sText("(1)"))+"Keď bol hrob otvorený a peklo nariekalo, Mária volala k skrytým apoštolom: Vyjdite, robotníci vinice, hlásajte slovo o vzkriesení: Pán vstal z mŕtvych, udeľujúc svetu veľké milosrdenstvo."),
    col2(sub(sText("(2)"))+"Pane, keď Mária Magdaléna stála pri tvojom hrobe a plakala, volajúc, mysliac si, že si záhradník, hovorila: Kde si ukryl Večný Život? Kde si uložil Toho, ktorý sedí na tróne cherubínov? Veď tí, čo ho strážili, od strachu ostali ako mŕtvi. Buď mi dajte môjho Pána, alebo spolu so mnou zvolajte: Ten, čo bol medzi mŕtvymi a mŕtvych vzkriesil — sláva Tebe."),
    "",
    gText([#translation.at("SI")]),
    col2("Gedeon predobrazuje počatie a Dávid zvestuje tvoje narodenie, Bohorodička: lebo Slovo zostúpilo do tvojho lona ako dážď na rúno a ty si bez semena vyklíčila, svätá zem, spásu svetu — Krista, nášho Boha, milosti plná."),
    col2([==== #translation.at("SIDALEN_PO") 2 ]),
    col2(sub(sText("(1)"))+"Život v hrobe ležal a pečať spočívala na kameni: Krista strážili vojaci ako spiaceho kráľa; a Pán vstal, neviditeľne poraziac svojich nepriateľov."),
    col2(sub(sText("(2)"))+"Jonáš predobrazuje tvoj hrob a Simeon zvestuje božské vzkriesenie, nesmrteľný Pane: lebo si zostúpil ako mŕtvy do hrobu a rozlomil brány podsvetia. A vstal si bez porušenia ako Vládca na spásu sveta, Kriste, Bože náš, ktorý si osvietil tých, čo sú v tme."),
    "",
    gText([#translation.at("SI")]),
    col2("Bohorodička, Panna, pros Syna svojho, dobrovoľne na kríž pribitého a z mŕtvych vstalého, Krista, Boha nášho, aby sa spasili naše duše."),
    col2([=== #translation.at("KANON") ]),
    col2(sub(sText("(1)"))+"Ako Izraeliti kráčali po suchu po bezodnej hlbine, vidiac, ako sa prenasledovateľ faraón topí, spievali Bohu víťaznú pieseň a volali."),
    col2(sub(sText("(3)"))+"Niet svätého ako Ty, Pane, môj Bože, ktorý si pozdvihol roh svojich verných, ó Blažený, a upevnil si nás na skale Tvojho vyznania."),
    col2(sub(sText("(4)"))+"Kristus je moja sila, Boh a Pán; ctihodná Cirkev boholepne spieva, z čistej mysle volajúc, sláviac sviatok Pánovi."),
    col2(sub(sText("(5)"))+"Božím tvojím svetlom, Blažený, osvieť duše tých, čo ti s láskou konajú rannú modlitbu; modlím sa, aby som ťa poznal, Slovo Božie, ako pravého Boha, volajúc z temnoty hriechu."),
    col2(sub(sText("(6)"))+"Keď vidím more života rozbúrené búrkou protivenstiev, utekám sa k tvojmu tichému prístavu a volám k tebe: pozdvihni môj život z porušenia, Mnohomilosrdný."),
    col2(sub(sText("(7)"))+"Anjel urobil pec rosodarnou pre ctihodných mládencov, kým Chaldejcov spálilo Božie nariadenie; mučiteľa prinútil volať: Požehnaný si, Bože, otcov našich."),
    col2(sub(sText("(8)"))+"Z plameňa si zbožným zoslal rosu a spravodlivého obetu si vodou spálil: veď všetko konáš, Kriste, stačí len chcieť. Teba zvelebujeme po všetky veky."),
    col2(sub(sText("(9)"))+"Boha nie je možné ľuďom vidieť, na ktorého sa neodvažujú hľadieť ani anjelské chóry; ale skrze teba, Prečistá, sa ľuďom zjavilo vtelené Slovo; jeho zvelebujúc, spolu s nebeskými zástupmi ťa blahoslavíme."),
    col2([=== #translation.at("CHVALITE") ]),
    sub(sText("(8)")),
    gText("Сотвори́ти въ ни́хъ сꙋ́дъ напи́санъ: сла́ва сїѧ̀ бꙋ́детъ всѣ̑мъ прпⷣбнымъ є҆гѡ̀."),
    col2("Tvoj kríž, Pane, je život a vzkriesenie tvojmu ľudu; a spoliehajúci sa naň tebe, nášmu Bohu, ktorý si vstal z mŕtvych, spievame: zmiluj sa nad nami."),
    sub(sText("(7)")),
    gText("Хвали́те бг҃а во ст҃ы́хъ є҆гѡ̀, хвали́те є҆го̀ во ᲂу҆тверже́нїи си́лы є҆гѡ̀."),
    col2("Tvoje pochovanie, Vládca, otvorilo raj ľudskému rodu; a oslobodení od porušenia spievame Tebe, nášmu vzkriesenému Bohu: zmiluj sa nad nami."),
    sub(sText("(6)")),
    gText("Хвали́те є҆го̀ на си́лахъ є҆гѡ̀, хвали́те є҆го̀ по мно́жествꙋ вели́чествїѧ є҆гѡ̀."),
    col2("Spolu s Otcom a Duchom zaspievajme Krista, ktorý vstal z mŕtvych, a k nemu volajme: Ty si náš život a vzkriesenie, zmiluj sa nad nami."),
    sub(sText("(5)")),
    gText("Хвали́те є҆го̀ во гла́сѣ трꙋ́бнѣмъ: хвали́те є҆го̀ во ѱалти́ри и҆ гꙋ́слехъ."),
    col2("Na tretí deň si vstal z hrobu, Kriste, ako je napísané, a spolu si pozdvihol nášho praotca. Preto Ťa ľudský rod oslavuje a ospevuje Tvoje zmŕtvychvstanie."),
    sub(sText("(4)")),
    gText("Хвали́те є҆го̀ въ тѷмпа́нѣ и҆ ли́цѣ, хвали́те є҆го̀ во стрꙋ́нахъ и҆ ѻ҆рга́нѣ."),
    col2("Pane, veľké a strašné je tajomstvo tvojho vzkriesenia: takto si vyšiel z hrobu ako ženích zo svadobnej siene, smrťou si premohol smrť, aby si oslobodil Adama. Preto na nebesiach anjeli jasajú a na zemi ľudia oslavujú tvoje milosrdenstvo, ktoré si nám preukázal, Človekomilovník."),
    sub(sText("(3)")),
    gText("Хвали́те є҆го̀ въ кѷмва́лѣхъ доброгла́сныхъ, хвали́те є҆го̀ въ кѷмва́лѣхъ восклица́нїѧ: всѧ́кое дыха́нїе да хва́литъ гдⷭ҇а."),
    col2("Ó najbezbožnejší Židia, kde sú pečate a strieborníky, ktoré ste dali vojakom? Poklad nebol ukradnutý, ale vstal z mŕtvych ako mocný. Vy sami ste sa zahanbili, keď ste zavrhli Krista, Pána slávy, ktorý trpel, bol pochovaný a vstal z mŕtvych: jemu sa pokloňme."),
    sub(sText("(2)")),
    gText("Воскрⷭ҇нѝ гдⷭ҇и бж҃е мо́й, да вознесе́тсѧ рꙋка̀ твоѧ̀, не забꙋ́ди ᲂу҆бо́гихъ твои́хъ до конца̀."),
    col2("Keď ste zapečatili hrob, Židia, akoby ste boli okradnutí; postavili ste stráže a priložili pečate, no Kráľ prešiel cez zavreté dvere. Buď ho predstavte ako mŕtveho, alebo sa mu klaňajte ako Bohu, spolu s nami spievajúc: Sláva, Pane, tvojmu krížu a tvojmu zmŕtvychvstaniu."),
    sub(sText("(1)")),
    gText("И҆сповѣ́мсѧ тебѣ̀ гдⷭ҇и всѣ́мъ се́рдцемъ мои́мъ, повѣ́мъ всѧ̑ чꙋдеса̀ твоѧ̑."),
    col2("Ženy myronosičky, plačúc, prišli, Pane, k tvojmu životodarnému hrobu a niesli voňavé myrá, hľadajúc pomazať tvoje prečisté telo. No našli žiarivého anjela, sediaceho na kameni, ktorý im povedal: Prečo plačete nad tým, ktorý zo svojho boku vydal život svetu? Prečo hľadáte v hrobe ako mŕtveho Nesmrteľného? Radšej utekajte a oznámte jeho učeníkom radosť celému svetu zo slávneho vzkriesenia; ktorým si aj nás, Spasiteľu, osvietil; daruj očistenie a veľké milosrdenstvo."),
  ))
])
