#import "../../../all.typ": *
#columns(2, gutter: 2pt, [

  #generateTable((
    col2([== #translation.at("V")]),
    col2(align(center,sText("("+translation.at("Ne_V")+")"))),
    cText[$#sym.ast.circle$],
    cText("Nacalo, 103, 12xHP, Kathisma, 3xHP, HV, 104 a 141 a 129"),
    col2([=== #translation.at("HOSPODI_VOZVACH")]),
    sub(sText("(6)")),
    gText("И҆зведѝ и҆з̾ темни́цы дꙋ́шꙋ мою̀, и҆сповѣ́датисѧ и҆́мени твоемꙋ̀."),
    col2("Spasiteľu, daj mi slzy pokánia so skrúšenou mysľou, aby som zmyl poškvrnu svojej duše, ktorú som zle poškvrnil, konajúc nespravodlivé skutky v každý čas, majúc pri tom za orodovníčku tú, ktorá ťa porodila, aj anjelské zbory a tvoju lásku k človeku."),
    sub(sText("(5)")),
    gText("Менѐ ждꙋ́тъ пра́вєдницы, до́ндеже возда́си мнѣ̀."),
    col2("Príď, ó duša, a kaj sa zo svojich mnohých hriechov, ktoré si spáchala v živote, a modli sa k množstvu nebeských zástupov so vzdychaním a slzami, aby sa ti daroval čas na pokánie, aby si nebola ako neplodný figovník odťatá a uvrhnutá do ohňa gehenny, ty vášňami zotročená."),
    sub(sText("(4)")),
    gText("И҆з̾ глꙋбины̀ воззва́хъ къ тебѣ̀ гдⷭ҇и, гдⷭ҇и, ᲂу҆слы́ши гла́съ мо́й."),
    col2("Na zemi som nesplnil ani jediné Tvoje prikázanie; ako sa ukážem pred Tebou, ktorý sedíš na tróne, aby som vydal počet a prijal súd za všetko, čo som vykonal vedome i nevedome, môj Kriste? Preto k Tebe volám: modlitbami Tvojich služobníkov ma spas, zblúdilého."),
    sub(sText("(3)")),
    gText("Да бꙋ́дꙋтъ ᲂу҆́ши твоѝ, вне́млющѣ гла́сꙋ моле́нїѧ моегѡ̀."),
    col2("Anjelské mocnosti, Kriste, stojace pred tvojím trónom, sa modlia za ľudský rod. Na ich príhovor daruj všetkým pokoj, opovážlivosť národov skroť."),
    sub(sText("(2)")),
    gText("А҆́ще беззакѡ́нїѧ на́зриши гдⷭ҇и, гдⷭ҇и, кто̀ постои́тъ; ꙗ҆́кѡ ᲂу҆ тебѐ ѡ҆чище́нїе є҆́сть."),
    col2("Vy, všetky anjelské rády, ktoré sa ustavične radujete okolo trónu Kráľa všetkých, chráňte nás, ktorí vás s vierou vzývame, a vyslobodzujte nás od múk."),
    sub(sText("(1)")),
    gText("И҆́мене ра́ди твоегѡ̀ потерпѣ́хъ тѧ̀ гдⷭ҇и, потерпѣ̀ дꙋша̀ моѧ̀ въ сло́во твоѐ, ᲂу҆пова̀ дꙋша̀ моѧ̀ на гдⷭ҇а."),
    col2("Otec, Boh nad všetkými, priviedol sily nebeských myslí, beztvarých a nehmotných spevákov svojej trojslnečnej slávy, i jediné Slovo, i Ducha."),
    "",
    gText([#translation.at("SI")]),
    col2("Slovo bezpočiatkové spolu s Otcom i Duchom; keď si, Bohorodička, archanjelským hlasom vo svojom lone počala, ukázala si sa vyššia než cherubíni, serafíni i tróny."),
    cText[$#sym.ast.circle$],
    cText("Svite tichyj"),
    col2([=== #translation.at("PROKIMEN")]),
    col2("Сѐ ны́нѣ бл҃гослови́те гдⷭ҇а всѝ рабѝ гдⷭ҇ни."),
    sText(translation.at("ST")),
    "Стоѧ́щїи во хра́мѣ гдⷭ҇ни, во дво́рѣхъ до́мꙋ бг҃а на́шегѡ.",
    cText[$#sym.ast.circle$],
    cText("N/S: 12xHP, Spodobi Hospodi, 12xHP"),
    col2([=== #translation.at("STICHOVNI")]),
    col2("Pri Tvojom strašnom príchode, Kriste, nech nepočujeme: „Nepoznám vás“; veď v Teba, Spasiteľu, sme vložili svoju nádej, hoci sme pre svoju nedbanlivosť nezachovali Tvoje prikázania; ale zmiluj sa nad našimi dušami, prosíme."),
    "",
    gText("Къ тебѣ̀ возведо́хъ ѻ҆́чи моѝ, живꙋ́щемꙋ на нб҃сѝ. сѐ ꙗ҆́кѡ ѻ҆́чи ра̑бъ въ рꙋкꙋ̀ госпо́дїй свои́хъ, ꙗ҆́кѡ ѻ҆́чи рабы́ни въ рꙋкꙋ̀ госпожѝ своеѧ̀: та́кѡ ѻ҆́чи на́ши ко гдⷭ҇ꙋ бг҃ꙋ на́шемꙋ, до́ндеже ᲂу҆ще́дритъ ны̀."),
    col2("Pokánie som si nezískal ani slzy; preto ťa prosím, Kriste Bože, obráť ma skôr, než príde koniec, a daj mi kajúcne pohnutie srdca, aby som bol vyslobodený od múk."),
    "",
    gText("Поми́лꙋй на́съ, гдⷭ҇и, поми́лꙋй на́съ, ꙗ҆́кѡ по мно́гꙋ и҆спо́лнихомсѧ ᲂу҆ничиже́нїѧ: наипа́че напо́лнисѧ дꙋша̀ на́ша поноше́нїѧ гобзꙋ́ющихъ, и҆ ᲂу҆ничиже́нїѧ го́рдыхъ."),
    col2("Tvoji mučeníci, Pane, sa neodvrhli od teba ani neodstúpili od tvojich prikázaní. Ich modlitbami sa nad nami zmiluj."),
    "",
    gText([#translation.at("SI")]),
    col2("Zaspievajme archanjelsky, verní, tú, ktorá je nebeskou komnatou a vpravde zapečatenou bránou: Raduj sa, pre ktorú nám vyrástol Spasiteľ všetkých, Kristus, Darca života a Boh. Zvrhni, Vládkyňa, mučiteľov, našich bezbožných nepriateľov, svojou rukou, Prečistá, nádej kresťanov."),
    cText[$#sym.ast.circle$],
    cText("Simeon, nacalo, K: 12xHP, tropar ak je, prepustenie"),
  ))
  #generateTable((
    col2([== #translation.at("U")]),
    cText[$#sym.ast.circle$],
    cText("Nacalo, Z19, Z20, nacalo, tropare, 12xHP, Slava svatej, 6zalmie, 12xHP, BohHospod"),
    col2([=== #translation.at("SIDALENY") ]),
    col2([==== #translation.at("SIDALEN_PO") 1 ]),
    col2(sub(sText("(1)"))+"Rozjímam o strašnom dni a oplakávam svoje zlé skutky: ako odpoviem Nesmrteľnému Kráľovi? Akou smelosťou vzhliadnem k Sudcovi ja, smilník? Dobrotivý Otče, Jednorodený Synu a Svätý Duchu, zmiluj sa nado mnou."),
    col2(sub(sText("(2)"))+"V údolí plaču, na mieste, ktoré si ustanovil, keď, Milostivý, zasadneš vyniesť spravodlivý súd, neodhaľuj moje skryté veci ani ma nezahanbuj pred anjelmi, ale ušetri ma, Bože, a zmiluj sa nado mnou."),
    "",
    gText([#translation.at("SI")]),
    col2("Preslávnu Božiu Matku, svätejšiu ako svätí anjeli, neprestajne ospevujme srdcom i ústami, vyznávajúc ju ako Bohorodičku, že vskutku porodila vteleného Boha a neprestajne sa modlí za naše duše."),
    col2([==== #translation.at("SIDALEN_PO") 2 ]),
    col2(sub(sText("(1)"))+"Zmiluj sa nad nami, Pane, zmiluj sa nad nami; lebo nevieme nájsť nijakú odpoveď. Túto modlitbu ti, ako Vládcu, my hriešni prinášame: zmiluj sa nad nami."),
    col2(sub(sText("(2)"))+"Pane, zmiluj sa nad nami, lebo v teba sme dúfali; nehnevaj sa na nás preveľmi ani nespomínaj na naše neprávosti, ale zhliadni na nás teraz ako milosrdný a vysloboď nás od našich nepriateľov. Lebo Ty si náš Boh a my sme Tvoj ľud, všetci sme dielom Tvojich rúk a Tvoje meno vzývame."),
    col2(sub(sText("(3)"))+"Svetlo je spravodlivým vždy; svätí, lebo tebou osvietení, žiaria ustavične ako svetlá, keď uhasili svietnik neveriacich. Ich modlitbami, náš Spasiteľ, rozsvieť moju lampu, Pane, a zachráň ma."),
    "",
    gText([#translation.at("SI")]),
    col2("Keď stojíme v chráme tvojej slávy, zdá sa nám, že stojíme v nebi. Bohorodička, nebeská brána, otvor nám brány svojho milosrdenstva."),
    col2([==== #translation.at("SIDALEN_PO") 3 ]),
    col2(sub(sText("(1)"))+"Desím sa, Kriste, strašného dňa tvojho príchodu a bojím sa neúprosného súdu, chvejem sa, lebo mám množstvo hriechov; no pred koncom ma obráť a spas, lebo si milosrdný Boh, modlitbami tvojich anjelov, dobrotivý Spasiteľu, jediný ľuďomilný."),
    col2(sub(sText("(2)"))+"Duša, celý svoj život tráviš v lenivosti, deň hrozného súdu nemáš na pamäti; prebuď sa teda a zvoľ si pokánie, obráť sa a zvolaj ku Kristovi: Milosrdný, nespomínaj naše mnohé hriechy v hodine odsúdenia."),
    "",
    gText([#translation.at("SI")]),
    col2("Nádej, ochrana a útočisko pre tých, čo v teba dúfajú, dobrotivá Bohorodička, orodovnica za svet, modli sa horlivo spolu s beztelesnými anjelmi k ľuďomilnému Bohu, ktorého si porodila, aby sa naše duše vyslobodili od každého odsúdenia, jediná požehnaná."),
    col2([=== #translation.at("KANON") ]),
    col2(sub(sText("(1)"))+"Viditeľný faraón bol utopený so všetkým vojskom, Izrael však prešiel stredom mora a volal: Spievajme Pánovi, nášmu Bohu, lebo sa preslávil."),
    col2(sub(sText("(3)"))+"Keď si upevnil zmýšľanie mojej duše na pevnej skale viery v teba, upevni ho, Pane; veď teba mám, Dobrotivý, za útočište i upevnenie."),
    col2(sub(sText("(4)"))+"Tvoja dobrota, Kriste, pokryla nebesá a tvojou chválou, Pane, sa všetko naplnilo."),
    col2(sub(sText("(5)"))+"Svetlo, ktoré zažiarilo svetu, Kriste, osvieť moje srdce, ktoré k tebe volá od noci, a zachráň ma."),
    col2(sub(sText("(6)"))+"Pohltený veľrybou hriechu, volám k Tebe, Kriste: ako si proroka vyslobodil z porušenia, vysloboď ma."),
    col2(sub(sText("(7)"))+"Keď si vyslyšal pieseň svojich svätých mládencov a rozpálenú pec si rosou ovlažil, požehnaný si, Pane, Bože našich otcov."),
    col2(sub(sText("(8)"))+"Tvoji ctihodní mládenci v peci napodobnili cherubínov, spievajúc trisvätú pieseň: Dobrorečte, spievajte a vyvyšujte ho po všetky veky."),
    col2(sub(sText("(9)"))+"Ty, ktorá si od anjela prijala pozdrav „Raduj sa“ a porodila svojho Stvoriteľa, Panna, zachráň tých, čo ťa zvelebujú."),
    col2([=== #translation.at("CHVALITE") ]),
    sub(sText("(4)")),
    gText("Хвали́те є҆го̀ въ тѷмпа́нѣ и҆ ли́цѣ, хвали́те є҆го̀ во стрꙋ́нахъ и҆ ѻ҆рга́нѣ."),
    col2("Nepriateľ ma našiel nahého bez cností a zranil ma šípom hriechu; ale ty, ako lekár duší i tiel, uzdrav rany mojej duše, Bože, a zmiluj sa nado mnou."),
    sub(sText("(3)")),
    gText("Хвали́те є҆го̀ въ кѷмва́лѣхъ доброгла́сныхъ, хвали́те є҆го̀ въ кѷмва́лѣхъ восклица́нїѧ: всѧ́кое дыха́нїе да хва́литъ гдⷭ҇а."),
    col2("Strupy môjho srdca, ktoré vyrástli z mnohých hriechov, uzdrav, Spasiteľu, ako lekár duší i tiel; ty, ktorý dávaš prosiacim odpustenie prestúpení, ustavične mi daruj slzy pokánia, udeľ mi odpustenie dlhov, Pane, a zmiluj sa nado mnou."),
    sub(sText("(2)")),
    gText("Воскрⷭ҇нѝ гдⷭ҇и бж҃е мо́й, да вознесе́тсѧ рꙋка̀ твоѧ̀, не забꙋ́ди ᲂу҆бо́гихъ твои́хъ до конца̀."),
    col2("Pane, na pamiatku tvojich svätých slávi celé stvorenstvo; nebesia sa radujú spolu s anjelmi a zem sa teší s ľuďmi. Ich modlitbami zmiluj sa nad nami."),
    sub(sText("(1)")),
    gText("И҆сповѣ́мсѧ тебѣ̀ гдⷭ҇и всѣ́мъ се́рдцемъ мои́мъ, повѣ́мъ всѧ̑ чꙋдеса̀ твоѧ̑."),
    col2("Archanjelské slovo si prijala a ukázala si sa ako cherubínsky trón, a na ruke si nosila, Bohorodička, nádej našich duší."),
  ))
])
