#import "../../../all.typ": *
#columns(2, gutter: 2pt, [

  #generateTable((
    col2([== #translation.at("V")]),
    col2(align(center,sText("("+translation.at("Po_V")+")"))),
    cText[$#sym.ast.circle$],
    cText("Nacalo, 103, 12xHP, Kathisma, 3xHP, HV, 104 a 141 a 129"),
    col2([=== #translation.at("HOSPODI_VOZVACH")]),
    sub(sText("(6)")),
    gText("И҆зведѝ и҆з̾ темни́цы дꙋ́шꙋ мою̀, и҆сповѣ́датисѧ и҆́мени твоемꙋ̀."),
    col2("Kto by nado mnou neplakal, že som pre nezdržanlivosť prestúpil prikázanie Najvyššieho? Namiesto raja som sa usídlil v pekle, kvôli pokrmu sladkému na pohľad, ktorý privodil smrť, a preň som sa stal cudzím Božej sláve a životu; ale prijmi ma kajúceho sa, Pane, lebo si milostivý a ľudomilný, pre svoje veľké milosrdenstvo."),
    sub(sText("(5)")),
    gText("Менѐ ждꙋ́тъ пра́вєдницы, до́ндеже возда́си мнѣ̀."),
    col2("Vzhliadni na môj smútok a bolesť, na nesmierne množstvo prehrešení, na trápenie mojej duše a rozumové poblúdenie; porozumej hlasu zúfalého a odsúdeného. Daj mi, Pane, skrušeného ducha a pokorné srdce a udeľ mi prameň sĺz i odpustenie mnohých prehrešení pre tvoje veľké milosrdenstvo."),
    sub(sText("(4)")),
    gText("И҆з̾ глꙋбины̀ воззва́хъ къ тебѣ̀ гдⷭ҇и, гдⷭ҇и, ᲂу҆слы́ши гла́съ мо́й."),
    col2("Bože, ty, ktorý chceš spásu všetkých ľudí, zhliadni a vyslyš moju modlitbu a neodmietni moje slzy ako márne. Veď kto prišiel k tebe v plači a hneď nebol spasen? Kto vrúcne volal k tebe a hneď nebol vyslyšaný? Ó, Vládca, rýchlo prichádzaš na spásu všetkým, čo sa k tebe modlia, lebo si vo svojom milosrdenstve nepremožiteľný."),
    sub(sText("(3)")),
    gText("Да бꙋ́дꙋтъ ᲂу҆́ши твоѝ, вне́млющѣ гла́сꙋ моле́нїѧ моегѡ̀."),
    col2("Na ceste života som zablúdil, nepohrdni mnou, Predchodca Spasiteľa; veď oči svojho srdca k tebe dvíham a upevni kroky mojej duše na skale pokánia; ukáž mi pravú cestu, aby som po nej kráčal, vedúcu k bránam spásy; a neodvrhni vzdychanie môjho zarmúteného srdca, najvznešenejší zo všetkých narodených."),
    sub(sText("(2)")),
    gText("А҆́ще беззакѡ́нїѧ на́зриши гдⷭ҇и, гдⷭ҇и, кто̀ постои́тъ; ꙗ҆́кѡ ᲂу҆ тебѐ ѡ҆чище́нїе є҆́сть."),
    col2("Krstiteľ a Predchodca Spasiteľa, buď mi pomocníkom, blahoslavený; mne, ponorenému v temnote nečistých myšlienok, podaj ruku, ktorá sa dotkla neporušiteľného temena; posilni ma statočne konať skutky pokánia, ktoré si hlásal, a aby som bol vo vnútri Kráľovstva, čomu si prvý učil; učiň mňa, svojho služobníka, hodným."),
    sub(sText("(1)")),
    gText("И҆́мене ра́ди твоегѡ̀ потерпѣ́хъ тѧ̀ гдⷭ҇и, потерпѣ̀ дꙋша̀ моѧ̀ въ сло́во твоѐ, ᲂу҆пова̀ дꙋша̀ моѧ̀ на гдⷭ҇а."),
    col2("Ty, ktorý si svojím narodením rozviazal matkinu neplodnosť a otcovu nemotu, rozviaž neplodnosť môjho jalového srdca; a každú nemotu duše rýchlo odním, veď si hlas Slova, hlásajúci pokánie. Učiň ma hodným, aby som ho vždy konal, mňa, ktorý som sa pre lenivosť vzdialil od Boha, Krstiteľ Kristov."),
    "",
    gText([#translation.at("SI")]),
    col2("Preukáž, Prečistá Panna, na mne biednom priepasť tvojej ľudomilnosti, aj hĺbku tvojho milosrdenstva a dobrotu tvojich nespočítateľných štedrostí. Uhas plameň hriechu, daruj mi čistotu a zachovaj moju dušu i telo nepoškvrnené, ty, ktorá si porodila Spasiteľa."),
    cText[$#sym.ast.circle$],
    cText("Svite tichyj"),
    col2([=== #translation.at("PROKIMEN")]),
    col2("Гдⷭ҇ь ᲂу҆слы́шитъ мѧ̀, внегда̀ воззва́ти мѝ къ немꙋ̀."),
    sText(translation.at("ST")),
    "Внегда̀ призва́ти мѝ, ᲂу҆слы́ша мѧ̀ бг҃ъ пра́вды моеѧ̀.",
    cText[$#sym.ast.circle$],
    cText("N/S: 12xHP, Spodobi Hospodi, 12xHP"),
    col2([=== #translation.at("STICHOVNI")]),
    col2("Pri Tvojom strašnom príchode, Kriste, nech nepočujeme: „Nepoznám vás“; veď v Teba, Spasiteľu, sme vložili svoju nádej, hoci sme pre svoju nedbanlivosť nezachovali Tvoje prikázania; ale zmiluj sa nad našimi dušami, prosíme."),
    "",
    gText("Къ тебѣ̀ возведо́хъ ѻ҆́чи моѝ, живꙋ́щемꙋ на нб҃сѝ. сѐ ꙗ҆́кѡ ѻ҆́чи ра̑бъ въ рꙋкꙋ̀ госпо́дїй свои́хъ, ꙗ҆́кѡ ѻ҆́чи рабы́ни въ рꙋкꙋ̀ госпожѝ своеѧ̀: та́кѡ ѻ҆́чи на́ши ко гдⷭ҇ꙋ бг҃ꙋ на́шемꙋ, до́ндеже ᲂу҆ще́дритъ ны̀."),
    col2("Pokánie som si nezískal ani slzy; preto ťa prosím, Kriste Bože, obráť ma skôr, než príde koniec, a daj mi kajúcne pohnutie srdca, aby som bol vyslobodený od múk."),
    "",
    gText("Поми́лꙋй на́съ, гдⷭ҇и, поми́лꙋй на́съ, ꙗ҆́кѡ по мно́гꙋ и҆спо́лнихомсѧ ᲂу҆ничиже́нїѧ: наипа́че напо́лнисѧ дꙋша̀ на́ша поноше́нїѧ гобзꙋ́ющихъ, и҆ ᲂу҆ничиже́нїѧ го́рдыхъ."),
    col2("Strastoterpci, mučeníci, nebeskí občania, ktorí na zemi trpeli a znášali mnohé muky. Ich modlitbami, Pane, a prosbami zachovaj nás všetkých."),
    "",
    gText([#translation.at("SI")]),
    col2("Nikto, kto sa k tebe utieka, neodchádza od teba zahanbený, prečistá Bohorodička, Panna; ale prosí o milosť a prijíma dar podľa osožnej prosby."),
    cText[$#sym.ast.circle$],
    cText("Simeon, nacalo, K: 12xHP, tropar ak je, prepustenie"),
  ))
  #generateTable((
    col2([== #translation.at("U")]),
    cText[$#sym.ast.circle$],
    cText("Nacalo, Z19, Z20, nacalo, tropare, 12xHP, Slava svatej, 6zalmie, 12xHP, BohHospod"),
    col2([=== #translation.at("SIDALENY") ]),
    col2([==== #translation.at("SIDALEN_PO") 1 ]),
    col2(sub(sText("(1)"))+"Rozjímam o strašnom dni a oplakávam svoje zlé skutky: ako odpoviem Nesmrteľnému Kráľovi? Akou smelosťou vzhliadnem k Sudcovi ja, smilník? Dobrotivý Otče, Jednorodený Synu a Svätý Duchu, zmiluj sa nado mnou."),
    col2(sub(sText("(2)"))+"V údolí plaču, na mieste, ktoré si ustanovil, keď, Milostivý, zasadneš vyniesť spravodlivý súd, neodhaľuj moje skryté veci ani ma nezahanbuj pred anjelmi, ale ušetri ma, Bože, a zmiluj sa nado mnou."),
    "",
    gText([#translation.at("SI")]),
    col2("Brány milosrdenstva nám otvor, blahoslavená Bohorodička, Panna; v Teba dúfajúci nech nezahynieme, ale nech sme Tebou vyslobodení z bied, lebo Ty si spása rodu kresťanského."),
    col2([==== #translation.at("SIDALEN_PO") 2 ]),
    col2(sub(sText("(1)"))+"Duša moja, prečo, skľúčená, slúžiš hriechu? A prečo, chorá, neprichádzaš k lekárovi? Povstaň už od zla, ktoré si vykonala, a zvolaj k Spasiteľovi, hovoriac: Nádej beznádejných, Život zúfalých, Spasiteľu, pozdvihni a spas ma."),
    col2(sub(sText("(2)"))+"Daruj mi, Pane, bdelosť múdrych panien a sviecu mojej duše osvieť olejom Tvojich milosrdenstiev, aby som Ti spieval anjelskú pieseň: Aleluja."),
    col2(sub(sText("(3)"))+"Svätí, ktorí ste pretrpeli strastotrpecký boj a od Teba prijali pocty víťazstva, zmarili ste úmysly bezbožných a prijali neporušiteľné vence. Na ich príhovor, Bože, daruj nám veľké milosrdenstvo."),
    "",
    gText([#translation.at("SI")]),
    col2("Nádej sveta, dobrotivá Bohorodička Panna, o tvoje jediné úctyhodné orodovanie prosíme: zľutuj sa nad bezmocnými ľuďmi, oroduj u milosrdného Boha, aby boli naše duše vyslobodené od každého trestu, jediná požehnaná."),
    col2([==== #translation.at("SIDALEN_PO") 3 ]),
    col2(sub(sText("(1)"))+"Ty si ukázal ľuďom cesty života, Ján, volajúc: Upravte svoje srdcia Pánovi. Zachráň moju mnohoriešnu dušu, priveď moju zatvrdnutú myseľ ku kajúcnosti a vysloboď ma od budúcich múk svojimi modlitbami, Predchodca Spasiteľa."),
    col2(sub(sText("(2)"))+"Búrka vášní a kruté rozbúrenie prehrešení ma potopili do hlbín zúfalstva, ó Slovo; no vystri ku mne Tvoju mocnú pravicu a zachráň ma ako Petra, svätými modlitbami Tvojho Predchodcu, z hlbín mojich preukrutných bezákonností."),
    "",
    gText([#translation.at("SI")]),
    col2("Toho, ktorý pred vekmi bol z Otca bez matky splodený, Syna a Božie Slovo, a ktorého si v posledných časoch bez muža porodila vteleného z tvojej čistej krvi, Bohorodička, pros, aby nám udelil odpustenie hriechov pred koncom."),
    col2([=== #translation.at("KANON") ]),
    col2(sub(sText("(1)"))+"Pomocník a ochranca bol mi na spásu; tento je môj Boh a oslávim ho, Boh môjho otca a vyvýšim ho; lebo slávne sa oslávil."),
    col2(sub(sText("(3)"))+"Utvrď, Pane, moje pohnuté srdce na skale tvojich prikázaní, lebo ty jediný si svätý a Pán."),
    col2(sub(sText("(4)"))+"Prorok počul o tvojom príchode, Pane, a zhrozil sa, že sa chceš narodiť z Panny a zjaviť sa ako človek, a hovoril: Počul som tvoj chýr a preľakol som sa. Sláva tvojej moci, Pane."),
    col2(sub(sText("(5)"))+"Od noci, vstávajúc k utierni, ó Milovník ľudí, osvieť ma, prosím, a nasmeruj aj mňa na tvoje prikázania a nauč ma, Spasiteľu, konať tvoju vôľu."),
    col2(sub(sText("(6)"))+"Zvolal som celým svojím srdcom k milosrdnému Bohu a vyslyšal ma z najhlbšieho pekla a vyviedol môj život zo skazy."),
    col2(sub(sText("(7)"))+"Zhrešili sme, bezbožne sme konali, neprávosť sme páchali pred tebou; ani sme nezachovali, ani sme nevykonali, ako si nám prikázal; no nevydaj nás do konca, Bože našich otcov."),
    col2(sub(sText("(8)"))+"Toho, ktorého chvália nebeské mocnosti a pred ktorým sa chvejú cherubíni i serafíni, nech všetko, čo dýcha, i celé stvorenstvo spieva, dobrorečí a zvelebuje ho po všetky veky."),
    col2(sub(sText("(9)"))+"Nevysloviteľné je narodenie z bezsémenného počatia, neporušený plod bezmužnej Matky; veď Božie narodenie obnovuje prirodzenstvo. Preto ťa všetky pokolenia ako Bohonevestnú Matku pravoslávne zvelebujeme."),
    col2([=== #translation.at("CHVALITE") ]),
    sub(sText("(4)")),
    gText("Хвали́те є҆го̀ въ тѷмпа́нѣ и҆ ли́цѣ, хвали́те є҆го̀ во стрꙋ́нахъ и҆ ѻ҆рга́нѣ."),
    col2("Nepriateľ ma našiel nahého bez cností a zranil ma šípom hriechu; ale ty, ako lekár duší i tiel, uzdrav rany mojej duše, Bože, a zmiluj sa nado mnou."),
    sub(sText("(3)")),
    gText("Хвали́те є҆го̀ въ кѷмва́лѣхъ доброгла́сныхъ, хвали́те є҆го̀ въ кѷмва́лѣхъ восклица́нїѧ: всѧ́кое дыха́нїе да хва́литъ гдⷭ҇а."),
    col2("Strupy môjho srdca, ktoré vyrástli z mnohých hriechov, uzdrav, Spasiteľu, ako lekár duší i tiel; ty, ktorý dávaš prosiacim odpustenie prestúpení, ustavične mi daruj slzy pokánia, udeľ mi odpustenie dlhov, Pane, a zmiluj sa nado mnou."),
    sub(sText("(2)")),
    gText("Воскрⷭ҇нѝ гдⷭ҇и бж҃е мо́й, да вознесе́тсѧ рꙋка̀ твоѧ̀, не забꙋ́ди ᲂу҆бо́гихъ твои́хъ до конца̀."),
    col2("Pane, keby sme nemali tvojich svätých za orodovníkov a tvoje k nám milosrdenstvo, ako by sme sa, Spasiteľ, odvážili spievať ti, ktorého anjeli neprestajne velebia? Ty, ktorý poznáš srdcia, zľutuj sa nad našimi dušami."),
    sub(sText("(1)")),
    gText("И҆сповѣ́мсѧ тебѣ̀ гдⷭ҇и всѣ́мъ се́рдцемъ мои́мъ, повѣ́мъ всѧ̑ чꙋдеса̀ твоѧ̑."),
    col2("Čistá Panna Bohorodička, stala si sa hodnou veľkých darov, lebo si v tele porodila Jedného z Trojice, Krista Životodarcu, na spásu našich duší."),
  ))
])
