#import "../../../all.typ": *
#columns(2, gutter: 2pt, [

  #generateTable((
    col2([== #translation.at("V")]),
    col2(align(center,sText("("+translation.at("Ut_V")+")"))),
    cText[$#sym.ast.circle$],
    cText("Nacalo, 103, 12xHP, Kathisma, 3xHP, HV, 104 a 141 a 129"),
    col2([=== #translation.at("HOSPODI_VOZVACH")]),
    sub(sText("(6)")),
    gText("И҆зведѝ и҆з̾ темни́цы дꙋ́шꙋ мою̀, и҆сповѣ́датисѧ и҆́мени твоемꙋ̀."),
    col2("Keď si bol ukrižovaný, dlhozhovievajúci Pane, otrasol si celou zemou, srdcia verných si však utvrdil. Preto ťa ospevujeme a s láskou sa klaniame tvojej nepochopiteľnej sile."),
    sub(sText("(5)")),
    gText("Менѐ ждꙋ́тъ пра́вєдницы, до́ндеже возда́си мнѣ̀."),
    col2("Na líce si bol uderený, Spasiteľu, a opľutý; zasadil si úder jedovatej zlobe nepriateľa, odnímajúc pád, ktorý utrpel Adam, olúpený pre vidinu."),
    sub(sText("(4)")),
    gText("И҆з̾ глꙋбины̀ воззва́хъ къ тебѣ̀ гдⷭ҇и, гдⷭ҇и, ᲂу҆слы́ши гла́съ мо́й."),
    col2("Slnko sa zatmelo, celá zem sa triasla a skaly sa rozštiepili, keď Ťa, Spasiteľu, videli nespravodlivo zaveseného na dreve a že si sa zriekol vlastnej vôle."),
    sub(sText("(3)")),
    gText("Да бꙋ́дꙋтъ ᲂу҆́ши твоѝ, вне́млющѣ гла́сꙋ моле́нїѧ моегѡ̀."),
    col2("Keď Panna stála pri kríži v čase ukrižovania s panenským učeníkom, plačúc volala: Beda mi, ako trpíš, Kriste, ktorý si bezstrasnosť všetkých."),
    sub(sText("(2)")),
    gText("А҆́ще беззакѡ́нїѧ на́зриши гдⷭ҇и, гдⷭ҇и, кто̀ постои́тъ; ꙗ҆́кѡ ᲂу҆ тебѐ ѡ҆чище́нїе є҆́сть."),
    col2("Keď rozjímam o tvojom bezsemennom počatí a prečistom narodení, veľmi sa divím: ako si takto, ako zločinec, uznal za dobré zomrieť, ó Spasiteľu? – zvolala Prečistá."),
    sub(sText("(1)")),
    gText("И҆́мене ра́ди твоегѡ̀ потерпѣ́хъ тѧ̀ гдⷭ҇и, потерпѣ̀ дꙋша̀ моѧ̀ въ сло́во твоѐ, ᲂу҆пова̀ дꙋша̀ моѧ̀ на гдⷭ҇а."),
    col2("Veru som ukrižovaný na dreve kríža a som pribíjaný ako človek, a do hrobu som kladený ako mŕtvy, Matka prečistá, Panna; no ako Boh znova v sláve vstanem na tretí deň."),
    "",
    gText([#translation.at("SI")]),
    col2("Najbezbožnejší ľudia ťa nespravodlivo pribíjali na drevo; keď to uzrela Panna, tvoja prečistá Matka, ako predpovedal Simeon, bola, Spasiteľu, ranená vo svojom lone."),
    cText[$#sym.ast.circle$],
    cText("Svite tichyj"),
    col2([=== #translation.at("PROKIMEN")]),
    col2("Млⷭ҇ть твоѧ̀ гдⷭ҇и, пожене́тъ мѧ̀ всѧ̑ дни̑ живота̀ моегѡ̀."),
    sText(translation.at("ST")),
    "Гдⷭ҇ь пасе́тъ мѧ̀, и҆ ничто́же мѧ̀ лиши́тъ, на мѣ́стѣ ѕла́чнѣ, та́мѡ всели́ мѧ.",
    cText[$#sym.ast.circle$],
    cText("N/S: 12xHP, Spodobi Hospodi, 12xHP"),
    col2([=== #translation.at("STICHOVNI")]),
    col2("Tvoj kríž, Pane, je život a ochrana tvojmu ľudu; a tí, čo v ňom dúfajú, tebe, ukrižovanému v tele, nášmu Bohu, spievame: zmiluj sa nad nami."),
    "",
    gText("Къ тебѣ̀ возведо́хъ ѻ҆́чи моѝ, живꙋ́щемꙋ на нб҃сѝ. сѐ ꙗ҆́кѡ ѻ҆́чи ра̑бъ въ рꙋкꙋ̀ госпо́дїй свои́хъ, ꙗ҆́кѡ ѻ҆́чи рабы́ни въ рꙋкꙋ̀ госпожѝ своеѧ̀: та́кѡ ѻ҆́чи на́ши ко гдⷭ҇ꙋ бг҃ꙋ на́шемꙋ, до́ндеже ᲂу҆ще́дритъ ны̀."),
    col2("Tvoj kríž, Pane, otvoril raj ľudskému rodu; oslobodení od porušiteľnosti, spievame Tebe, nášmu Bohu, ukrižovanému v tele: zmiluj sa nad nami."),
    "",
    gText("Поми́лꙋй на́съ, гдⷭ҇и, поми́лꙋй на́съ, ꙗ҆́кѡ по мно́гꙋ и҆спо́лнихомсѧ ᲂу҆ничиже́нїѧ: наипа́че напо́лнисѧ дꙋша̀ на́ша поноше́нїѧ гобзꙋ́ющихъ, и҆ ᲂу҆ничиже́нїѧ го́рдыхъ."),
    col2("Tí, ktorí pre Teba, Kriste, trpeli, podstúpili mnohé muky a prijali na nebesiach dokonalé vence; nech sa modlia za naše duše."),
    "",
    gText([#translation.at("SI")]),
    col2("Keď Prečistá Bohorodička uzrela náš Život visieť na dreve, matersky nariekajúc zvolala: Syn môj a Boh môj, spas tých, čo ťa s láskou ospevujú."),
    cText[$#sym.ast.circle$],
    cText("Simeon, nacalo, K: 12xHP, tropar ak je, prepustenie"),
  ))
  #generateTable((
    col2([== #translation.at("U")]),
    cText[$#sym.ast.circle$],
    cText("Nacalo, Z19, Z20, nacalo, tropare, 12xHP, Slava svatej, 6zalmie, 12xHP, BohHospod"),
    col2([=== #translation.at("SIDALENY") ]),
    col2([==== #translation.at("SIDALEN_PO") 1 ]),
    col2(sub(sText("(1)"))+"Tvoj kríž, Pane, sa posvätil; lebo ním prichádzajú uzdravenia chorým v hriechoch. Preto pred tebou padáme, zmiluj sa nad nami."),
    col2(sub(sText("(2)"))+"Len čo bolo vztyčené drevo tvojho kríža, Kriste, otriasli sa základy smrti, Pane; lebo peklo toho, ktorého nenásytne pohltilo, prepustilo s chvením; ukázal si nám svoje spasenie, Svätý; a oslavujeme ťa, Syn Boží, zmiluj sa nad nami."),
    "",
    gText([#translation.at("SI")]),
    col2("Nádej, zástupkyňa a útočište tvojho ľudu, Panna, veď z teba sa vpravde zrodila spása svetu. Ako si plakala pri kríži svojho Syna a Boha a zachraňuješ tých, čo v teba dúfajú, jeho teraz vypros, aby vyslobodil od skazy všetkých, čo ťa ospevujú."),
    col2([==== #translation.at("SIDALEN_PO") 2 ]),
    col2(sub(sText("(1)"))+"Dnes sa naplnilo prorocké slovo: hľa, klaniame sa na mieste, kde stáli tvoje nohy, Pane, a keď sme okúsili strom spásy, dosiahli sme oslobodenie od hriechu vášní, na príhovor Bohorodičky, jediný Milovník ľudí."),
    col2(sub(sText("(2)"))+"Pane, Židia ťa, život všetkých, odsúdili na smrť; tí, čo s palicou prešli Červené more, ťa pribili na kríž; a tí, čo z kameňa sali med, ti podali žlč. No dobrovoľne si to pretrpel, aby si nás oslobodil od otroctva nepriateľa: Kriste, Bože náš, sláva tebe."),
    col2(sub(sText("(3)"))+"Mučenícke zápasy na súde, mučiteľské rany na mučeníkoch a zbory beztelesných, nesúce pocty víťazstva, udivili mučiteľov i kráľov; premúdri mučeníci Kristovým vyznaním zvrhli prestupníka. Pane, ktorý si ich posilnil, sláva tebe."),
    "",
    gText([#translation.at("SI")]),
    col2("Stojac pri kríži neporušená panenská Matka zvolala k tomu, ktorý sa z nej narodil bez semena: Meč prebodne moje srdce, ó Synu; nevládzem zniesť vidieť ťa visieť na dreve, teba, pred ktorým sa chveje celé stvorenstvo ako pred Stvoriteľom a Bohom. Dlhotrpezlivý Pane, sláva tebe."),
    col2([==== #translation.at("SIDALEN_PO") 3 ]),
    col2(sub(sText("(1)"))+"Na kríži si sa z vlastnej vôle pre nás nechal pribiť, Kriste; stvorenstvo, vidiac to, sa chvelo strachom: slnko úplne zatemnilo svoje svetlo, skaly sa rozpukli a božská chrámová opona sa roztrhla — na usvedčenie krutých a bezzákonných Židov."),
    col2(sub(sText("(2)"))+"Strom priniesol praotcovi v Edene porušenosť; krížové drevo však rozkvitlo životom na Mieste Lebky; lebo zloba nepriateľova bola pošliapaná; a pribitím Kristovým bol omilostený a našiel raj, zvolal Adam: Ó, požehnané drevo!"),
    "",
    gText([#translation.at("SI")]),
    col2("Vždy Panna, panna dievčina, ktorá ťa porodila, Kriste, keď ťa videla pre nás pozdvihnutého na kríži, svojím žiaľom akoby mečom zraňovala svoje srdce i dušu a matersky plačúc nariekala; jej modlitbami sa nad nami zmiluj."),
    col2([=== #translation.at("KANON") ]),
    col2(sub(sText("(1)"))+"Ako Izraeliti kráčali po suchu po bezodnej hlbine, vidiac, ako sa prenasledovateľ faraón topí, spievali Bohu víťaznú pieseň a volali."),
    col2(sub(sText("(3)"))+"Niet svätého ako Ty, Pane, môj Bože, ktorý si pozdvihol roh svojich verných, ó Blažený, a upevnil si nás na skale Tvojho vyznania."),
    col2(sub(sText("(4)"))+"Kristus je moja sila, Boh a Pán; ctihodná Cirkev boholepne spieva, z čistej mysle volajúc, sláviac sviatok Pánovi."),
    col2(sub(sText("(5)"))+"Božím tvojím svetlom, Blažený, osvieť duše tých, čo ti s láskou konajú rannú modlitbu; modlím sa, aby som ťa poznal, Slovo Božie, ako pravého Boha, volajúc z temnoty hriechu."),
    col2(sub(sText("(6)"))+"Keď vidím more života rozbúrené búrkou protivenstiev, utekám sa k tvojmu tichému prístavu a volám k tebe: pozdvihni môj život z porušenia, Mnohomilosrdný."),
    col2(sub(sText("(7)"))+"Anjel urobil pec rosodarnou pre ctihodných mládencov, kým Chaldejcov spálilo Božie nariadenie; mučiteľa prinútil volať: Požehnaný si, Bože, otcov našich."),
    col2(sub(sText("(8)"))+"Z plameňa si zbožným zoslal rosu a spravodlivého obetu si vodou spálil: veď všetko konáš, Kriste, stačí len chcieť. Teba zvelebujeme po všetky veky."),
    col2(sub(sText("(9)"))+"Boha nie je možné ľuďom vidieť, na ktorého sa neodvažujú hľadieť ani anjelské chóry; ale skrze teba, Prečistá, sa ľuďom zjavilo vtelené Slovo; jeho zvelebujúc, spolu s nebeskými zástupmi ťa blahoslavíme."),
    col2([=== #translation.at("CHVALITE") ]),
    sub(sText("(4)")),
    gText("Хвали́те є҆го̀ въ тѷмпа́нѣ и҆ ли́цѣ, хвали́те є҆го̀ во стрꙋ́нахъ и҆ ѻ҆рга́нѣ."),
    col2("V kríži mám nádej, Kriste, a ním sa chváliac volám: Človekamilý Pane, zvrhni pýchu tých, čo nevyznávajú, že si Boh i človek."),
    sub(sText("(3)")),
    gText("Хвали́те є҆го̀ въ кѷмва́лѣхъ доброгла́сныхъ, хвали́те є҆го̀ въ кѷмва́лѣхъ восклица́нїѧ: всѧ́кое дыха́нїе да хва́литъ гдⷭ҇а."),
    col2("My, ktorí sme chránení Krížom, odporujeme nepriateľovi, nebojíme sa jeho úkladov ani štekania; lebo pyšný bol zneškodnený a pošliapaný mocou Krista pribitého na drevo kríža."),
    sub(sText("(2)")),
    gText("Воскрⷭ҇нѝ гдⷭ҇и бж҃е мо́й, да вознесе́тсѧ рꙋка̀ твоѧ̀, не забꙋ́ди ᲂу҆бо́гихъ твои́хъ до конца̀."),
    col2("Pamiatka mučeníkov, radosť bohabojných: lebo trpiac pre Krista prijali od Neho vence a teraz s dôverou sa modlia za naše duše."),
    sub(sText("(1)")),
    gText("И҆сповѣ́мсѧ тебѣ̀ гдⷭ҇и всѣ́мъ се́рдцемъ мои́мъ, повѣ́мъ всѧ̑ чꙋдеса̀ твоѧ̑."),
    col2("Keď Vládkyňa, od vekov nepoškvrnená a neporušená agnica, uzrela svojho Baránka na dreve kríža, matersky zvolala a v úžase hovorila: Najsladšie dieťa, čo je toto nové a preslávne videnie? Ako ťa bezmilostný zástup vydal Pilátovmu súdu a odsudzuje na smrť Život všetkých? No ospevujem tvoje nevysloviteľné zostúpenie, Slovo."),
  ))
])
