#import "../../../all.typ": *
#columns(2, gutter: 2pt, [

  #generateTable((
    col2([== #translation.at("V")]),
    col2(align(center,sText("("+translation.at("Sr_V")+")"))),
    cText[$#sym.ast.circle$],
    cText("Nacalo, 103, 12xHP, Kathisma, 3xHP, HV, 104 a 141 a 129"),
    col2([=== #translation.at("HOSPODI_VOZVACH")]),
    sub(sText("(6)")),
    gText("И҆зведѝ и҆з̾ темни́цы дꙋ́шꙋ мою̀, и҆сповѣ́датисѧ и҆́мени твоемꙋ̀."),
    col2("Boli ste služobníkmi veľkých Božích tajomstiev, teológovia a bohovidci, učeníci; prijali ste milosť uzdravení a uzdravujete choroby všetkých ľudí."),
    sub(sText("(5)")),
    gText("Менѐ ждꙋ́тъ пра́вєдницы, до́ндеже возда́си мнѣ̀."),
    col2("Veľké útočisko a ochrana našim dušiam, vyhnanie zlých duchov ste vy, bohovidci, Pánovi apoštoli; preto vás ustavične uctievame."),
    sub(sText("(4)")),
    gText("И҆з̾ глꙋбины̀ воззва́хъ къ тебѣ̀ гдⷭ҇и, гдⷭ҇и, ᲂу҆слы́ши гла́съ мо́й."),
    col2("Vy, božskí blahoslavení apoštoli, vysloboďte tých, čo vás s vierou oslavujú, od každého súženia, od diabolského škodenia, od prehrešení a od zlého zajatia."),
    sub(sText("(3)")),
    gText("Да бꙋ́дꙋтъ ᲂу҆́ши твоѝ, вне́млющѣ гла́сꙋ моле́нїѧ моегѡ̀."),
    col2("Blažený Mikuláš, zmiluj sa nado mnou, keď padám pred tebou; prosím ťa, múdry, a osvieť oči mojej duše, aby som čisto uzrel štedrého Darcu svetla."),
    sub(sText("(2)")),
    gText("А҆́ще беззакѡ́нїѧ на́зриши гдⷭ҇и, гдⷭ҇и, кто̀ постои́тъ; ꙗ҆́кѡ ᲂу҆ тебѐ ѡ҆чище́нїе є҆́сть."),
    col2("Od nepriateľov, ktorí sa usilujú mi uškodiť, vysloboď ma, svätý; keďže máš smelosť u Boha, svätiteľu Mikuláš blažený, zachráň ma od úhony a vysloboď ma od muža krvi."),
    sub(sText("(1)")),
    gText("И҆́мене ра́ди твоегѡ̀ потерпѣ́хъ тѧ̀ гдⷭ҇и, потерпѣ̀ дꙋша̀ моѧ̀ въ сло́во твоѐ, ᲂу҆пова̀ дꙋша̀ моѧ̀ на гдⷭ҇а."),
    col2("Teba, svätiteľu, sme si teraz, verní, získali ako bezbúrlivé prístavisko a nepremožiteľnú hradbu, aj stĺp pevnosti, aj bránu pokánia, aj učiteľa našich duší, aj ochranný val."),
    "",
    gText([#translation.at("SI")]),
    col2("Závidiac tvojmu stádu, Prečistá, zlý protivník neustále bojuje, chcejúc si z nás urobiť potravu; ale ty, Bohorodička, zbav nás tej ujmy."),
    cText[$#sym.ast.circle$],
    cText("Svite tichyj"),
    col2([=== #translation.at("PROKIMEN")]),
    col2("Бж҃е, во и҆́мѧ твоѐ сп҃си́ мѧ, и҆ въ си́лѣ твое́й сꙋди́ ми."),
    sText(translation.at("ST")),
    "Бж҃е, ᲂу҆слы́ши мл҃твꙋ мою̀, внꙋшѝ глаго́лы ᲂу҆́стъ мои́хъ.",
    cText[$#sym.ast.circle$],
    cText("N/S: 12xHP, Spodobi Hospodi, 12xHP"),
    col2([=== #translation.at("STICHOVNI")]),
    col2("Pane, apoštoli raz sieťami dosiahli morskú hĺbku, inokedy zas pre učenie výšinu Kráľovstva. Raz umením skúmali nepochopiteľnú hĺbku; inokedy zase vierou dosiahli tvoje neobsiahnuteľné lono a svetu zvestovali tvojho predvečného Syna. Ich modlitbami a modlitbami všetkých svätých, zmiluj sa nad nami."),
    "",
    gText("Къ тебѣ̀ возведо́хъ ѻ҆́чи моѝ, живꙋ́щемꙋ на нб҃сѝ. сѐ ꙗ҆́кѡ ѻ҆́чи ра̑бъ въ рꙋкꙋ̀ госпо́дїй свои́хъ, ꙗ҆́кѡ ѻ҆́чи рабы́ни въ рꙋкꙋ̀ госпожѝ своеѧ̀: та́кѡ ѻ҆́чи на́ши ко гдⷭ҇ꙋ бг҃ꙋ на́шемꙋ, до́ндеже ᲂу҆ще́дритъ ны̀."),
    col2("Keď tvoji učeníci, Kriste, boli na lodi zmietaní búrkou, volali: Učiteľu, zachráň nás, hynieme. A aj teraz voláme: Človekamilý Spasiteľu náš, vysloboď nás z našich bied, modlíme sa."),
    "",
    gText("Поми́лꙋй на́съ, гдⷭ҇и, поми́лꙋй на́съ, ꙗ҆́кѡ по мно́гꙋ и҆спо́лнихомсѧ ᲂу҆ничиже́нїѧ: наипа́че напо́лнисѧ дꙋша̀ на́ша поноше́нїѧ гобзꙋ́ющихъ, и҆ ᲂу҆ничиже́нїѧ го́рдыхъ."),
    col2("Kríž tvoj, Pane, sa stal pre mučeníkov neporaziteľnou zbraňou: vidiac smrť, ktorá ležala pred nimi, a predvídajúc budúci život, posilňovali sa nádejou v teba. Na ich modlitby sa nad nami zmiluj."),
    "",
    gText([#translation.at("SI")]),
    col2("Oko svojho srdca pozdvihujem k tebe, Vládkyňa; neprehliadni moje malé vzdychanie v hodine, keď bude tvoj Syn súdiť svet; buď mi ochranou a pomocníčkou."),
    cText[$#sym.ast.circle$],
    cText("Simeon, nacalo, K: 12xHP, tropar ak je, prepustenie"),
  ))
  #generateTable((
    col2([== #translation.at("U")]),
    cText[$#sym.ast.circle$],
    cText("Nacalo, Z19, Z20, nacalo, tropare, 12xHP, Slava svatej, 6zalmie, 12xHP, BohHospod"),
    col2([=== #translation.at("SIDALENY") ]),
    col2([==== #translation.at("SIDALEN_PO") 1 ]),
    col2(sub(sText("(1)"))+"Ako si prišiel uprostred svojich učeníkov, Spasiteľ, a dával si im svoj pokoj, príď aj k nám a spas nás."),
    col2(sub(sText("(2)"))+"Zástup tvojich učeníkov osvietil celý svet: kedysi boli rybármi rýb, teraz sa stali rybármi ľudí; pre nich, Bože, zmiluj sa nad nami."),
    "",
    gText([#translation.at("SI")]),
    col2("Množstvo mojich hriechov je veľké, Bohorodička; k tebe sa utiekam, Čistá, potrebujúc spásu: navštív moju chorľavú dušu a pros svojho Syna a nášho Boha, aby mi dal odpustenie zlých skutkov, ktoré som spáchal, jediná Požehnaná."),
    col2([==== #translation.at("SIDALEN_PO") 2 ]),
    col2(sub(sText("(1)"))+"Tvoji učeníci, Spasiteľu, poslaní až po končiny zeme, pobožne uloviac národy ako ryby, priviedli ich k tvojej dobrote. Preto ti voláme, Kriste: svojmu ľudu udeľ veľké milosrdenstvo."),
    col2(sub(sText("(2)"))+"Dvanástka apoštolov, Pane, ako dvanásťlúčové slnko sa zjavila zemi; pre nich si zmaril rozsievača klamu; pre nich osvecuješ duše svojich služobníkov; a aj nás pre nich spas, lebo si milosrdný."),
    col2(sub(sText("(3)"))+"Pane, pamiatka tvojich svätých sa dnes zjavila ako raj v Edene; lebo v ňom sa raduje celé stvorenstvo; a ich modlitbami nám udeľuješ pokoj a veľké milosrdenstvo."),
    "",
    gText([#translation.at("SI")]),
    col2("Presvätá Bohorodička, počas môjho života ma neopúšťaj; ľudskému orodovaniu ma nezver; ale sama sa ma zastaň a zmiluj sa nado mnou."),
    col2([==== #translation.at("SIDALEN_PO") 3 ]),
    col2(sub(sText("(1)"))+"Po celej zemi ako blesky vyšlo spásonosné hlásanie tvojich múdrych učeníkov, Vládca, Kriste, a osvietilo tých, čo boli v temnote a ukrutnostiach, urobilo z nás synov dňa a svetla. Preto ťa všetko stvorenstvo zbožne oslavuje."),
    col2(sub(sText("(2)"))+"Rybári sieťou božskej viery obrátili ľudí, všetkých vytiahli z hlbiny márnosti a odovzdali ich Bohu; tí Ho zbožne uctievajú a ustavične Ho velebia."),
    "",
    gText([#translation.at("SI")]),
    col2("Svätá Vládkyňa, Matka Krista, nášho Boha, ktorá si nevýslovne porodila Stvoriteľa všetkých, pros spolu so svätými apoštolmi vždy Jeho dobrotu, aby nás oslobodila od vášní a darovala nám odpustenie hriechov."),
    col2([=== #translation.at("KANON") ]),
    col2(sub(sText("(1)"))+"Ako Izraeliti kráčali po suchu po bezodnej hlbine, vidiac, ako sa prenasledovateľ faraón topí, spievali Bohu víťaznú pieseň a volali."),
    col2(sub(sText("(3)"))+"Niet svätého ako Ty, Pane, môj Bože, ktorý si pozdvihol roh svojich verných, ó Blažený, a upevnil si nás na skale Tvojho vyznania."),
    col2(sub(sText("(4)"))+"Kristus je moja sila, Boh a Pán; ctihodná Cirkev boholepne spieva, z čistej mysle volajúc, sláviac sviatok Pánovi."),
    col2(sub(sText("(5)"))+"Božím tvojím svetlom, Blažený, osvieť duše tých, čo ti s láskou konajú rannú modlitbu; modlím sa, aby som ťa poznal, Slovo Božie, ako pravého Boha, volajúc z temnoty hriechu."),
    col2(sub(sText("(6)"))+"Keď vidím more života rozbúrené búrkou protivenstiev, utekám sa k tvojmu tichému prístavu a volám k tebe: pozdvihni môj život z porušenia, Mnohomilosrdný."),
    col2(sub(sText("(7)"))+"Anjel urobil pec rosodarnou pre ctihodných mládencov, kým Chaldejcov spálilo Božie nariadenie; mučiteľa prinútil volať: Požehnaný si, Bože, otcov našich."),
    col2(sub(sText("(8)"))+"Z plameňa si zbožným zoslal rosu a spravodlivého obetu si vodou spálil: veď všetko konáš, Kriste, stačí len chcieť. Teba zvelebujeme po všetky veky."),
    col2(sub(sText("(9)"))+"Boha nie je možné ľuďom vidieť, na ktorého sa neodvažujú hľadieť ani anjelské chóry; ale skrze teba, Prečistá, sa ľuďom zjavilo vtelené Slovo; jeho zvelebujúc, spolu s nebeskými zástupmi ťa blahoslavíme."),
    col2([=== #translation.at("CHVALITE") ]),
    sub(sText("(4)")),
    gText("Хвали́те є҆го̀ въ тѷмпа́нѣ и҆ ли́цѣ, хвали́те є҆го̀ во стрꙋ́нахъ и҆ ѻ҆рга́нѣ."),
    col2("Búrku démonického klamu ste múdro utíšili do ticha, Kristovi apoštoli; celý svet ste priviedli k pravoslávnej viere a teraz sa modlite za naše duše."),
    sub(sText("(3)")),
    gText("Хвали́те є҆го̀ въ кѷмва́лѣхъ доброгла́сныхъ, хвали́те є҆го̀ въ кѷмва́лѣхъ восклица́нїѧ: всѧ́кое дыха́нїе да хва́литъ гдⷭ҇а."),
    col2("Pamiatku múdrych učeníkov Krista, nášho Kráľa, dôstojne piesňami uctime, verní: veď oni vo svete hlásali trojičnú vieru."),
    sub(sText("(2)")),
    gText("Воскрⷭ҇нѝ гдⷭ҇и бж҃е мо́й, да вознесе́тсѧ рꙋка̀ твоѧ̀, не забꙋ́ди ᲂу҆бо́гихъ твои́хъ до конца̀."),
    col2("Náš Boh je podivuhodný vo svojich vyvolených a svätých. Radujte sa a veseľte sa, všetci jeho služobníci, lebo vám pripravil vence a svoje kráľovstvo; no prosíme vás, ani na nás nezabudnite."),
    sub(sText("(1)")),
    gText("И҆сповѣ́мсѧ тебѣ̀ гдⷭ҇и всѣ́мъ се́рдцемъ мои́мъ, повѣ́мъ всѧ̑ чꙋдеса̀ твоѧ̑."),
    col2("Premena zarmútených, premena chorých si, Bohorodička, všetkými ospevovaná; zachráň mesto i ľud; upokojenie napádaných, ticho pre zmietaných búrkou, jediná prímluvkyňa verných."),
  ))
])
