#import "../../../all.typ": *
#columns(2, gutter: 2pt, [

  #generateTable((
    col2([== #translation.at("V")]),
    col2(align(center,sText("("+translation.at("St_V")+")"))),
    cText[$#sym.ast.circle$],
    cText("Nacalo, 103, 12xHP, Kathisma, 3xHP, HV, 104 a 141 a 129"),
    col2([=== #translation.at("HOSPODI_VOZVACH")]),
    sub(sText("(6)")),
    gText("И҆зведѝ и҆з̾ темни́цы дꙋ́шꙋ мою̀, и҆сповѣ́датисѧ и҆́мени твоемꙋ̀."),
    col2("Dlhotrpezlivý a ľudomilný môj Bože, preveľmi milosrdný a štedrý, že si vytrpel zabitie a smrť na dreve kríža za rod ľudský; oslavujeme tvoje milosrdenstvo."),
    sub(sText("(5)")),
    gText("Менѐ ждꙋ́тъ пра́вєдницы, до́ндеже возда́си мнѣ̀."),
    col2("Údery do tváre si pretrpel, aj trpezlivo ukrižovanie a poníženia, chtiac vyslobodiť všetkých od zvodcu, ó jediný Darca života, a všetko znášaš, Preblahý."),
    sub(sText("(4)")),
    gText("И҆з̾ глꙋбины̀ воззва́хъ къ тебѣ̀ гдⷭ҇и, гдⷭ҇и, ᲂу҆слы́ши гла́съ мо́й."),
    col2("Vystúpil si, Pastieru, na kríž a rozprestrel si ruky, volajúc: Príďte ku mne a buďte osvietení, ľudia, ktorí ste zatemnení klamom; lebo ja som Svetlo. Sláva tebe, jediný darca svetla."),
    sub(sText("(3)")),
    gText("Да бꙋ́дꙋтъ ᲂу҆́ши твоѝ, вне́млющѣ гла́сꙋ моле́нїѧ моегѡ̀."),
    col2("Moju dušu, skľúčenú najťažšou ťarchou hriechov, a zrazenú pozdvihni, Panna; veď máš Spasiteľa, ktorý pozdvihuje padlých a ochotne sa podrobuje tvojmu materinskému smelému orodovaniu; a roztrhni svojím orodovaním dlžobný zápis hriechov, prosím, pre tvoje veľké milosrdenstvo."),
    sub(sText("(2)")),
    gText("А҆́ще беззакѡ́нїѧ на́зриши гдⷭ҇и, гдⷭ҇и, кто̀ постои́тъ; ꙗ҆́кѡ ᲂу҆ тебѐ ѡ҆чище́нїе є҆́сть."),
    col2("Zhliadni na mňa, zúfalého pre hriechy a poškvrneného neprávosťami, ktorý som opovrhol Božími prikázaniami, a neodvrhni ma spred svojej tváre; lebo ty si, Bohorodička, moja nádej a orodovnica. Preto vypočuj moje modlitby a očisť ma od každej nečistoty pre tvoje veľké milosrdenstvo."),
    sub(sText("(1)")),
    gText("И҆́мене ра́ди твоегѡ̀ потерпѣ́хъ тѧ̀ гдⷭ҇и, потерпѣ̀ дꙋша̀ моѧ̀ въ сло́во твоѐ, ᲂу҆пова̀ дꙋша̀ моѧ̀ на гдⷭ҇а."),
    col2("Otvor mi dvere pokánia; daj mi, Presvätá, prameň sĺz; udeľ mi kajúcnu dojatosť a cnostné srdce. Lebo len tebe predkladám prosbu o tvoj osvedčený príhovor; k tebe pozdvihujem všetku svoju nádej. Neodvrhni ma zahanbeného, ale prijmi ma a spas ma, Vládkyňa, pre tvoje veľké milosrdenstvo."),
    "",
    gText([#translation.at("SI")]),
    col2("Keď ťa Prečistá videla pribitého na dreve, zvolala: Ó, môj Syn a Bože, aké preslávne a divné na počutie je to, čo pre svoju veľkú milosť trpíš."),
    cText[$#sym.ast.circle$],
    cText("Svite tichyj"),
    col2([=== #translation.at("PROKIMEN")]),
    col2("По́мощь моѧ̀ ѿ гдⷭ҇а, сотво́ршагѡ нб҃о и҆ зе́млю."),
    sText(translation.at("ST")),
    "Возведо́хъ ѻ҆́чи моѝ въ го́ры, ѿню́дꙋже прїи́детъ по́мощь моѧ̀.",
    cText[$#sym.ast.circle$],
    cText("N/S: 12xHP, Spodobi Hospodi, 12xHP"),
    col2([=== #translation.at("STICHOVNI")]),
    col2("Tvoj kríž, Pane, je život a ochrana tvojmu ľudu; a tí, čo v ňom dúfajú, tebe, ukrižovanému v tele, nášmu Bohu, spievame: zmiluj sa nad nami."),
    "",
    gText("Къ тебѣ̀ возведо́хъ ѻ҆́чи моѝ, живꙋ́щемꙋ на нб҃сѝ. сѐ ꙗ҆́кѡ ѻ҆́чи ра̑бъ въ рꙋкꙋ̀ госпо́дїй свои́хъ, ꙗ҆́кѡ ѻ҆́чи рабы́ни въ рꙋкꙋ̀ госпожѝ своеѧ̀: та́кѡ ѻ҆́чи на́ши ко гдⷭ҇ꙋ бг҃ꙋ на́шемꙋ, до́ндеже ᲂу҆ще́дритъ ны̀."),
    col2("Tvoj kríž, Pane, otvoril raj ľudskému rodu; oslobodení od porušiteľnosti, spievame Tebe, nášmu Bohu, ukrižovanému v tele: zmiluj sa nad nami."),
    "",
    gText("Поми́лꙋй на́съ, гдⷭ҇и, поми́лꙋй на́съ, ꙗ҆́кѡ по мно́гꙋ и҆спо́лнихомсѧ ᲂу҆ничиже́нїѧ: наипа́че напо́лнисѧ дꙋша̀ на́ша поноше́нїѧ гобзꙋ́ющихъ, и҆ ᲂу҆ничиже́нїѧ го́рдыхъ."),
    col2("Tvoji mučeníci, Pane, sa neodvrhli od teba ani neodstúpili od tvojich prikázaní. Ich modlitbami sa nad nami zmiluj."),
    "",
    gText([#translation.at("SI")]),
    col2("Keď kedysi pri dreve v čase ukrižovania stála Panna s panenským učeníkom a plačúc volala: Beda mi, ako trpíš, Kriste, ktorý si bezstrastnosťou všetkých."),
    cText[$#sym.ast.circle$],
    cText("Simeon, nacalo, K: 12xHP, tropar ak je, prepustenie"),
  ))
  #generateTable((
    col2([== #translation.at("U")]),
    cText[$#sym.ast.circle$],
    cText("Nacalo, Z19, Z20, nacalo, tropare, 12xHP, Slava svatej, 6zalmie, 12xHP, BohHospod"),
    col2([=== #translation.at("SIDALENY") ]),
    col2([==== #translation.at("SIDALEN_PO") 1 ]),
    col2(sub(sText("(1)"))+"Dnes sa naplnilo prorocké slovo: hľa, klaniame sa na mieste, kde stáli tvoje nohy, Pane, a keď sme okúsili strom spásy, dosiahli sme oslobodenie od hriechu vášní, na príhovor Bohorodičky, jediný Milovník ľudí."),
    col2(sub(sText("(2)"))+"Len čo bolo vztyčené drevo tvojho kríža, Kriste, otriasli sa základy smrti, Pane; lebo peklo toho, ktorého nenásytne pohltilo, prepustilo s chvením; ukázal si nám svoje spasenie, Svätý; a oslavujeme ťa, Syn Boží, zmiluj sa nad nami."),
    "",
    gText([#translation.at("SI")]),
    col2("Jediná nepoškvrnená ovca, Bohorodička Panna, keď si uvidela toho, ktorý sa z tvojej čistej krvi vtelesil, ako z vlastnej vôle visí na kríži, volala si, ó Panna, s horkými slzami: Syn môj nevinný, ospievam tvoje strašné celé prozreteľstvo."),
    col2([==== #translation.at("SIDALEN_PO") 2 ]),
    col2(sub(sText("(1)"))+"Tvoj kríž, Pane, sa posvätil; lebo ním prichádzajú uzdravenia chorým v hriechoch. Preto pred tebou padáme, zmiluj sa nad nami."),
    col2(sub(sText("(2)"))+"Pane, Židia ťa, život všetkých, odsúdili na smrť; tí, čo s palicou prešli Červené more, ťa pribili na kríž; a tí, čo z kameňa sali med, ti podali žlč. No dobrovoľne si to pretrpel, aby si nás oslobodil od otroctva nepriateľa: Kriste, Bože náš, sláva tebe."),
    "",
    gText([#translation.at("SI")]),
    col2("Stojaca pri kríži, Panna a Matka Toho, ktorý sa z nej nad rozum bez semena vtelenil, volala so slzami materskými: Neznesiem ťa vidieť mŕtveho, visiaceho, ty, ktorý dávaš dych žijúcim na zemi, ó Synu a Bože môj!"),
    col2([==== #translation.at("SIDALEN_PO") 3 ]),
    col2(sub(sText("(1)"))+"Kríž, vyháňač démonov, lekár chorých, pevnosť a ochranca verných, skutočná chvála pravoslávnych, opora Kristovej Cirkvi, buď nám štítom, múrom i ochrancom, požehnané drevo."),
    col2(sub(sText("(2)"))+"Na dreve kríža si bol z milosrdenstva a lásky vyzdvihnutý a keď ti kopijou prebodli bok, roztrhol si krutý dlžobný zápis hriechov ako všemohúci Boh; preto, Slovo, zbožne ospevujeme tvoje nevýslovné spásne riadenie."),
    col2(sub(sText("(3)"))+"Svetlo je vždy pre spravodlivých; veď svätí, Tebou osvietení, žiaria ustavične ako svetlá, zhasiac lampu bezbožných. Ich modlitbami, náš Spasiteľ, ty osvecuješ moju lampu, Pane, a zachráň ma."),
    "",
    gText([#translation.at("SI")]),
    col2("Presvätá Bohorodička, počas môjho života ma neopúšťaj; ľudskému orodovaniu ma nezver; ale sama sa ma zastaň a zmiluj sa nado mnou."),
    col2([=== #translation.at("KANON") ]),
    col2(sub(sText("(1)"))+"Ten, čo kedysi morskou vlnou prikryl prenasledovateľa a mučiteľa, pod zemou ukryl zachránených mládencov; ale my, ako devy, Pánovi spievajme, lebo sa slávne preslávil."),
    col2(sub(sText("(3)"))+"Teba, ktorý si nepochopiteľne zavesil celú zem na vodách, keď tvorstvo uvidelo, že visíš na Golgote, s veľkým údesom sa zachvelo a volalo: Niet svätého okrem Teba, Pane."),
    col2(sub(sText("(4)"))+"Habakuk, keď predvídal tvoje božské vyprázdnenie na kríži, v úžase volal: Ty, Dobrotivý, si zlomil moc mocných, pripojil si sa k tým, čo sú v podsvetí, ako Všemohúci."),
    col2(sub(sText("(5)"))+"K tebe sa zavčas rána modlím, Slovo Božie: pre milosrdenstvo si sa nezmeniteľne sám seba zmaril a bezstrastne si sa sklonil k utrpeniam; daruj mi, padlému, pokoj, Milovníku ľudí."),
    col2(sub(sText("(6)"))+"Bol zajatý, no Jonáš nebol zadržaný v útrobách veľryby; lebo niesol tvoj obraz, toho, ktorý trpel a dal sa pochovať, a vyšiel zo zvieraťa ako zo svadobnej komnaty. A volal na strážcov: vy, čo strážite márnosti a klamstvá, túto milosť ste opustili."),
    col2(sub(sText("(7)"))+"Nevysloviteľný zázrak: Ten, ktorý v peci vyslobodil zbožných mládencov z plameňa, je položený do hrobu mŕtvy, bez dychu, na spásu nás, čo spievame: Vysloboditeľu, Bože, požehnaný si."),
    col2(sub(sText("(8)"))+"Nech sa zhrozí a bojí sa nebo a nech sa pohnú základy zeme: hľa, Ten, čo žije na výsostiach, je zarátaný medzi mŕtvych a malý hrob ho prijíma ako hosťa. Jeho mládenci dobrorečte, kňazi ospevujte, ľudia vyvyšujte po všetky veky."),
    col2(sub(sText("(9)"))+"Neplač nado mnou, Matka, vidiac ma v hrobe, Syna, ktorého si bez semena v lone počala; lebo vstanem a budem oslávený a ako Boh neprestajne vyvýšim v sláve tých, čo ťa velebia vo viere a láske."),
    col2([=== #translation.at("CHVALITE") ]),
    sub(sText("(4)")),
    gText("Хвали́те є҆го̀ въ тѷмпа́нѣ и҆ ли́цѣ, хвали́те є҆го̀ во стрꙋ́нахъ и҆ ѻ҆рга́нѣ."),
    col2("V kríži mám nádej, Kriste, a ním sa chváliac volám: Človekamilý Pane, zvrhni pýchu tých, čo nevyznávajú, že si Boh i človek."),
    sub(sText("(3)")),
    gText("Хвали́те є҆го̀ въ кѷмва́лѣхъ доброгла́сныхъ, хвали́те є҆го̀ въ кѷмва́лѣхъ восклица́нїѧ: всѧ́кое дыха́нїе да хва́литъ гдⷭ҇а."),
    col2("My, krížom chránení, vzdorujeme nepriateľovi, nebojúc sa jeho ľsti ani nástrah; lebo pyšný bol zbavený moci a pošliapaný na dreve mocou ukrižovaného Krista."),
    sub(sText("(2)")),
    gText("Воскрⷭ҇нѝ гдⷭ҇и бж҃е мо́й, да вознесе́тсѧ рꙋка̀ твоѧ̀, не забꙋ́ди ᲂу҆бо́гихъ твои́хъ до конца̀."),
    col2("Pane, na pamiatku tvojich svätých slávi celé stvorenstvo; nebesia sa radujú spolu s anjelmi a zem sa teší s ľuďmi. Ich modlitbami zmiluj sa nad nami."),
    sub(sText("(1)")),
    gText("И҆сповѣ́мсѧ тебѣ̀ гдⷭ҇и всѣ́мъ се́рдцемъ мои́мъ, повѣ́мъ всѧ̑ чꙋдеса̀ твоѧ̑."),
    col2("Pribitý som bol ako človek na drevo, zomrel som a bol som položený do hrobu ako smrteľný; no ako Boh v sláve, ó čistá Matka, Panna, opäť vstávam tretieho dňa."),
  ))
])
