#import "../../../all.typ": *
#columns(2, gutter: 2pt, [

  #generateTable((
    col2([== #translation.at("V")]),
    col2(align(center,sText("("+translation.at("Pi_V")+")"))),
    cText[$#sym.ast.circle$],
    cText("Nacalo, 103, 12xHP, Kathisma, 3xHP, HV, 104 a 141 a 129"),
    col2([=== #translation.at("HOSPODI_VOZVACH")]),
    sub(sText("(6)")),
    gText("И҆зведѝ и҆з̾ темни́цы дꙋ́шꙋ мою̀, и҆сповѣ́датисѧ и҆́мени твоемꙋ̀."),
    col2("Idúc po stopách Kristových, celý mučenícky stav statočne vstúpil do mnohých zápasov a pred bezbožnými mučiteľmi i bezprávnymi kráľmi ho vyznával za Boha a mnohé muky pretrpel, očakávajúc prijať nebeské pocty; ktoré teraz vidiac, sa radujú a so všetkými chórami beztelesných mocností stoja pred Pánom."),
    sub(sText("(5)")),
    gText("Менѐ ждꙋ́тъ пра́вєдницы, до́ндеже возда́си мнѣ̀."),
    col2("Bohom vyvolené stádo Krista, prvého Pastiera, stali ste sa jemu podobnými, všesvätí pastieri: neporušene ste až do konca zachovali božské poklady zbožnosti, odháňajúc divých vlkov; a stádo ste dobre priviedli do nebeskej ohrady. Kde teraz prebývajúc, spomínajte s láskou na tých, čo vás velebia, a s dôverou sa modlite ku Kristovi za naše duše."),
    sub(sText("(4)")),
    gText("И҆з̾ глꙋбины̀ воззва́хъ къ тебѣ̀ гдⷭ҇и, гдⷭ҇и, ᲂу҆слы́ши гла́съ мо́й."),
    col2("Ctihodne ste žili, ctihodní otcovia všetci; démonov ste premohli a uhasili ste svedomné muky vášní; hrdinsky ste pretrpeli rozohnenia, blahoslavení, a teraz sa radujete s nebeskými silami, lebo ste sa v tele pripodobnili životu tých beztelesných. S nimi proste Krista, preblahého Boha, aby tí, čo si vás uctievajú, našli vyslobodenie z pádov."),
    sub(sText("(3)")),
    gText("Да бꙋ́дꙋтъ ᲂу҆́ши твоѝ, вне́млющѣ гла́сꙋ моле́нїѧ моегѡ̀."),
    col2("Tvoji mučeníci, Pane, sa neodvrhli od teba ani neodstúpili od tvojich prikázaní. Ich modlitbami sa nad nami zmiluj."),
    sub(sText("(2)")),
    gText("А҆́ще беззакѡ́нїѧ на́зриши гдⷭ҇и, гдⷭ҇и, кто̀ постои́тъ; ꙗ҆́кѡ ᲂу҆ тебѐ ѡ҆чище́нїе є҆́сть."),
    col2("Tvoji mučeníci, Pane, sa neodvrhli od teba ani neodstúpili od tvojich prikázaní. Ich modlitbami sa nad nami zmiluj."),
    sub(sText("(1)")),
    gText("И҆́мене ра́ди твоегѡ̀ потерпѣ́хъ тѧ̀ гдⷭ҇и, потерпѣ̀ дꙋша̀ моѧ̀ въ сло́во твоѐ, ᲂу҆пова̀ дꙋша̀ моѧ̀ на гдⷭ҇а."),
    col2("Strastoterpci, mučeníci, nebeskí občania, ktorí na zemi trpeli a znášali mnohé muky. Ich modlitbami, Pane, a prosbami zachovaj nás všetkých."),
    "",
    gText([#translation.at("SI")]),
    col2("Kto ťa nebude blahoslaviť, Presvätá Panna? Kto nezaspieva tvoj prečistý pôrod? Veď Jednorodený Syn, ktorý bezčasne zažiaril z Otca, ten istý z teba, Čistá, vyšiel, nevýslovne sa vtelil, podľa prirodzenosti Boh a podľa prirodzenosti sa stal človekom pre nás; nie rozdeľovaný na dve osoby, ale poznávaný v dvoch prirodzenostiach nezmiešane. Toho pros, Čistá, Všeblažená, aby sa zľutoval nad našimi dušami."),
    cText[$#sym.ast.circle$],
    cText("Svite tichyj"),
    col2([=== #translation.at("PROKIMEN")]),
    col2("Бж҃е, застꙋ́пникъ мо́й є҆сѝ ты̀, и҆ млⷭ҇ть твоѧ̀ предвари́тъ мѧ̀."),
    sText(translation.at("ST")),
    "И҆зми́ мѧ ѿ вра̑гъ мои́хъ бж҃е, и҆ ѿ востаю́щихъ на мѧ̀ и҆зба́ви мѧ̀.",
    cText[$#sym.ast.circle$],
    cText("N/S: 12xHP, Spodobi Hospodi, 12xHP"),
    col2([=== #translation.at("STICHOVNI")]),
    col2("Tí, ktorí pre Teba, Kriste, trpeli, podstúpili mnohé muky a prijali na nebesiach dokonalé vence; nech sa modlia za naše duše."),
    "",
    gText("Бл҃же́ни, ꙗ҆̀же и҆збра́лъ и҆ прїѧ́лъ є҆сѝ гдⷭ҇и."),
    col2("Kríž tvoj, Pane, sa stal pre mučeníkov neporaziteľnou zbraňou: vidiac smrť, ktorá ležala pred nimi, a predvídajúc budúci život, posilňovali sa nádejou v teba. Na ich modlitby sa nad nami zmiluj."),
    "",
    gText("Дꙋ́шы и҆́хъ во бл҃ги́хъ водворѧ́тсѧ."),
    col2("Začiatkom a zložením mojej bytosti bolo tvoje stvoriteľské nariadenie: lebo si chcel z neviditeľnej i viditeľnej prirodzenosti utvoriť mňa živého; zo zeme si stvoril telo a dal si mi dušu svojím božským a životodarným vdýchnutím. Preto, Spasiteľu, upokoj tvojich služobníkov v krajine živých a v príbytkoch spravodlivých."),
    "",
    gText(""),
    "",
    gText([#translation.at("SI")]),
    col2("Modlitbami tej, ktorá ťa porodila, Kriste, a tvojich mučeníkov, apoštolov, prorokov, svätiteľov, prepodobných a spravodlivých a všetkých svätých, upokoj svojich zosnulých služobníkov."),
    cText[$#sym.ast.circle$],
    cText("Simeon, nacalo, K: 12xHP, tropar ak je, prepustenie"),
  ))
  #generateTable((
    col2([== #translation.at("U")]),
    cText[$#sym.ast.circle$],
    cText("Nacalo, Z19, Z20, nacalo, tropare, 12xHP, Slava svatej, 6zalmie, 12xHP, BohHospod"),
    col2([=== #translation.at("SIDALENY") ]),
    col2([==== #translation.at("SIDALEN_PO") 1 ]),
    col2(sub(sText("(1)"))+"Ty si vždy svetlom pre spravodlivých, Pane; lebo svätí, osvietení tebou, žiaria ustavične ako svetlá, uhasili lampu bezbožných. Ich modlitbami, náš Spasiteľ, rozsvieť moju lampu a zachráň ma."),
    col2(sub(sText("(2)"))+"Svätí, podstúpiac mučenícky zápas a prijmúc od teba víťazné pocty, zmarili úmysly bezákonných a prijali neporušiteľné vence. Na ich orodovanie, Bože, daruj nám veľké milosrdenstvo."),
    "",
    gText([#translation.at("SI")]),
    col2("Keď si nazval svoju Matku blahoslavenou, prišiel si na utrpenie z vlastnej vôle, zažiaril si na kríži, aby si vyhľadal Adama, a anjelom si povedal: Radujte sa so mnou, lebo našla sa stratená drachma. Ty, ktorý múdro všetko usporiadal, náš Bože, sláva tebe."),
    col2([==== #translation.at("SIDALEN_PO") 2 ]),
    col2(sub(sText("(1)"))+"Trpiteľské zotrvanie v zápase a mučiteľské rany na mučeníkoch; a stáli tváre nehmotných, držiac víťazné pocty; udivili múdrych mučiteľov i premúdrych kráľov; odpadlíka zvrhli vyznaním Kristovým. Ty, ktorý si ich posilnil, Pane, sláva Tebe."),
    col2(sub(sText("(2)"))+"Pane, pamiatka tvojich svätých sa dnes zjavila ako raj v Edene; lebo v ňom sa raduje celé stvorenstvo; a ich modlitbami nám udeľuješ pokoj a veľké milosrdenstvo."),
    col2(sub(sText("(3)"))+"Vskutku všetko je márnosť a život je tieň a sen; lebo nadarmo sa lopotí každý pozemšťan, ako hovorí Písmo: aj keď získame svet, predsa vojdeme do hrobu, kde sú spolu králi i chudobní. Preto, Kriste Bože, upokoj zosnulých, ako milovník ľudí."),
    "",
    gText([#translation.at("SI")]),
    col2("Vzdychy srdca a z útrob ti prinášam, Všenepoškvrnená; prosím o milostivé orodovanie: zmiluj sa nad mojou vášňami zotročenou dušou; upros Mnohomilosrdného Boha, aby ma vyslobodil od súdu a od ohnivého jazera, jediná požehnaná."),
    col2([=== #translation.at("KANON") ]),
    col2(sub(sText("(1)"))+"Viditeľný faraón bol utopený so všetkým vojskom, Izrael však prešiel stredom mora a volal: Spievajme Pánovi, nášmu Bohu, lebo sa preslávil."),
    col2(sub(sText("(3)"))+"Keď si upevnil zmýšľanie mojej duše na pevnej skale viery v teba, upevni ho, Pane; veď teba mám, Dobrotivý, za útočište i upevnenie."),
    col2(sub(sText("(4)"))+"Počul som tvoju zvesť a zľakol som sa, pochopil som tvoje diela a zhrozil som sa: sláva tvojej moci, Pane."),
    col2(sub(sText("(5)"))+"Svetlo, ktoré zažiarilo svetu, Kriste, osvieť moje srdce, ktoré k tebe volá od noci, a zachráň ma."),
    col2(sub(sText("(6)"))+"Pohltený veľrybou hriechu, volám k Tebe, Kriste: ako si proroka vyslobodil z porušenia, vysloboď ma."),
    col2(sub(sText("(7)"))+"Keď si vyslyšal pieseň svojich svätých mládencov a rozpálenú pec si rosou ovlažil, požehnaný si, Pane, Bože našich otcov."),
    col2(sub(sText("(8)"))+"Tvoji ctihodní mládenci v peci napodobnili cherubínov, spievajúc trisvätú pieseň: Dobrorečte, spievajte a vyvyšujte ho po všetky veky."),
    col2(sub(sText("(9)"))+"Ty, ktorá si od anjela prijala pozdrav „Raduj sa“ a porodila svojho Stvoriteľa, Panna, zachráň tých, čo ťa zvelebujú."),
    col2([=== #translation.at("CHVALITE") ]),
    sub(sText("(6)")),
    gText("Хвали́те є҆го̀ на си́лахъ є҆гѡ̀, хвали́те є҆го̀ по мно́жествꙋ вели́чествїѧ є҆гѡ̀."),
    col2("Pane, na pamiatku tvojich svätých slávi celé stvorenstvo; nebesia sa radujú spolu s anjelmi a zem sa teší s ľuďmi. Ich modlitbami zmiluj sa nad nami."),
    sub(sText("(5)")),
    gText("Хвали́те є҆го̀ во гла́сѣ трꙋ́бнѣмъ: хвали́те є҆го̀ во ѱалти́ри и҆ гꙋ́слехъ."),
    col2("Pane, keby sme nemali tvojich svätých za orodovníkov a tvoje k nám milosrdenstvo, ako by sme sa, Spasiteľ, odvážili spievať ti, ktorého anjeli neprestajne velebia? Ty, ktorý poznáš srdcia, zľutuj sa nad našimi dušami."),
    sub(sText("(4)")),
    gText("Хвали́те є҆го̀ въ тѷмпа́нѣ и҆ ли́цѣ, хвали́те є҆го̀ во стрꙋ́нахъ и҆ ѻ҆рга́нѣ."),
    col2("Pamiatka mučeníkov, radosť bohabojných: lebo trpiac pre Krista prijali od Neho vence a teraz s dôverou sa modlia za naše duše."),
    sub(sText("(3)")),
    gText("Хвали́те є҆го̀ въ кѷмва́лѣхъ доброгла́сныхъ, хвали́те є҆го̀ въ кѷмва́лѣхъ восклица́нїѧ: всѧ́кое дыха́нїе да хва́литъ гдⷭ҇а."),
    col2("Náš Boh je podivuhodný vo svojich vyvolených a svätých. Radujte sa a veseľte sa, všetci jeho služobníci, lebo vám pripravil vence a svoje kráľovstvo; no prosíme vás, ani na nás nezabudnite."),
    sub(sText("(2)")),
    gText("Воскрⷭ҇нѝ гдⷭ҇и бж҃е мо́й, да вознесе́тсѧ рꙋка̀ твоѧ̀, не забꙋ́ди ᲂу҆бо́гихъ твои́хъ до конца̀."),
    col2("Adamovou chorobou bolo kedysi v Edene ochutnanie z dreva, keď had vyvrhol jed; preto vošla do celého ľudského rodu smrť, ktorá požiera človeka. Ale keď prišiel Vládca, premohol hada a daroval nám vzkriesenie. K nemu teda volajme: Zľutuj sa, Spasiteľu, a tých, ktorých si prijal, upokoj so svätými, lebo si človekomilný."),
    sub(sText("(1)")),
    gText("И҆сповѣ́мсѧ тебѣ̀ гдⷭ҇и всѣ́мъ се́рдцемъ мои́мъ, повѣ́мъ всѧ̑ чꙋдеса̀ твоѧ̑."),
    col2("Spoznali sme Boha, ktorý sa z teba vtelil, Bohorodička, Panna; jeho pros o spásu našich duší."),
    col2([=== #translation.at("STICHOVNI") ]),
    col2("Majúc k nám nepochopiteľné milosrdenstvo a nevyčerpateľný prameň božskej dobroty, ó Mnohomilosrdný, tých, čo k Tebe prišli, Vládca, uveď do zeme živých, do milovaných a túžených príbytkov, udeľujúc večné dedičstvo. Lebo si za všetkých prelial svoju krv, Spasiteľu, a životodarnou cenou si vykúpil svet."),
    sub(sText("(1)")),
    gText("Бл҃же́ни, ꙗ҆̀же и҆збра́лъ и҆ прїѧ́лъ є҆сѝ гдⷭ҇и."),
    col2("Životodarný, dobrovoľne si podstúpil smrť a vyprúdil si život; veriacim si dal večný pokrm, v ktorom upevni zosnulých v nádeji vzkriesenia, odpúšťajúc im z milosti všetky hriechy, lebo ty jediný si bezhriešny, jediný dobrý a ľudomil: nech je od všetkých ospevované tvoje meno, Kriste; oslavujeme tvoju spásonosnú ľudomilnosť."),
    sub(sText("(2)")),
    gText("Дꙋ́шы и҆́хъ во бл҃ги́хъ водворѧ́тсѧ."),
    col2("Ty, čo božskou prvotnou mocou panuješ nad živými a vládneš nad mŕtvymi, tebe, Kriste, vediac, sa modlíme my, tvoji verní služobníci: tých, ktorí odišli k tebe, jedinému Dobrodincovi, upokoj so svojimi vyvolenými, milujúci človeka, na mieste útechy, v svetlých príbytkoch svätých. Lebo ty si vládca milosrdenstva a ako Boh zachraňuješ tých, ktorých si podľa svojho obrazu stvoril, jediný mnohomilosrdný."),
    "",
    gText([#translation.at("SI")]),
    col2("Zjavila si sa ako príbytok božskej krásy, Prečistá: veď si obsiahla Boha a porodila Krista, Matka Panna, ktorá si nepoznala muža, ktorý je v dvoch prirodzenostiach, no v jednej osobe. Pros, Čistá, toho jednorodeného prvorodeného, ktorý teba, nepoškvrnenú Pannu, aj po pôrode zachoval, aby upokojil duše zosnulých vo viere vo svetle a v neporušiteľnom blaženstve."),
  ))
])
