#let translation = (
  "MINEA_OBS": "VŠEOBECNÁ MINEA",
  "M_PAN": "Пра́здникѡмъ Гдⷭ҇а на́шегѡ Їи҃са Хрⷭ҇та̀",
  "M_BOHORODICKA": "Пра́здникѡмъ Бг҃орѡ́дичнымъ",
  "M_KRIZ": "Чтⷭ҇но́мꙋ и҆ животворѧ́щемꙋ крⷭ҇тꙋ̀",
  "M_ANJELI": "Ст҃ы̑мъ а҆́гг҃лѡмъ и҆ про́чымъ безплѡ́тнымъ",
  "M_PREDCHODCA": "Іѡа́нна прⷣте́чи, прⷪ҇ро́ка и҆ крⷭ҇ти́телѧ гдⷭ҇нѧ",
  "M_SVATI_OTCOVIA": "Ст҃ы́хъ ѻ҆тє́цъ, на собо́ры",
  "M_PROROK_JEDEN": "Прⷪ҇ро́кꙋ є҆ди́номꙋ",
  "M_APOSTOL_JEDEN": "А҆пⷭ҇лꙋ є҆ди́номꙋ",
  "M_APOSTOL_VIAC": "Апⷭ҇лѡмъ двѣма̀ и҆ мнѡ́гимъ",
  "M_SVATITEL_JEDEN": "Ст҃и́телю є҆ди́номꙋ",
  "M_SVATITEL_VIAC": "Ст҃и́телємъ двѣма̀ и҆ мнѡ́гимъ",
  "M_PREPODOBNY_JEDEN": "Прпⷣбномꙋ є҆ди́номꙋ",
  "M_PREPODOBNY_VIAC": "Прпⷣбнымъ двѣма̀ и҆ мнѡ́гимъ",
  "M_MUCENIK_JEDEN": "Мч҃нкꙋ є҆ди́номꙋ",
  "M_MUCENIK_VIAC": "Мч҃нкѡмъ, двѣма̀ и҆ мнѡ́гимъ",
  "M_HIEROMUCENIK_JEDEN": "Сщ҃енномч҃нкꙋ є҆ди́номꙋ",
  "M_HIEROMUCENIK_VIAC": "Сщ҃енномч҃нкѡмъ двѣма̀, и҆ мнѡ́гимъ",
  "M_PREPODOBNY_MUCENIK_JEDEN": "Прпⷣбномч҃нкꙋ є҆ди́номꙋ",
  "M_PREPODOBNY_MUCENIK_VIAC": "Прпⷣбномч҃нкѡмъ двѣма̀ и҆ мнѡ́гимъ",
  "M_MUCENICA_JEDNA": "Мч҃нцѣ є҆ди́ной",
  "M_MUCENICA_VIAC": "Мч҃нцамъ, двѣма̀ и҆ мнѡ́гимъ",
  "M_PREPODOBNA_ZENA_JEDNA": "Прпⷣбнѣй женѣ̀ є҆ди́нѣй",
  "M_PREPODOBNA_ZENA_VIAC": "Прпⷣбнымъ жена́мъ двѣма̀ и҆ мнѡ́гимъ",
  "M_PREPODOBNA_MUCENICA_JEDNA": "Прпⷣбномч҃нцѣ є҆ди́ной",
  "M_SPOVEDNIK_JEDEN": "Сщ҃енноисповѣ́дникꙋ и҆ прпⷣбноисповѣ́дникꙋ",
  "M_DIVOTVORCA_JEDEN": "Безме́здникѡмъ и҆ чꙋдотво́рцємъ",
  // "M_":"",
  // "M_":"",

  "M_01_september": "MINEA MESIAC SEPTEMBER",
  "M_02_oktober": "MINEA MESIAC OKTÓBER",
  "M_03_november": "MINEA MESIAC NOVEMBER",
  "M_04_december": "MINEA MESIAC DECEMBER",
  "M_05_januar": "MINEA MESIAC JANUÁR",
  "M_06_februar": "MINEA MESIAC FEBRUÁR",
  "M_07_marec": "MINEA MESIAC MAREC",
  "M_08_april": "MINEA MESIAC APRÍL",
  "M_09_maj": "MINEA MESIAC MÁJ",
  "M_10_jun": "MINEA MESIAC JÚN",
  "M_11_jul": "MINEA MESIAC JÚL",
  "M_12_august": "MINEA MESIAC AUGUST",

  // 🕀🕁🕂🕃🕄
  "M_NAR_BOHORODICKY": "🕀 Ржⷭ҇тво̀ прест҃ы́ѧ влⷣчцы на́шеѧ бцⷣы, и҆ приснодв҃ы марі́и.",
  "M_VOZDV_KRIZA": "🕀 Всемі́рное воздви́женїе честна́гѡ и҆ животворѧ́щагѡ крⷭ҇та̀.",
  "M_JAN_BOHOSLOV": "🕁 Преставле́нїе ст҃а́гѡ а҆пⷭ҇ла и҆ є҆ѵⷢ҇лі́ста І҆ѡа́нна бг҃осло́ва.",
  "M_POKROV": "🕀 Покро́въ прест҃ы́ѧ влⷣчцы на́шеѧ бцⷣы и҆ приснодв҃ы мр҃і́и.",
  "M_DEMETER": "🕁 Ст҃а́гѡ и҆ сла́внагѡ великомꙋ́ченика дими́трїа мѷрото́чца.",
  "M_MICHAL": "🕁 Собо́ръ ст҃а́гѡ а҆рхїстрати́га мїхаи́ла, и҆ про́чихъ безпло́тныхъ си́лъ.",
  "M_JOZAFAT": "🕁",
  "M_ZLATOUSTY": "🕁 И҆́же во свѧты́хъ ѻ҆ц҃а̀ на́шегѡ і҆ѡа́нна, а҆рхїепі́скопа кѡнстанті́нѧ гра́да, златоꙋ́стагѡ.",
  "M_VOVEDENIE": "🕀 Вхо́дъ во хра́мъ прест҃ы́ѧ влⷣчцы на́шеѧ бцⷣы и҆ приснодѣ́вы марі́и.",
  "M_SAVA": "🕁 Прпⷣбнагѡ и҆ бг҃оно́снагѡ ѻ҆тца̀ на́шегѡ са́ввы ѡ҆свѧще́ннагѡ.",
  "M_MIKULAS": "🕁 И҆́же во ст҃ы́хъ ѻ҆тца̀ на́шегѡ нїкола́а, а҆рхїепі́скопа мѷрлѷкі́йскихъ чꙋдотво́рца.",
  "M_POCATIE_BOHORODICKY": "🕁 Зача́тїе ст҃ы́ѧ а҆́нны, є҆гда̀ зача́тъ прест҃ꙋ́ю бцⷣꙋ.",
  "M_NARODENIE": "🕀 Є҆́же по пло́ти, ржⷭ҇тво̀ гдⷭ҇а бг҃а и҆ сп҃са на́шегѡ і҆и҃са хрⷭ҇та̀.",
  "M_ZHROM_BOHORODICKA": "🕃 Собо́ръ прест҃ы́ѧ бцⷣы",
  "M_OBREZANIE": "🕀 По пло́ти ѡ҆брѣ́занїе гдⷭ҇а на́шегѡ і҆и҃са хрⷭ҇та̀",
  "M_BOHOZJAVENIE": "🕀 Ст҃о́е бг҃оѧвле́нїе гдⷭ҇а бг҃а и҆ сп҃са на́шегѡ і҆и҃са хрⷭ҇та̀",
  "M_ANTON": "🕁 Прпⷣбнагѡ и҆ бг҃оно́снагѡ ѻ҆ц҃а̀ на́шегѡ а҆нтѡ́нїа вели́кагѡ",
  "M_EUTMIOS": "🕁 Прпⷣбнагѡ и҆ бг҃оно́снагѡ ѻ҆ц҃а̀ на́шегѡ є҆ѵѳѵ́мїа вели́кагѡ",
  "M_TRAJA_SVATITELIA": "🕁 И҆ и҆́же во ст҃ы́хъ ѻ҆тцє́въ на́шихъ и҆ вели́кихъ і҆ера́рхѡвъ, васі́лїа вели́кагѡ, григо́рїа бг҃осло́ва и҆ і҆ѡа́нна златоꙋ́стагѡ",
  "M_OBETOVANIE": "🕀 ",
  "M_ZVESTOVANIE": "🕀 ",
  "M_JURAJ": "🕁 ",
  "M_JAN_EVANJELISTA": "🕁 ",
  "M_NAR_JAN_KRSTITEL": "🕀 Рождество̀ честна́гѡ сла́внагѡ прⷪ҇ро́ка, предте́чи и҆ крести́телѧ Іѡа́нна.",
  "M_PETER_PAVOL": "🕀 Ст҃ы́хъ сла́вныхъ и҆ всехва́льныхъ и҆ первоверхо́вныхъ а҆пⷭ҇лъ, Петра̀ и҆ Па́ѵла",
  "M_PAVOL_GOJDIC": "🕁 ",
  "M_ELIAS": "🕁 Ст҃а́гѡ сла́внагѡ прⷪ҇ро́ка Илїѝ.",
  "M_PREMENENIE": "🕀 Ст҃о́е преѡбраже́нїе гдⷭ҇а бг҃а и҆ сп҃са на́шегѡ Іи҃са Хрⷭ҇та̀.",
  "M_ZOSNUTIE": "🕀 Оу҆спе́нїе прест҃ы́ѧ сла́вныѧ влⷣчцы на́шеѧ Бцⷣы и҆ приснодв҃ы Марі́и.",

  "SI": "Sláva: I teraz:",
  "S": "Sláva:",
  "IN": "I teraz:",
  "PR": "пр",
  "PD": "pod",
  "VV": "v",
  "ST": "v",

  "HLAS": "Hlas",
  "TYZDEN": "Týždeň svätého pôstu",
  "KAFTIZMA": "Katizma",

  "Ne": "Nedeľa",
  "Po": "Pondelok",
  "Ut": "Utorok",
  "Sr": "Streda",
  "St": "Štvrtok",
  "Pi": "Piatok",
  "So": "Sobota",
  "M": "Malá večiereň",
  "V": "Večiereň",
  "P": "Povečerie",
  "N": "Polnočnica",
  "U": "Utiereň",
  "L": "Liturgia",
  "I": "Typika",
  "C": "Časy",
  "LPD": "Služba vopredposvetených darov",
  "1": "Prvý čas",
  "3": "Tretí čas",
  "6": "Šiesty čas",
  "9": "Deviaty čas",
  "So_V": "v sobotu večer",
  "So_N": "v sobotu v noci",
  "Ne_V": "v nedeľu večer",
  "Ne_N": "v nedeľu v noci",
  "Po_V": "v pondelok večer",
  "Po_N": "v pondelok v noci",
  "Ut_V": "v utorok večer",
  "Ut_N": "v utorok v noci",
  "Sr_V": "v stredu večer",
  "Sr_N": "v stredu v noci",
  "St_V": "v štvrtok večer",
  "St_N": "v štvrtok v noci",
  "Pi_V": "v piatok večer",
  "Pi_N": "v piatok v noci",
  "HOSPODI_VOZVACH": "Pane, ja volám",
  "PARAMIE": "Čítania",
  "LITIA": "Na lítii",
  "STICHOVNI": "Verše na stichovňi",
  "TROPAR": "Tropár",
  "PIESEN": "Pieseň",
  "SIDALEN": "Sedalen",
  "SIDALENY": "Sedaleny",
  "SIDALEN_PO": "Sedalen po",
  "VELICANIE": "Veličánie",
  "YPAKOJ": "Ypakoj",
  "STEPENNY": "Stepenny",
  "ANTIFONY": "Antifóny",
  "ANTIFON": "Antifóna",
  "PROKIMEN": "Prokimen",
  "STICH": "Verš",
  "ALLILUJA": "Aleluja",
  "KANON": "Kanón",
  "KATAVASIA": "Katavázia",
  "KONDAK_IKOS": "Kondák a Ikos",
  "KONDAK": "Kondák",
  "IKOS": "Ikos",
  "CHVALITE": "Verše na chváľte",
  "BLAZENNA": "Blaženstvá",
  "TROPAR_KONDAK": "Tropár a Kondák",
  "50_STICHIRA": "Stichira po 50 żalme",
  "SVITILEN": "Svitilen",
  "PRICASTEN": "Príčasten",
  "IRMOS": "Irmos",
  "JEDINORODNY": "Jednorodený",
  "VCHOD": "Vchod",
  "HOSPODI_POMILUJ": "Pane, zmiluj sa",
  "MOLITVA": "Modlitba",
  
  "HV_MINEA": "Та́же стїхи̑ры 3 и҆з̾ мине́и и҆лѝ и҆з̾ мине́и ѻ҆́бщей.",
  "HV_NOTE": "Сла́ва: и҆з̾ мине́и, И҆ ны́нѣ: бг҃оро́диченъ, а҆́ще не бꙋ́детъ, Сла́ва: И҆ ны́нѣ: бг҃оро́диченъ",
  "HV_N_NOTE": "Бг҃оро́диченъ во ᲂу҆ста́вѣ",
  "T_NOTE": "Сла́ва: мине́и; И҆ ны́нѣ: бг҃оро́диченъ воскрⷭ҇ный",

  "NACALO": "Začiatok",
  "PSALM": "Žalm",
  "PSALTYR": "Žaltár",

  "AFTER_KAFTIZMA": "По каѳі́смѣ, трист҃о́е. Та́же тропарѝ",
)